### ISSUE TITLE
[REQUEST] Visual enhancement of ELEC overhead panel

### ISSUE THREAD

**Issue by Wierin** [flybywiresim/aircraft#1060]
**Is your feature request related to a problem? Please describe.**

Suggested visual enhancement of the overhead electrical panel to be more accurate to the real A320

**Describe the feature you'd like to see implemented**

On the "ELEC" section of the overhead panel, the "AC ESS FEED" button should display "ALTN" when activated, and not "OFF" as it currently does. Moreover, the schematic green line should be connected to the "AC BUS 2" inscription to the right of the button, to accurately represent its functionnality (see links and picture below for pictures of how it looks on the real thing).

**References**

http://www.a320dp.com/A320_DP/electrical/sys-3.2.5.html
https://www.youtube.com/watch?v=bPr3FUSIld4&list=PLdOwRGupI0JerxH2yupf782i4iO9Zf-vG&index=23

![Overhead_panel_of_A320_aircraft_at_parking_stand](https://user-images.githubusercontent.com/6200287/94994523-6144d180-0598-11eb-9997-384484ef8258.jpg)

**Comment by Ares1378** [comment]
Note: The AC ESS FEED pb will only display ALTN if ACBUS2 is supplying power to the AC ESS BUS. The Fault light occurs when the AC ESS BUS is not powered and will display lights out if ACBUS1 is supplying power to the AC ESS BUS

**Comment by davidwalschots** [comment]
The ALTN light indication was fixed in #3383. So now only the green line remains.
