### ISSUE TITLE
[BUG] Unrealistic Pack Temperature on Bleed Page

### ISSUE THREAD

**Issue by HyperStryker** [flybywiresim/aircraft#1660]
**Mod Version**

master, latest dev release as of the evening of 10/30/2020

built: 2020-10-30T19:53:43+00:00
ref: refs/heads/master
sha: 0c0e40c59e3fbd4ee4da7583033cebb939e9fb49
actor: AdenFlorian
event_name: push

**Describe the bug**
Pack #2 temperature skyrockets at an unrealistic rate to an unrealistically high temperature (enough to where it resets and gets stuck around 1-10C).  It seemed to occur when I was playing around with failures (oil and fire on engine 1), having both thrust levers (including failed engine 1) at TOGA, and clearing the ECAM messages with CLR.  It seemed to stop increasing and started cooling down when pulling engine #1 thrust lever back from TOGA and FLX.

**To Reproduce**
1. Set up Engine 1 oil leak and 1-2 min later, fire
2. Took directly off from KLAX and a few minutes in engine 1 will eventually fail and catch fire (as expected), so agents are discharged to stop the fire and ENG 1 switch is turned off
3. Engine 1 is now dead, and Engine 2 is being relied on solely for thrust... APU turned on
4. Put Engine 2 thrust lever to TOGA and Engine 1 to idle, then switch to Bleed page and clear ECAM messages
5. Bleed page is for some reason cleared by CLR, so click on Bleed button again
6. Now put both thrust levers, together, to TOGA power
7. You should now see pack #2 skyrocketing in temperature and, eventually, reaching such a high value that it gets stuck into 1-9 degrees C.

**Expected behavior**
I expected it to not reach such insane temperatures with numbers that can't fit on the display.

**Actual behavior**
Pack #2 temperatures skyrocket at insane rates and reach a temperature hotter than the sun

**References**
https://youtu.be/rkTXW8jWXBE

**Additional context**
Was this working before/when did the issue start occurring?
    Unsure, only started testing fires/failures this patch
Is this a problem in the vanilla unmodded game?
    Unsure, not tested

Discord username (if different from GitHub): HyperStryker#6524

**Comment by lukecologne** [comment]
Pack and bleed system are not properly implemented yet, it's currently only a  placeholder implementation

**Comment by sidnov** [comment]
@BlueberryKing Though I'm aware we are not yet ready to simulate full-fledged failures, thought you should know that this issue still persists. 
![image](https://user-images.githubusercontent.com/29005005/155839633-887d4238-14ee-4d5c-84cf-e0320bc1080b.png)

I had to spawn on approach, fail ENG1, and fiddle with the thrust to reach this stage.

**Comment by Maximilian-Reuter** [comment]
With the new bleed system this isnt an issue anymore
