### ISSUE TITLE
[BUG] Cockpit seats do not have their bottom textures

### ISSUE THREAD

**Issue by LorDawid** [flybywiresim/aircraft#1801]
**Mod Version**

DEV Version from installer

**Describe the bug**

Chairs dont have their bottom textures

**To Reproduce**

1. Look at the bottom of chair

**Expected behavior**

There is a texture

**Actual behavior**

You can see-through the bottom of seats

**References**

**Additional context**

![Desktop Screenshot 2020 11 08 - 12 58 27 59](https://user-images.githubusercontent.com/44745662/98464371-be98f780-21c2-11eb-9149-e8b1c1e093d9.png)

Discord username (if different from GitHub):
LorDawid#6403

**Comment by Pleasure0102** [comment]
Seat model in max: 
![image](https://user-images.githubusercontent.com/9887283/98796098-4c672380-240b-11eb-93e4-a3101dea2f18.png)
as you can see in the next image, it is not the texture that is missing but rather, the model does not have a bottom mesh
![image](https://user-images.githubusercontent.com/9887283/98796184-69035b80-240b-11eb-8b72-839a83ca86af.png)

this is something we could change when we can edit the model, however currently definitely not possible. 
This issue will remain open until we can change it.

**Comment by Oberstumfuher** [comment]
> Seat model in max:
> ![image](https://user-images.githubusercontent.com/9887283/98796098-4c672380-240b-11eb-93e4-a3101dea2f18.png)
> as you can see in the next image, it is not the texture that is missing but rather, the model does not have a bottom mesh
> ![image](https://user-images.githubusercontent.com/9887283/98796184-69035b80-240b-11eb-8b72-839a83ca86af.png)
> 
> this is something we could change when we can edit the model, however currently definitely not possible.
> This issue will remain open until we can change it.

Generally, several 3D modelers use a technique of "excluding" parts of the models that will not be seen, parts that are hidden, as in this case, it was excluded so as not to cause more "weight" in the model. As you can see, this "dark" part inside the 3D model is just the "inside out" and so it becomes transparent, as if there were nothing. A good example to explain this technique would be a model of a kitchen, for example, if this kitchen is made only to be seen from the inside, decoration, lamps and etc., there is no reason to model the walls from the outside too, so when modeling the parts of the walls, ceiling, floor and etc. are excluded, and this makes the model lighter and a faster and smoother rendering. The same thing can be done on the aircraft's instrument panels, there is no reason to have the inner side modeled if it will not be seen.

**Comment by Pleasure0102** [comment]
yeah in this case they also sometimes remove the bottom mesh tho :D which we will most likely add, to make it look better, its just one face, and in some cases is nice to have, i have some other cases where i think they should have added the mesh
