### ISSUE TITLE
Should not be possible to silence the master warning alarm and light when in overspeed

### ISSUE THREAD

**Issue by SergeantTimelord** [flybywiresim/aircraft#182]
At the moment, pressing the master warning buttons will stop the alarm and turn off the lights even when the plane is in an overspeed condition. This should not be possible for an overspeed.

**Comment by SergeantTimelord** [comment]
I'll be working on a potential solution to this.

**Comment by PCGamesF1Tech** [comment]
Does the "EMER CANC" pb work? That's the way to cancel the overspeed warning.
Or just slow down ;-)

**Comment by Pruznak** [comment]
I was just looking around here and found this - I guess you could close this based on #8604 ?

**Comment by 2hwk** [comment]
> I was just looking around here and found this - I guess you could close this based on #8604 ?

Noted, this should be closed.
