### ISSUE TITLE
[REQUEST] Overhead panel light flickering when switching from APU to GPU.

### ISSUE THREAD

**Issue by firstpon** [flybywiresim/aircraft#1822]
**Describe the feature you'd like to see implemented**

Overhead panel light flickering when switching from APU to GPU or GPU to APU.

**References**

https://youtu.be/J0YN-PSnOBI

Discord username (if different from GitHub):
FIRST

**Comment by ilyeshammadi** [comment]
A screenshot or small video of the issue will be much appreciated in order to solve the issue.

**Comment by stevex77** [comment]
I understand it so when switching between GPU and APU sources (and vice versa), backlighting of whole overhead panel should turn off for a while and then on again. Right @firstpon ?

**Comment by firstpon** [comment]
> I understand it so when switching between GPU and APU sources (and vice versa), backlighting of whole overhead panel should turn off for a while and then on again. Right @firstpon ?

Yes(power transfer). sorry for my bad English.

**Comment by tracernz** [comment]
This does not occur in more recent MSNs.
