### ISSUE TITLE
Missed approach

### ISSUE THREAD

**Issue by cellotako** [flybywiresim/aircraft#1835]
**Is your feature request related to a problem? Please describe.**

On vatsim, sometimes going arround ossurs. but no missed approach course there, i feel so frustrated

**Describe the feature you'd like to see implemented**

add missed approach course when i put star on cdu

**References**

**Additional context**

Discord username (if different from GitHub):__Cellotako#1642

**Comment by antikythera288** [comment]
#1715 implements the GOAROUND functionality, but currently its limited to use HDG (vectors) . NAV (missed approach path) will follow at some point

**Comment by yorgosGK** [comment]
yah, it makes me cry there is no missed approach fix's of the star and it just ends at the ICAO :( lol would be killer to implement this. The runways missed approach.

**Comment by antikythera288** [comment]
Well, no need to cry ;) ... fortunately the Charts will give you the heading of the missed approach or the ATC can vector you via HDG ... this is possible now as the PR mentioned above got merged ... missed approached will come surely at some point ... until then, just use selected altitude and heading :)

**Comment by NathanInnes** [comment]
Major problem is im not even sure Asobos database stores missed approach procedures so this may be difficult

**Comment by Benjozork** [comment]
> Major problem is im not even sure Asobos database stores missed approach procedures so this may be difficult

I think they might, need to confirm

**Comment by antikythera288** [comment]
Is Asobo does not, I think the navigraph information do. Question is if they are loaded

**Comment by tracernz** [comment]
The missed approach legs are in the MSFS procedures. Will be done in CFPM at some point...
