### ISSUE TITLE
VOR Autotuning

### ISSUE THREAD

**Issue by mikecbr** [flybywiresim/aircraft#2050]
**Mod Version**
Latest master branch RADNAV rework 1 #1960   they merge it 2 days ago i guess but the bug im having it stills there

**Describe the bug**
 In the navigation display , when you select VOR in the FCU , It does not show any indication of the closest VOR

**To Reproduce**
![image](https://user-images.githubusercontent.com/74787268/99887369-05b3cd80-2c44-11eb-8f75-868ef02c301e.png)

![image](https://user-images.githubusercontent.com/74787268/99887383-1f551500-2c44-11eb-90b4-3dfef97ff82e.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/74787268/99887418-84a90600-2c44-11eb-9ba0-78abba47c915.png)

**Actual behavior**

**References**

**Additional context**

Was this working before/when did the issue start occurring?
No

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
You did set a VOR in the RAD NAV page, correct ?

Also, please don't leave those sections empty

> **Actual behavior**
>
> **References**

**Comment by mikecbr** [comment]
Ok sorry my bad...  no i didnt , the aircraft should do it automatically , it normally does not appear if the VOR is aout of range wich is not the case.

**Comment by lukecologne** [comment]
> 
> 
> Ok sorry my bad... no i didnt , the aircraft should do it automatically , it normally does not appear if the VOR is aout of range wich is not the case.

Autotuning is currently not implemented.

**Comment by mikecbr** [comment]
Ok so have I done well to open a new bug report , or you were aware of it ?

**Comment by St54Kevin** [comment]
Just rename it or mention in description that autotuning is not working. I initially did not understand what you mean.

**Comment by mikecbr** [comment]
Thats good to know thank you.

**Comment by blitzcaster** [comment]
> Just rename it or mention in description that autotuning is not working. I initially did not understand what you mean. Also the plane does not autotune the closest station. It tunes the station it can best triangular its position from

It does autotune to the closest navaid as the last resort. Anybody working on auto tuning? Currently I'm trying to at least implement the closest auto tuning.
![image](https://user-images.githubusercontent.com/29270388/105616732-9efd8c80-5e0b-11eb-89a3-d2f957791e2e.png)

**Comment by mikecbr** [comment]
> > Just rename it or mention in description that autotuning is not working. I initially did not understand what you mean. Also the plane does not autotune the closest station. It tunes the station it can best triangular its position from
> 
> It does autotune to the closest navaid as the last resort. Anybody working on auto tuning? Currently I'm trying to at least implement the closest auto tuning.
> ![image](https://user-images.githubusercontent.com/29270388/105616732-9efd8c80-5e0b-11eb-89a3-d2f957791e2e.png)

I don't  think so lol

**Comment by blitzcaster** [comment]
> > > Just rename it or mention in description that autotuning is not working. I initially did not understand what you mean. Also the plane does not autotune the closest station. It tunes the station it can best triangular its position from
> > 
> > It does autotune to the closest navaid as the last resort. Anybody working on auto tuning? Currently I'm trying to at least implement the closest auto tuning.
> > ![image](https://user-images.githubusercontent.com/29270388/105616732-9efd8c80-5e0b-11eb-89a3-d2f957791e2e.png)
> 
> I don't  think so lol

On the A32NX it still doesn't have autotuning, so no it doesn't autotune. The real aircraft, at least based on FCOM I quoted above, should autotuned to relevant navaid. If it can't find one, it autotune to the nearest one as the last resort.

I just bought XP11 and ToLiss A321neo recently. So I can observe how it behave on a well modeled simulator. It is kind of strange though. It does tune one of the VORs in the flight plan. Although sometimes it tuned to random VOR (possibly nearest), other times it tune to a VOR that is out of range.

**Comment by tracernz** [comment]
Fixed a long time back.
