### ISSUE TITLE
FCU should only start 10 seconds after battery connect

### ISSUE THREAD

**Issue by amsomers** [flybywiresim/aircraft#2606]
**Is your feature request related to a problem? Please describe.**

When connecting a battery the FCU is instantly online. All information is showing. IRL this takes about 10 seconds until that time the displays may have backlight but no info

**Describe the feature you'd like to see implemented**

When you start the plane with one or two batteries connected the FCU remains dark for about 10 seconds.

**References**

https://youtu.be/qlQc9LyeGUo

**Additional context**

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
can you provide a NEO reference ?

**Comment by amsomers** [comment]
I have not yet found a NEO reference. Will search for it. Could be that NEO starts faster? Only RL pilot can confirm I suppose?

**Comment by amsomers** [comment]
https://youtu.be/Mo7A3CuVb8g
This looks like a NEO, description does not really mention it though. at 1:01 you see the values coming up. Before that only backlight was visible, even with external power connected.

**Comment by lynara** [comment]
those are cfm56 engines and the video was uploaded before the first neo flight, so no neo.

**Comment by amsomers** [comment]
sorry, can't find a A320 Neo reference. Searched for it for a long time.

**Comment by TansyEliot** [comment]
> 
> 
> sorry, can't find a A320 Neo reference. Searched for it for a long time.

https://youtu.be/vj4nPjsVxC0
Did you saw this video? Maybe this video can help.

**Comment by amsomers** [comment]
That is a self build cockpit and A320-200. Hardly a good comparison. Only RL pilot can confirm.
