### ISSUE TITLE
RNAV APPROACH L&V/DEV squares

### ISSUE THREAD

**Issue by alainzu** [flybywiresim/aircraft#2792]
**Mod Version**

**Describe the bug**

L/DEV & V/DEV squares are missing during final approach

**To Reproduce**

1. create a flpn SKBO to SKBO
2. DEP Rwy 13R ARR procedure RNP Rw 13R
3. When final descent point displays on the MFD (BO612) arm APP
4. FINAL APP is displayed on the PFD but the L & V/DEV squares are missing

**Expected behavior**

FINAL APP is displayed on the PFD but the L & V/DEV squares are missing

**Actual behavior**

L & V/DEV square should be displayed on the PFD during final approach

**References**

**Additional context**

Was this working before/when did the issue start occurring?

Is this a problem in the vanilla unmodded game?

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by MisterChocker** [comment]
@lukecologne is this also implemented in your rework?

**Comment by jetstream2x4** [comment]
yeah ... I would like to confirm the issue ... Occassionally they pop up sometimes at the lower end of the PFD altitude tape. But I do not have the impression that it is really are working ... For most published NPAs under bad weather conditions the brick would be as elemental, as the diamond for precisions. So it would be good if it could be implemented on a stable base...

**Comment by tareksabet** [comment]
RNP landings have lots of issues plus the L/DEV and V/DEV are not working. 

Thanks for reporting this issue.

**Comment by robindupetitbois** [comment]
Hi everyone,
I really enjoy daily a32nx, my happiness would be complete if i can use realistic rnav approach, so can you tell me if the rnav approach square missing indicator bug resolution  is still on the table; do you know what it s the origin of this bug ?
Please help me to perform my favorite approach lfmn 04L  😉 
Thanks anyway to the FBW team you re the best👍👏

**Comment by karol-leszczynski** [comment]
Same thing, I tried 5 different airports at least 2 times each. L & V/DEV squares are missing. It works in Asobo a320 plane.

**Comment by tracernz** [comment]
> Same thing, I tried 5 different airports at least 2 times each. L & V/DEV squares are missing. It works in Asobo a320 plane.

I would say “works”, more like “exists”. We will add them when the functionality is properly implemented.

**Comment by karol-leszczynski** [comment]
That explains a lot. I will wait patiently. Thank you.

**Comment by juliansebline** [comment]
I'm on it. I'll do my best

**Comment by tracernz** [comment]
> I'm on it. I'll do my best

There’s a lot of underlying flight planning and guidance system work that needs done before this is possible. We have been and are working on it for some time.

**Comment by fililip** [comment]
Is this working now? I haven't been able to get V/DEV or APP NAV / FINAL APP to work, but maybe I'm doing something wrong. Is there additional work required in the new FMSv2 to support RNP-RNAV now that VNAV is supported?

**Comment by BlueberryKing** [comment]
No, this should not have been closed. That was a mistake I am afraid, FINAL APP is not yet available.

> Is this working now? I haven't been able to get V/DEV or APP NAV / FINAL APP to work, but maybe I'm doing something wrong. Is there additional work required in the new FMSv2 to support RNP-RNAV now that VNAV is supported?
