### ISSUE TITLE
[REQUEST] Glareshield angle correction 

### ISSUE THREAD

**Issue by Sadawalebg** [flybywiresim/aircraft#2795]
**Is your feature request related to a problem? : No

**Describe the feature you'd like to see implemented**

We agree, the glasshield of the 320 from Asobo is disproportionate and gives the impression that the cockpit is more compact but also that the rendering is very ugly. The cockpit of an A320 Neo is identical to that of a 320 Classic so this rounded elevation of the glasshield is not necessary. We can now remedy this as we can export and re-import a 3D model, I propose that we correct the cockpit to show the beauty of the A320.

**References**

The green line represents the perfect symmetry while the red is what we have now.
![Microsoft Flight Simulator Screenshot 2020 12 29 - 21 05 51 01](https://user-images.githubusercontent.com/73961641/103312048-3560ad00-4a1c-11eb-8e02-16a9a71ebc53.png)
![c49becb796ceb168b5086c92459755dd](https://user-images.githubusercontent.com/73961641/103312059-3c87bb00-4a1c-11eb-8081-50c1990727dc.jpg)
![Microsoft Flight Simulator Screenshot 2020 12 29 - 21 06 01 02](https://user-images.githubusercontent.com/73961641/103312083-4b6e6d80-4a1c-11eb-97a8-efcc5eaf27a8.png)
Below you can see the fairly large gap
![cockpit2-3-01](https://user-images.githubusercontent.com/73961641/103312087-4dd0c780-4a1c-11eb-8770-0d45f07e7309.jpg)

**Additional context**
I hope that this will be taken into account but I also see the difficulty for the correction as it is a large part of the cockpit that will have to be modified.

Discord username : Sawada_Sensei

**Comment by Benjozork** [comment]
> We can now remedy this as we can export and re-import a 3D model

We cannot immediately as both importer and exporter still need work.

**Comment by crocket63** [comment]
About time :D
