### ISSUE TITLE
[REQUEST] Landing light SimConnect variable decoupled from nose wheel light

### ISSUE THREAD

**Issue by sushiat** [flybywiresim/aircraft#2818]
**Is your feature request related to a problem? Please describe.**

Addon software that uses SimConnect to check whether the landing light is on doesn't read so until you also move the nose wheel light to TO. That light would be set to Taxi for landing and only after deploying the landing gear. Programs like OnAir and SelfLoading cargo via fsuipc tell me though that I didn't turn the landing light on below 10000 feet because of this - even though the main landing lights were on the whole time from around 10500 feet. Same story during takeoff where the fs2crew a320 crew application moves the nose wheel light to off after raising the gear. I'm also not sure if the runway turnoff lights are also included in the logic regarding the variable but the same applies as it also gets turned off once the gear is raised.

**Describe the feature you'd like to see implemented**

Have the variable these programs check if the landing lights are on only dependent on the actual landing light and remove the nose wheel light from that logic.

**References**

Sorry can't find any written references but "320 Sim Pilot" on youtube mentioned it multiple times (specifically in his lighting video here https://youtu.be/L9XUHepoFDg?t=1034 ) and I also assume that fs2crew researched the step correctly for the pilot monitoring to turn off the light after raising the gear even thought the lights are automatically turned off - the switch would still be moved.

**Additional context**

Discord username (if different from GitHub): sushi.at

**Comment by tracernz** [comment]
You can find the docs on how to switch lights individually here: https://docs.flybywiresim.com/fbw-a32nx/a32nx-api/a32nx-flightdeck-api/#external-lights-panel
