### ISSUE TITLE
CTRK TK labels wrongly positioned

### ISSUE THREAD

**Issue by Airbusinsider** [flybywiresim/aircraft#29]
![OVHD 320-251N](https://user-images.githubusercontent.com/70146837/91046777-50a84f80-e619-11ea-9db6-ca83b55c58d5.jpg)

FUEL panel of the A320NEO has to be the same as from an A321.

**Comment by noga-aviator** [comment]
do you mean that the default a320 doesn't have a correct model ?

**Comment by Airbusinsider** [comment]
Model should be fine in this case. Just change the textures.

But the ENG panel at the OVHD has the wrong model. Noted in separate issue.

**Comment by arvinjarvin** [comment]
Hello.

The team have reached out to Asobo Studios prior, in order to gain access to the raw 3D files, and we will keep you updated accordingly.

All the best!

Arvin

**Comment by Curtis-VL** [comment]
For future reference:
https://media.discordapp.net/attachments/750470119817347192/751921946870153317/Overhead.png?width=1166&height=874

**Comment by tareksabet** [comment]
@Pleasure0102 what can you do about that

**Comment by lukecologne** [comment]
I took a look in blender, and I think I can answer for him: Nothing without the model, you need to edit the mesh for changing this.

**Comment by Airbusinsider** [comment]
Hi gents, is really the model required to change the labeling of the CTRK TK pumps?
There is no need to add the ACT button. Just look at my inital photo.
