### ISSUE TITLE
Remove ENG N1 mode switches

### ISSUE THREAD

**Issue by Airbusinsider** [flybywiresim/aircraft#30]
Currently the OVHD ENG panel is from a IAE engine of a CEO airbus.

The NEO has no N1 Mode switches. Depending on eng version there has to be a dual cooling switch for the A320-271N.
The A320-251N has just nothing.

![OVHD 320-271N](https://user-images.githubusercontent.com/70146837/91047032-bbf22180-e619-11ea-800c-05408b9ee396.jpg)

**Comment by DABUS320** [comment]
this is the Pratt model.... not the leap model, Please refer to A320-251N
