### ISSUE TITLE
[REQUEST] Speed-brake amber flash when power is added against it

### ISSUE THREAD

**Issue by Mindbugss** [flybywiresim/aircraft#3087]
**Is your feature request related to a problem? Please describe.**

The speed-brakes do not flash amber when power is being added against it. 

**Describe the feature you'd like to see implemented**

Amber SPEED BRAKES on Lower ECAM  while Speed brakes are extended and engines are not at idle.

**References**

http://www.a320dp.com/A320_DP/flight-controls/sys-7.10.0.html

**Additional context**

-

Discord username (if different from GitHub): 
MindBugs_#6140

**Comment by beheh** [comment]
Yeah, that's an FWC memo. It will be in the FWC rework, but maybe someone is motivated to add it to the legacy system. It'll need a timer as well, as it doesn't start flashing instantly.

**Comment by beheh** [comment]
I've dropped "Good First Issue" for now because of the FWC rework that's in-progress.

**Comment by tracernz** [comment]
Fixed a while ago.
