### ISSUE TITLE
[BUG] Fuel System Crossfeed does not work

### ISSUE THREAD

**Issue by Docretro** [flybywiresim/aircraft#3120]
**Mod Version**
{
  "built": "2021-01-19T19:28:49+00:00",
  "ref": "",
  "sha": "",
  "actor": "DerL30N <leon.beeser@yahoo.de>",
  "event_name": "manual"
}

**Describe the bug**
When opening the the Fuel-X-Feed Valve and turning of fuel pumps (i.e. to react on a fuel imbalance) on one side,
both engines are spooling down and fail. After turning the pumps on again and closing the X-Feed, only Engine one is
relighting.

**To Reproduce**
 
1. Spawn on any place 
2. Start up engines
3. Open Fuel-X-Feed-Valve and turn of fuelpumps of one side of the fuelsystem (i.e. L TK Pumps 1+2)

**Expected behavior**
Engines stay in operation, fuel is used from the still active tanks

**Actual behavior**
Both engines cut off, only Engine 1 is relighting after resetting the the Valves and pumps

**References**
this procedure is not working with the actual mod

![Fuel Imbalance](https://user-images.githubusercontent.com/77463033/105214266-11424880-5b50-11eb-842a-6c173d9d1925.jpg)

**Additional context**

Was this working before/when did the issue start occurring?
Can't exactly say, did just try out this procedure on the mod and encountered the issue

Is this a problem in the vanilla unmodded game?

Yes

**Comment by derl30n** [comment]
Is this still an issue?

**Comment by donstim** [comment]
Should have been closed by PR #7817
