### ISSUE TITLE
No Portable Elec Device option

### ISSUE THREAD

**Issue by jeffies04** [flybywiresim/aircraft#346]
This is sort of silly, but at my airline many newer Airbus aircraft come with a "no electronic device" sign instead of a seatbelt sign. No smoking is included as a permanent placard. Unless the MSFS A320neo is a retrofitted 320, I expected to see this difference when I first launched it.

The NO SMOKING sign is a "NO PORTABLE ELEC DEVICE" sign (see pic if I can attach it). Turning this sign off, which is usually done at above 10,000 ft, also extinguishes the lighted exit signs in the cabin for passenger comfort (nobody is evacuating at cruise altitude).

![no_ped](https://user-images.githubusercontent.com/70678896/92070176-37617a80-ed60-11ea-858b-7a2c92a744cc.jpg)

**Comment by NathanInnes** [comment]
Is this something that people would like to see implemented?

Vote with reactions

**Comment by FlyingCarpet7** [comment]
It could perhaps be a nice texture option but I think the No Smoking sign is still by far the most used one by airlines..
