### ISSUE TITLE
[BUG] Main landing gear wheels rotate too fast

### ISSUE THREAD

**Issue by Inexorable95** [flybywiresim/aircraft#3506]
**Mod Version**
master

**Describe the bug**
The wheels of the main landing gear rotate too fast when the plane is moving, it is as if they were "slipping fast" on the ground instead of rolling on the ground.

**To Reproduce**
1. Go into the drone camera mode, with the follow mode switched on
2. Place the camera next to the main landing gear
2. Move the plane forward slowly

**Expected behavior**
The wheels should rotate at a speed at which the wheel's point of contact moves as fast as the ground below it

**Actual behavior**
The wheels rotate at a speed at which the wheel's point of contact moves much faster than the ground below it, giving the impression that the wheels are slipping on the ground

**References**

**Additional context**
I think the bug may be related to this PR: https://github.com/flybywiresim/a32nx/pull/3251
as in this PR (https://github.com/flybywiresim/a32nx/pull/3336), it is mentionned that it increased the wheel size and increased  the RPMs of the wheels (even though the wheel model didn't change size)

it seems that the wheel animation of the external model is based on the WHEEL RPM simvar, which would explain why they move too fast now.

Was this working before/when did the issue start occurring?
Unknown, but I noticed it two days ago.

Is this a problem in the vanilla unmodded game?
No.

Discord username (if different from GitHub): Inexorable

**Comment by donstim** [comment]
It's hard for me to tell whether the animation is off or not. Could try different wheel radii and see if that helps. But the current wheel radius is correct and provides the correct RPM for the ground speed of the airplane. For example, I set the airplane up going 35 knots ground speed. The nose gear wheel RPM was about 898 and the main gear wheel RPM about 674. The nose gear tire radius is 0.625 feet and the main gear tire radius is 0.833 ft. Multiplying the circumference (2πr)*RPM gives speed of about 3526-3528 ft/min or 58.8 ft/sec for both of them, which is about 35 knots.

**Comment by Inexorable95** [comment]
> It's hard for me to tell whether the animation is off or not. Could try different wheel radii and see if that helps. But the current wheel radius is correct and provides the correct RPM for the ground speed of the airplane. For example, I set the airplane up going 35 knots ground speed. The nose gear wheel RPM was about 898 and the main gear wheel RPM about 674. The nose gear tire radius is 0.625 feet and the main gear tire radius is 0.833 ft. Multiplying the circumference (2πr)*RPM gives speed of about 3526-3528 ft/min or 58.8 ft/sec for both of them, which is about 35 knots.

I mainly noticed it with the improved main landing gear textures in the brake fan PR, but it's also present in the dev version

**Comment by donstim** [comment]
I guess I'd rather have the actual speed correct than have the animation look better. Would be nice to know how to control the animation to fix the real problem, which isn't the wheel RPM.

**Comment by Inexorable95** [comment]
> I guess I'd rather have the actual speed correct than have the animation look better. Would be nice to know how to control the animation to fix the real problem, which isn't the wheel RPM (IMO).

I never implied the problem was the wheel RPM being wrong itself, I just noted that the animation relies on wheel RPMs, and that it worked before and it doesn't work now, so it needs to be fixed somehow, that's why this issue exists.

**Comment by avteknisyan** [comment]
@donstim 

does the radius value in flightmodel.cfg are for tire or just the wheel (rim)?

**Comment by donstim** [comment]
> @donstim
> 
> does the radius value in flightmodel.cfg are for tire or just the wheel (rim)?

According to the SDK, it is the wheel radius.

**Comment by donstim** [comment]
Wasn't this issue addressed by https://github.com/flybywiresim/a32nx/pull/6954?
