### ISSUE TITLE
[BUG] Light coming through dash

### ISSUE THREAD

**Issue by wodenf4** [flybywiresim/aircraft#3608]
![lighting](https://user-images.githubusercontent.com/75283012/108391008-3d002f00-71df-11eb-9a63-8fe1e09d69b8.png)

**Mod Version**
"master" 

**Describe the bug**
Light coming through solid objects such as through the front dashboard 

**To Reproduce**
I connect ground power and the caution light that is projected from the vehicle comes through

**Expected behavior**
Light not to come through :)

**Additional context**

Is this a problem in the vanilla unmodded game? yes

**Comment by Inexorable95** [comment]
This is a known issue, see #1190 or #95
Unfortunately there is not much we can do for now, that issue has to be fixed by Asobo.

**Comment by wodenf4** [comment]
Thanks for the follow up. I had searched the current issues list but didn’t find anything as I had looked for lights and the results would bring back keywords with “flights”. Anyway, thanks for letting me know.

**Comment by Snapmatics** [comment]
The issue can be fixed when we have our exporter ready. Apparently, Iceman found an idea that could solve it.
