### ISSUE TITLE
[REQUEST] Open Documents on EFB

### ISSUE THREAD

**Issue by Risechocolate** [flybywiresim/aircraft#3790]
It's hard to open another window to open a chart during a flight.

I want Flypad to be able to display PDF, txt, jpg, and png files.

Sorry, I don't have a picture of the actual device.

Discord username: rize_chocolate

**Comment by Risechocolate** [comment]
Yes, it would be preferable if the folder settings could be freely added in an ini file, etc.

**Comment by Kacper848** [comment]
From what I have seen in the FBW discord, there is a person working on accessing PDFs via the EFB. Not sure about the other file formats though.

**Comment by ErickSharp** [comment]
I believe this may soon be possible with @Lucky38i 's work on the local-api.

**Comment by ErickSharp** [comment]
This has just been accomplished on flypados 3 20 seconds ago.

**Comment by Lucky38i** [comment]
Re-opening as simbridge still not ready.

**Comment by BenJuan26** [comment]
Should this issue still be open? Local charts are working completely as far as I can tell.

**Comment by frankkopp** [comment]
Quite a few solved ones still open I guess. Hard to kerp up. 
Will close this one.
