### ISSUE TITLE
RAD-NAV page does not show VOR freq when injected by third party (minor)

### ISSUE THREAD

**Issue by frankkopp** [flybywiresim/aircraft#3916]
**Mod Version**
{
  "built": "2021-03-11T06:11:22+00:00",
  "ref": "fbw",
  "sha": "f4fc87c3e18bf84de6c71a0f426140da9451f99b",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**
When the VOR/ADF frequencies are injected by a third party tool (in my case AivlaSoft EFB) the ND shows the correct frequencies but the RAD NAV page does only show empty fields. 

**To Reproduce**
1. C&D start
2. Turn on VOR1+2 on ND
3. Change VOR freq in external tool
4. Check PFD VOR
5. Check RAD NAV page

**Expected behavior**
RAD NAV page reflects the VOR/ADF frequencies currently set

**Actual behavior**
RAD NAV page fields empty

**References**
![image](https://user-images.githubusercontent.com/16833201/110760213-c2ab5380-824e-11eb-8edb-76cd7cd6d587.png)

Was this working before/when did the issue start occurring?
Unknown

Is this a problem in the vanilla unmodded game?
n/a

Discord username (if different from GitHub): Cdr_Maverick

**Comment by Asianblade** [comment]
This was not working from the very beginning. Thank you

**Comment by tracernz** [comment]
I think injecting by a third party is more equivalent of tuning with RMP, in which case MCDU/FMGC tuning is disabled entirely.

**Comment by tracernz** [comment]
This is no longer relevant. It's not possible to tune externally when the FMS is controlling the radios.
