### ISSUE TITLE
upper ecam fuel warnings and memos - ctr tanks and low fuel

### ISSUE THREAD

**Issue by Duncan10** [flybywiresim/aircraft#4126]
**Is your feature request related to a problem? Please describe.**

Some upper ECAM warnings+memos are missing for the fuel system, below there are some examples mentioned.

**Describe the feature you'd like to see implemented**

Add ECAM warnings for fuel system events:
- CTR TK PUMPS OFF
- L(R) WING TK LO LVL
- L + R WING TK LO LVL
and corresponding memos.

**References**

LO WING TK level warning+memo is demonstrated in the official airbus Safety First | July 2015 edition (easy to find webpage).

**Additional context**

Discord username (if different from GitHub): Dunx#2505

**Comment by St54Kevin** [comment]
CTR TK PUMPS OFF message is not present anymore in the neo as it doesnt have pumps for the center tank. We are aware of that now and looking into changing over to neo specs

**Comment by Maximilian-Reuter** [comment]
this is done in the current dev version
