### ISSUE TITLE
Cabin window cubemap is facing the wrong way 

### ISSUE THREAD

**Issue by Codeh4ck** [flybywiresim/aircraft#4207]
**Mod Version**
{
  "built": "2021-03-30T22:44:03+00:00",
  "ref": "autopilot",
  "sha": "c7e6cbfe8a6e5d020d499a39aab1480a4ad6a943",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**
Not really something serious but the cabin seats are placed backwards, facing the tail of the plane. 

**To Reproduce**
1. Use the drone in showcase camera
2. Move the drone close to a window
3. Adjust the angle if necessary to get a better view of the interior

**Expected behavior**
Seats should be facing the cockpit.

**Actual behavior**
Seats are facing the tail of the aircraft.

**References**
I don't think this is really needed.

**Additional context**
https://prnt.sc/110cyy2

Was this working before/when did the issue start occurring?
Yes, it was working before. I can't really pinpoint when this issue occured but a couple of weeks ago the cabin layout was correct.

Is this a problem in the vanilla unmodded game?
No idea. I don't use the vanilla A320.

Discord username (if different from GitHub):
Codehack#6987

![Seat Orientation](https://user-images.githubusercontent.com/11696956/113080409-8b8de980-91df-11eb-97b4-f356e8c116fd.png)

**Comment by Riggie** [comment]
Yes, I have seen this in the FBW, all seats facing towards the tail.

**Comment by Benjozork** [comment]
This is not an actual interior but a simple texture in a cubemap

I think @pepperoni505 knows how to fix this

**Comment by FoxinTale** [comment]
It's not a cubemap, just a flat picture. Cubemaps are usually used to simulate metallic reflections in older games, I think.

**Comment by Benjozork** [comment]
> It's not a cubemap, just a flat picture. Cubemaps are usually used to simulate metallic reflections in older games, I think.

It is a cubemap, just not used for reflection. You can see because the image shifts as you rotate around it.

**Comment by glowfishDE** [comment]
I can confirm this. However it´s spooky that @Codeh4ck s screenshot almost looks like mine ^^

<img width="1919" alt="2021-08-08 23_32_56-Microsoft Flight Simulator - 1 18 15 0" src="https://user-images.githubusercontent.com/44566242/128647325-2b882d21-9acc-4905-b8b5-fbc4ca5a6acd.png">

**Comment by glowfishDE** [comment]
> @glowfishDE experimental is no longer supported and outdated. Please switch to either stable or development version!

sorry ^^ i meant the development branch of course. I always confuse the two ^^ i´ll correct the above post.

**Comment by tracernz** [comment]
Note that the portholes in the doors have the texture the right way around. 😂

**Comment by Codeh4ck** [comment]
Any update on this? It seems like it was left unfixed as I am still seeing it.

It does kill immersion a little bit.

**Comment by tracernz** [comment]
Can't be easily fixed, as some are the wrong way round and others are correct... so changing the texture just swaps that. There's a good chance it won't be solved until we replace the 3D model with our own.
