### ISSUE TITLE
PFD heading should display true heading in high latitudes

### ISSUE THREAD

**Issue by lcanet** [flybywiresim/aircraft#4217]
**Is your feature request related to a problem? Please describe.**
When flying in high latitudes (above 73° North or below 60° south), the PFD should display the true heading, not magnetic heading and a "TRUE" indicator should be displayed

**Describe the feature you'd like to see implemented**
Display true heading on PFD and ND bearing to next WPT

**References**
![image](https://user-images.githubusercontent.com/1287953/113208685-61d1d280-9272-11eb-9c49-02e843278a49.png)

**Additional context**
Spawn at BGTL runway 26. True heading is 264° but PFD display magnetic heading (318°)

**Comment by tracernz** [comment]
It is more than just the PFD. There’s a lot of work in properly implementing this throughout.

**Comment by tracernz** [comment]
Fixed a long time back.
