### ISSUE TITLE
Fully Simulated Automatic Flight Director Engagement after Power-On

### ISSUE THREAD

**Issue by avgeeek** [flybywiresim/aircraft#4242]
**Is your feature request related to a problem? Please describe.**
No. Just a little accuracy check based on actual aircraft behavior

**Describe the feature you'd like to see implemented**
Engage the Flight Directors automatically after power-up

with delay of around 12 seconds according to the youtube video

**References**

A320 NEO AMM 22-10-00-00 AP/FD ENGAGEMENT - Description and Operation
![Capture](https://user-images.githubusercontent.com/81854737/113474788-5baa4480-9472-11eb-9643-273936e8e997.PNG)

Airbus A320 Standards Document
![unknown](https://user-images.githubusercontent.com/81854737/113474690-bdb67a00-9471-11eb-805b-5bcd25edac15.png)

https://youtu.be/Mo7A3CuVb8g?t=48

**Additional context**

Discord username (if different from GitHub):

**Comment by MisterChocker** [comment]
iirc FDs are also automatically activated on take off trust engagement aka FLX or TOGA.

**Comment by aguther** [comment]
I'm up to now only aware of the automatic engagement on go around, not during take-off.

The engagement after power-up is correct and should be there.

**Comment by aguther** [comment]
With the latest dev version the flight directors are now engaged when the FCU is powered on.

No simulation of the start procedure of the FCU yet.

**Comment by aguther** [comment]
It turned also out that engagement of flight directors is bound to FMGC power-up and **not** FCU.
