### ISSUE TITLE
Takeoff calculations on EFB.

### ISSUE THREAD

**Issue by TLSY2** [flybywiresim/aircraft#4444]
**Is your feature request related to a problem? Please describe.**

Hi, it would be great to have a take off performance calculator with flex to temp calculation too and v speeds.
**Describe the feature you'd like to see implemented**

**References**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by tracernz** [comment]
You can remove the landing part (separate issue, and already underway in https://github.com/flybywiresim/a32nx/pull/3581).

**Comment by TLSY2** [comment]
> You can remove the landing part (separate issue, and already underway in #3581).

cool.

**Comment by FGrabi** [comment]
Great Idea. As a reference maybe you can use http://www.wabpro.cz/A320

I always use it for the Flex **and STAB TRIM** (put the actual MAC-"Center of Gravity" and the TOW in the fields) calculation.

**Comment by TLSY2** [comment]
> Great Idea. As a reference maybe you can use http://www.wabpro.cz/A320
> 
> I always use it for the Flex **and STAB TRIM** (put the actual MAC-"Center of Gravity" and the TOW in the fields) calculation.

Oh yes, i use that. Anyway i make some YouTube videos and get like 5 view per vid :DDD and when i record i forget to go to that website and i then have to cut a lot of footage because of wait time... It would just be easier to do it on the EFB as many other EFB's for X plain 12  have. And like i opened another enhancement about the checklist on the EFB, it would just be way too helpful. I remember all the checklists but i haven't flown in 2 weeks and when i got back I forgot to do my CG but remembered every small thing :DD

**Comment by FGrabi** [comment]
I total agree with you, it would be really a nice and meaningful enhancement. Maybe one of the developers of the EFB will find a way to implement the calculations in EFB!
BTW: Million thanks to ALL of you in the FBW Team. Without your work, the MSFS is only half the fun!

**Comment by TLSY2** [comment]
> I total agree with you, it would be really a nice and meaningful enhancement. Maybe one of the developers of the EFB will find a way to implement the calculations in EFB!
> BTW: Million thanks to ALL of you in the FBW Team. Without your work, the MSFS is only half the fun!

what you mean, half the fun, it would be less than a quarter. I try to fly the default 320 and its soo empty.

**Comment by FGrabi** [comment]
For the "other half" of fun I use the Aerosoft CRJ ;-)

**Comment by TLSY2** [comment]
> For the "other half" of fun I use the Aerosoft CRJ ;-)

that explains it :D. I cant afford that since I only have problems, starting with my professional Logitech headset breaking into pieces, my glass sidepanel smashing...

**Comment by rick2909** [comment]
I would love to take this and make this but I would need to learn all the calculations and stuff. and some help on getting the efb to work in browser window.

**Comment by TLSY2** [comment]
> I would love to take this and make this but I would need to learn all the calculations and stuff. and some help on getting the efb to work in browser window. I will do this after the merge of the landing calculator so i don't have to do double work.

Maybe i will dig and find calculations and maybe help you.

**Comment by rick2909** [comment]
> Maybe i will dig and find calculations and maybe help you.

That would help indeed, I'm not a pilot and don'y know how i would get to those calculations.

**Comment by TLSY2** [comment]
> > Maybe i will dig and find calculations and maybe help you.
> 
> That would help indeed, I'm not a pilot and don'y know how i would get to those calculations.

I want to be future pilot, Anyway, add me on steam so we can keep in touch?

**Comment by Phil7789** [comment]
**The following sources all refer to A320. Information about the Neo could not be found by me**

**Why there is (probably) no formula available**
As far as I've researched former Flex Temp calculation was done by RTOW charts which are mostly not publicly availabe. Nowerdays the calculation is done by the EFBs (e.g. Airbus Flysmart+ by NavBlue).
NavBlue TO calculation example: [https://www.navblue.aero/wp-content/uploads/2017/08/pdt4-6.jpg](https://www.navblue.aero/wp-content/uploads/2017/08/pdt4-6.jpg)

**Flex Temp corrections**
Flex temps would propably only be an estimated value but never a 100% realistic value like in real aviation. I found an older document explaining the corrections of Flex Temp in various conditions, although they also refer to RTOW charts (which are not included in the examples). In the document you can check pages 87 (printed page nr. 81) to 95 (printed page nr. 89).

- QNH Delta as -10 hPA (result is always -2° C)
- RWY condition (wet is -1° C)
- Anti-Ice (+ 2° C)

It is furthermore noticed that the following conditions have to be met to have a valid flex temp

- Corrected Temperature (CT) <= TFlex Max (a value which would be extracted from the RTOW chart, so probably not available)
- CT > OAT
- CT > TRef
- Thrust reduction must not exceed 25% of flat rated thrust

Source: [https://www.cockpitseeker.com/wp-content/uploads/goodies/ac/a320/pdf/Print_Only/PTM%20with%20airbus%20doc/pdf/U0S2SP0-L.pdf](https://www.cockpitseeker.com/wp-content/uploads/goodies/ac/a320/pdf/Print_Only/PTM%20with%20airbus%20doc/pdf/U0S2SP0-L.pdf)
Source 2 (Flex Takeoff definition and explanatory graphic): [https://www.skybrary.aero/bookshelf/books/2263.pdf](https://www.skybrary.aero/bookshelf/books/2263.pdf) Page 91 (printed 87) to 93 (printed 89)

**Examples of online takeoff calculators**
Source 1: [https://www.theairlinepilots.com/forumarchive/a320/a320-flex-calculation.xlsx](https://www.theairlinepilots.com/forumarchive/a320/a320-flex-calculation.xlsx) - This excel file can be unlocked for editing without a password and thus research the used formulas

Source 2: [https://flightsim.to/file/11740/takeoff-landing-performance-calculator-a320](https://flightsim.to/file/11740/takeoff-landing-performance-calculator-a320) - This excel file **cannot** be unlocked without a password and thus the formula is not visible, but might be a reference

Source 3: [https://www.fstools.tech/](https://www.fstools.tech/) - Online only as a website

**Data source for runways**
Navigraph might be able to allow the use of their data like they've done for several other addon developers (I don't know the exact requirements): [https://navigraph.com/community/developer-directory](https://navigraph.com/community/developer-directory).

I am still checking for a valid source for all the data needed for a correct calculation, but they mostly would be:

- Runway elevation
- Runway slope (increasing or decreasing the actual runway length)
- Runway length
- Wind component (head / tailwind)

**Comment by tracernz** [comment]
At least the runway elevation, length, and wind component are available within the sim navdata already. Not sure about slope.

**Comment by Phil7789** [comment]
I found a scientific work with some interesting functions in the appendix and explanations in the work itself:

https://documents.pub/document/joao-lemos-viana-takeoff-and-landing-performance-optimization.html

**Comment by TLSY2** [comment]
Hey! So its been a while. Does anyone know when this is implemented? Its a must have, a lot of companies have this on their ipads.

**Comment by tracernz** [comment]
We don't give dates, and there are many things considered "must have" that we are working on. When we have time and necessary data we will do this, but until then patience is necessary.

**Comment by TLSY2** [comment]
however whats the status of this?

**Comment by sidnov** [comment]
> however whats the status of this?

![image](https://user-images.githubusercontent.com/29005005/135690082-1f453f3a-0f70-4d8b-8dc1-dbae4b465f9c.png)

Unless someone has worked on it....it's not there

**Comment by TLSY2** [comment]
> > however whats the status of this?
> 
> ![image](https://user-images.githubusercontent.com/29005005/135690082-1f453f3a-0f70-4d8b-8dc1-dbae4b465f9c.png)
> 
> Unless someone has worked on it....it's not there

i dont care about the dates, but like is anyone working on it? Or is it just sitting there?

**Comment by sidnov** [comment]
Nope, it's an open source project. Unless there is a PR open for it, we consider no one is working on it

**Comment by TLSY2** [comment]
> ause you see if we could just "add this" we'd have finished the whole aircraft and made the most realistic A320 of

wheres that comment?

Yeah i understand what you are saying about data shortages.

I dont understand tho is if anyone is working on it currently, where do i see that?

**Comment by Benjozork** [comment]
You can't see that, because anyone could be working on it right now and we might not know. Someone can work on it without telling us. But it is unlikely that is the case.

Generally, someone working on it with minimally working code would open up a draft PR.

**Comment by TLSY2** [comment]
> You can't see that, because anyone could be working on it right now and we might not know. Someone can work on it without telling us. But it is unlikely that is the case.
> 
> Generally, someone working on it with minimally working code would open up a draft PR.

Dont they label it?

**Comment by Benjozork** [comment]
In theory they should, but someone might be working on something locally and have not told anyone yet.

**Comment by TLSY2** [comment]
> In theory they should, but someone might be working on something locally and have not told anyone yet.

How do i join the team to make it myself?

**Comment by sidnov** [comment]
> > In theory they should, but someone might be working on something locally and have not told anyone yet.
> 
> How do i join the team to make it myself?

You don't have to be on the team to contribute. All you need to do is refer to the Contributing section. https://docs.flybywiresim.com/dev-corner/development-guide/

**Comment by alex853** [comment]
![image](https://github.com/flybywiresim/aircraft/assets/11858152/f8a11b2a-facd-4e54-9c20-4e9c43e4aeda)
Quite trivial implementation of TRIM calculation, I will add some functionality to left-hand card as there is no(?) easy way to find planned gross weight CG during preflight phase except to wait for fully loaded aircraft and look at MCDU.

**Comment by jbud** [comment]
> ![image](https://private-user-images.githubusercontent.com/11858152/304003372-f8a11b2a-facd-4e54-9c20-4e9c43e4aeda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NTU4OTcsIm5iZiI6MTcwNzc1NTU5NywicGF0aCI6Ii8xMTg1ODE1Mi8zMDQwMDMzNzItZjhhMTFiMmEtZmFjZC00ZTU0LTljMjAtNGU5YzQzZTRhZWRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDE2MzMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4NTgwNzEyMzVlNGNjMDMxYmViNmU2ZGZmOTJkZWE4YzdkMWZkODMwZTJlNzYyMzkyMDE1NTU5YjM1NGU4ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3NoZfv3kSGWiVLAfnvTMS0XO2TYjHcsPKIeT4PQ-Ka4) Quite trivial implementation of TRIM calculation, I will add some functionality to left-hand card as there is no(?) easy way to find planned gross weight CG during preflight phase except to wait for fully loaded aircraft and look at MCDU.

Trim isn't really calculated, airbus SOP is to use the trim wheel to set the CG. 
![image](https://github.com/flybywiresim/aircraft/assets/6253799/8cf26cea-592a-422a-bcda-28a4f152522d)

The Gross CG can be found clicking this in the flypad on ground page for reference which IIRC is also set as L:A32NX_AIRFRAME_GW_CG_PERCENT_MAC_DESIRED once payload is loaded
![CG](https://github.com/flybywiresim/aircraft/assets/6253799/f7aea71b-c21c-4fc7-b251-0b50df96fd55)

**Comment by tracernz** [comment]
We should probably calculate the estimated takeoff CG and show it on the EFB. I might consider it in the takeoff calculator work currently underway.

**Comment by donstim** [comment]
Seems like something that would be on a dispatch sheet, not in a takeoff calculator.

**Comment by KOWA380** [comment]
https://jbud.github.io/Flex-Calculator-TS/ 

Can this be integrated in fllypad?

**Comment by jbud** [comment]
> https://jbud.github.io/Flex-Calculator-TS/ 
> 
> 
> 
> Can this be integrated in fllypad?
> 
> 

They are working on one. The origin of this tool was a failed PR to bring it to flypad. Ultimately it was decided my work was insufficient for the a32nx

**Comment by KOWA380** [comment]
seems okay i use it to calculate T/O for all my flights.

> They are working on one. The origin of this tool was a failed PR to bring it to flypad. Ultimately it was decided my work was insufficient for the a32nx
