### ISSUE TITLE
Fire handle textures and reading light textures

### ISSUE THREAD

**Issue by ghost** [flybywiresim/aircraft#4597]
**Aircraft Version**
{
  "built": "2021-04-23T22:37:56+00:00",
  "ref": "experimental",
  "sha": "c43d0267084cae66e5cb3950c1c76e9b78bf43d0",
  "actor": "aguther",
  "event_name": "manual"
}

**Describe the bug**
The textures of the mentioned lights have to be more detailed to match the rest of the cockpit.

**To Reproduce**
N/A

**Expected behavior**
The reading light lenses look like this:
https://forums.flightsimulator.com/t/diy-desk-lamp-from-cockpit-a320-reading-light/309121

And the illiminated fire handels look like this and it is extremely important to see all individual bulps:
https://de.scribd.com/document/343765125/A320-Fire-Protection-System-Review

**Actual behavior**
The textures of the mentioned lights have to be more detailed to match the rest of the cockpit.

**References**
See links above.

**Additional context**
N/A

Was this working before/when did the issue start occurring?
UNKNOWN

Is this a problem in the vanilla unmodded game?
UNKNOWN

Discord username (if different from GitHub):

**Comment by hotshotp** [comment]
both are known issues, so far we cannot change that other than having to change the model as far as i know

**Comment by davidwalschots** [comment]
Whenever someone tries to fix the fire handle emissives, note that the lights are powered by different buses, as depicted in the screenshot below:

![image](https://user-images.githubusercontent.com/1074786/122357419-08656f80-cf54-11eb-9811-7fc3cd5e580e.png)

**Comment by tracernz** [comment]
Fixed a while back with the model update.
