### ISSUE TITLE
Emissive for LDG GEAR down

### ISSUE THREAD

**Issue by davidwalschots** [flybywiresim/aircraft#5139]
### Aircraft Version

Development

### Description

Emissive (red) for LDG GEAR down is missing and should be added.

Not many details here, as this issue is made to split up the remaining items in #528.

### Discord Username (optional)

SjotgunSjonnie#9623

**Comment by tracernz** [comment]
Do you know from where it is powered?

**Comment by davidwalschots** [comment]
@tracernz Yep. AC ESS SHED powers the light.

![image](https://user-images.githubusercontent.com/1074786/122364778-5d0be900-cf5a-11eb-8c45-648d0ad0b97e.png)

**Comment by MisterChocker** [comment]
Since I see a red light now ![image](https://user-images.githubusercontent.com/1857322/130368231-262307ec-81ab-4470-98c9-7175049f2116.png) am I right to assume this issue has been addressed accordingly but forgotten to be closed?

**Comment by tracernz** [comment]
No, this is about the down arrow next to the L/G lever.
