### ISSUE TITLE
RST, CHR, DATE, GPS/INT, and RUN/STP/RST shouldn't light up

### ISSUE THREAD

**Issue by davidwalschots** [flybywiresim/aircraft#5142]
### Aircraft Version

Development

### Description

The CLOCK's RST, CHR, DATE, GPS/INT, and RUN/STP/RST shouldn't light up.

This issue is taken from #956 (which will be closed).

### Discord Username (optional)

SjotgunSjonnie#9623

**Comment by juliansebline** [comment]
@davidwalschots I think it's fixed already

**Comment by tracernz** [comment]
It's not:
![lit-chr](https://user-images.githubusercontent.com/9995998/165200980-befa16cc-b230-4440-a45e-81b5508062fc.PNG)
Real plane.. no integral lighting on the chrono:
![image](https://user-images.githubusercontent.com/9995998/165201288-d6361afa-4721-4897-88d9-fb18fec04695.png)

**Comment by juliansebline** [comment]
Oh ok, you can see it by night. Well, I suppose we have to use Blender to fix it ? I'll pass on this one because I did not manage to make the addons work few days ago

**Comment by tracernz** [comment]
I don't think it's very feasible to fix as it's part of a large decal mesh covering the whole main panel... and the text on the textures is shared amongst all the decals (multiple things UV mapped to each word sort of thing).

**Comment by juliansebline** [comment]
Something similar was used to fix the SEL led color in this PR: https://github.com/flybywiresim/a32nx/pull/7100

Do you think we can do something similar?
