### ISSUE TITLE
Fix LDG ELEV legend

### ISSUE THREAD

**Issue by bouveng** [flybywiresim/aircraft#5234]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-06-29T06:59:57+00:00",
  "ref": "HEAD",
  "sha": "4b526b9eaf3900b9949b1b08024135c467390478",
  "actor": "BBK <22713769+BlueberryKing@users.noreply.github.com>",
  "event_name": "manual"
}
```

### Describe the bug

Numbers on the LDG ELEV AUTO knob legend is cut off.

![ldg-elev-auto](https://user-images.githubusercontent.com/433429/123754925-b01b5f80-d8bb-11eb-893c-0e5d8cacca91.png)

### Expected behavior

Correctly aligned legends.

### Steps to reproduce

Spawn.
Look at OVHD.

### Discord Username (optional)

bouveng

**Comment by Illuminati270** [comment]
Yet, the texture itself is quite wrong. The knob is supposed to start at AUTO then negative scale, then positive.


![image](https://user-images.githubusercontent.com/85410344/124196847-9b99bb80-daa3-11eb-9263-72866768a245.png)

**Comment by Creative-Difficulty** [comment]
The screenshot in the docs for Starting the aircraft in the cabin pressurization section still has screenshots with the old texture.

**Comment by alepouna** [comment]
> The tutorial in the docs for Starting the aircraft in the cabin pressurization section still has screenshots with the old texture.

For the documentation please open an issue at https://github.com/flybywiresim/docs
