### ISSUE TITLE
Missing dot on fire panel test buttons

### ISSUE THREAD

**Issue by bouveng** [flybywiresim/aircraft#5536]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-04T18:35:13+00:00",
  "ref": "HEAD",
  "sha": "fe97ce409e1f9d55b11185de38ce069915934bc9",
  "actor": "Erick Torres <30361843+ErickSharp@users.noreply.github.com>",
  "event_name": "manual"
}
```

### Describe the bug

The white dot's, introduced by #5111 have been removed as a result of #5497.
![missing-dots](https://user-images.githubusercontent.com/433429/128236398-d8779b39-d79f-48b2-885b-ff9875c21aae.png)

### Expected behavior

The aforementioned buttons should have a white dot.

### Steps to reproduce

1. Spawn
2. Observe fire panel on the OVHD

### References (optional)

A320 OVHD
![121844937-05b11300-cce5-11eb-831e-38e5594864f9](https://user-images.githubusercontent.com/433429/128235975-19f84907-fc1d-48fc-abfd-d26f95a05e7f.png)
A32NX before #5497 
![121844665-99ceaa80-cce4-11eb-9239-7f43e2b3830a](https://user-images.githubusercontent.com/433429/128236040-18768807-5270-4c98-8367-d6ed379e203f.png)

### Discord Username (optional)

bouveng

**Comment by ErickSharp** [comment]
If the white dot is reintroduced, not just the fire test push buttons will have the white dot, but also the other push buttons that share the same textures as those buttons.

**Comment by bouveng** [comment]
> If the white dot is reintroduced, not just the fire test push buttons will have the white dot, but also the other push buttons that share the same textures as those buttons. 

@ErickSharp Was the previous implementation wrong? I only saw white dots on the fire panel as far I can remember.

**Comment by ErickSharp** [comment]
> > If the white dot is reintroduced, not just the fire test push buttons will have the white dot, but also the other push buttons that share the same textures as those buttons. 
> 
> @ErickSharp Was the previous implementation wrong? I only saw white dots on the fire panel as far I can remember.

Correct, the overhead fire panel looked correct but other buttons with the same textures had to all have a white dot because of that.

**Comment by hotshotp** [comment]
there are no other buttons with the same texture, so it is fine to implement i think

**Comment by ErickSharp** [comment]
> there are no other buttons with the same texture, so it is fine to implement i think

No there are on the overhead panel close to the ELT

**Comment by ErickSharp** [comment]
![image](https://user-images.githubusercontent.com/30361843/128521080-d66ca5a5-87b5-474e-9247-2c9b6fb49764.png)
