### ISSUE TITLE
Small texture bug on the Airbus overhead panel around the air conditioning exhaust 

### ISSUE THREAD

**Issue by fluffyGamingCat** [flybywiresim/aircraft#5607]
### Aircraft Version

Development

### Build info

```json
Newest Development build (but the texture bug is also present in the stable and the Experimental version.)
```

### Describe the bug

Hi and congratulations for this absolute impressive and beautyful Airbus!
In my opinion it is almost perfect and everything works fine, but I have found a little texture bug on the overhead panel on one of the air condition exhausts.
If you could take care of this texture bug the interior of the Airbus would be absolutely perfect :)
![image](https://i.ibb.co/Qb57n38/Microsoft-Flight-Simulator-09-08-2021-21-02-26.jpg)
![image](https://i.ibb.co/1Rnjgs0/Microsoft-Flight-Simulator-09-08-2021-22-12-53.jpg)

Thanks for contributing such a wonderful fantastic plane to this flight sim!

### Expected behavior

Texture bug on the overhead panel gone.

### Steps to reproduce

1. ) Sitting inside the Airbus
2.) looking at the overhead panel

### Discord Username (optional)

Murmeltier Deluxe#9219

**Comment by kilocharlie1** [comment]
It turns out it was just the livery causing the problem.

**Comment by tracernz** [comment]
Looks okay in blender :/
![image](https://user-images.githubusercontent.com/9995998/146641060-454c6ed2-a2a5-4c27-a053-c933bc4e356e.png)

**Comment by fluffyGamingCat** [comment]
Hi... hm I see. A strange problem indeed. In the Flight Simulator forum
someone said "it is a bug in the UV map" (sorry I don´t exactly know what
an UV map is because when I make textures I change only the textures and
the bumpmaps).
Maybe you are able to fix this some day :)
I wish you good luck and thank you very much for your effort bringing this
awesome Airbus to the new flight sim :)

Have a wonderful weekend and a nice evening, and don´t work too hard on
that Airbus and also have a look at the new Netflix Witcher series released
today.
