### ISSUE TITLE
DIR TO resets FLPN and manipulates FROM/TO airports

### ISSUE THREAD

**Issue by e4rthdog** [flybywiresim/aircraft#5687]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-18T21:30:52+00:00",
  "ref": "master",
  "sha": "b7076762217e0fa89881c4425816500a5d9f5b6a",
  "actor": "bouveng",
  "event_name": "manual"
}
```

### Describe the bug

FMC was programmed for a specific STAR and APPROACH. 

After passing the initial point of the STAR , VATSIM ATC gave me a direct to a waypoint not in the STAR or APPROACH procedure that i have set up.

After doing so: 
-  The flight plan disappeared and a green line was drawn probably directing to the waypoint i have inserted. There was no waypoint info in the MFD
- The flightplan became DEPARTURE ICAO / DEPARTURE ICAO in the FMC and the flight plan page was blank.

What i did to exit the situation:
- I went back and inserted the correct ICAO of the airports of the route
- The Flight plan page showed the 2 airports
- I inserted the STAR and APPROACH again and used a waypoint that existed in order to conrtinue. I couldn;t find a way to to the instructed waypoint.

### Expected behavior

After inserting the DIRECT i would expect the MFD to show that waypoint and issue a gap in the flightplan which i should be able to amend accordingly.

### Steps to reproduce

Flight LBSF/LBBG

STAR ESENA4D
APPROACH RNP04

After passing ESENA try to input a direct to BG364.

**Comment by Pat15250** [comment]
Hi,
I noticed that airac isn't always up to date in asobo flight simulator. Many way points are missing. I found the solution by updating airac with navigraph navdata center. Perhaps, you can try this.
Patrick

**Comment by e4rthdog** [comment]
> Hi,
> I noticed that airac isn't always up to date in asobo flight simulator. Many way points are missing. I found the solution by updating airac with navigraph navdata center. Perhaps, you can try this.
> Patrick

Thanks. I am always on the latest navigraph so in that case it wasn't that...

**Comment by tush0701** [comment]
I can confirm the issue with DIR TO, it resets the flight plan, and the aircraft keeps diverting to one of the starting waypoints, unless I choose directed HDG instead of managed.

**Comment by jmfs** [comment]
Can confirm this too. Got an ATC andry over this in SBGR in VATSIM.

**Comment by John-UK** [comment]
This is a long standing and well known issue of the ASOBO flight plan. It has been corrected in experimental. Select HDG use DIR to, to fight through the issue. Or use the very much improved experimental version.

**Comment by 2hwk** [comment]
Fixed by 4953 closing ☑️

**Comment by tracernz** [comment]
This one is actually broken again. It was fixed early on.

**Comment by derl30n** [comment]
Still an issue?

**Comment by tracernz** [comment]
It will still do bad things if you try to DIR TO an airport.

**Comment by 2hwk** [comment]
Improved by fms v2 but I'm not sure if its fully resolved.
