### ISSUE TITLE
CTD when starting descent

### ISSUE THREAD

**Issue by Venorcis** [flybywiresim/aircraft#5729]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-08-26T14:38:01+00:00",
  "ref": "master",
  "sha": "3f91a9c9e374b436c31fa402a404da0423ae37b5",
  "actor": "sidnov",
  "event_name": "manual"
}
```

### Describe the bug

MSFS crashes to desktop roughly 30s after starting a descent from cruise.
I've had this happen three times in total now, two times on stream (see references).
After the first CTD I reinstalled the latest development version and cleared the cache directory, but to no avail.

### Expected behavior

MSFS should not crash of course ;)

### Steps to reproduce

1. Be in cruise phase (possibly on FL310 or higher, not sure if it matters)
2. Start an open descent (possibly having the EFB descent performance calculator active and trying to print a VATSIM ATIS?)
3. Wait roughly 30 seconds

### References (optional)

EHAM-EKCH https://www.twitch.tv/videos/1127268684?t=01h10m45s
EHAM-EDDS https://www.twitch.tv/videos/1130256997?t=01h15m50s
It also happened off-stream today on a LFPG-EHAM flight, again shortly after starting descent (around HELEN).
In all cases the EFB performance calculator was active, not sure if that matters.

### Additional info (optional)

It seems to have started on the development versions from the 23rd somewhere; on the 22nd I did a similar flight (EDDK-EHAM) without issue (see https://www.twitch.tv/videos/1126040665), and I always keep up-to-date with the latest development version!

EDIT: I just reviewed my own reference videos, and in both cases I have the EFB performance calculator active (not sure if matters) and I'm trying to get the ATIS printed as well. I now remember on my LFPG-EHAM flight today I tried to get the WX as well just before it crashed. However, again ony my earlier EDDK-EHAM stream that all also worked without issue.

**Comment by Lucky38i** [comment]
This usually happens with AI aircraft loading in with incompatible liveries. I'd suggest clearing your community folder entirely and trying a flight with just the fbw a32nx. After that if there's no CTDs you could download liveries updated for SU5 from flightsim.to

**Comment by Venorcis** [comment]
> This usually happens with AI aircraft loading in with incompatible liveries. I'd suggest clearing your community folder entirely and trying a flight with just the fbw a32nx. After that if there's no CTDs you could download liveries updated for SU5 from flightsim.to

I'm not using any liveries. I only have the flybywire-aircraft-a320-neo and navigraph-navdata packages installed.

**Comment by Venorcis** [comment]
To come back on this issue, this is likely a duplicate of #5429, when not printing any VATSIM ATISes I don't get any crashes anymore lately.

**Comment by MisterChocker** [comment]
Great to hear, if the issue appears again unlinked to #5429 please do re-open this issue.
