### ISSUE TITLE
[BUG] Things light up that shouldn't

### ISSUE THREAD

**Issue by adenflorian** [flybywiresim/aircraft#575]
**Mod Version**

master

**Describe the bug**

There are things in the plane that should not light up as part of the integrated lights, but they do in the game.

- [x] parking brake #566
- [x] eng starter switches #566
- [ ] gravity gear extn (texture?)
- [ ] chronometer texts (texture?)
- [ ] ovhd circuits (texture?)

**References**

IRL photos:
chronometer texts like RST shouldn't light up ever:
![image](https://user-images.githubusercontent.com/3533988/92769574-b8230680-f35e-11ea-97e9-d894f74fcbd2.png)

**Additional context**

**Comment by konjakk** [comment]
Aft overhead panel: Data Loading Selector panel 52VU and Maintenance Panel 50VU is not equipped with integral lights and should never light up. One1E#8499

**Comment by konjakk** [comment]
Aft overhead panel left side: Cockpit Door Controller also is not equipped with integral lights and should never light up. One1E#8499
