### ISSUE TITLE
ELECTRICAL MAIN BUS VOLTAGE variable reporting 24.5V on cold/dark start

### ISSUE THREAD

**Issue by mjchernis** [flybywiresim/aircraft#5979]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-10-07T20:11:12+00:00",
  "ref": "master",
  "sha": "5ff82c0fa89fb80448d9106364703ee27f457428",
  "actor": "bouveng",
  "event_name": "manual"
}
```

### Describe the bug

The SIMCONNECT variable ELECTRICAL MAIN BUS VOLTAGE  is showing 24.5 volts when external power is disconnected and the generators/batteries are all off.   I believe it should be zero -- the stock 320/787/747 all run zero with everything disconnected or off.   It does jump up properly to 28v when batteries or generators are turned on.

Messes up the virtual power settings on remote cockpit devices/fips/panels.  Looked for an LVAR variable to replace it that properly shows the power bus state but could not find one.     

### Expected behavior

Variable should be ZERO on cold/dark dark like on other airliners.

### Steps to reproduce

Spawn aircraft to jetway -- cold/dark.   Make sure everything is off--external power is only listed as Avail.

Check SIMCONNECT variable:  ELECTRICAL MAIN BUS VOLTAGE.   Shows 24.5 when it should be zero. 

### Discord Username (optional)

MarkJC

**Comment by tracernz** [comment]
> 
> Harsh response, no? Was just trying to help. 

A little. Please don't take it personally. :)

> I’m a HUGE fan of everything you guys are doing! Does not seem “obvious" at all that the main would be at 24V with the batteries and external power disconnected. Especially, when the batteries read 27.9V on the OVHD. Assuming the batteries are connected to the main bus when switched off — which I suppose could be correct — where did the 3.9V go? And, if the batteries are still connected to the Main on this model (not to be confused with the stock airliners) when switched off, what do the battery switches actually do? Mark

We have our own electrical simulation, so we don't really use the MSFS one as such, although we do need it switched "on" to make some of the other built-in MSFS things work properly. The actual state of the A32NX elec system is contained in the simvar doc I linked previously, and not in the built-in sim variables.

**Comment by tracernz** [comment]
Search for the prefix `A32NX_ELEC` in that doc.
