### ISSUE TITLE
Strobes doesnt iluminate high Cirrus. 

### ISSUE THREAD

**Issue by brufervelit** [flybywiresim/aircraft#6007]
### Aircraft Version

Experimental

### Description

Good Morning Everyone, Was an awesome work on the lights on the last release. There is one thing i would request referring to the strobe lights. At night when im at cruise level when you are flying through high cirrus (like fog or something like that)  cant actually be aware that are actually there because strobe lights doesnt reflect/illuminate them. Strobe iluminates very strong other clouds like cumulus or Stratus ob lower levels, but not in this kind of clouds at high altitudes.  So on Icing conditions (between SAT 0 -40) you got to switch anti ice on when you are on humidity (high cirrus for example) but cause of the strobes not iluminating them we cant know if there are actually there. I noticed this when im near a Thunderstorm and the lighting iluminates the cirrus, and i realize that im in a huge amount of cirrus without notice it. This could be “dangerous” if you are in icing conditions. Thats  my request, hope i can help with this report. Thank you. And great work on the aircraft. 

### Additional info (optional)

Strobes doesnt iluminating high Cirrus in Icing Conditions could affect the flight safety, cause you dont know they are actually there so you can switch the anti ice on. And also would be great for the eyes.

### Discord Username (optional)

brufervelit#9807

**Comment by bouveng** [comment]
@brufervelit Hi! Lights illuminate clouds if the clouds have the right properties. This is nothing we can control or sense. Lights can either be volumetric and illuminate clouds, or not. Strobes are set to be volumetric and if they don't illuminate the cirrus then the cirrus cant be illuminated. I do not know how to fix this request.

The Airbus will warn you if in icing conditions that require anti-ice. It can also be calculated using temp and dewpoint.
