### ISSUE TITLE
[REQUEST] Support making 3D model changes

### ISSUE THREAD

**Issue by adenflorian** [flybywiresim/aircraft#604]
Master tracking issue for the glTF importer/exporter effort.

The main goal is to be able to import the plane model into blender, make modifications, and export back to glTF + bin file, and have it work in the mod.

1st milestone to work towards, is being able to import the plane into blender, and then export, without any modifications, and have the resulting gltf + bin match the vanilla ones, that way we know the tools are working.

# High Level TODO

- [ ]  fork official gltf io
    - [ ]  get mesh to show up in game
        - [ ]  add asobo mesh optimization extension
        - [ ]  look into other reasons why the mesh wouldnt display ingame
- [ ]  exporter
- [ ]  importer
- [ ]  import, export, then import it into blender AGAIN

I'm currently working on my fork of the official blender gltf2 importer/exporter: https://github.com/AdenFlorian/glTF-Blender-IO-a32nx. Importer mostly works, a couple skinned mesh positioning issues. Exporter needs a lot of work.

[https://www.khronos.org/files/gltf20-reference-guide.pdf](https://www.khronos.org/files/gltf20-reference-guide.pdf)

[https://docs.blender.org/api/current/info_overview.html](https://docs.blender.org/api/current/info_overview.html)

**Comment by tracernz** [comment]
I've written a patch that goes toward a couple of your goals: https://github.com/tracernz/msfs2blend/commit/655cca50fc441813cafe6d1120734a58c2ef2273. It's on top of https://github.com/bestdani/msfs2blend/pull/9, as I wrote it miguidedly in my attempts to fix that issue.
