### ISSUE TITLE
Aircraft altimeters shouldn't increment altitude on inHg

### ISSUE THREAD

**Issue by jcalor** [flybywiresim/aircraft#6089]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-10-26T18:35:23+00:00",
  "ref": "master",
  "sha": "8deaa453296a42f887e9a13fcb238754f49674b5",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Any altimeter (PFD, ISIS) should not increment altitude when it is on inHg and inHg is not the same as hPa. For example: If we have 29.93inHg (QNH 1014), if we increase it (29.94, 29.95), it should not increment altitude, ONLY when hPa and inHg coincides. It´s like the altimeter uses hPa internally, and rounds the inHg value to nearest, BUT it doesn´t increments altitude until 1 hPa is increased.

### Expected behavior

Altitude should increment only 1hPa by 1hPa, not every 0.01inHg as it is doing now on every aircraft altimeter

### Steps to reproduce

1. Load plane
2. Put QNH 1014 (for example)
3. Change to inHg
4. inHg should be now on 29.93. Increase it to 29.94 or 29.95 for example. It will increase the altitude

### References (optional)

Shared a video from real aircraft on #quality-assurance channel on Discord. Contact @tracernz or @BlueberryKing for more information.

### Discord Username (optional)

Jorge#6816

**Comment by derl30n** [comment]
Issue resolved

**Comment by tracernz** [comment]
This is still valid AFAIK? The in.Hg corrections are not truncated to the nearest hPa unit. Once MS fix the QNH correction in the sim altimeter I can continue implementing corrections properly in our ADIRU.

**Comment by derl30n** [comment]
Oh wait, I think I miss read the issue and did a test in msfs that proved nothing, whooopsie
