### ISSUE TITLE
CTD when starting an approach

### ISSUE THREAD

**Issue by Nocovabby** [flybywiresim/aircraft#6098]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-10-28T18:01:48+00:00",
  "ref": "v0.7.1",
  "sha": "8d8fb7132f1be95a336f25a6e8441b1420d74989",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Each time I start an approach (manual or auto) I experience Crash To Desktop. CTD occurs when I reach VIAS point

What I tried: 
Different approach (ILS, RNAV, Manual): Same issue
Empty community folder of all content but FBW A32NX: issue persists
Uninstall and Reinstall FBW A32NX via FBW Installer: issue persists
Uninstall and Reinstall MSFS then install FBW A32NX v0.7.1: Issue persists

### Expected behavior

No CTD

### Steps to reproduce

1. Load Aircraft at parking (LFMT Gate 1A in one of my tries)
2. Take off and select a cap and alt manually (330° FL140)
3. After a few minutes return to Airport using an approach(ILS Y 30R, RNAV 12L)
4. Crash should happen when reaching first approach point

### Additional info (optional)

It was working before. Issue started to occur between v0.7.0 and v0.7.1 release

### Discord Username (optional)

nocovabby#6186

**Comment by BlueberryKing** [comment]
Does this happen with other aircraft? Also, please join us on our Discord server https://discord.gg/MVtWqmyG. We can help you find the issue there.

**Comment by Nocovabby** [comment]
> Does this happen with other aircraft? Also, please join us on our Discord server https://discord.gg/MVtWqmyG. We can help you find the issue there.

No, I tried with several aircrafts including Vanilla A320 and issue does not occur.

**Comment by Vitorcm86** [comment]
Hello!

I'm facing exactly the same issue. I've tried a lot of different airports, altitudes, procedures, I've got same result every single time.
I've tried other planes with no problem.
