### ISSUE TITLE
Door opening issue

### ISSUE THREAD

**Issue by SebaDavinch** [flybywiresim/aircraft#6114]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-10-28T18:01:48+00:00",
  "ref": "v0.7.1",
  "sha": "8d8fb7132f1be95a336f25a6e8441b1420d74989",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

I accidentally clicked door button on the pad.
When you're flying on altitude like 2000-6000ft (I did not tested if it works higher also) you can open aft door
https://media.discordapp.net/attachments/838166223430090752/904355508771749908/unknown.png
But i can't do it with the front.

But there's no any door warnings appeared.

Only if you'll select DOOR page you'll see this:
https://media.discordapp.net/attachments/838166223430090752/904355852230721606/unknown.png

### Expected behavior

You can open DOOR AFT while flying. But you can't do the same with FRONT. But in this moment there's no any doors warning.

### Steps to reproduce

1. Take-off from any airport
2. Climb altitude 2000-6000ft
3. Go to the FlyPad and open aircraft ground services page
4. Click on DOOR AFT

### Discord Username (optional)

SebaDavinch#1870

**Comment by juliansebline** [comment]
Hi!

Is disabling the buttons if we are airborne is enough ? What do you think?
