### ISSUE TITLE
Checklists stop advancing on tick.

### ISSUE THREAD

**Issue by kwstoudt** [flybywiresim/aircraft#6184]
### Aircraft Version

Stable

### Build info

```json
{
  "built": "2021-11-08T18:43:55+00:00",
  "ref": "v0.7.2",
  "sha": "db3e3d606b3f003adbf16f38ed031fd4a6d85642",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

The checklist pages stop advancing after ticking certain items:

Preliminary Cockpit Prep: Rain Repellent Pressure and Quantity (INOP)
Cockpit Preparation: Overhead Panel > Fuel Mode Selector
Takeoff: At Acceleration Altitude > FMA
Climb: At 10000FT > Landing Lights
Descent: At 10000FT > Landing Lights
ILS Approach: Initial Approach > PERF Approach Phase
Non-Precision Approach: Initial Approach > Seatbelt Signs
Landing: At Touchdown > Engine Reversers
Go-Around: At Go-Around Thrust Reduction Alt > Thrust Levers
Rudder Jam (Emergency): For Approach > For Landing
Stabilizer Jam (Emergency): Appr Proc > For LDG

### Expected behavior

After ticking an item on any of the checklists, the list should automatically advance to highlight the next item.

### Steps to reproduce

1. Open Checklist Panel
2. Choose one of the above checklists
3. Select the first item in the checklist
4. Start clicking the "Tick Item" button until the list stops advancing

### References (optional)

https://user-images.githubusercontent.com/4512688/141817698-f70240bc-c474-4a13-9e5f-738f28ec5129.mp4

### Discord Username (optional)

kwstoudt#0622

**Comment by jmfs** [comment]
I think this might be a sim issue somehow, because some of the TBM 930 checklists do the same.

**Comment by derl30n** [comment]
Is this still an issue?
