### ISSUE TITLE
Missing Caution Decals

### ISSUE THREAD

**Issue by lolisec** [flybywiresim/aircraft#6251]
### Aircraft Version

Development

### Description

I recently notice while watching a few yt videos that the aircraft is missing some warning labels at first I thought this was only for that certain airlines livery but quickly realized it wasn't as I checked many other walk around videos.

Below I've provided how things currently look like in the sim.

![image](https://user-images.githubusercontent.com/50394269/143662851-fd50a551-e994-47ae-bfa0-384c39088b05.png)
![image](https://user-images.githubusercontent.com/50394269/143662679-deae8c63-8390-4b8f-b058-17a03d3db2b8.png)
![image](https://user-images.githubusercontent.com/50394269/143662781-19e6d8af-70f8-4e02-8dc5-8531da504ec4.png)
![image](https://user-images.githubusercontent.com/50394269/143662833-e5e79bdb-f9dd-44e0-95e9-2e51678d39b3.png)

### References (optional)

![image](https://user-images.githubusercontent.com/50394269/143662855-adda030c-8e72-4bb6-8a1e-92e6c34b62a6.png)
![image](https://user-images.githubusercontent.com/50394269/143662869-db44d28e-ca24-49da-9356-644e465f733e.png)
![image](https://user-images.githubusercontent.com/50394269/143662881-7c6a013e-f98e-431a-83bd-cb44110e44c6.png)
![image](https://user-images.githubusercontent.com/50394269/143662885-253cc473-804d-45bb-b84f-2a7057dca33c.png)
![image](https://user-images.githubusercontent.com/50394269/143662899-6ff1266a-3dcc-46e6-8704-d86cf9576807.png)
video screenshots were taken from:
https://www.youtube.com/watch?v=LNPrGbdWIbU
more examples of those tag
https://www.youtube.com/watch?v=Tdf_Ac7_gwA
https://www.youtube.com/watch?v=2B7Ku9ufxTk
https://www.youtube.com/watch?v=5kxH_li4LIc

**Comment by bouveng** [comment]
This is being worked on and all decals for this is created.
