### ISSUE TITLE
Perfomance Issue

### ISSUE THREAD

**Issue by DanP77** [flybywiresim/aircraft#6357]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-12-11T21:50:08+00:00",
  "ref": "master",
  "sha": "a67929151b900ead0589f00d7c58556562c48a75",
  "actor": "Benjozork",
  "event_name": "manual"
}
```

### Describe the bug

Performance (FPS )drop from the cockpit, and GPU working only at 60%

### Expected behavior

I have fixed max 30fps in my sim config.
from external I may be able to reach this FPS, from inside the GPU work only a few % and FPS drop.

### Steps to reproduce

Every flight on my case

### Additional info (optional)

How I can improve this situation, or How i can provide you the information to understand this issue? 

From the cockpit, with GPU working bad
![image](https://user-images.githubusercontent.com/72685565/146004481-0e42f51a-853d-4c8e-8261-73efa421474a.png)

From outside (typically heavier in the sims), but GPU is working better
![image](https://user-images.githubusercontent.com/72685565/146005607-daffe700-d2a0-43cb-acab-9f2785965f4e.png)

**Comment by DanP77** [comment]
Already a discussion on the Flight Simulator Forum

https://forums.flightsimulator.com/t/coherent-gt-and-performance-decreasing-during-flight/407244/

**Comment by Benjozork** [comment]
Hi, this can be caused by a known issues with the navigation display on some routes. Next time you have it, can you try turning both of them off for 20 seconds to see if this is the issue ?

**Comment by DanP77** [comment]
> Hi, this can be caused by a known issue with the navigation display on some routes. Next time you have it, can you try turning both of them off for 20 seconds to see if this is the issue ?

Really?
Thank you! I will try!!!

**Comment by Seth-Dark** [comment]
I could confirm also an fps drop performance issue inside the cockpit. After many tests i found which was the main cause ( at least in my situation).  When the navigation display is at 10 range/change after take off preparation with all engines working there is a big hit on fps. When i change the range to maximum range ( 320) fps become normal as it was. Looks like when range is at 10-40 range area gpu start to decrease. 
Marry christmas and a happy new Year

**Comment by DanP77** [comment]
At the moment I've only tried to switch off displays PFD and ND (CPT and FO) during flight.
There is a difference of about 10fps in my case (I have set limit to 30fps)

**Comment by Benjozork** [comment]
Can anyone having issues test this build ?

https://api.flybywiresim.com/api/v1/download?url=https://flybywiresim-packages.b-cdn.net/experimental/A32NX-experimental.zip

**Comment by DanP77** [comment]
I tested this build. In My case same behavior.

Outside the airplane 30fps (locked by conf)
From inside the performance drop till 15fps and less.

there are no significative changes between ND set from 10NM and 230NM

Performance have a significative improve switching off the Panels (close to 30FPS)

All performance DROP seems related to "CoherentGTUIThread"


The test was done in the following condition
DX11
Online on IVAO (as my previous flights)
Costant speed and altitude 
Good weather (no significative clouds)

My GPU configuration:
Radeon RX590 with the latest drivers.

**Comment by DanP77** [comment]
> Can anyone having issues test this build ?
> 
> https://api.flybywiresim.com/api/v1/download?url=https://flybywiresim-packages.b-cdn.net/experimental/A32NX-experimental.zip

I tested this build. In My case same behavior.

Outside the airplane 30fps (locked by conf)
From inside the performance drop till 15fps and less.

@Seth-Dark  there are no significative changes between ND set from 10NM and 320NM in my case

Performance have a significative improve switching off the Panels (close to 30FPS)

All performance DROP seems related to "CoherentGTUIThread"

The test was done in the following condition
DX11
Online on IVAO (as my previous flights)
Costant speed and altitude
Good weather (no significative clouds)

My GPU configuration:
Radeon RX590 with the latest drivers.

**Comment by Benjozork** [comment]
> > Can anyone having issues test this build ?
> > 
> > https://api.flybywiresim.com/api/v1/download?url=https://flybywiresim-packages.b-cdn.net/experimental/A32NX-experimental.zip
> 
> I tested this build. In My case same behavior.
> 
> Outside the airplane 30fps (locked by conf)
> From inside the performance drop till 15fps and less.
> 
> @Seth-Dark  there are no significative changes between ND set from 10NM and 320NM in my case
> 
> Performance have a significative improve switching off the Panels (close to 30FPS)
> 
> All performance DROP seems related to "CoherentGTUIThread"
> 
> The test was done in the following condition
> DX11
> Online on IVAO (as my previous flights)
> Costant speed and altitude
> Good weather (no significative clouds)
> 
> My GPU configuration:
> Radeon RX590 with the latest drivers.

Any screenshots ?

**Comment by DanP77** [comment]
> Any screenshots ?

Sorry, I didn't get them.
If need I will test it again in next days

**Comment by Seth-Dark** [comment]
Ok after many flight-routes  i didn't have any fps drop and  ND range/change worked with out any issue ( all ranges). 
Possibly a specific flight plan created this issue. 
@DanP77 Which is your  TOD settings? I had some fps drop ( on cruise mode)  when i had tod at 300. Try to decrease at 100 and check performance

**Comment by Benjozork** [comment]
@Seth-Dark Were you using the build I linked ?

**Comment by Seth-Dark** [comment]
> @Seth-Dark Were you using the build I linked ?

No i used the latest dev build. Made 3 different flight routes in Europe. No issues, fps stable and smooth. 
Will check more today

**Comment by Benjozork** [comment]
If a specific route can be isolated it can help narrow down the issue.

**Comment by Seth-Dark** [comment]
> If a specific route can be isolated it can help narrow down the issue.

I had those fps drops while changing ND range on LGAV as departure airport. Will check more today

**Comment by Benjozork** [comment]
Which departure ?

**Comment by DanP77** [comment]
> @DanP77 Which is your TOD settings? I had some fps drop ( on cruise mode) when i had tod at 300. Try to decrease at 100 and check performance

If you mean ND distance, I tested all.

**Comment by Seth-Dark** [comment]
> Which departure ?

Dont remember exactly which route had the issue, but for sure it was from LGAV airport as departure airport. I made a test flight yesterday and i had many stutters even with high fps ( 40 to 60 ) when i was panning around cockpit. The only solution to make it smooth was to turn off both Navigration displays. Just saw Experimental edition is back on Installer, should we use that build ? thanks

**Comment by Seth-Dark** [comment]
> > @DanP77 Which is your TOD settings? I had some fps drop ( on cruise mode) when i had tod at 300. Try to decrease at 100 and check performance
> 
> If you mean ND distance, I tested all.

I mean terrain level of detail. Looks like that everything over 100 creates some serious fps drops /stutters while you are on cruise mode with A32NX. I could confirm also that B787(heavy-decision mod) and CRJ 700-1000 works perfect with out any issue even on 300 ( tod)

**Comment by Benjozork** [comment]
https://forums.flightsimulator.com/t/after-playing-a-few-hours-fps-drops-from-40-to-5fps/389603/959

Are any of you using live weather ?

**Comment by Benjozork** [comment]
> > Which departure ?
> 
> Dont remember exactly which route had the issue, but for sure it was from LGAV airport as departure airport. I made a test flight yesterday and i had many stutters even with high fps ( 40 to 60 ) when i was panning around cockpit. The only solution to make it smooth was to turn off both Navigration displays. Just saw Experimental edition is back on Installer, should we use that build ? thanks

Yes, can you try it? And have Live Weather disabled before you start the flight.

**Comment by Seth-Dark** [comment]
> > > Which departure ?
> > 
> > 
> > Dont remember exactly which route had the issue, but for sure it was from LGAV airport as departure airport. I made a test flight yesterday and i had many stutters even with high fps ( 40 to 60 ) when i was panning around cockpit. The only solution to make it smooth was to turn off both Navigration displays. Just saw Experimental edition is back on Installer, should we use that build ? thanks
> 
> Yes, can you try it? And have Live Weather disabled before you start the flight.

I will make some test flights later with and with out live weather and different aircrafts. Dont think its from Live Weather as yesterday i think i was on clear skies ( live weather never worked )

**Comment by Benjozork** [comment]
Make sure it is disabled **before** you start the flight.

**Comment by Seth-Dark** [comment]
> Make sure it is disabled **before** you start the flight.

Made 2 flights yesterday with Experimental build and Rex Weather Force. Didn't have any fps issue or stutter so far. 
Never had the ND change-range weird issue also.  Just a question which is out of topic: Trying to connect the MCDU web interface on my ipad. PC is connected via Ethernet cable connection while Ipad is with Wifi on the same network. Is this an issue? thanks

**Comment by speedwaystar** [comment]
> trying to connect the MCDU web interface on my ipad. PC is connected via Ethernet cable connection while Ipad is with Wifi on the same network. Is this an issue? thanks

i had to let the server process through the Windows 10 firewall before machines on my local network could display the MCDU webpage.

**Comment by DanP77** [comment]
> > > Can anyone having issues test this build ?
> > > https://api.flybywiresim.com/api/v1/download?url=https://flybywiresim-packages.b-cdn.net/experimental/A32NX-experimental.zip
> > 
> > 
> > I tested this build. In My case same behavior.
> > Outside the airplane 30fps (locked by conf)
> > From inside the performance drop till 15fps and less.
> > @Seth-Dark  there are no significative changes between ND set from 10NM and 320NM in my case
> > Performance have a significative improve switching off the Panels (close to 30FPS)
> > All performance DROP seems related to "CoherentGTUIThread"
> > The test was done in the following condition
> > DX11
> > Online on IVAO (as my previous flights)
> > Costant speed and altitude
> > Good weather (no significative clouds)
> > My GPU configuration:
> > Radeon RX590 with the latest drivers.
> 
> Any screenshots ?

Here the requested screenshot

![image](https://user-images.githubusercontent.com/72685565/148655797-d4ba6c2b-d191-4a51-a561-a558a835d1fc.png)

![image](https://user-images.githubusercontent.com/72685565/148655811-fdf61dd5-fc9e-4a90-bc16-a1273328a493.png)


Check the different usage of GPU.
From outside I'm close to HW limit.
From inside CoherentGTUIThread is the limit.


With WT CJ4 that's not happen.

**Comment by DanP77** [comment]
I also tried other planes with Garmin and analog instrument.
The issue seems related only to FBW. ASAP I will try the Vanilla.

Anyway early will arrive SU8, to recheck better.

**Comment by DanP77** [comment]
Vanilla seems not affected by this issue.

**Comment by DanP77** [comment]
Partial Workaround.
I reduced as suggested (but with other airplanes I do not have this issue), refresh of the panel from High to Medium.

The results:

![image](https://user-images.githubusercontent.com/72685565/151530210-43e52f5a-f516-4358-9c06-05b3bc7b8867.png)

Now is usable, but the problem persist:

![image](https://user-images.githubusercontent.com/72685565/151530659-2506a651-369f-4144-9404-23d141e8e571.png)

Look the GPU utilization and performance stability from outside

**Comment by gandalfthewhite19890404** [comment]
Here is video, with experimental version 2022-03-22. You can see PFD slowdown, but ND and other displays was fine.
BUT you can see PFD became normal at approximately 800 feet.
https://drive.google.com/file/d/1t5B2VRk5nS0k-awAIs_ZWyBPW6ffs3xW/view?usp=sharing
