### ISSUE TITLE
LNAV fixed turn predictions after DECEL, and flap 1 & 2 pseudo-waypoints should factor in deceleration to those speed constraints

### ISSUE THREAD

**Issue by wpine215** [flybywiresim/aircraft#6495]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-01-04T08:12:39+00:00",
  "ref": "experimental",
  "sha": "00c94c19d48c6d75b813cc5d8abd0d7b64c47b02",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Currently, when viewing the navigation display showing the flight plan after a pseudo-waypoint with deceleration associated with it, the flight plan following the pseudo-waypoint does not factor in the lower speed which occurs after said pseudo-waypoint - it instead factors in the current speed or the last speed constraint of a non-pseudo waypoint. This leads to "fish-birding" of that portion of the drawn flight plan until the pseudo-waypoint in question is passed, or speed decreases significantly later in the flight. 

Although in most cases, this issue is visual only, it is still inaccurate to the real Honeywell FMS, and in some instances where a turn immediately follows a pseudo-waypoint, the plane can follow the incorrect, abnormally wide path before the predictions have a chance to correct it for the new speed.

### Expected behavior

Considering proper VNAV is still in the works, in the meantime, the aircraft should hardcode speed for the flight plan following DECEL as green dot speed (typically 210 - 225 kts, it varies but can be read from a simvar), the flight plan after Flap 1 pseudo-waypoint should assume ~195 kts (S speed), and the flight plan after Flap 2 pseudo-waypoint should assume some speed between F speed (lower bound) and 180kts.

### Steps to reproduce

1. Fly the flight plan `GCLA36 BIMB6T BIMBO IBBAN IBAN1P RNAV05Y LPMA05` with proper data entry in FMC (loading 100 passengers and 13,000 lbs of fuel, with cruise level of FL100 and cost index of 30).
2. Observe that prior to passing DECEL and the approach waypoint `MA508`, the turn prediction displayed on the ND is incorrect and far too wide - see screenshot below.
3. As you pass DECEL and begin to decelerate, the plane will follow the incorrect turn before predictions have a chance to factor in the new current speed, and will guide you into terrain, leading to a crash unless pilot intervention takes place.

### References (optional)

Prior to DECEL:

![image](https://user-images.githubusercontent.com/28059870/148482203-8c213c8f-2e2b-4489-accd-01c0be4479ad.png)

After DECEL, approaching flap 1 and 2 pseudo waypoints; controlled flight into terrain:

![image](https://user-images.githubusercontent.com/28059870/148482269-cba9b01f-6a05-44d0-9c91-26409d0390fc.png)

### Discord Username (optional)

Iceman#5540

**Comment by tracernz** [comment]
The "predicted" speed is already upper-limited by 250 knots for departure, arrival, and approach, and any applicable constraint. The "predicted" speed is not used when the leg is one of the next 3... then current speed is used.

**Comment by wpine215** [comment]
> The "predicted" speed is already upper-limited by 250 knots for departure, arrival, and approach, and any applicable constraint. The "predicted" speed is not used when the leg is one of the next 3... then current speed is used.

Ah i see. Updated the original post to remove the SPD LIM reference then.

As for using current speed instead of predicted speed for the 3 upcoming turns, is there a reference from documentation that states the limit? If it's just an assumption and not directly referencing anything, we should probably look into revising that for DECEL and Flap 1 at the very minimum. 

Although this is a slightly different approach (RNAV 05Z at the same airport), and for lack of a real-life reference video, here's a clip of the ToLiss A321 performing that approach - with the curve after decel remaining fairly constant in radius, without fishbirding:

https://www.youtube.com/watch?v=QGQMonUrQl0

**Comment by BlueberryKing** [comment]
Is this still relevant after https://github.com/flybywiresim/a32nx/pull/6808 was merged?

**Comment by 2hwk** [comment]
Definitely solved as of fms v2
