### ISSUE TITLE
MCDU: FUEL PRED page might disappear by filling ZFW

### ISSUE THREAD

**Issue by madebylydia** [flybywiresim/aircraft#6746]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-02-15T13:54:28+00:00",
  "ref": "master",
  "sha": "b497a6f857568cbf5f3922dcd9a8e34f12c22d00",
  "actor": "aguther",
  "event_name": "manual",
  "pretty_release_name": "master:b497a6f8"
}
```

### Describe the bug

When trying to populate the "ZFW/ZFWCG" in the MCDU, there might be a chance that the FUEL PRED page disappear. This seems to happens in different place, but resulting in the same behavior.
I had the same behavior when on ground, but only the page "FUEL PRED" (using the "FUEL PRED" button) was disappearing, however, the page "INIT B" (Clicking "INIT" then using a horizontal button).
But when I was in cruise, the disappearance behavior both happened in "FUEL PRED" and "INIT B". I assume that in cruise, they are the same page, but not on ground.

The page restore itself only after putting again the ZFW value.

### Expected behavior

The "FUEL PRED" page to act completely normally. :)

### Steps to reproduce

1. Setup fuel & paload and board all your passengers.
2. Go to "FUEL PRED" using the button "FUEL PRED". (This was it won't matter if you're on ground or cruise)
3. Click the button next to "ZFW/ZFWCG", and wait a little moment.
4. When the page disappear, you got the bug. Click on the same button as before to get the page on a normal state.

### References (optional)

The following was taken when in cruise:

https://user-images.githubusercontent.com/61093863/154556394-4cb1bf89-d31d-4242-b42f-b2922c46fc8c.mp4

I will take the same shot on ground ASAP! (Will edit this comment)

### Additional info (optional)

Please note that I'm a beginner, my issue might contain incorrect wordings and should be taken with caution/care, if so, feel free to correct me/ask for more informations. :) 

### Discord Username (optional)

Capt. Pred#0495

**Comment by Predeactor** [comment]
Apparently, just inserting the ZBW value isn't just enough, block also must be filled too. I also recommend filling a flight plan (With or without SimBrief shouldn't matter) to test this bug out.

Here's the same take as done before, but on the ground:

https://user-images.githubusercontent.com/61093863/154586265-e536e5d6-f856-47ce-90ee-e86c3a4d5e0d.mp4

**Comment by Maximilian-Reuter** [comment]
Pretty sure this isn't a bug anymore, if wrong please reopen
