### ISSUE TITLE
MCDU crashes / flightplan gets lost some time during flight - possible reason

### ISSUE THREAD

**Issue by Watsi01** [flybywiresim/aircraft#6843]
### Aircraft Version

Development

### Build info

```json
All dev and exp versions since implementation of cFMS.
```

### Describe the bug

I'm writing this here for documentation reasons. I may know why MCDU crashes / whole flightplan gets lost sometimes during flight (at least with a special use).
If you use a .pln file with MSFS (which gets imported into the MCDU), there are some glitches with cFMS (all versions).
1. any radio based fp waypoint is put at the end of the flightplan (no matter of their actual/correct position in fp)
2. the last two waypoints before destination are lost during import into MCDU and have to be added manually into the MCDU

I found out, that if one or both of these last two waypoints are part of an airway in the flightplan, the MCDU get's confused (cause they are lost when importing the fp / .pln into the MCDU) and will crash eventually. Even if you add them manually before departing from the gate, the MCDU still can crash some time during flight. 
If you build a flightplan and let the airway end **before** these last two waypoints, add them just as waypoints into the flightplan (and add them manually into the MCDU before departing), the MCDU won't crash.

I don't know if this is also an issue with SimBrief flightplanning (since I rarely use SimBrief > using LittleNavMap). But just in case...

### Expected behavior

MCDU not crashing. And if a good fairy would ask me: correct .pln import into MCDU with cFMS. 

### Steps to reproduce

see description.

### Discord Username (optional)

RogePete

**Comment by tracernz** [comment]
We should really decide if it's worth keeping MSFS plan syncing... it will be a lot more problematic with cfms-20, when we are not necessarily using the same nav database as MSFS.

**Comment by Watsi01** [comment]
> We should really decide if it's worth keeping MSFS plan syncing... it will be a lot more problematic with cfms-20, when we are not necessarily using the same nav database as MSFS.

I actually would like to keep it. At least the "load only" option. Even if it is bugged.

**Comment by Maximilian-Reuter** [comment]
this issue can be closed I think.
