### ISSUE TITLE
ENG Going off limits When Cruise

### ISSUE THREAD

**Issue by Lifedark** [flybywiresim/aircraft#6889]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2022-03-10T23:32:48+00:00",
  "ref": "master",
  "sha": "ba9ba9bb993fc350bb04028de63de1a1149b3479",
  "actor": "tracernz",
  "event_name": "manual",
  "pretty_release_name": "master:ba9ba9bb"
}
```

### Describe the bug

Well If plane its in cruise ENG Going off limits of Cost index 

### Expected behavior

![Przechwytywanie](https://user-images.githubusercontent.com/85799812/157887647-0ebde5a5-523d-4fbd-b6f8-1bbe9d9c8ff3.PNG)
e

### Steps to reproduce

1, Setup flight plan
2, Takeoff 
3, Go to cruise and set new ALT And should work if no dm me

### References (optional)

Check expected behavior

### Additional info (optional)

.

### Discord Username (optional)

dsdmnbc1#4494

**Comment by hotshotp** [comment]
This is completely within limits, what's the issue?

**Comment by Lifedark** [comment]
Uh this Orange/ Red thing its not limit thing?

**Comment by Lifedark** [comment]
Bruh, Sorry about this im dumb

**Comment by WJAtkin-2021** [comment]
Are you talking about the orange notch on the N1 reading or the TCAS STBY warning?

**Comment by tracernz** [comment]
> Bruh, Sorry about this im dumb

The orange carrots should not be below the thrust limit AFAIK, so seems valid to me.

**Comment by Lifedark** [comment]
> 
Oh im don't know

**Comment by Lifedark** [comment]
> 
All its good im thinked this orange thing should not be below When takeoff/Cruise

**Comment by WJAtkin-2021** [comment]
I think I found the issue, the amount of throttle used by the climb detent increases as you increase your altitude but the orange carrots do not move to reflect this.

**Comment by aguther** [comment]
Yes, this is correct the orange marks should move. This will happens with the rewrite of the EWD. You can try out experimental version, it contains this already.

**Comment by aguther** [comment]
I need to correct myself. The orange bar needs to equal TOGA limit in the current conditions. Needs to be updated in the new EWD.
