### ISSUE TITLE
Gravity Gear Extension sound plays while parked on ground.

### ISSUE THREAD

**Issue by notleks2411** [flybywiresim/aircraft#7159]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-05-04T17:19:01+00:00",
  "ref": "experimental",
  "sha": "02215d4b5cbfff87f91a06b01a84fd58b89fdb02",
  "actor": "Benjozork",
  "event_name": "manual",
  "pretty_release_name": "experimental:02215d4b"
}
```

### Describe the bug

After I completed my flight and was shutting down the aircraft, I noticed the Gravity Gear Extension was functional, and out of curiosity, I decided to click and turn it. After a few seconds as expected, and gear lowering sound was played, while parked sat at a gate. I figure this doesn't seem correct, if the aircraft is already parked up with gears down.

### Expected behavior

I would expect the sound not to play while the gear is down already. Why would it play if wheels are already down?

### Steps to reproduce

1. Park up on ground
2. Proceed to gate/park up/stop/which ever. (in my case, I was preparing to shut down the aircraft after securing and passengers have disembarked)
3. Scratch your head wondering if the GGE actually works like I did
4. Upon click and holding, gear lowering sound is played.

### Additional info (optional)

I found this out from curiosity. Just didn't seem normal to me.

### Discord Username (optional)

notleks#5398

**Comment by notleks2411** [comment]
> Is it just the clunk? The clunk is the doors unlocking which would indeed happen on the ground if you turned the handle

Um... possibly? I'm unsure, but it did sound very similar to the whole gear opening up and extending. I could be wrong.

I'm currently AFK, but I'll try this again later tonight and post the results. It just sounded like the normal landing gear sound, although I could be wrong.

**Comment by notleks2411** [comment]
https://youtu.be/2yWiGbwJ0cA

I had the Wheel page on lower ECAM popped out as a window, but Xbox Game Bar didn't capture it for some reason. But this is what I was talking about. I don't know if this is normal or not, but wanted to post just in case.

**Comment by hotshotp** [comment]
Okay yeah this is not intentional... I'll take a look

**Comment by juliansebline** [comment]
Up on this
