### ISSUE TITLE
Descend mode triggered in climb

### ISSUE THREAD

**Issue by Venorcis** [flybywiresim/aircraft#7247]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-05-25T01:03:21+00:00",
    "ref": "refs/heads/master",
    "sha": "bba5b4acc558c277c021082e749a20001aecee4b",
    "actor": "2hwk",
    "event_name": "manual",
    "pretty_release_name": "master:bba5b4ac"
}
```

### Describe the bug

The DES mode became active even though I was climbing on the SID.

### Expected behavior

Stay in CLB mode.

### Steps to reproduce

Unsure, see below.

### References (optional)

https://www.twitch.tv/videos/1310637697?t=00h16m30s
On the LOPI3S out of EHAM, CLB mode visible slightly overshot the initial FL60 (due to a very busy frequency)
You can't see the MCDU at the critical time but the 'STD' starts flashing as soon as the AP is enabled, suggesting it reverted to DES at that time (the transition level at my destination LSGG being auto-configured at FL80). Then DES mode shows...

**Comment by tracernz** [comment]
Sort of looks like ALT mode was a little trigger-happy engaging. Upon ALT mode engagement the pressure altitude is memorised and ALT made will attempt to maintain that pressure altitude and it appears that is what it did here.

**Comment by derl30n** [comment]
Looks to me like the DES phase was initialized by the unnecessary pull of the ALT knob (initiating a des since AC alt and sel alt below crz fl) which therefore transitioned the fmgc into DES phase.

**Comment by derl30n** [comment]
Interesting edge case tho, I'd like to know what the real bus would do in relation to pulling the alt knob and trying to initiate a des in that exact situation.

**Comment by derl30n** [comment]
To clarify, the des phase was initiated via the early descend functionality.
