### ISSUE TITLE
[BUG] Engine 1 doesn't works

### ISSUE THREAD

**Issue by Theo3245** [flybywiresim/aircraft#740]
**Mod Version** 0.02

**Describe the bug** I do a cold and dark start and after start the engine 1 and 2 the engine 1 shuts down for no reason (I'm currently using the newest patch, 1.8.3.0)

**To Reproduce**

1.I start the engine 
2.I'm waiting for it to stabilize
3.After few seconds the engine 1 shuts down

**Expected behavior**
I expected the engine 1 works normally and don't shuts down for no reason :)

**Actual behavior**
The engine 1 doesn't works

**References**

**Additional context**

Discord username (if different from GitHub):

**Comment by NathanInnes** [comment]
Duplicate issue as #716 .

Something only happens if you turn your APU off.

Once the APU is on, leave it for a temp work around.

**Comment by Theo3245** [comment]
ok I need to let my APU on during all the flight?

**Comment by NathanInnes** [comment]
Yes. If you don't mind closing this issue and checking #716 just so we dont have dupes

**Comment by Theo3245** [comment]
Ok thank you I will try this :)
