### ISSUE TITLE
INIT REQUEST ... >> NOT IN DATABASE !!!

### ISSUE THREAD

**Issue by aitalinassim** [flybywiresim/aircraft#7403]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-08-04T21:05:45+00:00",
    "ref": "refs/heads/master",
    "sha": "6647ffde2f97df847739b6a16f2a511dcf983c5a",
    "actor": "crocket63",
    "event_name": "manual",
    "pretty_release_name": "master:6647ffde"
}
```

### Describe the bug

I have MSFS 2020 Premium Deluxe Edition

Before and after Take Off, the PFD screen is not showing any plan !!! and the MCDU is not loading the flight plan. Only PPOS is visible.

### Expected behavior

Plight Plan shows in MCDU and PFD.

### Steps to reproduce

I created a route EDDF to EDDP in SimBrief
I have an active subscription to Navigraph Center

I start a new flight with FBW A320 by selecting to departure airport only (EDDF)

I import to FlyPad via SimBrief, all the plan is imported OK

When load to MCDU, the AOC Init is importing EDDF and EDDP

But when making the initiation page and click on Init Request, it imports only the flight number, but not the airports, and shows down NOT IN DATABASE.

I’ve read all the necessary, applied all possible configuration, used all FBW versions, but no changed, always plight plan not showing and INIT Request is giving NOT IN DATABASE.

I do not know where are the data that should be purchased, since I have now an update AIRAC.

### References (optional)

![c8](https://user-images.githubusercontent.com/28365138/183519105-542818c3-9a76-434b-8e8b-6fde3960471f.PNG)
![c6](https://user-images.githubusercontent.com/28365138/183519173-ad6515dd-78fb-4c3a-ad2e-abcec1b957db.PNG)
![c9](https://user-images.githubusercontent.com/28365138/183519206-99a14220-46bc-4839-9789-cd8ee00336c2.PNG)
![c3](https://user-images.githubusercontent.com/28365138/183519221-3ee4c69c-a15e-4f27-a887-edd19960850b.PNG)
![c4](https://user-images.githubusercontent.com/28365138/183519237-d05e2826-4571-4727-9d3d-a1d931a91968.PNG)
![c2](https://user-images.githubusercontent.com/28365138/183519258-c6a5875c-ac84-4c5e-a691-bfc99e99a023.PNG)
![c1](https://user-images.githubusercontent.com/28365138/183519266-cb076a96-6c86-4c72-a2eb-4df93ba83d7a.PNG)
![c7](https://user-images.githubusercontent.com/28365138/183519277-ac0d9333-ba38-446a-943e-b341a8afa40c.PNG)
![Capture](https://user-images.githubusercontent.com/28365138/183518902-c2228a27-d0f8-4c22-ad02-95d2c40cd717.PNG)

**Comment by Benjozork** [comment]
Have you installed Navigraph navdata into your simulator in the past ?

**Comment by aitalinassim** [comment]
No, never.
This is the first time that I install MSFS 2020 then the Navigraph Navdata Center.

Reinstalling all from clean does not resolve the problem.
Manual update of AIRAC to current without Navigraph is importing the database, which I verify in the MCDU screen, but always the same probleme, the MCDU shown NOT IN DATABASE for all the airports. only FLT NBR is imported with INIT REQUEST.

**Comment by tracernz** [comment]
What if you delete content.xml, then start the sim?

**Comment by aitalinassim** [comment]
I did it many times, win+R then %Appdata% and delete the content.xml

No changes, same problem.
The MCDU of original mods  is working very fine, only the one of A32NX have this problem.

**Comment by tracernz** [comment]
... you are using the latest official build of MSFS (sim update 9)...?

**Comment by aitalinassim** [comment]
Yes of course

**Comment by aitalinassim** [comment]
Update

Arrivals and approaches of all airports are not visible and could not be selected as destination.

**Comment by Benjozork** [comment]
Are you able to select them in the world map ?

**Comment by juliansebline** [comment]
Up on this @aitalinassim

**Comment by aitalinassim** [comment]
> Are you able to select them in the world map ?

Yes, in the world map I can select all the airports I want, but not the case in mcdu.

**Comment by anthosz** [comment]
Hello,

I have more/less the same issue (A32NX v0.9.1 (stable) since the last MFS upgrade (1.31.22.0 (not sure if related, last flight was done more/less there is one month).

- Tried several different flight plan
- Tried to restart mfs
- Cannot see any waypoint on the mcdu -> only airport + runway are available but cannot select also sid (no sid availableà
![image](https://user-images.githubusercontent.com/14294064/227648032-18fa2c21-0db2-479a-befb-a7cbc8e9b115.png)
![image](https://user-images.githubusercontent.com/14294064/227648048-e286bac6-e1f2-4924-b60e-e66b9be31bef.png)


Best

**Comment by tracernz** [comment]
Are there any procedures available at the world map, or in the default avionics (e.g. G1000/G3000/CJ4)? Have you had navigraph data installed before and no longer do?

**Comment by anthosz** [comment]
> Are there any procedures available at the world map, or in the default avionics (e.g. G1000/G3000/CJ4)? Have you had navigraph data installed before and no longer do?

-> G1000: All ok, I can find airways, etc
-> World map, no real procedure if switching to IFR:
![image](https://user-images.githubusercontent.com/14294064/227701381-dc6c5cfd-03a6-4c63-be1b-3068a392b91d.png)
-> Navigraph is installed but was not used -> New tentative without simbrief: same / New tentative with simbrief & navigraph: same
![image](https://user-images.githubusercontent.com/14294064/227701695-4fabcf8a-a89c-4fc0-b8dd-b2a40ebd4cf3.png)
-> Using the A320N integrated in MFS ootb:


Continuing investigations

**Comment by anthosz** [comment]
Thank you! Issue fixed: navigraph stuff in "Community" removed -> navigraph navdata center -> reinstalled -> All is back to normal :)

**Comment by Maximilian-Reuter** [comment]
As this is certainly not a plane issue in the current versions available I will close this.
