### ISSUE TITLE
wrong flight plan

### ISSUE THREAD

**Issue by mg153tc** [flybywiresim/aircraft#7411]
### Aircraft Version

Development

### Build info

```json
"built": "2022-08-12T17:01:34+00:00",
    "ref": "refs/heads/master",
    "sha": "050f64530475c68b7156f0a64fa55ac7d5c46738",
    "actor": "2hwk",
    "event_name": "manual",
    "pretty_release_name": "master:050f6453"
}
```

### Describe the bug

Why won't the a320neo load into the mcdu my selected flight plan from msfs 2020 simulator?  It loads correctly into the default asabo a320, and all other aircraft I have tried. My community folder is empty except for the a320neo.  I get this same problem with any a320 version.

### Expected behavior

I expect the selected flight plan to load correctly into the a320neo

### Steps to reproduce

I select a flight plan.
I start the flight.
The a320neo mcdu does not show the selected flight plan, but the msfs 2020 shows the correct flight plan and waypoints.

**Comment by Benjozork** [comment]
Are you spawning at the gate or the runway ? Which flight plan is input into the world map ?

**Note:** It is not recommended to use the built-in MSFS flight planner, as is the norm with other high-complexity aircraft such as the PMDG or fenix.

Instead, we recommend usnig a dedicated flight planning tool like simBrief to plan your flights.

We have a guide on how to seamlessly integrate the two here: https://docs.flybywiresim.com/fbw-a32nx/feature-guides/simbrief/

**Comment by 2hwk** [comment]
https://docs.flybywiresim.com/fbw-a32nx/feature-guides/flypados3/settings/#sim-options

Check that Sync MSFS Flight Plan in the EFB Settings is set to "Load Only" or "Save".
