### ISSUE TITLE
No Flight Plan in MCDU after completing INIT-A

### ISSUE THREAD

**Issue by Sankalp1465** [flybywiresim/aircraft#7432]
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2022-08-21T10:27:14+00:00",
    "ref": "refs/heads/experimental",
    "sha": "35db0fc99a5eb234223c82e3e3a71f185b86f80a",
    "actor": "2hwk",
    "event_name": "manual",
    "pretty_release_name": "experimental:35db0fc9"
}
```

### Describe the bug

I was flying from VIDP TO RJAA (I know this one is out of aircraft range but the bug happens me with me in every flight) and had not set any destination in MSFS I turned on batteries and external power Imported simbrief briefing in FlyPad refueled the aircraft and got to the MCDU configuration and completed INIT-A but no Flight Plan was there in F-PLN section. This happens with me just in A32NX not in default A320 neo.

### Expected behavior

To get the Flight Plan in F-PLN section of MCDU

### Steps to reproduce

1. Go to simbrief and create a flight plan from VIDP to RJAA and use runway 29 for takeoff and RJTT as alternate.
2. Open MSFS don't set an arrival just choose gate 224 of VIDP.
3. Follow the procedures and get into MCDU Configuration.
4. Complete INIT-A.
5. When you will check the F-PLN it will be blank

### References (optional)

![Screenshot 2022-08-22 174723](https://user-images.githubusercontent.com/98591037/185925812-60eceeb5-ecf4-407c-8b20-d87b3488334d.png)
![Screenshot 2022-08-22 174749](https://user-images.githubusercontent.com/98591037/185925866-589ca141-856f-4cb3-9888-8d0676fa6fea.png)

### Additional info (optional)

It happens with me every time no matter what airport or route it is.

### Discord Username (optional)

iamsankalp1465#6570

**Comment by K603AO750rus** [comment]
Hello! I have this problem! I can't think of a solution. Tell me how you managed to cope with it?

**Comment by tracernz** [comment]
Firstly, only the latest version of MSFS is supported at any given time... using older versions by some means will cause this kind of breakage due to API incompatibility.

If this is not the issue, the best thing to do is check in the debugger if you're able... firstly I *think* you need to enable dev mode in the MSFS settings, recreate the fault, then open Chrome (other web browsers may not work), and navigate to http://127.0.0.1:19999... Click `VCockpit08 - A320_Neo_CDU [coui://html_UI/Pages/VCockpit/Core/VCockpit.html]`, click the "console" tab and check for red errors, ignoring 404s.

**Comment by MubasheerSidd** [comment]
I'm having the same Issue with headwind a330

**Comment by archer884** [comment]
So, I'm flying the latest version of the game and the latest version of the plane, and I just had what *seems* to me like the same issue. When I followed the instructions above, it mentions an "unhandled promise rejection." "Cannot access uninitialized variable."

Line 422 in waypoint.js

![image](https://user-images.githubusercontent.com/679494/189462171-4cab7fc4-07d5-4172-a3d7-77259c1b8f9a.png)

**Comment by juliansebline** [comment]
Up on this

**Comment by Alphazor007** [comment]
> Firstly, only the latest version of MSFS is supported at any given time... using older versions by some means will cause this kind of breakage due to API incompatibility.
> 
> If this is not the issue, the best thing to do is check in the debugger if you're able... firstly I _think_ you need to enable dev mode in the MSFS settings, recreate the fault, then open Chrome (other web browsers may not work), and navigate to http://127.0.0.1:19999... Click `VCockpit08 - A320_Neo_CDU [coui://html_UI/Pages/VCockpit/Core/VCockpit.html]`, click the "console" tab and check for red errors, ignoring 404s.

This id the error that i am getting from the Debugger

![image](https://user-images.githubusercontent.com/132583080/236223392-eb66ef57-3bcd-4fa8-8381-2a03222e3b0e.png)

Do you have any soultion for this?

**Comment by Benjozork** [comment]
> > Firstly, only the latest version of MSFS is supported at any given time... using older versions by some means will cause this kind of breakage due to API incompatibility.
> > If this is not the issue, the best thing to do is check in the debugger if you're able... firstly I _think_ you need to enable dev mode in the MSFS settings, recreate the fault, then open Chrome (other web browsers may not work), and navigate to http://127.0.0.1:19999... Click `VCockpit08 - A320_Neo_CDU [coui://html_UI/Pages/VCockpit/Core/VCockpit.html]`, click the "console" tab and check for red errors, ignoring 404s.
> 
> This id the error that i am getting from the Debugger
> 
> ![image](https://user-images.githubusercontent.com/132583080/236223392-eb66ef57-3bcd-4fa8-8381-2a03222e3b0e.png)
> 
> Do you have any solution for this?

This is a simbridge error unrelated to this ticket. Please clearly state which issue you're having, and provide the version of your simulator and aircraft.

**Comment by Maximilian-Reuter** [comment]
this seems to be stale
