### ISSUE TITLE
Crash on Windows version & Windows username with special characters

### ISSUE THREAD

**Issue by cosad3s** [flybywiresim/aircraft#7491]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2022-06-18T02:11:53+00:00",
    "ref": "refs/tags/v0.8.2",
    "sha": "5cfa8478aea0fd20ae4a3e6f624714d0e04fab60",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.8.2"
}
```

### Describe the bug

It could only occurs on the Windows version of the game, not the Steam one.

The game is crashing when loading the flight if the username of the Windows account contains "special" characters, like accents. 
I think it concerns all extended ASCII characters.

### Expected behavior

Should not crash :)

### Steps to reproduce

1. Have a Windows username with an accent (For me: Sébastien).
2. Have a fresh installation of A32NX (Tested in stable, nothing more in Community folder)
3. Launch a flight with the A32NX, anywhere.

### Additional info (optional)

There is a workaround: 

- Win+R -> intl.cpl
- Administrative tab
- Click the Change system locale button.
- Enable Beta: Use Unicode UTF-8 for worldwide language support
- Reboot

**Comment by juliansebline** [comment]
Hello, thank you for your report.

Have you tried with another airplane? I sure you have but just asking.

**Comment by cactuschibre** [comment]
Yes I tried with another plane and no crash ;)

**Comment by tracernz** [comment]
This is a well known issue, and you've already identified the fix; enabling UTF-8 support. I'm not sure what is to be done with this issue?

**Comment by cactuschibre** [comment]
Ok, I did not see that point in docs, thanks. 
Well, I am not a dev on A32NX but I see two ways: 
- If it is because of bad UTF8 management from FS2020, independently of the A32NX, the workaround has to be kept (Which is possible, see https://forums.flightsimulator.com/t/flight-plan-lost-after-resuming-saved-flight/173081)
- If it is because of a specific implementation of A32NX, a fix could be planned

**Comment by 2hwk** [comment]
Unfortunately as this is a windows/MSFS issue, there's nothing that really can be done about this at this time, this should be reported to the platform developers (MS/Asobo). Closing.

**Comment by tracernz** [comment]
> Unfortunately as this is a windows/MSFS issue, there's nothing that really can be done about this at this time, this should be reported to the platform developers (MS/Asobo). Closing.

Isn't this fixed in SU15? https://forums.flightsimulator.com/t/sim-update-15-beta-release-notes-pc-1-37-2-0-xbox-1-37-3-0-february-14-2024/629823
> Fix issue with non ascii characters on path when building packages containing WASM
