### ISSUE TITLE
A32NX navdata problem

### ISSUE THREAD

**Issue by EvilWuZhi** [flybywiresim/aircraft#7524]
### Aircraft Version

Experimental

### Description

在Flybywire A320NX中 存在航路(NavData) 问题，在中国大陆机场会出现Dep 和 Arr 的程序中出现: NO STAR的错误
我建议在A320NX内置NavData(NaviGraph)，这样使中国机场的问题解决。 谢谢！

FlyByWire A32NX has a Nav Data error, no STARS appear for airports in mainland China. Suggest shipping navigraph Nav Data to solve the problem for these airfields, thanks!

**Comment by EvilWuZhi** [comment]
我建议在A320NX建模中 内置一个NavData数据，而不是依赖于游戏！谢谢。

**Comment by HorizonsQT** [comment]
You can use the payable Navigation data source for sim purporse : https://navigraph.com/.

I'm afraid that the Navigation database (specially the accurate navigation data base) is not as easy as you thought to develop and maintain.

Since it's an open source project, maybe you could help yourself to fullfill your wish.

**Comment by tracernz** [comment]
This is possible with the in-development `fms-v2` branch.

**Comment by EvilWuZhi** [comment]
> You can use the payable Navigation data source for sim purporse : https://navigraph.com/.
> 
> I'm afraid that the Navigation database (specially the accurate navigation data base) is not as easy as you thought to develop and maintain.
> 
> Since it's an open source project, maybe you could help yourself to fullfill your wish.

But Navigation navdata database is doesn't work on Flybywire A32NX.

**Comment by tracernz** [comment]
It works for all parts of the world that you have scenery for in MSFS, as it uses the sim's navigation database. As I said, in the upcoming `fms-v2` it will be possible to use another database instead.

**Comment by 2hwk** [comment]
MSFS Nav Data 缺少数据, A32NX + Navigraph NavData 应该不会有问题。

> 我建议在A320NX内置NavData(NaviGraph)

`fms-v2` 会解决 (可以用外部Nav Data数据), 这将需要一些时间

**Comment by EvilWuZhi** [comment]
> MSFS Nav Data 缺少数据, A32NX + Navigraph NavData 应该不会有问题。
> 
> > 我建议在A320NX内置NavData(NaviGraph)
> 
> `fms-v2` 会解决 (可以用外部Nav Data数据), 这将需要一些时间

中国大陆机场会出现问题！
