### ISSUE TITLE
ND Terrain INOP sticker still there, but Terrain ND button working

### ISSUE THREAD

**Issue by MStallen** [flybywiresim/aircraft#7622]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2022-11-27T21:40:05+00:00",
    "ref": "refs/heads/master",
    "sha": "5909ecf2ff51aabd46e8c034f71bd33ce5184fd9",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "master:5909ecf2"
}
```

### Describe the bug

ND Terrain INOP sticker still there, but Terrain ND button working

### Expected behavior

No INOP sticker

### Steps to reproduce

Use FBW development version

**Comment by jcc1953** [comment]
For me today only the button works but there is nothing on the ND. It works only with an old development version fcb173f9 (2022/11/24)
