### ISSUE TITLE
SID, STARS and some APP not loading correctly on ND

### ISSUE THREAD

**Issue by FormulaC1** [flybywiresim/aircraft#7634]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2022-12-02T13:05:37+00:00",
    "ref": "refs/heads/master",
    "sha": "af3ff37cbb5977a7a2e7bf936cec78dbcef5d97a",
    "actor": "crocket63",
    "event_name": "manual",
    "pretty_release_name": "master:af3ff37c"
}
```

### Describe the bug

When loading LARP2C SID from LEBL RWY06R it makes a 360 on SLL34 and it should not be there

### Expected behavior

Load the correct SID track

### Steps to reproduce

Power the aircraft

Program FMC

Select LARP2C SID for RWY06R  in LEBL

### References (optional)

![Microsoft Flight Simulator 01_12_2022 15_27_22](https://user-images.githubusercontent.com/119819938/205519978-85acc850-fda0-4d0c-be62-8f4dfa45681d.png)

![Uploading Microsoft Flight Simulator 04_12_2022 21_17_54.png…]()

### Additional info (optional)

As seen in the pictures, the first one makes a 360 and it shouldn't be there. The second one, in the plan mode, (made with the fenix a320) it loads the correct track.

### Discord Username (optional)

Formula_C#8947

**Comment by Benjozork** [comment]
Are you using navigraph or default navdata ?

**Comment by FormulaC1** [comment]
I am using navigraph.

**Comment by tracernz** [comment]
Can't repro as SID doesn't exist anymore. May be fixed especially with fms-v2.
