### ISSUE TITLE
"autobrake off" callout

### ISSUE THREAD

**Issue by DerbeQ** [flybywiresim/aircraft#7710]
### Aircraft Version

Experimental

### Description

Include an "autobrake off" callout in the FBW A32NX. Reference below. It's a sound effect, triggers a master caution as well.

### References (optional)

https://youtu.be/oaIUNfbxYmM

### Additional info (optional)

If possible, make it selectable in the EFB whether to use it or not.

### Discord Username (optional)

DerbeQ#9424

**Comment by tameraktasTU** [comment]
said "Autobrake Off" callout appears at time marker 20:15

link with timestamp:

https://youtu.be/oaIUNfbxYmM?t=1215

**Comment by literalyammer** [comment]
Another video with a more clear sound is here:

https://www.youtube.com/watch?v=tHCTitrLm3U

Not sure if you need it but it's definitely good to have

**Comment by tracernz** [comment]
Just to note on this one, it is from a different FWC standard than we currently target so we can't really add it immediately without risking inconsistencies elsewhere.

**Comment by literalyammer** [comment]
> Just to note on this one, it is from a different FWC standard than we currently target so we can't really add it immediately without risking inconsistencies elsewhere.

Of course. Makes sense.

**Comment by tracernz** [comment]
Will you do this in the new FWC branch or is it something you expect to be done in master?

**Comment by beheh** [comment]
Not any time soon.

**Comment by Beginna78** [comment]
Thumbs up for this request.
