### ISSUE TITLE
GSX Pushback Support 

### ISSUE THREAD

**Issue by HanSolo80** [flybywiresim/aircraft#7768]
### Aircraft Version

Experimental

### Description

When doing pushbacks with GSX the NW STRG DISC message in the ECAM is not shown. Since recently we got full GSX support for Fuel and Payload in Experimental I would like to know if GSX is able to trigger the NW STRG DISC message on the FBW when inserting the bypass pin into the aircraft.

### Discord Username (optional)

HanSolo80#3772

**Comment by Tebro** [comment]
I tried to have a look at this, and there is a simvar called `FSDT_GSX_BYPASS_PIN`, but GSX does not seem to set that correctly when using their pushback system. If someone is able to verify that would be great.
