### ISSUE TITLE
Auto-import simbrief data for GSX integration

### ISSUE THREAD

**Issue by Keight8** [flybywiresim/aircraft#7772]
### Aircraft Version

Experimental

### Description

Now having the gsx integration could you consider adding an option to automatically load simbrief payload data? Similarly to the one we have for dashboard page currently? As for the refuellig ideally would be to import simbrief fuel and start refueling once the hose connected (there is a gsx lvar). The idea is to minimize steps interacting with efb and automate the process. So you spawn at gate, turn on the efb, request boarding and refuelling via gsx, and everything happens on its own.

### Discord Username (optional)

K8#4795

**Comment by Maximilian-Reuter** [comment]
I think it would be more clear if you added a step by step list of how you would like the new interaction to occur.
Just to remove any room for interpretation of what you request.

**Comment by Keight8** [comment]
Currently the procedure is as follows: enter manually or load from simbrief pax and cargo values on the efb payload page then request boarding from gsx menu. for the refuelling request refuelling from gsx menu once the truck arrived ad hose conntcted enter manually or load from simbrief fuel quantity and press the play button to start refuelling. 
What I am suggesting is having an option to load payload data from simbrief automatically once the efb launched. exactly the same as for dashboard page (there is an option "automatically import simbrief data"). As for the refuelling, load simbrief fuel data **and** start refuelling automatically once the hose connected. So given your simbrief plan ready you only interact with gsx menu to load the airplane.
