### ISSUE TITLE
loc: Missing localization in 'SimBridge Remote' section on the EFB

### ISSUE THREAD

**Issue by alepouna** [flybywiresim/aircraft#7815]
### Aircraft Version

Experimental

### Description

It seems that in my PR https://github.com/flybywiresim/a32nx/pull/7708, I forgot to add localization. 

### Discord Username (optional)

Alepouna🌙#9824

**Comment by ImPlasmaTbh** [comment]
can I get myself assigned to this? checking efb code and looks like it still needs localization
