### ISSUE TITLE
Remove Old EICAS Files

### ISSUE THREAD

**Issue by tracernz** [flybywiresim/aircraft#7819]
### Aircraft Version

Stable

### Build info

```json
master
```

### Describe the bug

The old EICAS files are all still in the tree.

### Expected behavior

Remove the files and rememdy any remaining dependencies to address the technical debt.

### Steps to reproduce

Look in https://github.com/flybywiresim/a32nx/tree/master/fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS.

**Comment by Evanjt1** [comment]
@tracernz I'll look at taking this over the weekend. Longtime lurker and flight simmer looking to start contributing

**Comment by cptnuss-ops** [comment]
Hi @Evanjt1, is this issue still in your hands?
