### ISSUE TITLE
Several approaches are not rendered although correctly input and flown

### ISSUE THREAD

**Issue by nickchen120235** [flybywiresim/aircraft#7877]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-03-17T10:10:36+00:00",
    "ref": "refs/heads/master",
    "sha": "2e853ffc998056798c20386fffd76163a0e28da2",
    "actor": "svengcz",
    "event_name": "manual",
    "pretty_release_name": "master:2e853ffc",
    "version": "v0.10.0-dev.2e853ff"
}
```

### Describe the bug

Several approaches are not rendered although correctly input and flown, in this case LDA28, RWY10, RWY28 are not shown for RCSS

![image](https://user-images.githubusercontent.com/45678482/225920566-03e36460-5eed-4ef1-802c-03ddee7a754a.png)

![image](https://user-images.githubusercontent.com/45678482/225921127-0b5c3285-e477-426a-b77d-bcf91aba4b50.png)

![image](https://user-images.githubusercontent.com/45678482/225920964-f1ffda2e-e01e-4e8d-953a-85d1cf631699.png)

The approach waypoint string is correctly input and flown

![image](https://user-images.githubusercontent.com/45678482/225921440-5e9b2e3d-7407-49e9-851e-0c4feac18555.png)

The approach is also not shown on ND

![image](https://user-images.githubusercontent.com/45678482/225922015-63cde8b2-b7ad-4b2c-b01e-165988b3b05a.png)

### Expected behavior

The selected approach should be correctly shown on the MCDU and ND

### Steps to reproduce

1. C/D start at RCKH
2. Route: RCKH/27 TNN2D TNN W4 HLG HL1J RCSS/28
3. At the F-PLN page select RCSS (LSK6L) and select ARRIVAL (LSK1R), observe the bug

### References (optional)

The available approaches into RCSS

![image](https://user-images.githubusercontent.com/45678482/225923258-87ae1208-75ad-4933-800a-a76375ca7c0a.png)

### Discord Username (optional)

nickchen120235#9303

**Comment by tracernz** [comment]
This is a sim bug I have also noticed with the latest SU12 beta build. The navdata from the sim has blank approach names.

**Comment by tracernz** [comment]
This is fixed.
