### ISSUE TITLE
bug(isis): alt tape is upside down when digits are -ve

### ISSUE THREAD

**Issue by tracernz** [flybywiresim/aircraft#7898]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2023-03-24T10:32:43+00:00",
    "ref": "HEAD",
    "sha": "b2d7668d7dcbef695cf7462635c9800234b5967c",
    "actor": "Frank Kopp <frank@familie-kopp.de>",
    "event_name": "manual",
    "pretty_release_name": "master:b2d7668d",
    "version": "v0.10.0-dev.b2d7668"
}
```

### Describe the bug

![image](https://user-images.githubusercontent.com/9995998/227502087-df825406-f793-400a-a8f7-ba435269870c.png)

### Expected behavior

20 40 80 00 should be 00 20 40 80 from top to bottom below 0 feet.

### Steps to reproduce

1. Turn on and wait for ISIS to align.
2. Wind baro knob until alt is -ve.

**Comment by aweissoertel** [comment]
So I looked into this and this is the result:
https://www.youtube.com/watch?v=FmhJLGNLKPg

But while investigating, I realized the PFD also does the 80 60 40 20 00 top to bottom.
Then I checked a payware A320 and it has the same 80 60 ... ordering for PFD and ISIS with negative altitude.
Was this maybe correct all along? Does somebody have a reference maybe?
I couldn't find any for negative altitude

My code needs a bit of final polishing and testing but I can create a PR soon

**Comment by aweissoertel** [comment]
found this ![isis](https://cdn.discordapp.com/attachments/864211349550268447/1051817172286058506/IMG_9089.jpg) and ![pfd](https://cdn.discordapp.com/attachments/864211349550268447/1051817083094183946/IMG_9093.jpg)
So the tape was indeed upside down right?
It would be easy to also change the pfd alt tape, now that I have the logic
