### ISSUE TITLE
Auto Rudder OFF

### ISSUE THREAD

**Issue by IoulianosVoudouris** [flybywiresim/aircraft#7961]
### Aircraft Version

Stable

### Description

Hello! 
Aircraft A320NX v 0.9.1 - Controls: LOGITECH Flight Yoke System. Community Folder contains nothing else than the aircraft. (flybywire-aircraft-a320-neo & flybywire-externaltools-simbridge)
MSFS version:1.31.22.0 - Windows 11 fully updated.
Question: Since the Auto Rudder should be deactivated, I have to use "left-right brakes" which gives no satisfactory maneuverability while on the ground. Is there a way around this issue?
Thank you in advance 
George Voudouris
v.pixart@gmail.com 

### Additional info (optional)

If I activate the Auto Rudder, the aircraft cannot run straight on the runway

**Comment by 2hwk** [comment]
Use the sepearted tiller option -> See https://docs.flybywiresim.com/fbw-a32nx/feature-guides/nw-tiller/#using-an-axis
