### ISSUE TITLE
A32NX_AUTOPILOT_VS_SELECTED is zero even if A320_Neo_FCU_VSpeed_State is idle

### ISSUE THREAD

**Issue by pubgrub** [flybywiresim/aircraft#8000]
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2023-04-27T21:19:23+00:00",
    "ref": "refs/heads/experimental",
    "sha": "c907a0913975558481d0988df291df0d96a030d4",
    "actor": "BlueberryKing",
    "event_name": "manual",
    "pretty_release_name": "experimental:c907a091",
    "version": "v0.10.0-exp.c907a09"
}
```

### Describe the bug

The FCU shows dashes '- - - - -' when V/S Mode is not on, or after some time when a V/S value has been set, but V/S mode has not been activated afterwards. ( A320_Neo_FCU_VSpeed_State becomes 'Idle'

This works like IRL. 

However, for external Instruments, A32NX_AUTOPILOT_VS_SELECTED stays zero, independently whether zeros or dashes are displayed on the FCU.

### Expected behavior

Either:

when VSpeed_State becomes 'Idle', A32NX_AUTOPILOT_VS_SELECTED should be set to a value outside the normal range (i.e. -99999)

- or - 

a new variable should be available to show the actual VSpeed_State.

### Steps to reproduce

Read value of A32NX_AUTOPILOT_VS_SELECTED while dashes are displayed on the V/S part of the FCU.

### Discord Username (optional)

pubgrub#5761

**Comment by tracernz** [comment]
New FCU coming https://github.com/flybywiresim/a32nx/pull/7587
