### ISSUE TITLE
APU bleed pressure showing 0 PSI when APU is off

### ISSUE THREAD

**Issue by BravoMike99** [flybywiresim/aircraft#8009]
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2023-04-27T21:19:23+00:00",
    "ref": "refs/heads/experimental",
    "sha": "c907a0913975558481d0988df291df0d96a030d4",
    "actor": "BlueberryKing",
    "event_name": "manual",
    "pretty_release_name": "experimental:c907a091",
    "version": "v0.10.0-exp.c907a09"
}
```

### Describe the bug

APU bleed pressure shows 0 PSI when the APU is off.
![APU BLEED](https://user-images.githubusercontent.com/119708186/236674653-0b5de432-6437-4311-80ef-5ff6e6461f65.PNG)

### Expected behavior

APU bleed pressure to be crossed out

### Steps to reproduce

1) Align IRS
2) Observe APU bleed pressure with the APU off

### References (optional)

https://youtu.be/2SHR2ouBaGc
https://youtu.be/VUjfYWNijA8
![image](https://user-images.githubusercontent.com/119708186/236675829-04ea64e6-de62-4676-9063-8283ea014785.png)

### Discord Username (optional)

Bruno_pt99#5802

**Comment by BlueberryKing** [comment]
This should be fixed in the latest version. The change was made in https://github.com/flybywiresim/aircraft/pull/8118

![image](https://github.com/flybywiresim/aircraft/assets/22713769/c24b927f-9cd1-4849-ac80-ad581037eb1c)
