### ISSUE TITLE
Batteries showing 0.00 Volts and EXT PWR Switch not working

### ISSUE THREAD

**Issue by Fantomas01** [flybywiresim/aircraft#8012]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-05-10T20:52:42+00:00",
    "ref": "refs/heads/master",
    "sha": "c75d4fa054107cba5032eb887c07289baee0c5d8",
    "actor": "BlueberryKing",
    "event_name": "manual",
    "pretty_release_name": "master:c75d4fa0",
    "version": "v0.10.0-dev.c75d4fa"
}
```

### Describe the bug

When starting Cold and Dark at the gate the battery displays are at 0.00v.  The EXT PWR switch is showing AVAIL but when clicked nothing happens.

Freshly installed version of Windows 11 with all updates.
MSFS version - 1.32.7.0
FBW Version - Development c75d4fa
Empty community folder bar the FBW A320
Clean Install of FBW A320 

Tested at various default airports Eg. EGCC Gate 27
Tested with default A320 and had no issue.

Turned off all AV and Firewall settings to test
Confirmed UTF-8 Beta box is ticked.

### Expected behavior

Expect battery voltages to show around 26.0 volts and the aircraft systems to power up when EXT PWR button is pressed.

### Steps to reproduce

Freshly installed version of Windows 11 with all updates.
MSFS version - 1.32.7.0
FBW Version - Development c75d4fa
Empty community folder bar the FBW A320
Clean Install of FBW A320 

Tested at various default airports Eg. EGCC Gate 27
Tested with default A320 and had no issue.

Turned off all AV and Firewall settings to test
Confirmed UTF-8 Beta box is ticked.

### References (optional)

![UTF-8 settings](https://github.com/flybywiresim/a32nx/assets/47577088/1b9ed579-912d-42d3-b8ed-11be35f1d917)
![default_a320_colddark](https://github.com/flybywiresim/a32nx/assets/47577088/3c3a3e23-ccaa-4900-9aeb-440c777df762)
![Empty Community Folder](https://github.com/flybywiresim/a32nx/assets/47577088/d32bf3c9-ba8d-44e9-a713-5280ced69c84)
![FBW_A320_colddark](https://github.com/flybywiresim/a32nx/assets/47577088/01a7b81b-7ebf-45c4-ab95-dc0e7fd7cf6a)

### Additional info (optional)

Had no previous issues on my old PC.
Recently rebuilt a new PC and installed the Game Pass 40th Anniversary addition of MSFS and had issues ever since.

### Discord Username (optional)

Fantomas01#1850

**Comment by 2hwk** [comment]
https://docs.flybywiresim.com/fbw-a32nx/support/reported-issues/?h=#solutions-to-commonly-reported-issues

Also please use the discord support channel #a32nx-support if the FAQ and common trouble shooting steps (i.e. checking for other addons in the community folder, clean reinstalling the addon using the installer) do not work. 

This issue will be closed in the future as this is not a problem with the codebase.

**Comment by MateusPab** [comment]
The is happening to me!
