### ISSUE TITLE
MCDU & ND won't turn on

### ISSUE THREAD

**Issue by MatatatDespe** [flybywiresim/aircraft#8031]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2023-05-15T13:42:40+00:00",
    "ref": "refs/tags/v0.10.0",
    "sha": "b0b83346027796b7526415ff8aa13b726308bf36",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.10.0",
    "version": "v0.10.0-rel.b0b8334"
}
```

### Describe the bug

Everytime I start a new flight, switch the batteries on and the external power on, all of the screen turn on except MCDU & ND, what could be the issue?

### Expected behavior

The MCDU & ND should start

### Steps to reproduce

1. Turn on batteries
2. Turn on External power
3. all screens power up, but the MCDU & ND

**Comment by Luz5020** [comment]
For your information, you'll probably receive support faster on our discord https://discord.gg/flybywire

**Comment by MateusPab** [comment]
The same bug is happening to me! The library folder is empty, only the a32nx is installed, I do a clean reinstall also using the installer

**Comment by gabegeforce** [comment]
is there any updates on this? the ND still shows no display as in dead

**Comment by tracernz** [comment]
The plane will only work with the latest retail version of MSFS (and may or may not work with flighting/betas when they're available), and will break regularly with certain types of mods installled e.g. "newlight". If these aren't your issues please seek support on Discord as above.

**Comment by gabegeforce** [comment]
hi Tracernz, I'll check mine. I know what I have is the 2020 version.. I'll get back to you in a moment

**Comment by gabegeforce** [comment]
Hello Tracernz, this is what it shows 1.19.9.0

**Comment by tracernz** [comment]
While the A32NX is free and open source, the sim is not, and you must buy a copy.
