### ISSUE TITLE
Option to use Fahrenheit or Celsius for certain screens where applicable

### ISSUE THREAD

**Issue by pdellaert** [flybywiresim/aircraft#8041]
### Aircraft Version

Stable

### Description

Today, the COND page on the ECAM shows the temperatures in Celsius and there's no way to change that. 

Looking at the video below, US carriers can change this to Fahrenheit for better references. 

Ideally, there would be a configuration option in the EFB similar to the one for the weights, that allows the selection of the display mode for the temperatures where it is applicable. 

This should only apply to screens where Fahrenheit is actually an option for it to be shown, the COND screen is one of those, but there might be others (requires some research). Temperature indications for places where only Celsius is available/displayed, should always remain Celsius for realism reasons. 

### References (optional)

https://www.youtube.com/watch?v=5AT9F-ms4iQ

![image](https://github.com/flybywiresim/a32nx/assets/942391/c5dd563e-5e17-4199-bf50-561bd8aabd9a)

### Discord Username (optional)

DesertIce#5535

**Comment by tracernz** [comment]
Also the air cond indications on the CRUISE page.

**Comment by patmack14** [comment]
> Also the air cond indications on the CRUISE page.

I'd  like to try and take this on
Two questions:
1.Any other (known) spots where the conversion would be applied.
2. Thoughts on a new button being required for this?  Or assume anyone that wants lbs would also want F and maybe rename button?

**Comment by pdellaert** [comment]
> I'd like to try and take this on Two questions: 
> 1.Any other (known) spots where the conversion would be applied. 

I'm not sure myself, I think the first step would be the COND and CRUISE pages of the ECAM. That'll have people look into things and might find other pages.

> 2. Thoughts on a new button being required for this? Or assume anyone that wants lbs would also want F and maybe rename button?

I'd do the same as is present for Weight Units in the EFB Aircraft settings page (https://docs.flybywiresim.com/fbw-a32nx/feature-guides/flypados3/settings/?h=setting#aircraft-options-pin-programs): Introduce a new setting variable and use that in the ECAM code to determine the right unit to use.

I suggest the variable to be default set to Celsius, to remain backward compatible with the current behavior.

**Comment by tracernz** [comment]
IRL this is offered along with the feet for runway length and pounds for weight options, not separately. IMO too many options that nobody practically wants separate quickly becomes annoying.

**Comment by patmack14** [comment]
Sorry this took a bit, notification got buried.

So:
Add in tie feature and tie to the lbs button on EFB?

**Comment by tracernz** [comment]
The setting is actually `CONFIG_USING_METRIC_UNIT`, which applies to the customer option as a whole.
