### ISSUE TITLE
The game freezes inside the cabin

### ISSUE THREAD

**Issue by y0zhyck** [flybywiresim/aircraft#8074]
### Aircraft Version

Stable

### Build info

```json
The plane does not load at any of the airports
```

### Describe the bug

I chose the A320 plane, then put the car in the parking lot, loads it before the start of the "start flight" button, after clicking on the button, the game freezes in the task manager "Does not respond"

### Expected behavior

So that the players do not feel discomfort and enjoy the flight

### Steps to reproduce

1) Deleted all files from the Community folder
2) Put a clean installation
3) Went into the game and chose the plane
4) Pressed the "Start flight" button

### Discord Username (optional)

yozhyck

**Comment by Luz5020** [comment]
Clean install doesn't freeze for me, do you have no other mods in your community folder?

**Comment by y0zhyck** [comment]
> Clean install doesn't freeze for me, do you have no other mods in your community folder?

Не имеется, только fly by wire

**Comment by Luz5020** [comment]
I'd recommend the discord for support, makes replying easier https://discord.gg/flybywire
