### ISSUE TITLE
A/P Disconnects

### ISSUE THREAD

**Issue by dg1234567** [flybywiresim/aircraft#8075]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-06-09T12:58:01+00:00",
    "ref": "refs/heads/master",
    "sha": "e7c4fa0ff6e22cc1268abb30f82f28372d301267",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "master:e7c4fa0f",
    "version": "v0.10.0-dev.e7c4fa0"
}
```

### Describe the bug

Random A/P disconnects throughout flight

### Expected behavior

A/P remains on until turned off by pilot

### Steps to reproduce

Spawn in FBW A320
Takeoff
Turn on A/P 
When switching to exterior view then back into cockpit view A/P will have had disconnected

### Discord Username (optional)

d1234

**Comment by Kostiskat** [comment]
Very unlikely to be a bug, your reproduction steps are too poor to make out what's wrong. I suggest reaching out to the Discord server (https://discord.gg/flybywire) for full support. Make sure to attach pictures of your ND/PFD/MCDU pages if needed when receiving support

**Comment by dg1234567** [comment]
Well I have narrowed it down to it turning off when I switch to exterior mode then back into the cockpit

**Comment by ErikNL80** [comment]
Maybe check some key kindings? That the same key is used for switching views as for disconnecting the autopilot?
