### ISSUE TITLE
Lower starting fuel amount

### ISSUE THREAD

**Issue by Samueleonard** [flybywiresim/aircraft#8092]
### Aircraft Version

Experimental

### Description

currently the aircraft loads in with around 9000kg of fuel in cold and dark which is very unrealistic and renders gsx fueling integration almost useless because for many flights you would have to defuel..

It would be far more realistic to have this around 2-3t of fuel

**Comment by tracernz** [comment]
If you don’t alt+F4 the sim each time it should save your last fuel quantity and load with that IIRC?

**Comment by Saschl** [comment]
Fuel is persisted when on ground and engines are off I think. ALT + F4 should not matter here as it’s written to a file. But depending on the livery (I.e. if they do not set atc_id properly) the mechanism might not work.

**Comment by tracernz** [comment]
Eh, we already have too many settings 😬. Keeping the last fuel is reasonable and not really ever a problem with one exception... if you spawn airborne with no fuel, in which case maybe we should have a minimum amount for airborne spawns.

**Comment by gandalfthewhite19890404** [comment]
> Eh, we already have too many settings 😬. Keeping the last fuel is reasonable and not really ever a problem with one exception... if you spawn airborne with no fuel, in which case maybe we should have a minimum amount for airborne spawns. Empty, full, and half don't really make any sense for an airliner.

I mean configurable fuel amount for Cold and Dark state at a gate. If you spawn at runway or in a air - there will be default MSFS value.

**Comment by Maximilian-Reuter** [comment]
I still would say we should lower the starting fuel amount to a few tons at most. 
Especially for people who switch liverries quite often the saved fuel is useless.

**Comment by tracernz** [comment]
> I still would say we should lower the starting fuel amount to a few tons at most. Especially for people who switch liverries quite often the saved fuel is useless.

Yeah, perhaps 1400 kg or something like that?

**Comment by pinatacolada** [comment]
Most of the time you arrive at the destination with something in between 2t-3t, I think anything in that band is a good value

**Comment by Maximilian-Reuter** [comment]
I would go with the lower end of that number range so 2 tons. That makes sure you almost always have to fuel which I think is fine  and expected.

**Comment by Fragtality** [comment]
I too favor such a Change - around 2 Tons sounds plausible!
But: I'd leave the desired Fuel (A32NX_FUEL_DESIRED) so that a reasonable Refuel Target still exists.
