### ISSUE TITLE
Please include default weather radar

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/aircraft#8098]
### Aircraft Version

Development

### Description

A few days ago a mod appeared on flightsim.to adding the default weather radar in the A32nx. Since this is based on the A32nx ND it will break when you guys update the ND. So therefore a request to embed it in the default version. I hope you can do that same thing as with the working wipers.

And before asking: This weather radar is not drawn by the "Bing maps" system with the same map projection https://microsoft.github.io/msfs-avionics-mirror/docs/framework/classes/index.BingComponent

but the direct native <bing-map> component from MapInstrument library, which allows us to update the position (lat/long) directly. This way, there's no shifting or misalignment issue.
### References (optional)

https://flightsim.to/file/57681/weather-radar-mod-for-fbw-a320-neo-development-version

**Comment by Benjozork** [comment]
There is only one single way of drawing a weather radar and it's using the bing map system. The bing map in the avionics framework and MapInstrument are ultimately the same thing, just different implementations. It ends up both being rendered by the exact same sim system.

**Comment by Benjozork** [comment]
Besides the issue was never about updating the position, that's possible either way, it's about the sim using Mercator projection while the A320 navigation display uses azimuthal equidistant projection.
