### ISSUE TITLE
ECAM fuel page display lines are a bit off

### ISSUE THREAD

**Issue by Finn-D-AEWG** [flybywiresim/aircraft#8106]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-07-12T13:35:03+00:00",
    "ref": "refs/heads/master",
    "sha": "bee1f6ba3d965683308d19a1fe003d9a50e259f7",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "master:bee1f6ba",
    "version": "v0.11.0-dev.bee1f6b"
}
```

### Describe the bug

Some lines on the ECAM Fuel page are too thin or even gray instead of white.

F.USED: Should be a bit thicker
Fuel tanks outlines: Should be thicker and maybe also white(not sure about that)
FOB: Thicker and white (is also bit off placed)
Button lines on all pages: Thicker and white.

See reference picture for more info...

### Expected behavior

To look like in the reference

### Steps to reproduce

Just load into the a32nx

### References (optional)

![Screenshot 2023-07-13 164239](https://github.com/flybywiresim/aircraft/assets/72933147/c5dd9490-2962-41ae-885b-de3376046390)

### Discord Username (optional)

Finn_D-AILY

**Comment by lukecologne** [comment]
The lines should be all grey. It's just hard to see on some photos. See #8036, and we also have other references that state they should be grey. I agree that the fuel tank outlines, FOB box and fuel used lines should be thicker. not sure about the permanent data area (the bottom section) separator lines, they look good to me

**Comment by Finn-D-AEWG** [comment]
> The lines should be all grey. It's just hard to see sometimes. See #8036, and we also have other references that state they should be grey. I agree that the fuel tank outlines, FOB box and fuel used lines should be thicker. not sure about the permanent data area (the bottom section) separator lines, they look good to me

Yeah I couldn't find better references, so you are probably right. But if you compare the permanent data area lines to the FOB box, they are the same thickness. And if you compare the brightness of these two with the letters "FOB" they also have nearly the same white and the letters are definitely white.

**Comment by Finn-D-AEWG** [comment]
![Screenshot (249)](https://github.com/flybywiresim/aircraft/assets/72933147/6ddef4e3-b6f1-4953-acb5-f4f7879c7e1d)
You were right, they are not white. Here you can clearly see a difference in brightness. But I just noticed that the font used for the green Fuel used numbers is a bit to thick haha

**Comment by lukecologne** [comment]
That's true yeah, the font for the F.USED text is also too thick
