### ISSUE TITLE
MCDU: Cold and Dark popout display shows MCDU menu instead of blank

### ISSUE THREAD

**Issue by auroraisluna** [flybywiresim/aircraft#8124]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-07-20T17:51:47+00:00",
    "ref": "refs/heads/master",
    "sha": "3f1edb89e14625a0b8186082d722a58f3542338a",
    "actor": "Gurgel100",
    "event_name": "manual",
    "pretty_release_name": "master:3f1edb89",
    "version": "v0.11.0-dev.3f1edb8"
}
```

### Describe the bug

Popup MCDU screen when the aircraft is in COLD AND DARK, shows the MCDU menu.
![image](https://github.com/flybywiresim/aircraft/assets/98479040/07eefea9-d6b0-48d4-87a9-e46b9c0950cf)

### Expected behavior

The MCDU popout screen should be off.

### Steps to reproduce

1. Start cold & dark
2. Popout MCDU using ALT+GR left click on the MCDU screen

### Additional info (optional)

Reported on Discord by bradclooney

### Discord Username (optional)

alepouna

**Comment by tracernz** [comment]
Duplicate https://github.com/flybywiresim/aircraft/issues/5386
