### ISSUE TITLE
FMS appr: Temperature and QNH fields mandatory when distance to dest greater than 180NM

### ISSUE THREAD

**Issue by BravoMike99** [flybywiresim/aircraft#8126]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-07-20T17:51:47+00:00",
    "ref": "refs/heads/master",
    "sha": "3f1edb89e14625a0b8186082d722a58f3542338a",
    "actor": "Gurgel100",
    "event_name": "manual",
    "pretty_release_name": "master:3f1edb89",
    "version": "v0.11.0-dev.3f1edb8"
}
```

### Describe the bug

In the FMS approach page, QNH and temperature fields appear in mandatory amber boxes instead of brackets when the airplane is more than 180NM from the programmed destination.
![PROG](https://github.com/flybywiresim/aircraft/assets/119708186/284f0519-b331-4385-bd78-ae2127bfbc3d)
![APPR](https://github.com/flybywiresim/aircraft/assets/119708186/e7d469ca-378c-4c25-845d-c167274ffb8b)
![F-PLN](https://github.com/flybywiresim/aircraft/assets/119708186/cc51f0ed-d3aa-44d9-9cd6-a28b40390fa2)

### Expected behavior

QNH and temperature fields should only be shown in mandatory amber boxes, if distance to destination is less than 180NM.

### Steps to reproduce

1) Observe the performance approach page when more than 180NM away from the destination airport.

### References (optional)

![image](https://github.com/flybywiresim/aircraft/assets/119708186/4473b851-526e-4755-9c94-2420e8d070a4)

### Discord Username (optional)

Bruno_pt99#5802

**Comment by tracernz** [comment]
I've noticed this one happening for a few months now too.
