### ISSUE TITLE
ND: Chrono digits glitching out

### ISSUE THREAD

**Issue by BravoMike99** [flybywiresim/aircraft#8130]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-07-20T17:51:47+00:00",
    "ref": "refs/heads/master",
    "sha": "3f1edb89e14625a0b8186082d722a58f3542338a",
    "actor": "Gurgel100",
    "event_name": "manual",
    "pretty_release_name": "master:3f1edb89",
    "version": "v0.11.0-dev.3f1edb8"
}
```

### Describe the bug

Under certain circumstances the chrono digits on the ND appear to be wrongly displayed.
![Chrono3](https://github.com/flybywiresim/aircraft/assets/119708186/a8e9f65b-b569-4c5d-a3c5-2789267bcb02)
![Chrono](https://github.com/flybywiresim/aircraft/assets/119708186/5cc6e726-eca6-4d47-a29d-d4c608e9fee9)
![Chrono2](https://github.com/flybywiresim/aircraft/assets/119708186/e3966e41-e24f-4198-8a1a-cd08e35e7801)

### Expected behavior

N/A

### Steps to reproduce

1) Start the chrono and put the ND in PLN mode.
2) Observe the digits as they change.

### Additional info (optional)

Plan and rose modes on the ND seem to cause the chrono digits to glitch more often, however, I have seen it happen in ARC mode. If a digit is looking weird in PLN mode for example and one switches to arc mode, it fixes it.

https://github.com/flybywiresim/aircraft/assets/119708186/0f69398d-86b0-4176-b4b8-d6746b73237a

I think this started happening after ND V2 was introduced. I've seen it myself a few times on other versions since then.

### Discord Username (optional)

bruno_pt99

**Comment by tracernz** [comment]
This is a rendering bug in the sim that also affects other aircraft (including default ones). We don't really understand why it happens so frequently with the chrono on the ND, and there's no obvious fix.
