### ISSUE TITLE
Strange loop over arriving runway

### ISSUE THREAD

**Issue by Wibblerr** [flybywiresim/aircraft#8144]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2023-06-26T11:17:08+00:00",
    "ref": "refs/tags/v0.10.1",
    "sha": "cc6713243ee251197b2ff16834d0b6f659e6e0a9",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.10.1",
    "version": "v0.10.1-rel.cc67132"
}
```

### Describe the bug

I am having problems inserting a STAR and approach. As usual, I insert my simbrief flight plan using init req in the init page. I insert my SID all fine but then when I insert my STAR things go wrong. I inserted a pictures below. I have this for about half the airports that I fly into using the flybywire A32NX

I do not know how to fix and any help would be appreciated. 
![20230729170012_1](https://github.com/flybywiresim/aircraft/assets/140939430/2c463d67-d486-4ada-abca-b5ce1f8f7bf4)

![Screenshot (20)](https://github.com/flybywiresim/aircraft/assets/140939430/44074626-fac2-4d2b-af6b-0516df5de9df)

### Expected behavior

My STAR to insert just fine and my ILS approach able to use. 

### Steps to reproduce

I have always had this and I am not sure if it is a bug or me not doing something correctly. 

### Additional info (optional)

I have always had this issue, but never with the Asobo A320neo for msfs.

**Comment by tracernz** [comment]
You need to select an appropriate approach transition/via. The FMS will not handle a course reversal at the FACF/FAF well without it, IRL and in the sim.
