### ISSUE TITLE
Bell sound effect

### ISSUE THREAD

**Issue by jcc1953** [flybywiresim/aircraft#8148]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-07-30T15:11:22+00:00",
    "ref": "refs/heads/master",
    "sha": "0fc6f2a0b15cebe5adfb62c88354a78100265a59",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "master:0fc6f2a0",
    "version": "v0.11.0-dev.0fc6f2a"
}
```

### Describe the bug

During all the flight I hear a bell sound effect (dong) every 2mn 15s

### Expected behavior

Remove this sound

### Steps to reproduce

Do a flight.

**Comment by hotshotp** [comment]
this is passengers in the cabin dinging the flight attendants. it is a bit too often though so i will tone down the frequency of it. and also closing the cockpit door will make it not audible in the cockpit.
