### ISSUE TITLE
efb reverse thrust is not considered

### ISSUE THREAD

**Issue by obrunsmann** [flybywiresim/aircraft#8154]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-08-02T15:50:02+00:00",
    "ref": "refs/heads/master",
    "sha": "65308bc4fd1d2ddb859a404320934dd32e349fa9",
    "actor": "lukecologne",
    "event_name": "manual",
    "pretty_release_name": "master:65308bc4",
    "version": "v0.11.0-dev.65308bc"
}
```

### Describe the bug

No matter if I select reverse thrust yes or no, the distance does not change

### Expected behavior

shorter landing distance with revese thrust

### Steps to reproduce

<img width="1295" alt="image" src="https://github.com/flybywiresim/aircraft/assets/763812/7c6d580b-d00e-49c7-8fb7-4eaeb23b91a8">

<img width="1400" alt="image" src="https://github.com/flybywiresim/aircraft/assets/763812/028d4e52-4990-41f6-8f67-caeffba68871">

**Comment by donstim** [comment]
Hi, this is not a bug. No distance "credit" is given for use of reverse thrust on a dry runway. The effect of reverse thrust becomes significant when braking capability is reduced, that is, on slippery runways. Try the same calculation, but change the runway condition to Poor (1). As you work up through the runway conditions from 1 to 5, you will see that the effect of reverse thrust decreases, until at 6 (a dry runway), there is no effect shown at all.

**Comment by obrunsmann** [comment]
> Hi, this is not a bug. No distance "credit" is given for use of reverse thrust on a dry runway. The effect of reverse thrust becomes significant when braking capability is reduced, that is, on slippery runways. Try the same calculation, but change the runway condition to Poor (1). As you work up through the runway conditions from 1 to 5, you will see that the effect of reverse thrust decreases, until at 6 (a dry runway), there is no effect shown at all.

Oh yeah! You're right. I did some research because I had a hard time believing it. The explanation is that less auto breaks are used when the reversers are used. That's exciting to me, I thought it was often landed with full reverse.

Thanks!
