### ISSUE TITLE
Strange sound in external view with speedbrakes fully deployed

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/aircraft#8177]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-08-25T06:43:37+00:00",
    "ref": "refs/heads/master",
    "sha": "f68af169ae33e037b8f64691b96cf3d4e4c6a590",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "master:f68af169",
    "version": "v0.11.0-dev.f68af16"
}
```

### Describe the bug

Sine a while I am noticing the following when in external view mode. Aircrfat sounds OK, but when descending using speedbrakes full a strange sound (sounds a bit like an engine that does not start) appears. This sound disappears when the speedbrakes are retracted.

### Expected behavior

The sound mentioned above should not be there.

### Steps to reproduce

I noticed this issue for a while now, and hope you can reproduce:
1. Run a flight at cruise level
2. Descend and use the speedbrakes (full)
3. Go to the external view and listen
4. There is a strange sound which should not be there

### References (optional)

Unfortunately I could not capture a video as this time, but the sound is very good noticable...

**Comment by cmayl0** [comment]
I've also noticed this issue while descending with speedbrakes deployed 50% (max during AP) with engines at idle. It's easy to reproduce for me - descending in idle with speedbrakes deployed in external view makes the strange repeating ascending tone. I do not notice the sound in cockpit.

**Comment by ErikNL80** [comment]
Unfortunately the issue described above is still present after #8188

**Comment by hotshotp** [comment]
I thought that would fix it for sure... it'll be a while until I can fix it since my access to the files is through another computer but I'll try to fix it in when I get it

**Comment by ErikNL80** [comment]
Thank you!

**Comment by ErikNL80** [comment]
@hotshotp Do you have an update on this issue?
