### ISSUE TITLE
10 minute engine start - No reaction to thrust levers after start - Generator Faults

### ISSUE THREAD

**Issue by JonH130** [flybywiresim/aircraft#8181]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-08-25T06:43:37+00:00",
    "ref": "refs/heads/master",
    "sha": "f68af169ae33e037b8f64691b96cf3d4e4c6a590",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "master:f68af169",
    "version": "v0.11.0-dev.f68af16"
}
```

### Describe the bug

Issue has been experienced for the past few builds. Have successfully performed engine starts hundreds of times previously.

If beginning flight on runway with engines started, no issue. This only occurs while manually starting engines.

When starting cold and dark or after engine shutdown, engines are slow to start (approx 10 minutes per engine) and the thrust levers have no effect on thrust. N2 rises very very slowly. The thrust lever animations and ECAM position indications are working correctly. Thrust will not increase past 20.1%. Eventually the engines shut down on their own.

Notes:
APU bleed ON, all fuel pumps ON. Starter switch to START, desired engine master switch to ON.
Turning off packs, hydraulic pumps, generators has no effect.
Setting pack flow to LOW has no effect

### Expected behavior

Both engines OFF
APU ON
APU Bleed ON
Start switch to START
Engine Master 1 (or 2) to ON
Rapid rise in N2
Fuel flow indicated
EGT spike and return to normal
N1 rises to 20% (ECAM shows AVAIL)
Start switch to NORM
Engine reacts to thrust lever position

### Steps to reproduce

Both engines OFF
APU ON
APU Bleed ON
Start switch to START
Engine Master 1 (or 2) to ON
Very slow rise in N2
Fuel flow indicated after 6 minutes
EGT does not spike, rises gradually
N1 rises to 20% (ECAM shows AVAIL) after 10 minutes
Start switch to NORM
Engines do not increase thrust with thrust lever movement.
Thrust lever angle is shown accurately on ECAM, lever animation correct as well.
Cannot proceed further as aircraft will not move.
Engine will eventually shut down (ECAM shows XXs but also AVAIL).

### References (optional)

![2023 08 27 - 10 21 59 14](https://github.com/flybywiresim/aircraft/assets/143345770/2023b33c-2df0-4bb6-87c3-396035f5624b)
![2023 08 27 - 09 58 50 73](https://github.com/flybywiresim/aircraft/assets/143345770/3b71d937-19cc-489f-8d14-a3e8ae83603f)

### Additional info (optional)

Occurring the past 4 development versions approximately.
Occurs during cold and dark start or after engine shut down.

**Comment by tshomas** [comment]
Hello, do you happen to use the "newlight" mods? A recent change has meant the mod is now outdated and is causing a lot of engine start up issues?

**Comment by JonH130** [comment]
I do! I missed that one when I removed all A32NX mods/liveries from
Community. Will remove. If that resolves the issue,  I will delete the bug.

You are really fast in responding. You guys are amazing.

Jon

**Comment by tshomas** [comment]
No problem at all, keep us in the loop!

**Comment by JonH130** [comment]
tshomas, that was the problem. Can't believe I missed removing that addon.
Normal engine start on latest Dev version.
