### ISSUE TITLE
Installer wont load images or anything else.

### ISSUE THREAD

**Issue by YousefLoai** [flybywiresim/aircraft#8187]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2023-06-26T11:17:08+00:00",
    "ref": "refs/tags/v0.10.1",
    "sha": "cc6713243ee251197b2ff16834d0b6f659e6e0a9",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.10.1",
    "version": "v0.10.1-rel.cc67132"
}
```

### Describe the bug

One  day, I opened my installer to use the FSTL traffic addon and the images names and more etc, Were not loading in and did not work, and still this day does not work properly, and I've tried installing a the installer again and still did not work.

### Expected behavior

![Screenshot 2023-08-29 175739](https://github.com/flybywiresim/aircraft/assets/103374518/6713d2bf-80ad-4486-a841-7bed23b9fa4e)

### Steps to reproduce

Nothing happened to encounter this issue out of nowhere it came.

### References (optional)

![Screenshot 2023-08-29 175739](https://github.com/flybywiresim/aircraft/assets/103374518/6713d2bf-80ad-4486-a841-7bed23b9fa4e)

### Discord Username (optional)

theonepeaceisreal5498

**Comment by BlueberryKing** [comment]
Is this issue still present? Please file an issue at https://github.com/flybywiresim/installer or ask on our Discord 👍 Thank you!
