### ISSUE TITLE
Cockpit interior lights not brighten the cockpit

### ISSUE THREAD

**Issue by PowerNow** [flybywiresim/aircraft#8189]
### Aircraft Version

Stable

### Build info

```json
"built": "2023-06-26T11:17:08+00:00",
    "ref": "refs/tags/v0.10.1",
    "sha": "cc6713243ee251197b2ff16834d0b6f659e6e0a9",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.10.1",
    "version": "v0.10.1-rel.cc67132"
```

### Describe the bug

The dome, foot and other white lights inside the cockpit are ON, but the cockpit itself is not brightened. Only the buttons and displays are visible, fot other aircrafts and Asobo A320N it works. In earlier versions (I think before the update in April) all worked fine. I just have removed FBW in the community and package folder completely but without sucess. What else can I try out?

### Expected behavior

The cockpit should be brightened by the flood lights (e.g dome, foot,...)

### Steps to reproduce

1. Set any departure airport without flightplan
2. Start Sim
3. Battery ON
5. External Power ON
6. Set INT LT DOME to BRT or DIM
7. Cockpit stays dark

**Comment by tracernz** [comment]
Remove any other mods, especially incompatible ones like "newlight".

**Comment by PowerNow** [comment]
Thxs, I disabled yesterday all mods and found the reason. It's z-Newlight-settinglight-FBW-A320NX-dev.

**Comment by awtera** [comment]
you're right。
