### ISSUE TITLE
Perf Cruise page speed is incorrectly displayed

### ISSUE THREAD

**Issue by pinatacolada** [flybywiresim/aircraft#8190]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-08-29T20:29:53+00:00",
    "ref": "refs/heads/master",
    "sha": "1f57e528133eb19bcdabf2f00b0e526d53b54770",
    "actor": "Maximilian-Reuter",
    "event_name": "manual",
    "pretty_release_name": "master:1f57e528",
    "version": "v0.11.0-dev.1f57e52"
}
```

### Describe the bug

Line 3L, which displays the FMGS computed ECON speed/Mach incorrectly only displays speed in KIAS.

### Expected behavior

Line 3L to display speed in KIAS below FL250, and in Mach above FL250.

### Steps to reproduce

Be in cruise, or maybe even just load a flight onto the FMS, with a cruise level above FL250, and open the PERF CRZ page.

### References (optional)

DSC-22_20-50-10-25 MCDU - PAGE DESCRIPTION - PERF CRUISE PAGE
DSC-22_20-40-10 PERFORMANCE - OPTIMIZATION

**Comment by BlueberryKing** [comment]
Thanks for the report! Do you know what it displays when the cruise level is exactly FL250?

**Comment by pinatacolada** [comment]
> Thanks for the report! Do you know what it displays when the cruise level is exactly FL250?

No idea! 😂 it might keep kias, a didnt climb into mach type of thing maybe. I'll see what I can do
