### ISSUE TITLE
ELEC: Turning batteries off and on does not initiate a charging cycle

### ISSUE THREAD

**Issue by BravoMike99** [flybywiresim/aircraft#8195]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-09-04T02:30:14+00:00",
    "ref": "refs/heads/master",
    "sha": "12c8e357bccc95d58b6fab4d2e2051ca6b9940fb",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "master:12c8e357",
    "version": "v0.11.0-dev.12c8e35"
}
```

### Describe the bug

Upon turning off and on the batteries, the charging cycle does not seem to be initiated as the current stays constant.

https://github.com/flybywiresim/aircraft/assets/119708186/0d7b19c0-9ae8-47cd-9658-30c7f6fac38a

### Expected behavior

Battery current should spike and then come back down due to the charging cycle.

### Steps to reproduce

1) Turn off both batteries and turn them on again

### References (optional)

https://youtu.be/1reXoBafQr8
![image](https://github.com/flybywiresim/aircraft/assets/119708186/2b754661-e232-417b-8ed2-73cec9fdf8b9)

### Discord Username (optional)

bruno_pt99

**Comment by Gurgel100** [comment]
The behavior is correct like this. The batteries are nearly full before you initiate the charging. Therefore, the current is not that high. Also the arrows are only shown if the current is higher than 5A (IIRC)

**Comment by BravoMike99** [comment]
> The behavior is correct like this. The batteries are nearly full before you initiate the charging. Therefore, the current is not that high. Also the arrows are only shown if the current is higher than 5A (IIRC)

My bad, I misunderstood the charging process whenever you cycle them. My apologizes
