### ISSUE TITLE
Wrong Cabin temperature on Cruise SD 

### ISSUE THREAD

**Issue by twasono** [flybywiresim/aircraft#8213]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-09-04T02:30:14+00:00",
    "ref": "refs/heads/master",
    "sha": "12c8e357bccc95d58b6fab4d2e2051ca6b9940fb",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "master:12c8e357",
    "version": "v0.11.0-dev.12c8e35"
}
```

### Describe the bug

The fwd and aft temperatures are using the LVAR for cockpit temperature.

I think it's a regression caused by this PR: https://github.com/flybywiresim/aircraft/pull/8118

I already put a comment on that PR.

### Expected behavior

The fwd and aft temperatures should use their own LVAR to get the right temp

### Steps to reproduce

Fly as usual and try to change the cockpit temp.

You will see that all temps (including fwd and aft) will be displayed as cockpit temp

**Comment by tracernz** [comment]
Good catch 👍.

**Comment by cptnuss-ops** [comment]
Do I have to assign the issue to myself prior to fixing? Or this done by creating a PR for this issue?

**Comment by Saschl** [comment]
Hi, it’s best you create a draft PR already which mentions this issue you want to fix.
