### ISSUE TITLE
PFD SPEED SEL message

### ISSUE THREAD

**Issue by becas22** [flybywiresim/aircraft#8217]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-09-16T06:20:39+00:00",
    "ref": "refs/heads/master",
    "sha": "4783ebcadace8462bc71af4f8c1bb4c1ebdb322c",
    "actor": "2hwk",
    "event_name": "manual",
    "pretty_release_name": "master:4783ebca",
    "version": "v0.11.0-dev.4783ebc"
}
```

### Describe the bug

The SPEED SEL message in the line 3 of the FMA it's missing the ":".
It displays "SPEED SEL 225"

### Expected behavior

Should display "SPEED SEL: 225"

### Steps to reproduce

1. Prior to takeoff, presel a speed in PERF CLB
2. During climb check the 3rd line of the FMA

### References (optional)

DSC-22_30-80-20
![image](https://github.com/flybywiresim/aircraft/assets/11005754/983369f7-fa24-47f8-bca1-a0de5621a9d9)

https://youtu.be/RhyQK7Jz56g?t=94

### Additional info (optional)

This was tested with a preselected CLB speed, but should be the same for preselected CRZ speed

### Discord Username (optional)

Bernardo R

**Comment by aaronschweig** [comment]
Hello @becas22,
I am looking to get into contributing to this project and found this labeled as a good first issue.

Is the missing colon also relevant for a preselected MACH value or only for speed values?

**Comment by tracernz** [comment]
> Hello @becas22, I am looking to get into contributing to this project and found this labeled as a good first issue.
> 
> Is the missing colon also relevant for a preselected MACH value or only for speed values?

![image](https://github.com/flybywiresim/aircraft/assets/9995998/6dfa4013-34b4-4fa0-9cc6-ef08bbb2f12a)
