### ISSUE TITLE
Items overlapping on EFB Ground Services page

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/aircraft#8223]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-09-20T10:17:24+00:00",
    "ref": "refs/heads/master",
    "sha": "a59f745143b5620d20d1ce61d76da2ad369a8a6b",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "master:a59f7451",
    "version": "v0.11.0-dev.a59f745"
}
```

### Describe the bug

I noticed that in the latest build the ground services page has some overlapping items, see the attached screenshot.

### Expected behavior

I would expect the page to be the same with the items below each other.

### Steps to reproduce

1. Start a flight
2. Open the EFB
3. Navigate to the Ground Services page
4. Notice the overlapping items

### References (optional)

![Schermafbeelding 2023-09-21 110045](https://github.com/flybywiresim/aircraft/assets/71258178/be379d11-0ca1-411f-b285-433734884162)

**Comment by 2hwk** [comment]
Will be Fixed by https://github.com/flybywiresim/aircraft/pull/8226 🔧🦺🚀
