### ISSUE TITLE
Refueling Order

### ISSUE THREAD

**Issue by Jet-A1** [flybywiresim/aircraft#8229]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2023-06-26T11:17:08+00:00",
    "ref": "refs/tags/v0.10.1",
    "sha": "cc6713243ee251197b2ff16834d0b6f659e6e0a9",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.10.1",
    "version": "v0.10.1-rel.cc67132"
}
```

### Describe the bug

On the EFB Bodendienste (Ground Service), Treibstoff (Fuel) Page the Outer Wing Tanks are full and the Inner Wing Tanks are not till 12424 Kg. The same behaviour when i put the Slider for refueling  from emtpy to 8000 Kg Block Fuel, the Outer Wing Tanks are full, and the rest of Fuel is in the Inner Wing Tanks. The refueling Order through the Tanks is wrong. This seems to be a Bug. 

### Expected behavior

On A320 the automatic Refueling Procedure is as follows:

From 0 Kg to 11038 Kg only the Inner Wing Tanks will be filled. There after the Outer Wing Tanks are filled till 12424 Kg. At last the Center Tank will be filled till 19046 Kg. So the Fueling Order is, first Inner Wing Tanks, then Outer Wing Tanks, then Center Tank.

On the EFB when you fill up 6.0 to Block Fuel, you have 3000 Kg in each Inner WIng Tank. Only when the Inner Wing Tanks reach 11038  Kg the Outer Wing Tanks will be filled with Fuel. When the Wings are full then the Center Tank will be filled.

### Steps to reproduce

1. On EFB set Refueling Slider to 0, Press > . All Tanks are empty.
2.  Put Refueling slider to 6000 Kg, Press > . Left, Right Inner Tanks have 4614 Kg, Left, Right Outer Tanks have 1388 Kg. Thats wrong, because at 6000 Kg Block Fuel you have 3000 Kg in each Inner Wing Tank in RL.  

### References (optional)

I have refueled many Aircraft through 20 Years as Refueler at an International Airport. 

### Discord Username (optional)

bulli3991

**Comment by beheh** [comment]
Hello! I think there's some confusion here. While to my understanding the fuel is indeed ultimately in the inner thanks and fed from there to the engines, the outer tanks are what's actually connected to the fuel system and the inner tanks will be fuelled by means of spill pipes. Then, in flight, the vents from the outer tanks to the inner tanks will empty once the inner tanks are below a certain threshold.
Hence the wing fuel always starts in the outer tanks, which is what I believe the EFB tries to model.

[Here's an Airbus Safetyfirst page explaining this](https://safetyfirst.airbus.com/avoiding-fuel-spills-on-a320-family-aircraft/) in more detail:
> The center tank and the outer wing tanks are filled first in a normal refuelling operation. Once the outer tank is full of fuel, the inner wing tank will be filled with fuel passing through the spill pipe (fig.3).

The page above also shows schematics showing the refuel system being connected to the outer tanks.
