### ISSUE TITLE
MCDU: F-PLN arrival page does not display ILS information if available

### ISSUE THREAD

**Issue by BravoMike99** [flybywiresim/aircraft#8253]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-10-13T14:50:15+00:00",
    "ref": "refs/heads/master",
    "sha": "c3755f729129c94b2f9e0559d50dbeccdda53509",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "master:c3755f72",
    "version": "v0.11.0-dev.c3755f7"
}
```

### Describe the bug

F-PLN arrival page does not display ILS frequency nor identifier for an approach when an ILS is available.
![image](https://github.com/flybywiresim/aircraft/assets/119708186/0d4c7ccc-1f6c-4d91-9432-23fb145a49fa)

### Expected behavior

F-PLN arrival page should display the identifier and ILS frequency for the specific approach (if available).

### Steps to reproduce

Select an arrival airport with ILS available and ope F-PLN arrival page.

### References (optional)

![image](https://github.com/flybywiresim/aircraft/assets/119708186/940b368b-1cd2-449d-a7ce-0a4d7fb88a59)
![image](https://github.com/flybywiresim/aircraft/assets/119708186/4d22f139-dea6-420d-a6ae-d53355cdd6a3)

### Discord Username (optional)

bruno_pt99

**Comment by tracernz** [comment]
I have implemented this about 3 times in different branches. I guess none have made it so far 😆 .

**Comment by BravoMike99** [comment]
> I have implemented this about 3 times in different branches. I guess none have made it so far 😆 .

Nice, did you do the same for the departure page? Just noticed its missing there too 😛 
![image](https://github.com/flybywiresim/aircraft/assets/119708186/b98b2912-bf5d-4b58-924f-46389379c6af)

**Comment by tracernz** [comment]
It's there on the departure page if it's in the navdata. You have a third party scenery for LIRF?
