### ISSUE TITLE
Pause at TOD doesn't trigger when thrust is not in managed mod

### ISSUE THREAD

**Issue by hargn** [flybywiresim/aircraft#8261]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-10-20T23:27:31+00:00",
    "ref": "refs/heads/master",
    "sha": "581edbca8c25bad8562274fef1370bbcbf9545c8",
    "actor": "Gurgel100",
    "event_name": "manual",
    "pretty_release_name": "master:581edbca",
    "version": "v0.11.0-dev.581edbc"
}
```

### Describe the bug

This is an issue i've encountered on the HW A339 here : [https://github.com/headwindsim/A339X/issues/77](https://github.com/headwindsim/A339X/issues/77)

As i believe it's related to the FBW systems and EFB, i post it here in order it can be solved.

Two times in different flights the aircraft didn't respect the Pause at TOD :
I've found it still flying at cruise level after to have overpass the last flightplan waypoint in the last heading it had the time it reached it.

After some tests, i've figured that the Pause at TOD doesn't trigger when the Speed Selector has not be enforced in managed mod.

### Expected behavior

When the aircraft reach the point on flightplan, the distance it has been set in the EFB from the TOD point and the AP is on, the aircraft should pause the simulation, whatever the state of knobs on the FCU.

Pause at TOD should trigger if the autothrust is in managed mod or in selected mod.

### Steps to reproduce

1. Take the aircraft in cruise level, far away the TOD, with the AP on, and the autothrust in
2. Setup in the EFB the Pause at TOD feature, at a random distance (at it seems to don't matter)
3. Disconnect the AP : Pause is triggered.
4. Click OK and reconnect the AP
5. Disconnect the AP : Pause don't trigger
6. Reconnect the AP and **push the Speed Selector knob to enforce the managed speed**
7. Disconnect the AP : Pause trigger as it should

### Discord Username (optional)

alwiswennerstroem

**Comment by Revyn112** [comment]
@hargn can you test this behaviour in the a32nx aswell?

**Comment by hargn** [comment]
Yes i'll test, but not today : i'm on a OMDB-WSSS flight with the HW A339 on which i've performed my tests.

**Comment by Maximilian-Reuter** [comment]
Just to clarify, by *Autothrust Knob* you mean the *Speed Selector* ? Ie. Managed and Selected Speed ?
![image](https://github.com/flybywiresim/aircraft/assets/5833783/aed4ed4a-92d3-4f80-9f94-107059ea8f5c)
this one ?

**Comment by hargn** [comment]
Yes, you have to push it **even** if the aircraft is in managed mode in order to activate the Pause at TOD.

**Comment by tracernz** [comment]
@2hwk Do you remember why it only pauses when speed is managed? It explicitly checks that in the code.

**Comment by hargn** [comment]
Hi, i did some tests this weekend and the FBW 32NX has the same behavior than i've described.

**Comment by hargn** [comment]
So i did some tests and i've reproduced the issue on the FBW32NX.
It seems that the problem where you have to push the thrust knob to enforce the managed mod was due to a timeout (10s if i remember the code).

So i can make a PR where i can:
1. Remove the condition on the managed mod, in order to have the break at ToDwhatever the speed mode engaged (managed or selected)
2. Remove the timeout, or reduce it

Another thing i would also change, is the maximum of 50NM for the distance from ToDthe pause should be triggered.
In SLC (Self Loading Cargo) i use, you've to advert the crew minimum 10min before the ToD, and 50NM is too late.

**Comment by 2hwk** [comment]
> @2hwk Do you remember why it only pauses when speed is managed? It explicitly checks that in the code.

I believe it's part of the check that automatically pauses the sim if it detects that the AP has been automatically deactivated due to a sudden deviation caused by weather or other factors.
