### ISSUE TITLE
Captain's ND Shows ILS1

### ISSUE THREAD

**Issue by tracernz** [flybywiresim/aircraft#8265]
### Aircraft Version

Development

### Build info

```json
8231d7c
```

### Describe the bug

Captain's ND in ROSE LS mode shows ILS1 and FO's ILS2. Regression from NDv2.

### Expected behavior

Should be the other way around.

### Steps to reproduce

Switch NDs to ROSE LS mode and observe the top right corner info.

**Comment by Saschl** [comment]
Fixed now with https://github.com/flybywiresim/aircraft/pull/8268
