### ISSUE TITLE
[FMS]: Average tailwind not taking correctly in account for predictions in F-PLN 

### ISSUE THREAD

**Issue by BravoMike99** [flybywiresim/aircraft#8274]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-10-27T09:05:48+00:00",
    "ref": "refs/heads/master",
    "sha": "8f6f01721371c3d817d33604e618752dad69e734",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "master:8f6f0172",
    "version": "v0.12.0-dev.8f6f017"
}
```

### Describe the bug

Average wind component inserted in INIT FUEL PRED/INIT B is not taken into account correctly for the predictions on the F-PLN page. As visible, inserting a Tailwind of 62kts results in a greater trip time than no winds.
![TL62](https://github.com/flybywiresim/aircraft/assets/119708186/e51231c2-fce0-4c1d-b91b-4166df32ba8e)
![FPLN](https://github.com/flybywiresim/aircraft/assets/119708186/54f761d1-45c4-413c-a0c4-9f2b33b40ed1)
![TRIPWIND2](https://github.com/flybywiresim/aircraft/assets/119708186/d8865ecb-6f9d-4526-9045-d9c99de13fa3)
![FPLN2](https://github.com/flybywiresim/aircraft/assets/119708186/e4d7125c-b40d-4f0a-9a97-b0587ce03f5f)

### Expected behavior

Flight time to decrease and EFOB to increase if significant tail winds are inserted.

### Steps to reproduce

Insert a big tailwind value on the INIT page and observe the predictions on the FPLN page. Then change such value to a headwind or no wind at all.

### Additional info (optional)

It seems like tailwind is considered as a headwind for the F-PLN page predictions. When I inserted a headwind of 62kts the prediction result was the same as a tailwind.

### Discord Username (optional)

bruno_pt99

**Comment by BlueberryKing** [comment]
Nice catch. The wind predictions have other short comings as well unfortunately, but this one is easy to fix.

`getTripWind()` [here](https://github.com/flybywiresim/aircraft/blob/master/fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js#L5085)
```javascript
getTripWind() {
    return this.averageWind; 
}
```

should be this
```javascript
getTripWind() {
    if (this._windDir === this._windDirections.TAILWIND) {
        return -this.averageWind;
    } else if (this._windDir === this._windDirections.HEADWIND) {
        return this.averageWind;
    }
}
```

**Comment by BravoMike99** [comment]
> Nice catch. The wind predictions have other short comings as well unfortunately, but this one is easy to fix.
> 
> `getTripWind()` [here](https://github.com/flybywiresim/aircraft/blob/master/fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js#L5085)
> 
> ```js
> getTripWind() {
>     return this.averageWind; 
> }
> ```
> 
> should be this
> 
> ```js
> getTripWind() {
>     if (this._windDir === this._windDirections.TAILWIND) {
>         return -this.averageWind;
>     } else if (this._windDir === this._windDirections.HEADWIND) {
>         return this.averageWind;
>     }
> }
> ```

Nice! So that's why it made no difference between headwind and tailwind 😄

**Comment by tracernz** [comment]
Would it make sense to to just store headwind as negative? That is after all also how it can be input (either -, H, HD for headwind, and no sign, +, T, TL for tailwind).

**Comment by BlueberryKing** [comment]
> Would it make sense to to just store headwind as negative rather than a separate flag? That is after all also how it can be input (either -, H, HD for headwind, and no sign, +, T, TL for tailwind).
> 
> ```ts
> getTripWind() {
>     if (this._windDir === this._windDirections.TAILWIND) {
>         return -this.averageWind;
>     } else if (this._windDir === this._windDirections.HEADWIND) {
>         return this.averageWind;
>     }
> }
> ```
> 
> would have the wrong sign according to the usual convention (and the input format).

Yes, I think that would make sense. My code snippet matches the convention I had chosen for VNAV, where a headwind is positive. You are making a convincing argument for this convention to be changed though 😄.
