### ISSUE TITLE
[CPDLC] Connection asks for ATC FLT NBR

### ISSUE THREAD

**Issue by RicardoPlacido** [flybywiresim/aircraft#8287]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2023-11-03T17:47:36+00:00",
    "ref": "refs/tags/v0.11.1",
    "sha": "f055eb02dc0af32441f8b2873f58e8316d7ca638",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.11.1",
    "version": "v0.11.1-rel.f055eb0"
}
```

### Describe the bug

I tried to connect to a IVAO station, with CPDLC ID: QXGS, however, when I tried to put the CPDLC ID code in the MCDU, I got a message: ENTER ATC FLT NBR.

### Expected behavior

I should be able to connect putting only the CPDLC ID and not receive the message ENTER ATC FLT NBR

### Steps to reproduce

1. On MCDU, click on ATC COMM button
2. Once ATC MENU page is open, click CONNECTION
3. Once CONNECTION page is open, click NOTIFICATION
4. Once NOTIFICATION page is open, insert ATC CENTER CPDLC ID (e.g. QXGS)
5. You will get the message ENTER ATC FLT NBR
<img width="518" alt="Captura de ecrã 2023-11-06 152253" src="https://github.com/flybywiresim/aircraft/assets/71703673/b6b8412a-63cd-4a43-9bc1-33478578e2ab">
<img width="520" alt="Captura de ecrã 2023-11-06 152311" src="https://github.com/flybywiresim/aircraft/assets/71703673/d4cb46db-30c1-4943-bfe9-49599d476761">

**Comment by Lauvaan** [comment]
Hello, you need to have a flight number(callsign) into the init page to be able to connect to cpdlc

**Comment by RicardoPlacido** [comment]
Yes, you are right. I am sorry for my fault.
Thank you very much for answering.
