### ISSUE TITLE
Printing external thermal

### ISSUE THREAD

**Issue by Waltervizzi** [flybywiresim/aircraft#8297]
### Aircraft Version

Development

### Build info

```json
I dont know
```

### Describe the bug

I can no longer print with my thermal printer when I click print on the mcdu simbridge it crashes

### Expected behavior

it should print instead no

### Steps to reproduce

it should print instead no

**Comment by Finn-D-AEWG** [comment]
I have the same issue

**Comment by Maximilian-Reuter** [comment]
This is a known bug and is being worked on in this PR
https://github.com/flybywiresim/simbridge/pull/99

**Comment by Waltervizzi** [comment]
> Questo è un bug noto e si sta lavorando su questo PR [flybywiresim/simbridge#99](https://github.com/flybywiresim/simbridge/pull/99)

Do you know more or less when it will be fixed?

**Comment by auroraisluna** [comment]
> > Questo è un bug noto e si sta lavorando su questo PR [flybywiresim/simbridge#99](https://github.com/flybywiresim/simbridge/pull/99)
> 
> Do you know more or less when it will be fixed?

It has been merged now, update your Simbridge. Does this work for you now?

**Comment by Maximilian-Reuter** [comment]
@Waltervizzi this issue should be fixed now so please try it with the newest simbridge release and reopen if still problematic!
