### ISSUE TITLE
No HOPPIE CONECTION

### ISSUE THREAD

**Issue by Siberier** [flybywiresim/aircraft#8302]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-11-14T18:44:31+00:00",
    "ref": "refs/heads/master",
    "sha": "72a6813c7abcb600a0d7209e67fb2a6c7e68f677",
    "actor": "beheh",
    "event_name": "manual",
    "pretty_release_name": "master:72a6813c",
    "version": "v0.12.0-dev.72a6813"
```

### Describe the bug

"No hoppie connection" appears each time when try to check-in HOPPIE via CDU. 

### Expected behavior

To chek-in in to Hoppie

### Steps to reproduce

1. Try to notify any station (eg EDDF) 
2. "No hoppie connection" appears

**Comment by Siberier** [comment]
Hoppie Connection has already enabled. But still no hoppie connection. As for the other product, fenix for example, all work properly.

**Comment by Maximilian-Reuter** [comment]
As written in the guide that was posted, you need to select VATSIM as METAR source in the EFB ATSU settings page.

**Comment by Siberier** [comment]
Thx all of u very much!

**Comment by Maximilian-Reuter** [comment]
> Thx all of u very much!

If this means your issue has been resolved then please close this issue as resolved!

**Comment by Lulsgate** [comment]
I'm having this issue too, despite following all of the steps.
