### ISSUE TITLE
Engines don´t start

### ISSUE THREAD

**Issue by Rikore** [flybywiresim/aircraft#8305]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2023-11-14T18:44:31+00:00",
    "ref": "refs/heads/master",
    "sha": "72a6813c7abcb600a0d7209e67fb2a6c7e68f677",
    "actor": "beheh",
    "event_name": "manual",
    "pretty_release_name": "master:72a6813c",
    "version": "v0.12.0-dev.72a6813"
}
```

### Describe the bug

Hello everyone!
I fly already from more than 2 years the Stable version of the AMAZING! A32NX.
But since about one week the engines don´t start.
Please URGENT HELP ME!!! My email is plsw@hotmail.com
Thank you!
Ricardo Nunes

### Expected behavior

Engines start normaly...

### Steps to reproduce

1....
2.

**Comment by tshomas** [comment]
Hi, do you use any of the "newlight" mods? If so could you remove them and retry? The mods are known to conflict with our systems!

**Comment by Rikore** [comment]
> Hi, do you use any of the "newlight" mods? If so could you remove them and retry? The mods are known to conflict with our systems!

i'am portuguese and i don't know what are newlight" mods

**Comment by tshomas** [comment]
Hi Rikore,

The mod in question is this: https://flightsim.to/file/55166/new-light-fbw-a32nx-enhancement-taxi-landing-light-and-other-extrior-light
This is known to cause your issue, if you do use it, please remove it and retry!

If you don't use this mod, can you reply please with some screenshots of when you're trying to start and we can diagnose further, faster help may also be found on our discord #a32nx-support channel

**Comment by Rikore** [comment]
> to

i wiil see if i have any of the "newlight" mods. If so i will remove them and retry.

**Comment by 2hwk** [comment]
Unable to reproduce, try with a clean community folder without liveries etc. Reopen if this is still an issue.
