### ISSUE TITLE
PACKS show when TOGA even if the FADEC is off

### ISSUE THREAD

**Issue by auroraisluna** [flybywiresim/aircraft#8313]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-11-14T18:44:31+00:00",
    "ref": "refs/heads/master",
    "sha": "72a6813c7abcb600a0d7209e67fb2a6c7e68f677",
    "actor": "beheh",
    "event_name": "manual",
    "pretty_release_name": "master:72a6813c",
    "version": "v0.12.0-dev.72a6813"
}
```

### Describe the bug

The PACKS indicator on the upper ECAM displays when throttles on TOGA even though both FADECS are off.

 ![image](https://github.com/flybywiresim/aircraft/assets/98479040/595c111c-816c-4c4e-ac21-9123276b0881)

### Expected behavior

The indicator should not be visible as the signal to the EEC is lost. 

### Steps to reproduce

1. Spawn the aircraft in C&D
2. Move throttles to TOGA, observe PACKS display on upper ecam
3. Wait 5 minutes for both FADEC to de-energize 
4. Repeat step 2

### Discord Username (optional)

alepouna

**Comment by auroraisluna** [comment]
Could attempt to fix it myself but I do not know how this signal is processed in the real aircraft to know where to "stop" it in the simulation

**Comment by ArtemisPlayer** [comment]
I am working on it (as a first issue), if the FADECS off are the only issue, that's an easy fix. However, it would be better the follow the behavior given here: [https://www.aviationhunt.com/a320-ecam-engine-warning-display/](https://www.aviationhunt.com/a320-ecam-engine-warning-display/ ). The best way would be to check that the engines are actually providing bleed air. It is normal that there are no faults on PACK 1 & PACK 2 when the engines are not running ?

**Comment by BlueberryKing** [comment]
Hi, great to see you interested in contributing! 

> I am working on it (as a first issue), if the FADECS off are the only issue, that's an easy fix. However, it would be better the follow the behavior given here: https://www.aviationhunt.com/a320-ecam-engine-warning-display/. The best way would be to check that the engines are actually providing bleed air.

I would just implement the FADEC power on/off logic for now. The current logic just checks whether the pack valve is open to determine whether to show the memo. I suspect there's more to it as it might not show PACKS are supplied APU rather than the engines

> It is normal that there are no faults on PACK 1 & PACK 2 when the engines are not running ?

I assume this is because you have the APU bleed on.
