### ISSUE TITLE
Disable in sim printer when using external one

### ISSUE THREAD

**Issue by lewiscorcoranwvr** [flybywiresim/aircraft#8316]
### Aircraft Version

Development

### Description

Would it be possible when using Simbridge to print via an external printer, to disable the in-sim printer to prevent duplicate printing. 

### Discord Username (optional)

.lewisc

**Comment by tracernz** [comment]
Yes, would be nice! We have a bug for that already :).
Duplicate https://github.com/flybywiresim/aircraft/issues/6444.
