### ISSUE TITLE
[PFD] TRK Diamond displayed off the scale

### ISSUE THREAD

**Issue by becas22** [flybywiresim/aircraft#8337]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-12-21T22:17:59+00:00",
    "ref": "refs/heads/master",
    "sha": "de25ee7e325402e2ad8f4eb8e923c6cc0f478863",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "master:de25ee7e",
    "version": "v0.12.0-dev.de25ee7"
}
```

### Describe the bug

Actual Track Symbol (small green diamond) is displayed off the scale.

![image](https://github.com/flybywiresim/aircraft/assets/11005754/daec347d-31b4-4688-9a29-be8efee5712a)

### Expected behavior

The symbol shall be contained within the heading reference

### Steps to reproduce

1. Get a drift angle bigger than the HDG scale

### Discord Username (optional)

Bernardo R

**Comment by Saschl** [comment]
Will have a look, can confirm
