### ISSUE TITLE
PTU Indication on SD Doesn't Appear

### ISSUE THREAD

**Issue by MrBacon8742** [flybywiresim/aircraft#8348]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-12-27T00:17:22+00:00",
    "ref": "refs/heads/master",
    "sha": "ef77d8d1f866dd2f10f46280b818d3a748733d4a",
    "actor": "lukecologne",
    "event_name": "manual",
    "pretty_release_name": "master:ef77d8d1",
    "version": "v0.12.0-dev.ef77d8d"
}
```

### Describe the bug

When powering the Yellow Electric Pump, the PTU indication on the hydraulic system display page won't show the direction of power transfer when switching to the SD page. If viewing the SD page, the PTU indication will display normally until the page is changed to another then back again.

### Expected behavior

The PTU indication to display normally when switching to the hydraulic SD page.

### Steps to reproduce

1. Ensure the SD page is not on the hydraulics page.
2. Turn on the Yellow Elec Pump.
3. Check that HYD PTU is shown on the EWD memo.
4. Switch to the hydraulics SD page.

### References (optional)

https://github.com/flybywiresim/aircraft/assets/86271675/3e07ed2f-38e1-48c4-8e41-aa5c645c69f5

### Discord Username (optional)

carlo_06

**Comment by robertxing2004** [comment]
Unable to reproduce, indications seem to display correctly on latest build unless I'm missing something?

https://github.com/flybywiresim/aircraft/assets/73909958/37bbf997-b266-4fcb-8ee1-9f020f0c91ef

Perhaps someone with more system knowledge than myself could verify that this is correct behaviour.

**Comment by Pruznak** [comment]
I tested multiple pages, also couldn´t reproduce, same results as above.

**Comment by flogross89** [comment]
Couldn’t re reproduced by three users -> closed
