### ISSUE TITLE
Engine goes to inoperable

### ISSUE THREAD

**Issue by Adi-18** [flybywiresim/aircraft#8365]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2024-01-01T16:30:08+00:00",
    "ref": "refs/heads/master",
    "sha": "1c2b9b644e85e2832950962d3d235aec81ff2e93",
    "actor": "Maximilian-Reuter",
    "event_name": "manual",
    "pretty_release_name": "master:1c2b9b64",
    "version": "v0.12.0-dev.1c2b9b6"
}
```

### Describe the bug

I can start my plane as before. But totay the engine goes to inoperable (i don't now how to explain)
After Start
![image](https://github.com/flybywiresim/aircraft/assets/29123730/7a61936d-5bf1-4fda-96e3-b69a06ea338b)

after while:
![image](https://github.com/flybywiresim/aircraft/assets/29123730/134fc8d4-5010-4e7e-85a0-3e8167dc23a7)

Over head panel:
![image](https://github.com/flybywiresim/aircraft/assets/29123730/5744f1d8-df4a-404f-9c6a-e6346c37d227)

### Expected behavior

There is no error message or anything for help.

### Steps to reproduce

1. Start MSFS
2. Load flight plan from world view
3. enter information like INIT and PREF
4. ask for take of clearance
5. While this time engine goes to inoperable

### Additional info (optional)

It tokes me 3h für this problem and now I am frustrated.

**Comment by beheh** [comment]
Your engine is not running in either screenshot. The indications turn amber after a few minutes as the digital systems in the engine turn themselves off.
