### ISSUE TITLE
INIT/REVIEW times resetting at touchdown

### ISSUE THREAD

**Issue by Vitold69** [flybywiresim/aircraft#8369]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-01-02T11:57:34+00:00",
    "ref": "refs/heads/master",
    "sha": "1f16d82017a1b163a6c4de4db6c7092d6b175ff8",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "master:1f16d820",
    "version": "v0.12.0-dev.1f16d82"
}
```

### Describe the bug

INIT/REVIEW times resetting at touchdown. After takeoff there are two identical times for OFF and ON fields. ON ground time is equal take OFF time probably because of micro jumps during takeoff roll. IN field is never filled. The whole page resets to empty exactly at touchdown moment. See pictures attached 

![3](https://github.com/flybywiresim/aircraft/assets/20175971/b12259aa-1731-4449-b3b3-81c2a44afd5e)
![4](https://github.com/flybywiresim/aircraft/assets/20175971/25d105ed-9094-41e5-8f9e-4f7ab1c7d0e2)

### Expected behavior

Some say this page should be reset at next flight. I don't know if it's possible. But it should not resets before full power down or exit a flight.

### Steps to reproduce

1. Do a full flight and look at INIT/REVIEW page

### Discord Username (optional)

Vitold69

**Comment by Vitold69** [comment]
Anyone?

**Comment by Vitold69** [comment]
> Happy to give this a shot

Any news? Thanks

**Comment by cptnuss-ops** [comment]
The values are cleared when the flightphase is set to done.
On boeing planes there is a timeout until this data is cleared to allow review/send.

Does anybody know what the real plane would behave? As some kind of workaround I would suggest to implement a 10 minute delay after the last engine is switched of and cleare the values afterwards?

I would wait for some feedback before I start writing the code.

FYI: @Vitold69 @2hwk

**Comment by tshomas** [comment]
> The values are cleared when the flightphase is set to done. On boeing planes there is a timeout until this data is cleared to allow review/send.
> 
> Does anybody know what the real plane would behave? As some kind of workaround I would suggest to implement a 10 minute delay after the last engine is switched of and cleare the values afterwards?
> 
> I would wait for some feedback before I start writing the code.
> 
> FYI: @Vitold69 @2hwk

Hi so yeah the ATSU side is airline specific but the OOOI times usually will remain until a new OUT time is recorded, at that point the others will blank, so in other words, when the next aircraft movement is recorded.

**Comment by cptnuss-ops** [comment]
Hi @tshomas,
thanks for the reply :).
What about the first page. Are the INIT-Values like Dep/Arr ICAO cleared then? If that's the case, not clearing the times should do the trick. So OOOI times will be overwritten if newer ones are present?

**Comment by tshomas** [comment]
In my airlines ATSU, the previous flights ICAO are cleared out after 5 mins or by the start of filling out the INIT page, so whichever you prefer!
The good part about ATSU is that you can effectively write it however you want, each airline has their own version, so as long as you can justify the logic then it's all good 👍

**Comment by rahulrathnakumar** [comment]
I've modified the ON time logic to ensure that the takeoff and landing times aren't recorded as the same value.
