### ISSUE TITLE
Bug: Development: FIRSTOFFICER_AVATAR has odd twitching movement from time to time

### ISSUE THREAD

**Issue by Popespice** [flybywiresim/aircraft#8382]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-01-04T21:00:56+00:00",
    "ref": "refs/heads/master",
    "sha": "b0e45def6c276e9494347e6c4503ac352ef3838b",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "master:b0e45def",
    "version": "v0.12.0-dev.b0e45de"
}
```

### Describe the bug

First Officer avatar has odd twitching motion from time to time during animation.

### Expected behavior

No twitching during animation.

### Steps to reproduce

1. Download latest Dev build of A32NX
2. Load into any airport
3. Turn on copilot avatar setting in EFB (off by default)
4. Turn to copilot and observe twitching animation in forearms and hands

### References (optional)

https://github.com/flybywiresim/aircraft/assets/155582210/d4acfd09-afaa-4cd5-ae1b-282101d9a46c

### Discord Username (optional)

popespice

**Comment by tracernz** [comment]
The animations/poses and the avatars themselves are from the sim, not from the A32NX. You can change the avatars in your sim settings. The poses/animations are then selected from a pre-determined set by the sim depending on the body type and aircraft type.
