### ISSUE TITLE
EFB: Pushback-radius dissapears when map is dragged with mouse

### ISSUE THREAD

**Issue by floriannr24** [flybywiresim/aircraft#8396]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-01-08T21:35:42+00:00",
    "ref": "refs/heads/master",
    "sha": "4230ccef32e6c711e513153b659d7a87428a6739",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "master:4230ccef",
    "version": "v0.12.0-dev.4230cce"
}
```

### Describe the bug

The EFB provides a pushback-functionality which lets you control the pushback of the aircraft (including pushbacks to the left and to the right). When you do a pushback to the left or to the right, the corresponding turning radius gets shown. However, the turning radius dissapears when you drag the "pushback-map" with your mouse. If you click the "center to plane" button, the radius appears again. 

### Expected behavior

The pushback-radius should be visible at all times, no matter if the map has been dragged or not

### Steps to reproduce

1. Do a straight default pushback 
2. Click the left/right buttons to move the aircraft into the desired direction: The pushback-radius appears.
3. With your mouse, click and drag the pushback-map a bit: The pushback-radius dissapears.
4. Click the "center to plane" button: The pushback-radius reappears

### Discord Username (optional)

Repa24

**Comment by frankkopp** [comment]
Works as intended - it must be in centered mode to be shown. 

```ts
  {/* Aircraft and Turning Radius Indicator */}
  <div className="flex absolute inset-0 justify-center items-center">
      {centerPlaneMode && !Number.isNaN(turningRadius) && Number.isFinite(turningRadius)
          && (
              <div
                  className="absolute"
                  style={{
                      transform: `rotate(-90deg) 
                  scaleX(${tugCmdSpdFactor >= 0 ? 1 : -1}) 
                  scaleY(${tugCmdHdgFactor >= 0 ? 1 : -1}) 
                  translateY(${turningRadius}px)`,
                  }}
              >
                  <TurningRadiusIndicator turningRadius={turningRadius} />
              </div>
          )}
      <IconPlane
          className="text-theme-highlight"
          style={{ transform: `rotate(-90deg) translateY(${Math.sign(aircraftIconPosition.x) * Math.min(1000, Math.abs(aircraftIconPosition.x))}px) translateX(${Math.sign(aircraftIconPosition.y) * Math.min(1000, Math.abs(aircraftIconPosition.y))}px)` }}
          size={a320IconSize(mapRange)}
          strokeLinejoin="miter"
          stroke={1}
      />
  </div>
```
