### ISSUE TITLE
Absence . In mach 

### ISSUE THREAD

**Issue by Waltervizzi** [flybywiresim/aircraft#8414]
### Aircraft Version

Stable

### Build info

```json
Last version
```

### Describe the bug

hi guys, I noticed that in reality when you are on a cruise in the FCU of the real plane in mach there is the. example -.-- instead in fbw there are only dashes without . example --- instead in the fenix it is correct. so that's bullshit but it would be nice to add it Thank you I say this because I love fbw and I want to give my contribution
![IMG-20240114-WA0015](https://github.com/flybywiresim/aircraft/assets/127858800/65b811e8-7ba2-4efa-9e1b-9954f68d0c9f)
![IMG-20240114-WA0014](https://github.com/flybywiresim/aircraft/assets/127858800/a2c6f343-9e4d-476a-8a38-bd95d7e769a2)
 In the primay proto its a correct real airbus 
The secondo photo its incorrect 

### Expected behavior

Only .

### Steps to reproduce

No bug

**Comment by jbud** [comment]
> > In a few areas of this video you can see during cruise the mach setting on the FCU does not display any decimal in managed mode. This is correct behavior. It's possibly a difference between the CEO and NEO. ![image](https://private-user-images.githubusercontent.com/6253799/297101507-f335f776-fc2b-4f88-aeee-5bf580822a25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MTkyNTksIm5iZiI6MTcwNTQxODk1OSwicGF0aCI6Ii82MjUzNzk5LzI5NzEwMTUwNy1mMzM1Zjc3Ni1mYzJiLTRmODgtYWVlZS01YmY1ODA4MjJhMjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTZUMTUyOTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTQ0ZDI4MDk2YTI4OTQwY2FlMmM5NjdkZmExMjQ5NmQ0MTA0YjQ1NDgxZjQwM2RiZDBhODFlMjc2ZTMxNjJiYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.U3plI_-7XA8Mr_RnVnBp1FTUiC8YofhS-nYF2iLRsfA)
> > [reference video](https://www.youtube.com/watch?v=Y1yQziRUFNY)
> 
> I have actually a second reference from here. https://youtu.be/emjgHkU5StE?si=VUm86PhVT-mEzYHU It has the decimal. I assume Airbus did both or the angle from the camera hides it in the Madeira one. ![Screenshot_20240116_162908_YouTube](https://private-user-images.githubusercontent.com/43846666/297104861-4c56d0b8-92d7-4b71-bc36-00fc897b2675.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0Mjc0NDUsIm5iZiI6MTcwNTQyNzE0NSwicGF0aCI6Ii80Mzg0NjY2Ni8yOTcxMDQ4NjEtNGM1NmQwYjgtOTJkNy00YjcxLWJjMzYtMDBmYzg5N2IyNjc1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDE3NDU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkOWI2MzQ5OTNjY2EzYTdjNTdiZjQxYmE4ZWJlZGI1NDViNDY2NDE5YzY2OTcwYzU5NmYxNjBmN2Q0MWY5OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HzMLu0Qmf4A0rVm75xBeEmQhZ9JuVKoKxXNP6ReyQZo)

Looking at the reference that is a 319ceo A319-112 It's possible the neo has different FCU software. Can you find any references on the NEO specifically as that is FBW's target?

**Comment by tshomas** [comment]
![Screenshot_20240116-175221](https://github.com/flybywiresim/aircraft/assets/74841560/2a23af0c-0a24-4224-98e2-f5750a153972)

Best I could do, you can just about see it, this is a NEO and I'll try to check in the future

**Comment by Waltervizzi** [comment]
yes sir the airbus a320 neo have point  -.--- see this video 12:53 minuts
https://www.youtube.com/watch?v=gNIP7t-fH3c&t=773s

**Comment by Waltervizzi** [comment]
another video https://www.youtube.com/watch?v=Vq8Lj0pp39o
look at the minute 2:10
