### ISSUE TITLE
Performance page v speeds locked after a rejected takeoff. 

### ISSUE THREAD

**Issue by johnpmaguire** [flybywiresim/aircraft#8423]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-01-17T00:02:22+00:00",
    "ref": "refs/heads/master",
    "sha": "d67cd0d3829ba675b6df780e4d5b5d3a39d3d245",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "master:d67cd0d3",
    "version": "v0.12.0-dev.d67cd0d"
}
```

### Describe the bug

After a rejected takeoff the v speeds are no longer editable. If an entry is attempted by using the LSK for V1 V2 or VR the message "not allowed" is displayed in the scratch pad. This was discussed on Discord with Shomas.  The suggestion to reset the FD as this is required irl was tested. No change the entries remained locked and the not allowed message displayed.

Although the FD on/off is required irl I am not sure this should prevent a change in the data set for v speed. 

### Expected behavior

After a rejected takeoff the v speeds should be able to be changed by using the scratch pad to enter the new speeed and any of the v speed LSK should alter the speed if a valid speed was entered into the scratchpad.

### Steps to reproduce

Set up a full departure from the runway will be sufficient. Reject the takeoff after TO thrust is set. Edit the perf page and enter a new value for any v speed. Test with and without turning off/on both FD. The value will not be entered and a message "not allowed" will be displayed. 

### Additional info (optional)

Shomas believed this may have worked in the past. This was the first time I rejected a takeoff. I cannot provide any confirmation.

### Discord Username (optional)

john P Maguire#9027

**Comment by beheh** [comment]
This was intentionally removed back in #7117. We have no evidence this is possible in the real aircraft, an in fact evidence that suggest an engine shutdown is necessary (or possibly a re-init).

**Comment by beheh** [comment]
I'll follow up on the FD deactivation.

**Comment by beheh** [comment]
After some [discussion in Discord](https://discord.com/channels/738864299392630914/838062729398976522/1197296835484717148) it seems we identified that the current implementation is indeed correct. Closing this for now.
