### ISSUE TITLE
Plane does not move

### ISSUE THREAD

**Issue by jaoord** [flybywiresim/aircraft#8426]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-01-17T00:02:22+00:00",
    "ref": "refs/heads/master",
    "sha": "d67cd0d3829ba675b6df780e4d5b5d3a39d3d245",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "master:d67cd0d3",
    "version": "v0.12.0-dev.d67cd0d"
}
```

### Describe the bug

The plane does not move on the ground.

### Expected behavior

With one or both engines running and the parking brake off, the plane should move once a bit of throttle has been applied.

### Steps to reproduce

1. load dev version
2. load plane up (flightplan, fuel, pax) like you would normally do
3. start apu
4. start engines
5. try to taxi. it does not move. See video below.

### References (optional)

https://medal.tv/games/microsoft-flight-simulator/clips/1PQgWeLZVwa0Xm/d1337JxOoVAn?invite=cr-MSxYZXAsMTU3ODE3NDM2LA

### Additional info (optional)

I also tried with one engine (RH engine) and then the plane did actually move. But after starting the left hand engine i could not taxi anymore.

I tested with safety cones/chocks on and off in the flypad sim settings, but it did not make a difference (they were on by default when I loaded the plane).

### Discord Username (optional)

speedbrake

**Comment by donstim** [comment]
You will normally get faster service in our Discord support channel for issues like this. It appears to me from looking at your brake pressure indicator that you have the left brake being applied. I would check your controller bindings to see if you have an expected binding or a stuck controller that is applying the left brake.

**Comment by jaoord** [comment]
Thanks, i'll double check my controller settings tonight and if there are still issues I'll take it to Discord.
