### ISSUE TITLE
Init Request needs adjustment due Simbrief Update

### ISSUE THREAD

**Issue by derfelix54** [flybywiresim/aircraft#8428]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-01-17T22:33:13+00:00",
    "ref": "refs/heads/master",
    "sha": "0024437e56e6599f836f6135896cd7565d6ea281",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "master:0024437e",
    "version": "v0.12.0-dev.0024437"
}
```

### Describe the bug

When doing an init request from simbrief you get the initial altitude as CRZ FL imported. This was correct before as Simbrief was using the CRZ FL as inital altitude. Now however Simbrief does not use the cruising altitude as initial altitude anymore. 
![image](https://github.com/flybywiresim/aircraft/assets/43846666/94c55944-47e6-44a5-b716-dd90707c0f3a)

Here in the screenshot you can see under the route section that the crusing altitude later on would be FL380 at waypoint KPT. 
When doing an init request you can see I get the initial altitude as CRZ FL:
![image](https://github.com/flybywiresim/aircraft/assets/43846666/ef7e1e2c-b43a-40cf-b8d4-45a325e36d5b)

### Expected behavior

Getting the correct CRZ FL imported from Simbrief.

### Steps to reproduce

1. Create an Flightplan from Simbrief.
2. Do init request in the MCDU.
3. Observe inital altitude as CRZ FL

### Discord Username (optional)

verolix22

**Comment by tracernz** [comment]
This seems to be imported correctly, but just a weird flight plan. This would be like cruising at FL120 initially (due to airway ceiling) and then step climb to FL380? Step climbs are supported. Probably L856 is not an appropriate airway however.

**Comment by derfelix54** [comment]
> This seems to be imported correctly, but just a weird flight plan. This would be like cruising at FL120 initially (due to airway ceiling) and then step climb to FL380? Step climbs are supported. Probably L856 is not an appropriate airway however.

Are you saying that in this case the initial import of FL120 as CRZ is correct ?

**Comment by tracernz** [comment]
Yes. That is the highest cruising altitude allowed on the airway L856.

**Comment by derfelix54** [comment]
Okay my mistake then. I will close this issue. Thanks!

**Comment by tracernz** [comment]
No problem! It's certainly a peculiar case and quite interesting to look at!
