### ISSUE TITLE
FMA second box misplaced

### ISSUE THREAD

**Issue by DerbeQ** [flybywiresim/aircraft#8429]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-01-17T22:33:13+00:00",
    "ref": "refs/heads/master",
    "sha": "0024437e56e6599f836f6135896cd7565d6ea281",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "master:0024437e",
    "version": "v0.12.0-dev.0024437"
}
```

### Describe the bug

As in the title, FMA second box text is misplaced. Attention getting box seems to work just fine.

### Expected behavior

Text would be centered inside the box.

### Steps to reproduce

1. Spawn in the A32NX
2. Do whatever to cause changes in the second FMA box (e.g. reach cruising altitude, capture the glide slope)

### References (optional)

https://www.youtube.com/watch?v=6SGN3dtba2s

Screenshots of the current state of the FBW systems:
![image](https://github.com/flybywiresim/aircraft/assets/38384268/7f7b576f-ba0d-409a-8af5-fbfd1f43d77f)
![image](https://github.com/flybywiresim/aircraft/assets/38384268/23047b1d-9bbd-480f-85f6-940d02919ec1)

### Discord Username (optional)

DerbeQ

**Comment by BravoMike99** [comment]
Id guess some PR must have touched the PFD which broke this bit unintentionally, since this was fine until some days ago if I'm not mistaken. Ill try to take a look nonetheless.

**Comment by BravoMike99** [comment]
I just gave it a spin and this is how the FMA looks on my end, perhaps some addon causing conflicts? 
![image](https://github.com/flybywiresim/aircraft/assets/119708186/0c7fd3df-36e1-4e32-b418-d70fee068dfc)

**Comment by DerbeQ** [comment]
> I just gave it a spin and this is how the FMA looks on my end, perhaps some addon causing conflicts? ![image](https://private-user-images.githubusercontent.com/119708186/298186215-0c7fd3df-36e1-4e32-b418-d70fee068dfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2OTU0NDMsIm5iZiI6MTcwNTY5NTE0MywicGF0aCI6Ii8xMTk3MDgxODYvMjk4MTg2MjE1LTBjN2ZkM2RmLTM2ZTEtNGUzMi1iNDE4LWQ3MGZlZTA2OGRmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQyMDEyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDFmYzg3MjMzNGU4ZTFmZDVkY2E2MjI4Zjk0N2IwYjE3N2ZiNjBmZjVhZmU5MzcyZTY0NWNmNDExN2I0NmViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X6cBku4PZxM6bK2ztVcriBgqToRUTAFcxtUxua9nERU)

That's quite interesting. Actually I noticed this issue with our (Horizon) LVFR A321neo mod and then verified it happens with the A32NX as well. One of our devs has it also. We'll investigate then.

**Comment by DerbeQ** [comment]
![image](https://github.com/flybywiresim/aircraft/assets/38384268/5c309c6f-7b73-4d76-98d8-475c0318a166)
It's how it looks as of now.

**Comment by BravoMike99** [comment]
I did a quick ILS test and it also looks fine to me. I guess whatever is causing it on your end seems to be affecting the whole vertical FMA 
![image](https://github.com/flybywiresim/aircraft/assets/119708186/d64d870d-f016-418b-8bd2-499ea49f2657)

**Comment by tshomas** [comment]
I've just been trying to do some testing on another PR and noticed DerbeQs behaviour, can confirm vertical FMA column seems to get displaced to the left slightly, not sure what triggers it yet

**Comment by BravoMike99** [comment]
I was just doing a flight and noticed the issue myself. No idea why it didn't trigger when I did some patterns a few days ago. Seems to be caused by an extra char in the PFD file introduced in a recent PR
