### ISSUE TITLE
ND: VOR bearing pointer appears on top of DME & Chrono

### ISSUE THREAD

**Issue by BravoMike99** [flybywiresim/aircraft#8445]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-01-25T02:53:25+00:00",
    "ref": "refs/heads/master",
    "sha": "cf1e4f4a3cebd96c68cdc4e82f6a1a6d875403ef",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "master:cf1e4f4a",
    "version": "v0.12.0-dev.cf1e4f4"
}
```

### Describe the bug

VOR Bearing pointer appears drawn on top of the VOR indications & chrono at the bottom of the ND. 
![image](https://github.com/flybywiresim/aircraft/assets/119708186/6514a1cc-0613-4db0-8ebc-47f2769db3f4)
![ND2](https://github.com/flybywiresim/aircraft/assets/119708186/fc67d06a-f414-4df0-9d3e-37f55283cc0d)

### Expected behavior

VOR bearing pointer should "stay behind" the VOR info & chrono.

### Steps to reproduce

Position yourself in such a way in relation to a VOR station so that the bearing pointer appears on the bottom area of the ND

### Discord Username (optional)

bruno_pt99

**Comment by tracernz** [comment]
NDv2 regression.

**Comment by Saschl** [comment]
Will check that and #8445

**Comment by BravoMike99** [comment]
@Saschl since you are working on this ND regression and a few others, I managed to an issue where sometimes the VOR DME indication seems to have this huge spacing from the "NM" text which causes it to go partly outside the display once DME is greater than 3 digits. I've never been able to replicate it/figure out what causes hence why I never created an issue. Just letting you know in case you want to try and take a look at that in your PR.(If it doesn't fix this already)
![ND VOR](https://github.com/flybywiresim/aircraft/assets/119708186/e9750bb5-377d-4cc9-b1c2-a2e8921d6ae2)

**Comment by Saschl** [comment]
Thanks, I was able to reproduce the issue artificially, I think it's due to the tspan still taking place (not being blanked out when range >20) but is hidden.

**Comment by tracernz** [comment]
There are two types of hidden. Not visible on the screen but still considered in the layout (e.g. SVG `visibility`), and not visible or even considered in the layout (`display: none`, or better our `HiddenElement` CSS class). Both are useful for different things. More hints here: https://coherent-labs.com/Documentation/cpp-gt/df/dd6/hiding_showing_elements.html
