### ISSUE TITLE
Heading bug appears on ND after pressing TRK/FPA while in NAV mode

### ISSUE THREAD

**Issue by BravoMike99** [flybywiresim/aircraft#8449]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-01-27T23:22:37+00:00",
    "ref": "refs/heads/master",
    "sha": "f79d82e6dc4ce68dd54aa6c095a9a28c132b9754",
    "actor": "aguther",
    "event_name": "manual",
    "pretty_release_name": "master:f79d82e6",
    "version": "v0.12.0-dev.f79d82e"
}
```

### Describe the bug

Pressing TRK/FPA button on the FCU while "NAV" mode is engaged causes the heading bug to appear on the Navigation Display.

https://github.com/flybywiresim/aircraft/assets/119708186/2e8336ba-e4e6-4e70-a340-9f8b5a27343f

### Expected behavior

ND bug not to appear since navigation is a managed mode.

### Steps to reproduce

Press TRK/FPA button on the FCU while "NAV" mode is engaged

### Discord Username (optional)

bruno_pt99

**Comment by Saschl** [comment]
Will check this and #8445

**Comment by Saschl** [comment]
Looks like the Simvar `A32NX_AUTOPILOT_HEADING_SELECTED` is being set to a wrong value (~359°) when being airborne and switching to TRK/FPA. Per our docs, the Simvar is `-1` when managed heading is active and uses this to show/hide the bug.
