### ISSUE TITLE
AI CO-PILOT asks for clearance without power to aircraft via external power/APU

### ISSUE THREAD

**Issue by ethanhines** [flybywiresim/aircraft#8452]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2023-11-03T17:47:36+00:00",
    "ref": "refs/tags/v0.11.1",
    "sha": "f055eb02dc0af32441f8b2873f58e8316d7ca638",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.11.1",
    "version": "v0.11.1-rel.f055eb0"
}
```

### Describe the bug

After the world menu and after pressing "Ready to Fly" in the cold/dark state, if the AI-Copilot Radio Communications is active, _even_ if the aircraft has no power the ai-copilot will attempt to get clearance, after power is properly restored via external or APU power the ai-copilot continues to get proper clearance.

### Expected behavior

When in the cold/dark state the ai-copilot should not attempt to make any attempt to communicate with anyone if the com panel has no power.

### Steps to reproduce

Ensure that AI Radio Communications (ATC) is activated
Select the FBW A320N in the world menu
Select a gate to start at
Wait for the "Ready to Fly" button appears press the button
The Ai-Copilot will not attempt to communicate with anyone (Clearance/Tower/Ground) _untill_ power is applied to the aircraft.

### References (optional)

https://github.com/flybywiresim/aircraft/assets/2016753/9bc92911-5c4f-41f5-8bbc-9112a6a12694

### Discord Username (optional)

ethanhines

**Comment by frankkopp** [comment]
We do not support the AI CoPilot.
This will be closed.

**Comment by Vitold69** [comment]
> We do not support the AI CoPilot. This will be closed.

🤦🏻‍♂️
He is taking about different thing! Radio SHOULD NOT WORK at cold&dark plane!

**Comment by alepouna** [comment]
> > We do not support the AI CoPilot. This will be closed.
> 
> 🤦🏻‍♂️ He is taking about different thing! Radio SHOULD NOT WORK on cold&dark plane!

And it does not work under normal conditions, the OP suggests the issue appears when using the AI CoPilot. We do not support this, therefore misbehavior and bugs are to be expected.

**Comment by ethanhines** [comment]
> > We do not support the AI CoPilot. This will be closed.
> 
> 🤦🏻‍♂️ He is taking about different thing! Radio SHOULD NOT WORK on cold&dark plane!

Exactly the radios should not work in a cold&dark plane forgive me for mentioning the ai copilot......

**Comment by ethanhines** [comment]
This does not happen in any other MSFS vanilla aircraft so it’s obviously a bug in the FBW aircraft......

**Comment by ethanhines** [comment]
>And it does not work (it is not powered, to be exact) under normal flight conditions, the OP suggests the issue appears when using the AI CoPilot. We do not support this, therefore misbehavior and bugs are to be expected.

What I also said was AI Radio Communications (ATC) is activated

**Comment by Benjozork** [comment]
We don't support any of the AI features at the moment.

**Comment by tracernz** [comment]
> This does not happen in any other MSFS vanilla aircraft so it’s obviously a bug in the FBW aircraft......

It’s only a bug if we intend to support this use-case, which we don’t.
