### ISSUE TITLE
EFB when popped out on Throttle Calibration temporarily locks up

### ISSUE THREAD

**Issue by FWB800** [flybywiresim/aircraft#8455]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2023-11-03T17:47:36+00:00",
    "ref": "refs/tags/v0.11.1",
    "sha": "f055eb02dc0af32441f8b2873f58e8316d7ca638",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.11.1",
    "version": "v0.11.1-rel.f055eb0"
}
```

### Describe the bug

During throttle calibration on the EFB, if for example you were calibrating then changed screens away from MSFS then returned to MSFS, the EFB would behave as though it had locked up in that there would be no movement of the throttles indicated. If you zoomed out to show the EFB in the background, there would be no response on the 'normal' size EFB. Viewing the co-pilots EFB would be the same, no movement. For example if you were calibrating CLB position, to get movement to be acknowledged again, you had to select any other throttle position such as TOGA. This would then allow you to continue calibrating. At any point during calibration if you saved and applied, the indicated throttle position will change to Idle no matter what it was set to. I was setting up the TCA Airbus Captains X Quadrant.

### Expected behavior

I expected the EFB to just be able to continue calibrating the throttle positions.

### Steps to reproduce

Just simply using the EFB to calibrate the various A320 throttle positions, this problem was 100% repeatable.

### Additional info (optional)

Not known if this is old or new problem as this was the 1st time I had 'popped' out any part of the cockpit.

### Discord Username (optional)

SAshton

**Comment by frankkopp** [comment]
Can you provide a video? 
I do not really understand your description.

**Comment by FWB800** [comment]
When your calibrating the throttle positions, the EFB shows the throttle
position and the dead zones. So for example if you were calibrating IDLE
then you go away from MSFS to goto Discord or Facebook for example then
return to MSFS and click on the EFB, the throttle position bars when
calibrating do not respond, neither does the efb on the co-pilot side, they
do not show any throttle movement. If you then click on CLB for example the
throttle bars then show a response.

regards

Steve

**Comment by frankkopp** [comment]
Sim Issue - mouse must be on the sim's screen not any pop-out window. 
See video.

https://github.com/flybywiresim/aircraft/assets/16833201/1b5471be-3e0c-4473-af1c-2ec008ddd43f
