### ISSUE TITLE
Engine starting issue

### ISSUE THREAD

**Issue by psl235** [flybywiresim/aircraft#8456]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-01-29T23:38:38+00:00",
    "ref": "refs/heads/master",
    "sha": "b4c2044e8bf3e13ec90fd5711d520f82e65526e6",
    "actor": "flogross89",
    "event_name": "manual",
    "pretty_release_name": "master:b4c2044e",
    "version": "v0.12.0-dev.b4c2044"
}
```

### Describe the bug

Suddenly, after recent updates. I am unable to start the engines, using the standard starting procedure. 

### Expected behavior

Engines startup as normal

### Steps to reproduce

I have tried the stable version as well, I also completely uninstalled and reinstalled, but with same problem (the engines won't start) the

**Comment by donstim** [comment]
I suggest you seek assistance in our Discord support channel https://discord.com/channels/738864299392630914/785976111875751956. Do you have the newlight mod installed?  That is known to prevent the engines from starting. Try this: https://docs.flybywiresim.com/fbw-a32nx/support/reported-issues/#test-with-only-the-a32nx-add-on-in-community to determine if one of your mods or liveries is causing this. If not, try this: https://docs.flybywiresim.com/fbw-a32nx/settings/#utf-8-support

**Comment by psl235** [comment]
Hello,
The problem is gone, after removing LVFR A321 NEO....
Thank you very much and Best Regards
