### ISSUE TITLE
[BUG] Fire Extinguisher bug

### ISSUE THREAD

**Issue by LorDawid** [flybywiresim/aircraft#849]
**Mod Version**

dev version, newest msfs version

**Describe the bug**

The fire button illumination looks awful

**To Reproduce**

1.Pop the fire extinguisher
2.Use the test button
3.see how awful it looks

**References**

Discord username (if different from GitHub): LorDawid#6403

**Comment by LorDawid** [comment]
for some reason the photos didnt show up at all, so i will link them there 
![image](https://user-images.githubusercontent.com/44745662/94194480-08977980-feb2-11ea-9961-05275f03233d.png)
![Microsoft Flight Simulator Screenshot 2020 09 24 - 21 50 54 40](https://user-images.githubusercontent.com/44745662/94194505-13520e80-feb2-11ea-9cc7-fb965c60fb94.png)

**Comment by calwalker1** [comment]
Just to chime in on this bug, this is also the case on the nose-gear tiller. The top of the handle when flying at night has a faulty texture map similar to this, so it is not honouring it being night-time.

**Comment by derl30n** [comment]
Current state:

![image](https://user-images.githubusercontent.com/1857322/162617758-baa2fa5a-e82a-4a32-9a66-7e008ebab757.png)
