### ISSUE TITLE
Master caution/Master warning not working in DEV, but working in Stable using Skalarki FCU

### ISSUE THREAD

**Issue by ErikNL80** [flybywiresim/aircraft#8506]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-02-18T00:39:53+00:00",
    "ref": "refs/heads/master",
    "sha": "5897a9175368735fb3dd4bad7b4a52b8dc3fca14",
    "actor": "lukecologne",
    "event_name": "manual",
    "pretty_release_name": "master:5897a917",
    "version": "a32nx-v0.12.0-dev.5897a91"
}
```

### Describe the bug

I am using a Skalarki FCU, but also a StreamDeck XL. When powering the aircraft C&D, the master caution appears on the StreamDeck, but not on the FCU. In the stable version, but also on the HorizonMod and Headwind A330neo (all based on FBW) everything is working OK. Is something changed regarding these variables? (Master warning, master caution and autoland button)?

### Expected behavior

I would expect the master caution to be visible on the Skalarki FCU as well.

### Steps to reproduce

1. Install the stable version
2. Start a flight C&D
3. Check the Master Caution/Master warning on the Skalarki FCU [OK]
4. Install the dev version
5. Start a flight C&D
6. Check the Master Caution/Master warning on the Skalarki FCU [N OK]

### Discord Username (optional)

eriknl80

**Comment by tracernz** [comment]
Some old legacy files with no longer used vars are removed. That is probably the cause.

**Comment by ErikNL80** [comment]
> Some old legacy files with no longer used vars are removed. That is probably the cause.

Can you please indicate which vars and how I can find them?

**Comment by tracernz** [comment]
Left master caution light top half, and the bottom half is SEQ2_CODE below: https://github.com/flybywiresim/aircraft/blob/d9a3917b02d1a6b5f748a7aa5c2aa22bc2df6c38/fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml#L5051

Left master warning: https://github.com/flybywiresim/aircraft/blob/d9a3917b02d1a6b5f748a7aa5c2aa22bc2df6c38/fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml#L5075

You can find the right side also nearby in that file. We will hopefully wrap these in input (B) events at some point so 3rd parties don't need to duplicate the electrical logic etc.
