### ISSUE TITLE
Autopilot display text messed up

### ISSUE THREAD

**Issue by NorwegianAvgeek** [flybywiresim/aircraft#8544]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-03-01T18:14:00+00:00",
    "ref": "refs/heads/master",
    "sha": "83ea2851d9a7472362bdbdd8f61bcb9ab9c9b3e7",
    "actor": "Gurgel100",
    "event_name": "manual",
    "pretty_release_name": "master:83ea2851",
    "version": "a32nx-v0.12.0-dev.83ea285"
}
```

### Describe the bug

The text is almost out of the display and the text on it asvel is very small. 

### Expected behavior

i expected it to be just as on the normal a320 neo.

### Steps to reproduce

1. I got thrown ot of Vatsim in MSFS due to the plane not beeing updatet.
2. I left and updated the plane.
3. When i got on MSFS the next day it just was messed up.

### References (optional)

![Screenshot 2024-03-01 204354](https://github.com/flybywiresim/aircraft/assets/161881962/70f351a5-3d54-4f1b-9d5c-58d9ec74ed21)

### Additional info (optional)

I have flown the A320 neo FBW plane for a long time, and have not been an issue until now recently.

### Discord Username (optional)

tcmNinja2#6483

**Comment by tracernz** [comment]
Remove mods and this problem will go away. Specifically something is overriding your FCU with an old version.
