### ISSUE TITLE
TRK / FPA annunciators missing from FCU

### ISSUE THREAD

**Issue by lirondco** [flybywiresim/aircraft#8549]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-03-01T18:14:00+00:00",
    "ref": "refs/heads/master",
    "sha": "83ea2851d9a7472362bdbdd8f61bcb9ab9c9b3e7",
    "actor": "Gurgel100",
    "event_name": "manual",
    "pretty_release_name": "master:83ea2851",
    "version": "a32nx-v0.12.0-dev.83ea285"
}
```

### Describe the bug

TRK | FPA doesn't show up in place of HDG | V/S when switching, and TRK doesn't replace HDG above the the knob. 

### Expected behavior

TRK | FPA and TRK should show up on the FCU when we switch modes

### Steps to reproduce

1. load into the plane
2. wait for plane to boot up
3. switch to TRK/FPA

### References (optional)

![image](https://github.com/flybywiresim/aircraft/assets/60845154/17c554f8-2ee9-4500-b0a0-9d9593078ed6)
![image](https://github.com/flybywiresim/aircraft/assets/60845154/d97b3ba3-8894-4b41-9e52-ba341bee244a)

**Comment by frankkopp** [comment]
Make sure to test and reproduce this with ONLY the A32NX in Community. Really - only one folder in Community, the a32nx folder.
If the issue still is there, please report back. 
Otherwise please close this report as another mod/add-on caused this.
