### ISSUE TITLE
With current Update, can no more start APU.

### ISSUE THREAD

**Issue by Adi-18** [flybywiresim/aircraft#8550]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2024-03-01T18:14:00+00:00",
    "ref": "refs/heads/master",
    "sha": "83ea2851d9a7472362bdbdd8f61bcb9ab9c9b3e7",
    "actor": "Gurgel100",
    "event_name": "manual",
    "pretty_release_name": "master:83ea2851",
    "version": "a32nx-v0.12.0-dev.83ea285"
}
```

### Describe the bug

Push on the APU MASTER SW and START. its on fault imitatively.
![image](https://github.com/flybywiresim/aircraft/assets/29123730/39d06803-e39e-4003-a17e-126a52f1888f)

### Expected behavior

simply push on the APU MASTER SW and START. The APU should be on within one minute.

### Steps to reproduce

Start MSFS wit FBW A320
Press Ext Power
Press APU MASTER
Press APU START

**Comment by BravoMike99** [comment]
You need the batteries turned on in order to start the APU. The starter is powered by the battery bus and not by any of the AC buses.

**Comment by kiwi2021** [comment]
> You need the batteries turned on in order to start the APU hence why you are getting the fault. The APU starter & ECB (Electron ic control box) are only powered by the battery bus.

APU can be started using power from the aircraft's batteries, normal electrical system or ground service. This meaning that batteries wouldn't necessarily need to be one if external power is available?

**Comment by tshomas** [comment]
Nope as BravoMike says, the batteries supply the APU control units so they are required to be on, if you check the ELEC page during an APU start, even with GPU connected the batteries will deplete and then be recharged

**Comment by denmax18** [comment]
![20240303213406_1](https://github.com/flybywiresim/aircraft/assets/57813016/a337233a-04d4-4600-8fa6-d472f6b1a371)
  Its working fine APU

**Comment by denmax18** [comment]
![20240303214229_1](https://github.com/flybywiresim/aircraft/assets/57813016/c54afeb8-9e1a-4663-9eb8-719c63b81bbf)
Its working fine APU
