### ISSUE TITLE
throttle

### ISSUE THREAD

**Issue by shams227** [flybywiresim/aircraft#8561]
### Aircraft Version

Stable

### Build info

```json
can not tell
```

### Describe the bug

Hi
I have velocity tutle beach v1 throttle and thrust master hotas t4 , problem is the throttle is giving me only 79% thrust and on idle it goes to thrust reverse , i tried both my controles separatly disconnecting one and working on the other one but  same result, I tried all the fixes in the book but stil no hope , now i am totally grounded with ur aircraft so please help 

### Expected behavior

toga thrust

### Steps to reproduce

do not know

### Discord Username (optional)

drsg227979

**Comment by jbud** [comment]
Have you completed all steps here?: [https://docs.flybywiresim.com/fbw-a32nx/feature-guides/flypados3/throttle-calibration/](https://docs.flybywiresim.com/fbw-a32nx/feature-guides/flypados3/throttle-calibration/)

Sounds like you may have reverser on axis on. As far as TOGA thrust it is almost never 100% thrust and is very dependant on environment such as OAT, density altitude etc.

some screenshots can be very helpful to further diagnose

**Comment by shams227** [comment]
I will recheck and if I find that I did all the steps and problem continue I will send u screen shots thanx for ur reply


Sent from Yahoo Mail for iPhone


On Monday, March 11, 2024, 11:41 PM, Joe Jackson ***@***.***> wrote:




Have you completed all steps here?: https://docs.flybywiresim.com/fbw-a32nx/feature-guides/flypados3/throttle-calibration/

Sounds like you may have reverser on axis on. As far as TOGA thrust it is almost never 100% thrust and is very dependant on environment such as OAT, density altitude etc.

some screenshots can be very helpful to further diagnose

**Comment by jbud** [comment]
Did this end up resolving your issue? Just wanted to check in 👍 

> I will recheck and if I find that I did all the steps and problem continue I will send u screen shots thanx for ur reply Sent from Yahoo Mail for iPhone On Monday, March 11, 2024, 11:41 PM, Joe Jackson ***@***.***> wrote: Have you completed all steps here?: https://docs.flybywiresim.com/fbw-a32nx/feature-guides/flypados3/throttle-calibration/ Sounds like you may have reverser on axis on. As far as TOGA thrust it is almost never 100% thrust and is very dependant on environment such as OAT, density altitude etc. some screenshots can be very helpful to further diagnose — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>
