### ISSUE TITLE
Erroneous sound? Or easter egg... FBW_A320_NEO_2.PC_89

### ISSUE THREAD

**Issue by sparxooo** [flybywiresim/aircraft#8562]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-03-10T19:20:51+00:00",
    "ref": "refs/heads/master",
    "sha": "47dbbd872ed469c9b1f9f5e141a8d6cb666c888c",
    "actor": "Maximilian-Reuter",
    "event_name": "manual",
    "pretty_release_name": "master:47dbbd87",
    "version": "a32nx-v0.12.0-dev.47dbbd8"
}
```

### Describe the bug

There appears to be a sound of someone shouting "AMONG US" in the sound pack files.

In FBW_A320_NEO_2.PC.pck, "PC_89"

### Expected behavior

Not to brown my pants whilst listening to what sounds are in the mod 😶

### Steps to reproduce

Listen to sound 89? In sound pack 2.

### References (optional)

[FBW_A320_NEO_2.PC_89.zip](https://github.com/flybywiresim/aircraft/files/14563593/FBW_A320_NEO_2.PC_89.zip)

**Comment by hotshotp** [comment]
:P

**Comment by sparxooo** [comment]
May the brown pants be plentiful into the future.

Please please please make a really rare and random act trigger this sound in flight... 😂
