### ISSUE TITLE
Simbridge wont run?

### ISSUE THREAD

**Issue by acgrahame62** [flybywiresim/aircraft#8567]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-03-10T19:20:51+00:00",
    "ref": "refs/heads/master",
    "sha": "47dbbd872ed469c9b1f9f5e141a8d6cb666c888c",
    "actor": "Maximilian-Reuter",
    "event_name": "manual",
    "pretty_release_name": "master:47dbbd87",
    "version": "a32nx-v0.12.0-dev.47dbbd8"
}
```

### Describe the bug

SimBridge will not start?

### Expected behavior

SimBridge will not start?

### Steps to reproduce

Cant start SimBridge from the installer

**Comment by alepouna** [comment]
Hi, you have not provided any information about the issue so it's hard to troubleshoot. I would recommend joining our [Discord](https://discord.gg/flybywire) and use the support channels there 👍

**Comment by acgrahame62** [comment]
Hi - I’ve  provided all I can SimBridge simply won’t start? Never had an issue before. I have tried everything including a full re-install. Let me know what data you require to assist meThanks On 12 Mar 2024, at 18:37, Aurora Takemi ***@***.***> wrote:﻿
Hi, you have not provided any information about the issue so it's hard to troubleshoot. I would recommend joining our Discord and use the support channels there 👍

**Comment by deiks** [comment]
Might be missing tray icon (actually there's but invisible -- can be pointed by mouse). I have that issue, but the process is started and works fine.

**Comment by acgrahame62** [comment]
Thanks deiks - I have now worked it out, it was my webroot anti-virus not letting simbridge run. No idea why it suddenly blocked it unless FMW have made changes to the .exe - anyway now all up and running.

**Comment by jbud** [comment]
this can be closed now
