### ISSUE TITLE
First STAR Waypoint has no limits set

### ISSUE THREAD

**Issue by aaaabcv** [flybywiresim/aircraft#8572]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-03-10T19:20:51+00:00",
    "ref": "refs/heads/master",
    "sha": "47dbbd872ed469c9b1f9f5e141a8d6cb666c888c",
    "actor": "Maximilian-Reuter",
    "event_name": "manual",
    "pretty_release_name": "master:47dbbd87",
    "version": "a32nx-v0.12.0-dev.47dbbd8"
}
```

### Describe the bug

Limits in first WP of STAR are not used if there are some. I have reproduced this with LOWW and EDDM and compared it with Littlenavmap as well as inibuilds A310.

### Expected behavior

The limits are set correctly on first waypoint of star

### Steps to reproduce

1.  e.g. use followinf enroute route for EDDM to LOWW: ODSU2C SOVIL DCT SITNI DCT BAGSI DCT MATIG DCT AMADI Q113 NAPSA in MCDU via simbrief.
2. Note that NAPSA has no limits but is in the route of course
3. Add Arrival NAPS1B for RW26L (the approach is not relevant)
4. NAPSA should have limits B10000, B250 but they are not set

### Additional info (optional)

It appears that the limits are in the data from MSFS but are not used and (no proof) it might be an issue that the WP is already there and the merge between first STAR and existing WP is resolved by dropping the first STAR WP and omitting the limits.

**Comment by Pruznak** [comment]
Can confirm on BIMP5U STAR to EPWA and on ALBE2E STAR to LIPZ, may have happened on more STARs, I just don´t remember.

**Comment by BlueberryKing** [comment]
Fixed with #7692

**Comment by Pruznak** [comment]
I think this can be closed now ? I retested on EDDF/25C N0433F360 OBOK5N OBOKA Z29 TORNU DCT ABNED L980 LOGAN LOGA2H EGLL/27R, where I could reproduce it before, but now I can´t reproduce it.

**Comment by BlueberryKing** [comment]
> I think this can be closed now ? I retested on EDDF/25C N0433F360 OBOK5N OBOKA Z29 TORNU DCT ABNED L980 LOGAN LOGA2H EGLL/27R, where I could reproduce it before, but now I can´t reproduce it.

Yep, you're right!
