### ISSUE TITLE
press: Switching between manual and auto pressurization control causes a cabin altitude jump on the ground

### ISSUE THREAD

**Issue by BravoMike99** [flybywiresim/aircraft#8576]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-03-16T11:45:16+00:00",
    "ref": "refs/heads/master",
    "sha": "6341eaef60d955dd2259009da60f80cfff653ade",
    "actor": "2hwk",
    "event_name": "manual",
    "pretty_release_name": "master:6341eaef",
    "version": "a32nx-v0.12.0-dev.6341eae"
}
```

### Describe the bug

Toggling manual pressurization when on the ground causes the cabin altitude to decrease instantaneously by hundreds of feet
https://github.com/flybywiresim/aircraft/assets/119708186/e582f58c-3ded-469e-bfde-9b276a7e1c4c
https://github.com/flybywiresim/aircraft/assets/119708186/70cf7a13-e22b-4b26-8722-28f986b60c26

### Expected behavior

Cabin altitude to stay the same

### Steps to reproduce

Press the MODE SEL button on the pressurization panel to switch between automatic and manual cabin pressure control and observe the cabin altitude on the PRESS SD page as you do so.

### Discord Username (optional)

bruno_pt99

**Comment by mjuhe** [comment]
Thank you so much for noticing this feature (not a bug!) 😄 

The cabin altitude indication is calculated differently in auto and in manual mode. In auto within 5000ft of departing or landing airports, it is done based on the actual altitude above sea level (using the barometric correction from the ADIRS), whereas in manual it always uses standard atmosphere (aka 1013.25 hpa).

Am I right in saying that in your two videos above, you were using real weather and the ambient pressure was not 1013hpa?

**Comment by BravoMike99** [comment]
Yep you are right. I just found the AMM chapter & tested it in STD conditions and it works as you described. Cool stuff TIL, apologies for the issue 😅
