### ISSUE TITLE
[A380X] V1 callout

### ISSUE THREAD

**Issue by SimonSVK** [flybywiresim/aircraft#8577]
### Aircraft Version

Development

### Description

Not sure about the A320 family, but A380 has auto V1 call-out. Would be nice to add this feature. Doing so will also enhance realism in my opinion.

### References (optional)

https://youtu.be/fLrZloqULnY?si=xUwpaNJCPbx9Oidc
You can hear the V1 call-out by the synthetic voice when taking off

**Comment by 2hwk** [comment]
A380 only

**Comment by flogross89** [comment]
Wwise event: `V1`
