### ISSUE TITLE
A320 HUD

### ISSUE THREAD

**Issue by Jasonjjgit** [flybywiresim/aircraft#8578]
### Aircraft Version

Stable

### Description

Seems pretty straight forward. A heads up display.
![image_2024-03-20_191344523](https://github.com/flybywiresim/aircraft/assets/64889107/dfbbadec-3dc2-4e31-adf8-a370fae978c5)
 

### Discord Username (optional)

jasonjj

**Comment by tracernz** [comment]
Duplicate of https://github.com/flybywiresim/aircraft/issues/3415
