### ISSUE TITLE
I ask the question and I answer myself! None of this for the very, very poor relatives of the Xbox edition?

### ISSUE THREAD

**Issue by afruzu** [flybywiresim/aircraft#8590]
### Aircraft Version

Stable

### Description

A320Neo Microsoft/Asobo MSFS 2020 Xbox edition. I ask the question and obviously I answer myself!
None of this for the very, very poor relatives of the Xbox edition?
Tanks and good fly!

**Comment by VeIocityy** [comment]
They've already said there's not going to be a version for Xbox/ The iniBuilds/Microsoft one is the solution to that problem.

**Comment by alepouna** [comment]
"Due to a number of contributing factors, FlyByWire Simulations' addons will not be released on the Xbox or the Marketplace. [You can read more here](https://flybywiresim.com/notams/marketplace-announcement/)."
