### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by Lammmier** [flybywiresim/aircraft#8591]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-03-28T02:37:26+00:00",
    "ref": "refs/heads/master",
    "sha": "d34ddf6ef5456b897ab500bf37ec2d5645146e7e",
    "actor": "2hwk",
    "event_name": "manual",
    "pretty_release_name": "master:d34ddf6e",
    "version": "a32nx-v0.12.0-dev.d34ddf6"
}
```

### Describe the bug

So there is no sound in the cockpit, gpws, engine sounds, announcements and every sound that you should be able to hear in the cockpit. It sound works in the external view but not in the cockpit. It only happens in the flybywire a32nx because when I use other aircrafts, it works.

### Expected behavior

I expected that there should be sound in the cockpit but one day it all suddenly dissapeared.

### Steps to reproduce

1. Find out how the sound dissapears
2. Fix it

### Additional info (optional)

It was working before but now it dosen't

**Comment by psilentrain1** [comment]
Try with nothing else in your community folder:

https://docs.flybywiresim.com/fbw-a32nx/support/reported-issues/#test-with-only-the-a32nx-add-on-in-community

**Comment by Lammmier** [comment]
I reinstalled it and it works now thanks
