### ISSUE TITLE
THR LVR FLX/MCT detent commands idle thrust

### ISSUE THREAD

**Issue by ExampleWasTaken** [flybywiresim/aircraft#8616]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-04-11T09:40:23+00:00",
    "ref": "refs/heads/master",
    "sha": "85d041413c2b47ffd0a054d748aa5a5305f84dac",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "master:85d04141",
    "version": "a32nx-v0.12.0-dev.85d0414"
}
```

### Describe the bug

Idle thrust is commanded when the THR LVRs are set to FLX/MCT. This does not seem to be affecting the rest of the takeoff logic (T/O inhibit is correctly displayed when THR LVR set to FLX/MCT).

ECAM message is shown (see image below)

### Expected behavior

FLX/MCT thrust commanded when THR LVR set to FLX/MCT detent.

### Steps to reproduce

1. Load the aircraft following all procedures.
2. Start takeoff roll and notice FADEC commanding idle power when THR LVRs are set to FLX/MCT.

### References (optional)

Video of the issue showcasing the THR LVR position, commanded thrust on ECAM as well as throttle config on the EFB:
https://youtu.be/qyAvf7F4qTI

![image](https://github.com/flybywiresim/aircraft/assets/58574351/49079519-dc0d-47f1-bcf6-30d17ea1dbe0)

### Additional info (optional)

This issue is likely linked to #8547 

Other users are stating similar issues. See [Discord #a32nx-support](https://canary.discord.com/channels/738864299392630914/785976111875751956/1227964472656924824)

### Discord Username (optional)

examplewastaken

**Comment by frankkopp** [comment]
Thanks for this report - will look into this as it might indeed be connected to the last update.

**Comment by ExampleWasTaken** [comment]
@frankkopp I saved the FDR file of the recording in case you need it. I can DM it to you on Discord. GitHub complains about the file type.
