### ISSUE TITLE
Autobrakes disarm when stowing reverse

### ISSUE THREAD

**Issue by pinatacolada** [flybywiresim/aircraft#8618]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-03-19T07:46:14+00:00",
    "ref": "refs/heads/master",
    "sha": "0fe4a89c577478ed19d54d477abf1be309f61581",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "master:0fe4a89c",
    "version": "a32nx-v0.12.0-dev.0fe4a89"
}
```

### Describe the bug

When disarming reverses from MAX REV to IDLE (not idle rev) with MED autobrake during landing, or MAX during an RTO, autobrakes disarmed on their own

### Expected behavior

Autobrakes should not deactivate when stowing reverses. They should when:
- The system disarmed, or
- The ground spoilers retract. In this case it remains armed.

The system disarms when:
- Flight crew presses the pushbutton switch, or
- One or more arming conditions is lost, or
- After take-off/touch and go, or
- Flight crew applies enough deflection to at least one brake pedal when autobrake is active in MAX, MED or LO mode.

### Steps to reproduce

1. Begin a normal take off, ensuring auto brake MAX is armed
2. Above 72 knots (ideally well above 72 knots to make it easier) abort take off by applying MAX REV
3. When stowing reverses notice auto brakes disarmed

OR

1. Make a normal landing, ensuring auto brake LOW or MED is armed
2. When stowing reverses notice auto brakes disarmed

### References (optional)

FCOM DSC-32-30-10

### Additional info (optional)

This was noticed with MAX REV, but it probably also happens with IDLE REV

**Comment by lukecologne** [comment]
Did the ground spoilers retract? They shouldn't but it might be a bug in the ground spoiler logic

**Comment by pinatacolada** [comment]
good spot, spoilers are retracting if the thrust levers are moved above idle

**Comment by lukecologne** [comment]
Ok, after looking at the logic, indeed if both thrust levers are above idle, the ground spoilers will retract. Maybe you accidentally increased the thrust levers a little above idle when resetting from reverse? IRL there might be a small threshold to make sure that doesn't happen I'll have to check that

**Comment by pinatacolada** [comment]
The margin is pretty large actually:

> **RETRACTION**
> The ground spoilers retract: 
> - After landing, when the ground spoilers are disarmed 
> - After a rejected takeoff, when the ground spoilers are disarmed
> - During a touch and go, when at least one thrust lever is advanced above 20 °.

DSC-27-10-20

You are essentially forced to go above idle to get past the detent irl as you need quite a bit of force to get past it, which usually makes you overshoot it.
