### ISSUE TITLE
Please add comm 2 transmit functionality

### ISSUE THREAD

**Issue by vanhavele** [flybywiresim/aircraft#8634]
### Aircraft Version

Development

### Description

Please add comm 2 transmit functionality for use on vatsim
currently when button is pressed com 2 come alive
but when you press the xmit key it xmits on vatsim channel 1

### References (optional)

![image](https://github.com/flybywiresim/aircraft/assets/13174353/ae5416b3-4d03-4066-b290-786a6e4972b0)

### Additional info (optional)

its really useful when flying with company on vatsim
The Fenix has the abbility to xmit on comms 2 but that plane sucks
need it to fly with my friends

### Discord Username (optional)

Salty Butter

**Comment by alepouna** [comment]
WIP #7866

**Comment by tracernz** [comment]
The FBW correct sets the sim transmit vars. There was an issue a long time back on the vpilot side where it interprets COM RECEIVE ALL as COM 1 + 2 only, as it was in FSX and P3D with only 2 COM radios but MSFS has 3. I guess that is still an issue, but it’s not on our side.
