### ISSUE TITLE
Unexpected ECAM WARNING "CAB PR EXCES RESIDUAL WARNING" occured after parking the aircraft

### ISSUE THREAD

**Issue by popa15cz** [flybywiresim/aircraft#8642]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-04-27T16:40:29+00:00",
    "ref": "refs/heads/master",
    "sha": "7518ab0c54b296f4cb774519889171ed7d8b4df5",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "master:7518ab0c",
    "version": "a32nx-v0.12.0-dev.7518ab0"
}
```

### Describe the bug

![image](https://github.com/flybywiresim/aircraft/assets/61908132/989e742c-7a2e-4e53-bdc4-61a0316f5bc9)

"CAB PR EXCES RESIDUAL PRESSURE" warning on ecam randomly after parking maybe after or before shutting down engines, occured 2 times of my flights from after "Pressurization Failures" update in FBW DEV version. Nothing amber / red and normal values on ECAM SD PRESS PAGE.

### Expected behavior

This warning shouldn't activate.

### Steps to reproduce

I encountered this bug 2 times of my flights after "PRESSURIZATION FAILURES" update in FBW DEV version.
This happen after parking the aircraft, i don't remember if i shut down the engines.
To reproduce luck is required...

### Discord Username (optional)

popa15_cz

**Comment by Mike737377** [comment]
Can confirm and replicate the issue everytime including on the most recent build #1a6e658. 

### Steps to reproduce

After parking at gate with engines still running and ADIRS aligned:
1. APU bleed on
2. Engine mode normal
3. Engine master switches off
4. Fuel pumps off
5. Beacon 
6. External power on
7. ADIRS off

ECAM will display warning and master warning will trigger.

Seems to be directly related to ADIRS being switched off after engine masters off with engine mode normal.

**Comment by Watsi01** [comment]
Hi there, we are aware of the issue. As it doesn't appear all the time, we're still looking for a fix. But we're on it.
