### ISSUE TITLE
Add aircraft callsigns on mfd

### ISSUE THREAD

**Issue by JXNXH28** [flybywiresim/aircraft#8658]
### Aircraft Version

Stable

### Description

Show the ai traffic/vatsim callsigns on the mfd like in the screenshot below. I‘m not sure when this is displayed instead of the tcas markers.

### References (optional)

![IMG_5723](https://github.com/flybywiresim/aircraft/assets/76184493/cee59322-757b-4815-a285-169e097d8ce4)

### Discord Username (optional)

jonah9224

**Comment by tracernz** [comment]
This is ATSAW. It's not currently possible as the sim does not make the callsign available to us.

Duplicate of https://github.com/flybywiresim/aircraft/issues/5014
