### ISSUE TITLE
Popped-Out PFD Not Showing ILS Loc & G/S Deviation Scale ("Purple Diamonds")

### ISSUE THREAD

**Issue by GBFoxx** [flybywiresim/aircraft#8659]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2023-11-03T17:47:36+00:00",
    "ref": "refs/tags/v0.11.1",
    "sha": "f055eb02dc0af32441f8b2873f58e8316d7ca638",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.11.1",
    "version": "v0.11.1-rel.f055eb0"
}
```

### Describe the bug

I am using a popped-out primary flight display (meaning I moved PFD to another monitor/display using right ALT-click). On all ILS approaches, the ILS Loc & G/S Deviation Scale (purple diamonds & white circles) do not appear on the popped-out PFD. They do appear on the "main window" PFD (the one I click on to create the popped-out PFD), just not on the popped-out PFD itself.

### Expected behavior

ILS Loc & G/S Deviation Scale appear on popped-out PFD.

### Steps to reproduce

1. Flying the FlyByWire Simulations A320neo (LEAP) with ILS already programmed in MCDU, I press APPR button to capture ILS glideslope
2. Popped-out PFD shows I am established (LOC and CAT1 appear), but ILS Loc & G/S Deviation Scale do not
3. ILS Loc & G/S Deviation Scale DO appear on the "main window" PFD
4. To double check, I confirmed that RADNAV page of MCDU, and it shows the ILS frequency (LS/FREQ section)
6. Airplane successfully follows glideslope, I had no problem landing, this appears to be purely a display bug

### References (optional)

![unnamed](https://github.com/flybywiresim/aircraft/assets/133608592/5729c395-f212-447e-8d7d-69f8b4637380)
![Screenshot 2024-05-21 224146](https://github.com/flybywiresim/aircraft/assets/133608592/58ab2411-984a-414b-8e70-8730af938d92)

### Additional info (optional)

Game: Microsoft Flight Simulator 1.36.2.0.
System: Windows 11 Home, 23HZ
Livery: FlyByWire Simulations A320neo (LEAP)
Mods: No other mods in Community folder (see screenshot), but bug was first detected while with other mods were in folder
Other tests: I tested using the stock A320 (that comes with the game) and the ILS Loc & G/S Deviation Scale DO appear on my popped-out PFD. Therefore this bug appears specific to FlyByWire

### Discord Username (optional)

WC4J

**Comment by tracernz** [comment]
I can’t reproduce this. Are you sure you have the same PFD popped out?

**Comment by GBFoxx** [comment]
Apologies - user error on my part, I had the FO PFD popped out specifically for FlyByWire by mistake. Sure enough, I pressed LS on the FO side and everything worked properly on my most recent ILS landing. I am so sorry to have wasted the team's time on this. You all do amazing work, keep it up (and I'll try to get smarter :) )

**Comment by tracernz** [comment]
No problem. It was pretty easy to do a quick check while doing some other stuff in the sim 😄 . Have fun!
