### ISSUE TITLE
ND doesn't show flight path in PLAN mode

### ISSUE THREAD

**Issue by StephN-B** [flybywiresim/aircraft#8677]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-06-14T17:06:16+00:00",
    "ref": "refs/heads/master",
    "sha": "20c8d7141b3b23e1d28f827549df54a97616a07c",
    "actor": "BlueberryKing",
    "event_name": "manual",
    "pretty_release_name": "master:20c8d714",
    "version": "a32nx-v0.12.0-dev.20c8d71"
}
```

### Describe the bug

After loading a flight plan (via Simbrief), when I set the ND to show in PLAN mode, no flight path is shown.
![image](https://github.com/flybywiresim/aircraft/assets/87286233/26b1dca2-c80e-4a85-8d83-7c2d16491514)

When changing to ARC or NAV mode, all is fine:
![image](https://github.com/flybywiresim/aircraft/assets/87286233/58545897-d315-43a4-9037-b7287a78e7d7)

### Expected behavior

Flight path should be shown in PLAN mode on the ND

### Steps to reproduce

1. Start C/D
2. Power up the aircraft
3. Load flight plan from Simbrief
4. Wait for IRS to have aligned
5. Enter Departure details in MCDU F-PLAN page
6. Change ND display to PLAN mode -> no path is shown

### Discord Username (optional)

StephN-B

**Comment by BlueberryKing** [comment]
Hi, we've looked into this and it seems like a mod conflict causes this. Remove everything apart from the A32NX from your Community folder and try again. Feel free to contact us on Discord if the issue persists 👍

**Comment by ronleeon** [comment]
Me too,and I do not know what plug-in causes the conflict

**Comment by BlueberryKing** [comment]
> Me too,and I do not know what plug-in causes the conflict

Do you have a weather radar mod installed? That caused issues for someone on the team. It conflicts with our addon.

**Comment by ronleeon** [comment]
> > Me too,and I do not know what plug-in causes the conflict
> 
> Do you have a weather radar mod installed? That caused issues for someone on the team. It conflicts with our addon.

OK,I will check

**Comment by ronleeon** [comment]
> > Me too,and I do not know what plug-in causes the conflict
> 
> Do you have a weather radar mod installed? That caused issues for someone on the team. It conflicts with our addon.

OK,I will check it.

**Comment by FGrabi** [comment]
Same problem here. Had the WX Radar Mod installed. Disabled it, problem still exists.
After latest Update. also the WP will NOT display even in ARC mode. Only track line straight ahead. Worked before latest update - also with WX Radar but without the Flight Path in PLAN mode

**Comment by frankkopp** [comment]
> Same problem here. Had the WX Radar Mod installed. Disabled it, problem still exists. After latest Update. also the WP will NOT display even in ARC mode. Only track line straight ahead. Worked before latest update - also with WX Radar but without the Flight Path in PLAN mode

Remove everything else from the Community folder - leave only the A32NX in it - then double check again.

(you last sentence doesn't add value - the WXR mod brakes the aircraft because it virtually overwrites A32NX files. And any change we then make to these files will not be seen by the sim because of this mod - we really recommend to not use it at all - esp. not on the Development version)

**Comment by StephN-B** [comment]
Just did the following:
- downloaded the latest build, with the reversal of vertical deviation indicator
- removed the wxradar-a320-neo-dev plugin
After these changes, the issue is gone:
![image](https://github.com/flybywiresim/aircraft/assets/87286233/0f534fd0-5446-40a4-8ab9-3b3899c3d832)

Therefore I will close this issue.
