### ISSUE TITLE
Freeze Bug

### ISSUE THREAD

**Issue by vorzaf** [flybywiresim/aircraft#8685]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-06-17T22:23:35+00:00",
    "ref": "refs/heads/master",
    "sha": "958f635151c7a8751da108f8147da19305b8c671",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "master:958f6351",
    "version": "a32nx-v0.12.0-dev.958f635"
}
```

### Describe the bug

Hello! My bug is that when I launch a flight with an airplane from FlyByWire, as soon as the flight is loaded and I click I can fly, my game just freezes

### Expected behavior

I expected to see how the plane I loaded worked well and I could fly it safely

### Steps to reproduce

1. I downloaded the FlyByWire installer
2. Then I installed the A32NX aircraft in the Community folder
3. And finally, I started the game and chose the FlyByWire plane. After the flight has loaded and I clicked I can fly, my game just freezes.

### Discord Username (optional)

quertof

**Comment by psilentrain1** [comment]
Try the troubleshooting in this doc:
[ https://docs.flybywiresim.com/fbw-a32nx/support/reported-issues/#msfs-freezes-after-ready-to-fly](https://docs.flybywiresim.com/fbw-a32nx/support/reported-issues/#msfs-freezes-after-ready-to-fly)

**Comment by vorzaf** [comment]
Thank you!! Its worked!!!
