### ISSUE TITLE
Tuned VOR To Waypoint wrong color

### ISSUE THREAD

**Issue by pinatacolada** [flybywiresim/aircraft#8691]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-06-20T01:51:42+00:00",
    "ref": "refs/heads/master",
    "sha": "c6c13868fd1abc4346d1001ba3f32b4565e8e5aa",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "master:c6c13868",
    "version": "a32nx-v0.12.0-dev.c6c1386"
}
```

### Describe the bug

The ND is coloring a VOR To Waypoint in white

![image](https://github.com/flybywiresim/aircraft/assets/13833056/64b85bd3-63da-4233-87d5-f5f5f00f031d)

### Expected behavior

Should be blue

![image](https://github.com/flybywiresim/aircraft/assets/13833056/74519f7b-af4f-4067-86bd-f24e5d512b06)

### Steps to reproduce

1. In the air, enter a direct to a nearby VOR
2. observe that the FMS autotunes said VOR (it should, if not just manually tune it)
3. white

**Comment by KnedlikMCPE** [comment]
Additional references:
![image](https://github.com/flybywiresim/aircraft/assets/60871255/65473339-a27d-48f3-951b-a46ff5c908e8)
![image](https://github.com/flybywiresim/aircraft/assets/60871255/cf8c36ed-3129-4146-a24c-8fb57829b86e)

I'll take a look at this later if I have the time
