### ISSUE TITLE
FPLN: Arrival page shows incorrect RWYs for some airports

### ISSUE THREAD

**Issue by StephN-B** [flybywiresim/aircraft#8692]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-06-20T01:51:42+00:00",
    "ref": "refs/heads/master",
    "sha": "c6c13868fd1abc4346d1001ba3f32b4565e8e5aa",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "master:c6c13868",
    "version": "a32nx-v0.12.0-dev.c6c1386"
}
```

### Describe the bug

This issue seems to have been introduced with https://github.com/flybywiresim/aircraft/pull/7692.

What I find is that, when I am planning an Arrival on the Arrival page, I see an incorrect list of available Approaches - at least for some airports. One example is EDDK.

EDDK has an **ILS13L** approach, but this approach isn't listed on the Arrival page. Instead an approach **14L** is listed, which doesn't exist.

### Expected behavior

Show the correct list of available Approaches, and allow their selection.
The below shows the correct selection, using the iniBuilds A320:
![image](https://github.com/flybywiresim/aircraft/assets/87286233/77ee5e4c-8c41-46a8-b5d5-19d1afadeb31)
![image](https://github.com/flybywiresim/aircraft/assets/87286233/3d35c434-7c94-4e0e-98ef-e802eafd01e7)
![image](https://github.com/flybywiresim/aircraft/assets/87286233/5dccf6e4-20b0-4857-891d-b58b357409f5)

### Steps to reproduce

1. Enter a flight plan, either manually or via SimBrief: EDDS/EDDK
2. Select FPLN
3. Enter departure details (OK in the above example)
4. Try to enter arrival details for RWY ILS13L -> runway is not available:
![image](https://github.com/flybywiresim/aircraft/assets/87286233/ea4fb882-e717-40d4-9474-721de891e56e)
![image](https://github.com/flybywiresim/aircraft/assets/87286233/1c1525da-6c69-4b9e-b71b-20385d7736aa)
![image](https://github.com/flybywiresim/aircraft/assets/87286233/890a0274-e38d-46b1-8136-cc1451896e0f)

### References (optional)

List of RWYs at EDDK according to Navigraph:
![image](https://github.com/flybywiresim/aircraft/assets/87286233/af83040c-d8af-42f9-a36b-2f4c3d731e5b)

### Discord Username (optional)

StephN-B

**Comment by Saschl** [comment]
I suspect there is a mismatch between navdata and scenery. Please make sure that:

1.  Navigraph data is up to date if used
2. Any 3rd party EDDK sceneries are updated (EDDK from Aerosoft got updated fairly recently as the runway numbers changed)
3. If nothing of the above helps try with an empty community folder (besides the A32NX). The base sim should have the correct runways after a worldhub update (at least it was submitted in April 2024)

**Comment by StephN-B** [comment]
Thanks @Saschl for those tips, but unfortunately no joy on my side.
I can confirm that my Community folder is cleared out to the minimum content:
![image](https://github.com/flybywiresim/aircraft/assets/87286233/f90423de-75e4-47ce-ae19-55edfab95882)

and that the Navigraph Data are all up-to-date:
![image](https://github.com/flybywiresim/aircraft/assets/87286233/82bbd8f3-0928-49b2-b7ee-f660edd4294b)

The issue still persists.

**Comment by Saschl** [comment]
I was able to check this and according to navigraph, they have submitted the runway change to worldhub: https://forum.navigraph.com/t/msfs2020-latest-airac-cycle-2404-missing-eddk-changed-13l-31r-and-sids/15476/3

However, it seems like the change is not in the sim yet, I am seeing the same issue. Unfortunately, there'S nothing we can do there as the data comes from the sim. The v2 A320 uses WASM as main technology and the Sim API seems to work differently there. But you can see it's also struggling a bit as the runway length is 0m. 

I can confirm correct runways with the Aerosoft EDDK. Let's some another Worldhub update will include the correct runways in the default sim.

**Comment by StephN-B** [comment]
Ok, many thanks for the update.
Given that a required fix is outside of the FBW project, I will close this ticket. 

Thanks also for the explanation why it works for the v2 a320 and not here - much appreciated.
