### ISSUE TITLE
[A380X] SD status area: Fix GW & FOB

### ISSUE THREAD

**Issue by flogross89** [flybywiresim/aircraft#8720]
### Aircraft Version

Development

### Description

Currently, GW & FOB use the MSFS variables. Switch to a more accurate implementation using the FMS ZFW + FQMS data

### References (optional)

see FCOM

**Comment by cptnuss-ops** [comment]
Hi @flogross89 ,
can the A380 issued be developed by specific users only? Or could I implement this feature?

Thanks and best regards!

**Comment by alepouna** [comment]
> Hi @flogross89 , can the A380 issued be developed by specific users only? Or could I implement this feature?
> 
> Thanks and best regards!

The repository & code for the A380 is public for a reason! If you feel like up for the task, feel free! Just beware that we can not provide you with the model, if you want to do local testing you will have to connect the instruments to another a/c (e.g. the 32NX)

**Comment by flogross89** [comment]
> Hi @flogross89 , can the A380 issued be developed by specific users only? Or could I implement this feature?
> 
> Thanks and best regards!

Exactly what @alepouna said, you could render the SD in one of the A32nx screens and develop there 👍 Testing in the a380x is not yet possible publicly, but we’re making it a priority to enable public development. 
If you want to start just tell us, we can provide the Simvars for the needed data from the FMS

**Comment by flogross89** [comment]
Closed with https://github.com/flybywiresim/aircraft/pull/8855
