### ISSUE TITLE
[A380X] Add TCAS

### ISSUE THREAD

**Issue by flogross89** [flybywiresim/aircraft#8724]
### Aircraft Version

Development

### Description

Add TCAS

**Comment by CaptCrystal** [comment]
I could take a look at this.

**Comment by CaptCrystal** [comment]
It appears like the a32nx TCAS system has already been ported over into the a380x.

**Comment by CaptCrystal** [comment]
Okay, after a lot of review. The TCAS system already appears to have been implemented into the A380.

**Comment by CaptCrystal** [comment]
Did you have something you wanted completed in specific?

**Comment by flogross89** [comment]
I had a look at the current state. I suggest to wait with that PR, for multiple reasons:
ND, TCAS and transponder are involved components, we have a few dependencies which are not merged yet
It uses an old sync mechanism (FlowEventSync), we should update that first
EFIS CP filters need to display the traffic layer, couldn't check whether that happens atm
I can't verify that the ND can actually retrieve traffic data, neither FlowEventSync nor EventBus worked in the first try
I also think that this would be an issue for an experienced MSFS/avionics developer, there's just too much complex technology and integration work needed (move to systems-host, change sync mechanism, integrate into EFIS/ND)
