### ISSUE TITLE
A32NX version development 6f34a3b : The PERF page of the MCDU is empty

### ISSUE THREAD

**Issue by PatriceCesson** [flybywiresim/aircraft#8732]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-07-03T03:55:34+00:00",
    "ref": "refs/heads/master",
    "sha": "6f34a3b3e023e493cdad54869f00778d3e19914f",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "master:6f34a3b3",
    "version": "a32nx-v0.12.0-dev.6f34a3b"
}
```

### Describe the bug

I load the plane in MSFS., state ready to take off, engines running.
I check the MCDU.
All pages are Ok except the PERF page which is empty

### Expected behavior

The PERF page shall have all entries required to enter the Take Off data

### Steps to reproduce

1. Start MSFS
2. Choose A32NX as plane with FBW livery
3. Choose airport, time and weather
4. Load the scenario
5. Once in the cockpit, check MCDU
6. The PERF page is empty when opened.

### References (optional)

An image of the content of the PERF page:
![snap085](https://github.com/flybywiresim/aircraft/assets/30781354/2f9340ae-2a88-4045-acd4-a4d22bb9e70b)

### Additional info (optional)

It is the first time I see this behavior.
flybywire-wxradar-a320-neo-dev addon is not in the community folder.
ambitiouspilots-toolbar-pushback addon is not in the community folder
MSFS Store version on PC latest version dated 30 may 2024

**Comment by PatriceCesson** [comment]
Tried same conditions with this version:
{
    "built": "2024-02-01T14:24:29+00:00",
    "ref": "refs/heads/master",
    "sha": "6f3af7b4b7b5013d03dc5e14b638c466d4e4ac59",
    "actor": "crocket63",
    "event_name": "manual",
    "pretty_release_name": "master:6f3af7b4",
    "version": "v0.12.0-dev.6f3af7b"
}
And all is OK.

**Comment by Saschl** [comment]
Hi there, after you entered a flight plan, does the page stay blank or does it work normally?

**Comment by PatriceCesson** [comment]
Hi,At this moment, i do not enter any FP. I just make some tests to ensure my configuration works ok. In the test with the preceding version, i did not enter a FP either and it was ok. But I will make a test to check the behavior in this case.Thanks.Patrice.Envoyé de mon iPadLe 3 juil. 2024 à 13:50, Saschl ***@***.***> a écrit :﻿
Hi there, after you entered a flight plan, does the page stay blank or does it work normally?

**Comment by PatriceCesson** [comment]
Hi,
After a brief test, the page is ok if i load a FP.
Why this behavior now?
So every time I want to pilot this plane I have to enter a FP now?
This is very restrictive.
Thanks.
Patrice.

**Comment by Saschl** [comment]
No, this is a bug. Just wanted to ensure under which conditions it appears, we will fix that.

**Comment by PatriceCesson** [comment]
Thanks for the prompt fix.
Patrice.
