### ISSUE TITLE
FMS: Manually tuned navaids not deleted in DONE phase

### ISSUE THREAD

**Issue by BravoMike99** [flybywiresim/aircraft#8740]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-07-04T19:47:34+00:00",
    "ref": "refs/heads/master",
    "sha": "74e195a8ce4d0b1dbe7fe7dce046f7e6c4b44aff",
    "actor": "BlueberryKing",
    "event_name": "manual",
    "pretty_release_name": "master:74e195a8",
    "version": "a32nx-v0.12.0-dev.74e195a"
}
```

### Describe the bug

Manually tuned navaids during the flight are not detuned after landing.

### Expected behavior

FMS should delete the manually tuned navaids once it changes to DONE phase.

### Steps to reproduce

1) Perform a flight and manually tune a VOR for example through the RAD NAV page.
2) After landing, the "M" flag remains visible on the ND and the VOR remains tuned.

### References (optional)

https://youtu.be/Lqn0kKWhngM?t=499

### Discord Username (optional)

bruno_pt99

**Comment by tracernz** [comment]
Was never quite sure about that. This video is perfect 👌.
