### ISSUE TITLE
FMS: LPLA RWY 33 REGLA1B SID guidance/vnav crash

### ISSUE THREAD

**Issue by BravoMike99** [flybywiresim/aircraft#8742]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-07-04T19:47:34+00:00",
    "ref": "refs/heads/master",
    "sha": "74e195a8ce4d0b1dbe7fe7dce046f7e6c4b44aff",
    "actor": "BlueberryKing",
    "event_name": "manual",
    "pretty_release_name": "master:74e195a8",
    "version": "a32nx-v0.12.0-dev.74e195a"
}
```

### Describe the bug

Selecting the REGLA1B SID at LPLA causes the VNAV predictions to stop working due to the following crash: 
![Guidance](https://github.com/flybywiresim/aircraft/assets/119708186/906ca61c-4044-4c8d-ab0d-4895041575c6)
The drawing of the SID on the ND ia also missing after the 1500ft CA leg.

### Expected behavior

Guidance not to crash

### Steps to reproduce

Insert LPLA as your departure airport in the FMS. Select REGLA1B as the SID (runway 33)

### Additional info (optional)

Using MSFS navdata. 

### Discord Username (optional)

bruno_pt99

**Comment by BlueberryKing** [comment]
Yeah, we don't support this leg sequence yet unfortunately. I've been working on a fix for this 👀 
![image](https://github.com/flybywiresim/aircraft/assets/22713769/06a5fd42-13b0-44f1-8ef5-cbf501859689)
