### ISSUE TITLE
Cannot start engines since latest update

### ISSUE THREAD

**Issue by StephN-B** [flybywiresim/aircraft#8748]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-07-09T00:03:30+00:00",
    "ref": "refs/heads/master",
    "sha": "de2903cf13ac93c2639ceea9b0d3bc3232750c2e",
    "actor": "flogross89",
    "event_name": "manual",
    "pretty_release_name": "master:de2903cf",
    "version": "a32nx-v0.12.0-dev.de2903c"
```

### Describe the bug

I am not able to start up the engines since the latest upgrade, neither using
- the normal, manual steps
- nor using a Aircraft State -> Preset (Ready for Pushback, Ready for Taxi)

### Expected behavior

Engines should start up.

### Steps to reproduce

Here are the steps I took:
1. Load aircraft C/D (I used YBLN, any gate)
2. Using Simbrief, load flight plan YBLN - YPPH
3. Go through all usual pre-flight procedures
4. Call for Tug
5. Make sure all is ready for engines to start up, especially:
- APU is running, fuel pumps and bleed is on:
![image](https://github.com/flybywiresim/aircraft/assets/87286233/bea169c7-1c91-4131-bf5f-3c602164bb6e)
- Turn on IGN/Start, and then turn on Masterswitch:
![image](https://github.com/flybywiresim/aircraft/assets/87286233/0f0fc643-dc72-40ec-a855-7c2db5e3add8)

**CURRENT OUTCOME**
Nothing is happening
![image](https://github.com/flybywiresim/aircraft/assets/87286233/42197ad4-e840-4c23-a453-8c663f263958)

### Discord Username (optional)

StephN-B

**Comment by alepouna** [comment]
Hi, thanks for the report. Can you confirm you do not have any other addons in your community folder when testing this? 
If you do, please try and remove all other mods/liveries from the community folder and test our addon again. This will help rule out mod conflicts.

See [this step](https://docs.flybywiresim.com/fbw-a32nx/support/reported-issues/#test-with-only-the-a32nx-add-on-in-community) in our troubleshooting guide for more details on how to do this easily.

**Comment by StephN-B** [comment]
Hmm - must be one of the addons. I stripped the community folder to the bare minimum, and now the aircraft is starting up just fine. Will be tricky to identify the culprit, but I'll take an somewhat educated guess for the order in which I reintroduce addons (with liveries being the first choice I guess) to see if I can find it.

**Comment by StephN-B** [comment]
I am currently no longer able to recreate this issue, even after reintroducing all my addons.
@alepouna - should I keep this open in case I (or someone else) find a way to recreate this, or rather close the ticket?

**Comment by Pruznak** [comment]
I think if the issue was most likely related to addons and it's been solved, you may close this

**Comment by StephN-B** [comment]
Closed, as currently I am no longer able to reproduce.

**Comment by Aleloplt** [comment]
Shall I open a new issue as I'm experiencing the exact same thing here consistently. Starter Valves do not open on ignition, ENG EGT is 0 constantly, N1 limit is broken and below the N1 indicators.

"built": "2024-07-14T12:11:22+00:00",
 "ref": "refs/heads/master",
"sha": "cb0d80192bbc8a174f3c0d873c3ade92b4b2ee5e",
"actor": "flogross89",
"event_name": "manual",
"pretty_release_name": "master:cb0d8019",
"version": "a32nx-v0.12.0-dev.cb0d801"

![Screenshot 2024-07-17 082853](https://github.com/user-attachments/assets/be8d772c-2c05-471d-9195-0a546cccaf8a)
![Screenshot 2024-07-17 084902](https://github.com/user-attachments/assets/1c6cb7a2-5e84-4f7d-8f78-8f32da3b5e37)
![Screenshot 2024-07-17 084922](https://github.com/user-attachments/assets/a66acc1e-c27c-4ccb-82a0-e2af0f143053)

**Comment by StephN-B** [comment]
Can you try to recreate this by also removing the gsx folders from Community?
If the issue still persists, I would create a new ticket, but maybe refer to this ticket here as well.

The difference between your and my issue is that mine disappeared after I cleared out the community folder, and never came back, even after I reintroduced all my add ons. Your's however seems to persist, and therefore maybe easier to recreate by a developer.

**Comment by Aleloplt** [comment]
Even with just the FBW aircraft and no GSX im having this issue. Sometimes it fixes itself when i change between the stable and dev branch but other than that i have no clue.

**Comment by StephN-B** [comment]
I suggest that you raise a new ticket. And when you do, the best way of helping the developers is to describe the steps you take as clearly as possible, as this greatly helps them if they investigate the issue (I am a former QA engineer for a software team ;-) ). 
From what you said ('sometimes it fixes itself') - maybe there is some sort of memory/caching issue after upgrading or switching. This is just a guess, but worth exploring.
 
Something I'd like you to try is the following:
- Install Stable
- Check if startup works
- Restart MSFS
- Check if startup works
- Install Dev
- Check if startup works
- Restart flight (not MSFS)
- Check if startup works
- Restart MSFS
- Check if startup works
