### ISSUE TITLE
fma: radio label overlaps with height

### ISSUE THREAD

**Issue by MStallen** [flybywiresim/aircraft#8753]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-07-10T17:42:10+00:00",
    "ref": "refs/heads/master",
    "sha": "2cdf866fb140b72151c25e2413dd5365364ba08f",
    "actor": "BlueberryKing",
    "event_name": "manual",
    "pretty_release_name": "master:2cdf866f",
    "version": "a32nx-v0.12.0-dev.2cdf866"
}
```

### Describe the bug

Radio altitude on PFD is written through RADIO (see picture)

### Expected behavior

Correct placement
![RAD-ALT](https://github.com/user-attachments/assets/173a87b8-7f3d-43f9-aea8-1d758a52326c)

### Steps to reproduce

Input radio-altitude on Approach Perf page

### Additional info (optional)

Before it was good, I'm not sure how many days ago.
![RAD-ALT](https://github.com/user-attachments/assets/a6bf6931-747c-4dc7-9857-53291de5a927)

**Comment by yourcptainspeaking** [comment]
I tried to reproduce this using the ILS 22L into KDTW but it displayed normally.

**Comment by MStallen** [comment]
Affirm, with the newest install the problem is gone.

**Comment by yourcptainspeaking** [comment]
> Affirm, with the newest install the problem is gone.

Perfect, can you close the issue when you get a chance?
