### ISSUE TITLE
[A380X] FO RMP brightness knob resets INTEG lights

### ISSUE THREAD

**Issue by MoreRightRudder** [flybywiresim/aircraft#8774]
### Aircraft Version

Development

### Build info

```json
blah
```

### Describe the bug

FO RMP brightness knob resets the INTEG light knob to zero when RMP brightness is turned to 0. 

FO RMP to 0 resets the INTEG brightness on pedestal and MIP to 0. 

CAPT RMP works as expected.

### Expected behavior

FO RMP brightness goes to 0 without affecting INTEG light knob.

### Steps to reproduce

Turn FO RMP brightness to zero and observe INTEG light.

**Comment by MoreRightRudder** [comment]
<3

**Comment by tracernz** [comment]
Is it possible the other one inadvertently uses the RMP potentiometer indices?

**Comment by tracernz** [comment]
Both using potentiometer 85 🤣 .
