### ISSUE TITLE
VOR A, RNP B, etc. Approach routes including letters will not appear in the listings on the Arrivals page

### ISSUE THREAD

**Issue by kiokio0987** [flybywiresim/aircraft#8797]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-08-02T17:31:58+00:00",
    "ref": "refs/heads/master",
    "sha": "e0dbfda66baf2c7d442d520c92feba92ac487eac",
    "actor": "crocket63",
    "event_name": "manual",
    "pretty_release_name": "master:e0dbfda6",
    "version": "a32nx-v0.12.0-dev.e0dbfda"
}
```

### Describe the bug

Routes with approaches including the word "A,B" will not list on the Arrivals page.

Example
VOR A at Tokyo International Airport (RJTT), 
VOR A at New Chitose Airport (RJCC), 
RNP B 18L/18R at Gimhae International Airport (RKPK), etc,

Navigraph is used.　MSFS world map includes approaches.
![20240804071259_1](https://github.com/user-attachments/assets/ce12305a-ec2b-448b-9bee-4bfb341e8274)
![arrival_d](https://github.com/user-attachments/assets/c77f3f67-c41e-4afd-9e07-b5c1c92678d7)

### Expected behavior

These approaches should be included in the list.

### Steps to reproduce

Set RJTT, RJCC, etc. in the TO section of the init page.
Open the F-PLN page and go to the Arrival page.
Check the approach list.

### References (optional)

N/A

### Additional info (optional)

Since FMS v2, this issue has happened.

**Comment by tracernz** [comment]
This is intentional. We checked on a number of real aircraft and circling approaches were not available on any of them.
