### ISSUE TITLE
[A380X] Allow multi selection for EFIS CP filters

### ISSUE THREAD

**Issue by flogross89** [flybywiresim/aircraft#8813]
### Aircraft Version

Development

### Description

EFIS CP filters (CSTR, WPT, VORD, NDB, ARPT) should allow some multi-selection under specific circumstances. Current EFIS CP uses the A32NX logic, which is wrong.

- CSTR, ARPT and TRAF can be toggled on and off the whole time, without limitations
- Only one of WPT, VORD or NDB can be active 
- Only one of WX and TERR can be active

**Comment by derl30n** [comment]
What's the difference between this issue and https://github.com/flybywiresim/aircraft/issues/8791

**Comment by flogross89** [comment]
> What's the difference between this issue and #8791

Ah shoot, forgot about that one. Thanks!
