### ISSUE TITLE
[A380X] Trim Tank Fuel refueling is still unfinished

### ISSUE THREAD

**Issue by 2hwk** [flybywiresim/aircraft#8827]
### Aircraft Version

Development

### Build info

```json
experimental
```

### Describe the bug

Currently just blindly adds 4000kg then full, should follow the values indicated in the refueling table.

### Expected behavior

Should gradually add trim tank past 270t as indicated in the table, (but also depends on desired CG)

### Steps to reproduce

*

### Discord Username (optional)

2cas

**Comment by becas22** [comment]
Any way to set the fuel quantities in each tank manually for debug?
Point being that the tables might not be applicable to our model, because, according to Luke, each fuel tank has a fixed H-Arm.

**Comment by alepouna** [comment]
Have you enabled the developer mode LVAR? That should let you use the W&B menu
