### ISSUE TITLE
[A380X] DRAIMS issues

### ISSUE THREAD

**Issue by becas22** [flybywiresim/aircraft#8858]
### Aircraft Version

Development

### Description

1. Default VHF STBY freq is 113.900, which is a navaid frequency. When in the STBY window, it can be tuned. Tunable VHF freq band should be 118.000-136.975
https://discord.com/channels/738864299392630914/1193615390861951086/1279018037281947649

2. Unable to tune some frequencies if the whole channel is written instead of dropping the leading 1 (xx.xxx)
   2.1 Unable to tune 11x.xxx frequencies (https://discord.com/channels/738864299392630914/1193615390861951086/1279019835250184216)
   2.2 Unable to tune xxx.12x and xxx.97x (https://discord.com/channels/738864299392630914/1193615390861951086/1279019922277662732 and https://discord.com/channels/738864299392630914/1193615390861951086/1279018457362333771)

3. INT/RAD sw in the RAD position by default. Should be in the middle

~~4. After setting a squawk code, it requires an LSK press to confirm the code. According to FCOM, this should not be necessary (https://youtu.be/6TSQdISWlkI?t=767)~~

 

### Discord Username (optional)

Bernardo R

**Comment by flogross89** [comment]
moved 4. (squawk auto-validate) to #8935

**Comment by tracernz** [comment]
> 3. INT/RAD sw in the RAD position by default. Should be in the middle

This one I can't repro. The first time you use it will be centred, and each subsequent load it will be where you left it.
