### ISSUE TITLE
[A380X] OANS "FOR BTV: SELECT EXIT" displayed at the wrong moment

### ISSUE THREAD

**Issue by pilotseyea350** [flybywiresim/aircraft#8865]
### Aircraft Version

Development

### Build info

```json
FS Expo Showcase build
```

### Describe the bug

When watching the FsExpo showcase, I noticed something that didn't make sense On the OANS, "FOR BTV: SELECT EXIT" message appears as soon as the ND range is set to ZOOM, from what I've seen and unless it's already been corrected or that's the normal behavior, the message should appear when a RWY has been selected on the OANS.

### Expected behavior

1. Set EFIS Range to ZOOM
2. Observe "FOR BTV: SELECT EXIT" does not appear
3. Select a runway you want to use for BTV
4. Observe "FOR BTV: SELECT EXIT" message appears

### Steps to reproduce

1. Set EFIS Range to ZOOM
2. Observe "FOR BTV: SELECT EXIT"

### References (optional)

OANS Without "FOR BTV: SELECT EXIT" : 16 minutes 10
OANS With "FOR BTV: SELECT EXIT" : 1 hour 18 minutes 56 seconds
https://www.youtube.com/watch?v=AI8yFhuEa4Q

OANS Without "FOR BTV: SELECT EXIT" : 41 minutes 45
OANS With "FOR BTV: SELECT EXIT" : 1 hour 08 minutes 45 seconds
https://www.youtube.com/watch?v=p28erS6uWHE&t=2502s

Current behavior : https://www.youtube.com/watch?v=rZBMmapOOJ0

### Additional info (optional)

Again, I do not know if this is expected behavior and if not, if it has been corrected because there isn't any issue open about this bug nor have I seen any commit fixing this. If this has changed please do let me know and close this issue !

### Discord Username (optional)

PilotEyesA350

**Comment by pilotseyea350** [comment]
It also looks like after touchdown, RWY, EXIT and ROT data are replace by wind direction and wind speed. But on the showcase video, the OANS was turned on before touchdown unlike the reference videos.

**Comment by flogross89** [comment]
1) In the FSExpo show case, a runway from another airport was still selected, leading to this behavior. That's fixed now.
2) RWY/EXIT selection and thus ROT and TURNAROUND info is displayed in PLAN mode. In ARC mode (as used during approach), you'll have wind data
