### ISSUE TITLE
THR levers issues

### ISSUE THREAD

**Issue by becas22** [flybywiresim/aircraft#8886]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-09-07T19:25:01+00:00",
    "ref": "refs/heads/a380x-experimental",
    "sha": "02f7264f43a503cf13e4dbe77c9d2ea3c44f1d6c",
    "actor": "flogross89",
    "event_name": "manual",
    "pretty_release_name": "a380x-experimental:02f7264f",
    "version": "a380x-v0.12.0-a380x-experimental.02f7264"
}
```

### Describe the bug

1. THR lever detents position do not match cockpit decals
2. Mouse-dragging THR lever 1 or 4 activates reverse thrust (visible in E/WD, sounds and taxi speed)

### Expected behavior

1. Detents matching decals
2. Reverse thurst not being possible in eng 1 and 4

### Steps to reproduce

1. move THR levers and check detent positions vs cockpit decals
2. mouse-drag eng 1 and 4 into reverse

### Discord Username (optional)

Bernardo R

**Comment by BravoMike99** [comment]
The "detent sound" doesn't seem to match either. There is a "click" way before CLB position is reached for e.g.
