### ISSUE TITLE
Add room design

### ISSUE THREAD

**Issue by Kawaharu869** [flybywiresim/aircraft#8897]
### Aircraft Version

Development

### Description

**Nothing is displayed because there is no design for the guest room or seats. I want you to create a design.**
A32NX Version : Development c4ab989  MSFS Version : 1.37.19.0

### References (optional)

![image](https://github.com/user-attachments/assets/94b50310-172b-4dbb-ae49-e3aaf5c754ce)

### Discord Username (optional)

kawaharu3697

**Comment by benutzer9867** [comment]
Adding a cabin is a planned feature but not a priority at the moment

**Comment by alepouna** [comment]
Duplicate, there are plans for a cabin after the A380X.
