### ISSUE TITLE
CPT MW p/b with no sound

### ISSUE THREAD

**Issue by becas22** [flybywiresim/aircraft#8904]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-09-13T19:31:48+00:00",
    "ref": "refs/heads/a380x-experimental",
    "sha": "74f1594ff159fa17b96b0ee67c3452730accbc10",
    "actor": "flogross89",
    "event_name": "manual",
    "pretty_release_name": "a380x-experimental:74f1594f",
    "version": "a380x-v0.12.0-a380x-experimental.74f1594"
}
```

### Describe the bug

Captain's Master Warning pushbutton with no click sound

### Expected behavior

`*click*`

### Steps to reproduce

1. Click CPT's MW p/b

**Comment by flogross89** [comment]
Most likely due to a naming issue in the GLTF model file: 
Node is named `PUSH_GLARESHIELD_CS_MASTERAWARN`, but should be named `PUSH_GLARESHIELD_CS_MASTERWARN`

**Comment by tracernz** [comment]
The clickspot + blue highlight wouldn't work if it was a naming issue? It's definitely got the right name in the last blend file I have (and the origin is in the right place too):
![image](https://github.com/user-attachments/assets/573c9e72-4c2d-4072-ba5a-8cdcf8bd69e3)

**Comment by flogross89** [comment]
We do have both spellings at the moment, with and without the typo. I suppose the clickspot works because of the correctly named node, but I don't know why the WWISE event won't trigger. I suggested to Rep to clean up the typo, let's see then

**Comment by pilotseyea350** [comment]
The sound isn't the only thing missing, the animation is also missing
