### ISSUE TITLE
FMS: Radio Tuning by Ident Broken

### ISSUE THREAD

**Issue by tracernz** [flybywiresim/aircraft#8905]
### Aircraft Version

Development

### Build info

```json
master
```

### Describe the bug

The FMS pages implement radio tuning by ident incorrectly, always taking the first result with no duplicate navaid page. This means a random result is picked and tuned.

We should disable this function for release to remove the blocker tag if nobody fixes it.

### Expected behavior

The duplicate navaid selection page should pop up when there are duplicates allowing you to pick the correct one.

### Steps to reproduce

Enter any navaid ident with duplicates in the VOR or ILS boxes.

**Comment by FoxtrotSierra6829** [comment]
Does MSFS provide a GPS position property for the navaid? If so, maybe an easy fix is to order the results by distance and select the closest until a user interface has been implemented?

**Comment by tracernz** [comment]
We should either implement it properly, or disable it. Anything else will cause unexpected behaviour.
