### ISSUE TITLE
A380X Baro preselection not remembering entered value

### ISSUE THREAD

**Issue by alexr4339** [flybywiresim/aircraft#8913]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-09-14T04:43:33+00:00",
    "ref": "refs/heads/a380x-experimental",
    "sha": "164e9b6b6b803aaa52c02f2f15c57272c149ec0f",
    "actor": "flogross89",
    "event_name": "manual",
    "pretty_release_name": "a380x-experimental:164e9b6b",
    "version": "a380x-v0.12.0-a380x-experimental.164e9b6"
}
```

### Describe the bug

When Baro is in STD and preselecting 1020 for example, the value disappears after a while which is ok. However when switching back to QNH, the value is 1013 and not 1020 as preselected. The preselection only works when switching from STD to QNH before the preselected value disappears

### Expected behavior

It should still set the QNH to the preselected value

### Steps to reproduce

Set QNH to STD
Preselect Value
Wait until preselected value disappears
Switch back to QNH

### Discord Username (optional)

alexdnzdmb

**Comment by flogross89** [comment]
Have we confirmed that the real aircraft stores the value?

**Comment by becas22** [comment]
https://youtu.be/p28erS6uWHE?t=4942

**Comment by Pruznak** [comment]
> > https://youtu.be/p28erS6uWHE?t=4942
> 
> Can’t see anything unfortunately 😄 Does it switch to something which is not 1013?

You can't see it directly, but when the video switches to the PFD + ND view after some seconds, you can see the QNH is set to 30.29 on the PFD and I think it would be strange that they would switch it and not set the value right away.

**Comment by flogross89** [comment]
> > > https://youtu.be/p28erS6uWHE?t=4942
> > 
> > 
> > Can’t see anything unfortunately 😄 Does it switch to something which is not 1013?
> 
> You can't see it directly, but when the video switches to the PFD + ND view after some seconds, you can see the QNH is set to 30.29 on the PFD and I think it would be strange that they would switch it and not set the value right away.

Indeed, thanks! So it seems the value is indeed stored even when the presel is not visible, this is something which would have to be changed in the AFS CP XML or in the FCU code (which is currently being ported). 
I'd say we halt this until #8919 is merged
