### ISSUE TITLE
A380X TERR mode being displayed on ILS and VOR pages

### ISSUE THREAD

**Issue by alexr4339** [flybywiresim/aircraft#8914]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-09-14T04:43:33+00:00",
    "ref": "refs/heads/a380x-experimental",
    "sha": "164e9b6b6b803aaa52c02f2f15c57272c149ec0f",
    "actor": "flogross89",
    "event_name": "manual",
    "pretty_release_name": "a380x-experimental:164e9b6b",
    "version": "a380x-v0.12.0-a380x-experimental.164e9b6"
}
```

### Describe the bug

The VOR and ILS pages do display TERR when selected in the FCU and additionally show the vertical TERR profile in the bottom of the ND. The TERR itself isn't a problem, just that it displays on ILS and VOR pages which it shouldnt.

### Expected behavior

There shouldnt be any TERR displayed on VOR and ILS pages

### Steps to reproduce

Turn on TERR
Switch to ILS or VOR page

**Comment by flogross89** [comment]
ILS or VOR ROSE should also display TERR, all ROSE modes should -> closed
