### ISSUE TITLE
Pack 1 fault-light

### ISSUE THREAD

**Issue by MStallen** [flybywiresim/aircraft#8928]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-09-16T10:27:01+00:00",
    "ref": "refs/heads/master",
    "sha": "b314f7dca6509a026d083f895f9a4a15b275216e",
    "actor": "Gurgel100",
    "event_name": "manual",
    "pretty_release_name": "master:b314f7dc",
    "version": "a32nx-v0.12.0-dev.b314f7d"
}
```

### Describe the bug

During start-up the LVAR A32NX_OVHD_COND_PACK_1_PB_HAS_FAULT is 1, but the fault- light is off. A32NX_OVHD_COND_PACK_2_PB_HAS_FAULT  is also 1 and the fault-light is on

### Expected behavior

With value 1 fault-light on

### Steps to reproduce

1. start-up
2. batteries on

(not connected to ecternal power)

**Comment by komp1821** [comment]
This behavior is correct. 

Pack 1 pushbutton annunciators receive their power from AC ESS SHED bus, which isn't powered in this situation (batteries only on ground). Pack 2 pushbutton annunciators are on STAT INV bus, which is powered.

**Comment by MStallen** [comment]
Ah very good. Thank you. Where can I find more information about this, maybe they're more annunciators etc. which have the same wiring

**Comment by komp1821** [comment]
You can have a look at PR #3980 
It lists all power supplies for all annunciators (and more)
