### ISSUE TITLE
[A380X] runway.flt preset not fully configured for take-off

### ISSUE THREAD

**Issue by flogross89** [flybywiresim/aircraft#8936]
### Aircraft Version

Development

### Build info

```json
master
```

### Describe the bug

Make sure that T.O memo is green (fix flaps, signs, and potentially more)
Important for newbie users

### Expected behavior

-

### Steps to reproduce

-

### Discord Username (optional)

floridude

**Comment by 2hwk** [comment]
Currently not set:
1. XPDR
2. Flaps
3. Seatbelt sign is sometimes bugged (?) - Check if this is fixed in latest exp

**Comment by flogross89** [comment]
fixed in https://github.com/flybywiresim/aircraft/pull/8885
