### ISSUE TITLE
[A380X] Feed tank 4 main pushubtton animates standby button

### ISSUE THREAD

**Issue by BravoMike99** [flybywiresim/aircraft#8943]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-09-19T11:14:35+00:00",
    "ref": "refs/heads/master",
    "sha": "c8c6b9fa02f02420c1d9fa847ec0ddc602413a03",
    "actor": "lukecologne",
    "event_name": "manual",
    "pretty_release_name": "master:c8c6b9fa",
    "version": "a380x-v0.12.0-dev.c8c6b9f"
}
```

### Describe the bug

Pressing the main feed TK 4 pushbutton on the overhead panel also animates the standby pump pushbutton of the same tank.

### Expected behavior

One to not affect the other.

### Steps to reproduce

As mentioned above.

### Discord Username (optional)

bruno_pt99

**Comment by beheh** [comment]
Needs to be fixed in the model, the XML looks good.

**Comment by beheh** [comment]
Rep says this is fixed in the latest model, needs verifying.

**Comment by beheh** [comment]
Fixed.
