### ISSUE TITLE
Radio Nav page blocks input

### ISSUE THREAD

**Issue by matssederholm** [flybywiresim/aircraft#8944]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-09-16T10:27:01+00:00",
    "ref": "refs/heads/master",
    "sha": "b314f7dca6509a026d083f895f9a4a15b275216e",
    "actor": "Gurgel100",
    "event_name": "manual",
    "pretty_release_name": "master:b314f7dc",
    "version": "a32nx-v0.12.0-dev.b314f7d"
}
```

### Describe the bug

Nothing can be manually entered in the Radio Nav Page

### Expected behavior

Entering e.g. a valid VOR frequency should result in that frequence is then displayed in the VOR field. 

### Steps to reproduce

1 Create a flight standing at gate
2 Turn on pwr
3 Open the Radio nav page in the FMS
4 Try enetering a VOR frequency for e.g. the current airport, or an ILS

### Discord Username (optional)

matssederholm

**Comment by tracernz** [comment]
Fix will be available in the installer in a short while, thanks again.
