### ISSUE TITLE
a380x: new dest field won't accept focus/input

### ISSUE THREAD

**Issue by tracernz** [flybywiresim/aircraft#8959]
### Aircraft Version

Development

### Build info

```json
master
```

### Describe the bug

Open the revise menu on a waypoint and select NEW DEST. The popup opens, but the input field cannot be focused to input the new destination.

### Expected behavior

Input accepts focus and input so a new destination can be inserted at the revise point.

### Steps to reproduce

As in description.

**Comment by flogross89** [comment]
solved on 0.12
