### ISSUE TITLE
a380x: duplicate names page appears on airway termination

### ISSUE THREAD

**Issue by tracernz** [flybywiresim/aircraft#8960]
### Aircraft Version

Development

### Build info

```json
master
```

### Describe the bug

Setup flight plan `NZCH/02 GUTBU1P.GRETA NZWN`, revise -> airways on GRETA, enter Y393, then try to enter WARDS as the termination. The duplicate names page appears with a 2nd WARDS that is no on Y393 from GRETA.

### Expected behavior

The FMS should only consider fixes on the airway.

### Steps to reproduce

As in description.

**Comment by flogross89** [comment]
Just to check: Wouldn't the A32NX also have this problem, since it uses getOrCreateWaypoint which calls deduplicate in case of multiple waypoints? I plan to implement a function in PendingAirways which looks for fixes on the last/tail airway

**Comment by tracernz** [comment]
> Just to check: Wouldn't the A32NX also have this problem, since it uses getOrCreateWaypoint which calls deduplicate in case of multiple waypoints? I plan to implement a function in PendingAirways which looks for fixes on the last/tail airway

If it does, it's an fms-v2 regression. But I don't think it does as I use this route all the time for testing.
