### ISSUE TITLE
Alt magenta visible on PFD with FDs off

### ISSUE THREAD

**Issue by BravoMike99** [flybywiresim/aircraft#8971]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-09-21T09:36:47+00:00",
    "ref": "refs/heads/master",
    "sha": "497d0a8b6a80e52655a6629fcf7bf4ee07c817a2",
    "actor": "Maximilian-Reuter",
    "event_name": "manual",
    "pretty_release_name": "master:497d0a8b",
    "version": "a32nx-v0.12.0-dev.497d0a8"
}
```

### Describe the bug

Altitude magenta displayed on PFD despite FDs being off and no guidance mode being active.
![Managed](https://github.com/user-attachments/assets/c50a9c31-716d-45aa-b4eb-668eff4902d7)

### Expected behavior

Altitude magenta to not be displayed in the above conditions.

### Steps to reproduce

1) Fly an arrival using managed descent with an altitude constraint (AT/AT OR ABOVE). Select an FCU altitude higher or the same as the constraint.
2) Disconnect AP & FDs
3) Select an altitude below the constraint on the FCU and observe PFD.

### Discord Username (optional)

bruno_pt99

**Comment by lukecologne** [comment]
Looks like it's because the current logic in the PFD applies negative logic (i.e. CSTR when NOT in selected modes) instead of positive logic (i.e. in managed modes). This will be fixed in #7587, where the logic is redone and moved to the FG.
