### ISSUE TITLE
No Flypad Map

### ISSUE THREAD

**Issue by hakkemanu** [flybywiresim/aircraft#9005]
### Aircraft Version

Stable

### Build info

```json
Hiii, why is there no flypad map anymore, where i can see my plane & my route on the worldmap?
```

### Describe the bug

Hiii, why is there no flypad map anymore, where i can see my plane & my route on the worldmap?

### Expected behavior

Hiii, why is there no flypad map anymore, where i can see my plane & my route on the worldmap?

### Steps to reproduce

Hiii, why is there no flypad map anymore, where i can see my plane & my route on the worldmap?

**Comment by 2hwk** [comment]
Was removed as it caused a memory leak. Currently not planned.
