### ISSUE TITLE
[A380X] Better AP Disconnect Logic

### ISSUE THREAD

**Issue by pilotseyea350** [flybywiresim/aircraft#9008]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-09-30T16:42:48+00:00",
    "ref": "refs/heads/a380x-experimental",
    "sha": "c090953517e912d5833db4783ac671c61fb1db69",
    "actor": "aguther",
    "event_name": "manual",
    "pretty_release_name": "a380x-experimental:c0909535",
    "version": "a380x-v0.12.0-a380x-experimental.c090953"
}
```

### Describe the bug

Currently when disconnecting the autopilot, the events are as follow:
- Autopilot Disconnect
- 3 Autopilot disconnect chimes
- 3 Landing Capability Downgraded clicks

No matter the number of click on the sidestick takeover button, the sequence is the same

### Expected behavior

When disconnecting the autopilot, the sequence should be:
-  Autopilot Disconnect
- Master Warning Light should come on and stay on until the sidestick takeover has been clicked a second time or the master warning button has been pushed
- Autopilot disconnect chimes until the sidestick takeover has been clicked a second time or the master warning button has been pushed
- 3 Landing Capability Downgraded clicks if switching from an ILS CAT3 approach to an ILS CAT1 (iirc)

### Steps to reproduce

1. Fly above 400ft AGL
2. Engage autopilot
3. Disengage autopilot
4. Observe the events after autopilot is off

### References (optional)

https://www.youtube.com/watch?v=qcXQKQukxkI&t=59s

& many other A380 cockpit landing videos

### Discord Username (optional)

PilotEyesA350

**Comment by flogross89** [comment]
The exact logic is a little bit more complicated, and should be implemented in the FWS (together with the AP OFF memo, ...)

**Comment by pilotseyea350** [comment]
Yeah I assumed it was a bit more in complex than that. Just opened it to highlight it ! Do we have a FWS PR or issue opened for this already ?

**Comment by flogross89** [comment]
All good, no there's no issue for it. Just commenting for future implementation

**Comment by lukecologne** [comment]
This issue is not exclusive to the A380X btw, the A32NX suffers from the same simplistic logic

**Comment by henrybungee** [comment]
Found this in the A319/20/21 FCOM. I can't imagine that the autopilot disconnect logic is any different in the A380. 

<img width="711" alt="Screenshot 2024-11-13 at 10 00 23 AM" src="https://github.com/user-attachments/assets/2b75f843-f227-432d-a674-6554ff47b9d2">

The only time the triple click should be audible after disconnecting the autopilot should be when the autoland FMA mode is reverted to CAT I. 

I don't remember if the triple click logic is implemented into the FMA in general (any FMA mode reversion, e.g. turning the flight directors off, heading select while using a managed climb or descent mode) but if not that's also something that could help improve the AP disconnect logic.

**Comment by flogross89** [comment]
In the meantime, the FWS logic for AP disconnect has been overhauled for the A380X, it should be fairly accurate now. It is a little different than the a320, for example there’s no minimum CRC time, it can be cancelled right away. 

One exception though: The triple click logic is still inaccurate, because we would need changes on the AP/FG side for that. 
So future fixes should concentrate on the triple click.
