### ISSUE TITLE
[A32NX/FMS]: TO waypoint track displayed on top right of ND in manual leg

### ISSUE THREAD

**Issue by BravoMike99** [flybywiresim/aircraft#9016]
### Aircraft Version

Development

### Build info

```json
master
```

### Describe the bug

When a manual leg is active, the TO Waypoint Track is visible on the rop right of the ND.
![Manual](https://github.com/user-attachments/assets/27caced5-9de4-469d-90cb-c05ab8b8b650)

### Expected behavior

Track should not appear under manual leg.

### Steps to reproduce

Have a manual leg as the active leg of the flightplan (e.g. LPPT RWY 02 or 20 missed approach) and observe the ND on the top right.

### References (optional)

![image](https://github.com/user-attachments/assets/e3701846-2f12-47b2-80be-09baf45b2893)

(also applicable to the A380):
![image](https://github.com/user-attachments/assets/5d86f29c-24c8-4e45-9235-c8e82f3b2a84)

### Discord Username (optional)

bruno_pt99

**Comment by tracernz** [comment]
Does that depend on the specific type of manual leg, or all?

**Comment by tracernz** [comment]
Do you know what procedures, and the nav db data provider for your pics?

**Comment by BravoMike99** [comment]
> Do you know what procedures, and the nav db data provider for your pics?

LPPT RWY 02 Missed approach on the first one (should be a FM leg) with LIDO, however, with jep its the same I believe. In the sim it shows the track on that one with both navi & navblue/default IIRC.
Second one with the A380 is ILS 08R missed approach on CDG and should be LIDO as its air france but I just looked and it seems the procedures have changed so unless you can go back in time its useless (sorry 😅 ) .
