### ISSUE TITLE
[A380X] Cobra maneuver

### ISSUE THREAD

**Issue by flogross89** [flybywiresim/aircraft#9021]
### Aircraft Version

Development

### Build info

```json
master
```

### Describe the bug

With AP engaged, when descending with extended spoilers and when extending flaps from 0 to 1, aircraft enters cobra maneuver, disregarding FD commands

### Expected behavior

It shouldn't do a cobra maneuver, we're not a fighter aircraft.

### Steps to reproduce

1. Level flight or descend on profile or using OP DES, aircraft speed well above VLS, AP engaged
2. Extend spoilers to FULL
3. Extend flaps from 0 to 1
4. Sometimes (frequency not yet clear), aircraft develops a severe pitch up moment, leading to a cobra maneuver

### References (optional)

![image](https://github.com/user-attachments/assets/2653a569-0cec-46e6-8718-47cebedb8dd5)

### Discord Username (optional)

floridude

**Comment by becas22** [comment]
I suggested yesterday in Discord that, if we are unable to fix this quickly, consider publishing an OEB
