### ISSUE TITLE
Rudder in full deflection when doing a cold start

### ISSUE THREAD

**Issue by Raphi02** [flybywiresim/aircraft#9031]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2023-11-03T17:47:36+00:00",
    "ref": "refs/tags/v0.11.1",
    "sha": "f055eb02dc0af32441f8b2873f58e8316d7ca638",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.11.1",
    "version": "v0.11.1-rel.f055eb0"
}
```

### Describe the bug

When I load into the game at a ramp, the rudder is fully tilted into one direction at the start.

### Expected behavior

When loading into a new flight at a ramp the rudder should be in neutral position.

### Steps to reproduce

1. Load into a new flight at Ramp 3 in Liverpool (EGGP)

### References (optional)

![image](https://github.com/user-attachments/assets/ff270a3c-3510-47f4-8f34-77fc896dbd62)

### Additional info (optional)

I checked that the AI option for automatic rudder is off in the option ribbon and the assistance options. I tried setting (and loading) with the efb setting 'separate tiller from rudder inputs' on and off. You can also read the deflection values in the F-CTL ECAM page. Interestingly I could not observe the behaviour when starting with a prepared aircraft on the runway. The bug can also be observed in the current development version:

```
{
    "built": "2024-10-05T18:50:36+00:00",
    "ref": "refs/heads/master",
    "sha": "154a4f3c1b9d851e4a92aeca6f1f4e8714028910",
    "actor": "crocket63",
    "event_name": "manual",
    "pretty_release_name": "master:154a4f3c",
    "version": "a32nx-v0.12.0-dev.154a4f3"
}
```

I suspect the bug came with updating to the game version 1.38.2.0 as I could start a flight a view days ago without any problems and I loaded this update today before playing.

**Comment by alepouna** [comment]
This is perfectly normal, the hydraulic pumps are not running (because your engines are off at cold start) so the wind will move the rudder. Once the engines are running, or you use the electric HYD pump on the overhead, the rudder will center it self and will also move at pedal command.

**Comment by tshomas** [comment]
That is correct as the hydraulics are off so the rudder can't self centre, it will move around in the wind effect, often sitting at one side fully deflected.

![iberia-airbus-a320-passenger-plane-parked-alongside-an-airbridge-at-malaga-airport-malaga-spain-2DAJ8W1](https://github.com/user-attachments/assets/fa6223da-00a1-49ca-b5c6-63a0147c7927)
![Easyjet_Airbus_A320_Parked_at_Bristol_Airport](https://github.com/user-attachments/assets/f3c58d70-9285-482b-8ba5-694209cb0671)
