### ISSUE TITLE
Take Off calculator

### ISSUE THREAD

**Issue by romfootvff** [flybywiresim/aircraft#9037]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2023-11-03T17:47:36+00:00",
    "ref": "refs/tags/v0.11.1",
    "sha": "f055eb02dc0af32441f8b2873f58e8316d7ca638",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.11.1",
    "version": "v0.11.1-rel.f055eb0"
}
```

### Describe the bug

Hello, in the tablet I do not have the performance calculator for takeoff, I looked at the documentation and in the images I see it clearly but not in my a32nxHello, in the tablet I do not have the performance calculator for takeoff. 

### Expected behavior

I looked at the documentation and in the images I see it clearly but not in my a32nx.

### Steps to reproduce

1.Open tablet
2.Go to the performance calculator

**Comment by Gurgel100** [comment]
The takeoff performance calculator is not available on stable yet. Switch to the development version of the plane (by switching to development in the installer).
