### ISSUE TITLE
[A380X][A32NX] Performance tables do not match actual engine model

### ISSUE THREAD

**Issue by BlueberryKing** [flybywiresim/aircraft#9042]
### Aircraft Version

Development

### Build info

```json
master
```

### Describe the bug

The engine model in the cfg files do not match the performance tables (`EngineModel.ts`) used for predictions. 

Required changes: 

- Make EngineModel aircraft-specific
- - Update values for A32NX to reflect engines.cfg values
- Update values for A380X to reflect engines.cfg values

### Expected behavior

The tables should match.

### Steps to reproduce

See description

**Comment by flogross89** [comment]
Also present for the A32NX, it was missed to update the polynomial coefficients
