### ISSUE TITLE
[REQUEST] SIDESTICK PRIORITY FIX

### ISSUE THREAD

**Issue by PANAM741** [flybywiresim/aircraft#908]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

The sidestick priority red arrows are missing and sides priorities are wrong. Also if it can be functional.

![176991B1-DD3E-4DC5-A4B0-0973C3588301](https://user-images.githubusercontent.com/71863590/94347159-8fa23a00-fff7-11ea-835b-990f8876a0ac.jpeg)

**References**

![54FB42B8-7F9A-4FAA-9959-9F7CB43B94C6](https://user-images.githubusercontent.com/71863590/94347152-83b67800-fff7-11ea-8ce7-f46f9bbd5b06.jpeg)

**Additional context**

Discord username (if different from GitHub):

**Comment by NathanInnes** [comment]
Texture change would be okay to do but for full functionality it would be completely pointless to even spend time working on in my opinion. I don't even think it would work even if you had sharedcockpit functionality as there's only 1 main input for flight controls.
