### ISSUE TITLE
Hope to add cabin model for A320NX

### ISSUE THREAD

**Issue by 0Yanxuewen** [flybywiresim/aircraft#9169]
### Aircraft Version

Stable

### Description

Thank you to the staff of FBW developers for providing the free A320NX aircraft! You have worked hard! I've been flying A320NX all along, it's really good! I hope to add cabin models to the A320NX in the future! Make the entire plane look more realistic!

**Comment by NathanInnes** [comment]
Thanks for kind words on behalf of everyone involved. Existing request has already been raised so I will close this one. #2577
