### ISSUE TITLE
PLAN mode in ND not working

### ISSUE THREAD

**Issue by ennkay654** [flybywiresim/aircraft#9177]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-29T06:08:03+00:00",
    "ref": "refs/heads/master",
    "sha": "1e04beb3d44533dfb27fd73c6829f18506530c14",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "master:1e04beb3",
    "version": "a32nx-v0.13.0-dev.1e04beb"
}
```

### Describe the bug

When selecting PLAN mode for the ND display, the flight plan does not appear. The display appears, but it is empty.

### Expected behavior

I expected the flight plan (which appears in ARC mode) to appear.

### Steps to reproduce

1. Open aircraft
2. Turn battery and ext power on
3. IRS on NAV mode
4. insert flight plan in MCDU
5. Confirm flight plan appears in ARC
6. Flight plan does not appear in PLAN

**Comment by alepouna** [comment]
> Have you tried reinstalling? I have tried to reproduce with the steps you provided but on my side it seems normal...

+1 to this. We recommend stepping by our Discord server first for support! https://discord.gg/flybywire

**Comment by tracernz** [comment]
Try with nothing except A32NX in your community directory and I suspect this will go away.

**Comment by ennkay654** [comment]
Thank you, the a32nx wx radar addon caused it. Removed addon and all is good.
