### ISSUE TITLE
 proper V-speed calculator

### ISSUE THREAD

**Issue by EvanPlayzXplane12** [flybywiresim/aircraft#9180]
### Aircraft Version

Stable

### Description

I think that a V-speed calculator would be an amazing thing for A32NX and the A380X. things it should include is runway length and slope. Thank you for taking this into consideration.

**Comment by tracernz** [comment]
This is already implemented in the A32NX, and duplicate of https://github.com/flybywiresim/aircraft/issues/9176 for the A380X.
