### ISSUE TITLE
PARK BRK ON indication not displayed at the top of ECAM Memo

### ISSUE THREAD

**Issue by G-DRAW** [flybywiresim/aircraft#9181]
### Aircraft Version

Development

### Build info

```json
Any
```

### Describe the bug

[A380X PARK BRK Indication.docx](https://github.com/user-attachments/files/17563063/A380X.PARK.BRK.Indication.docx)

### Expected behavior

The PARK BRK ON indication takes priority over all other messages, and should be displayed at the top of the ECAM Memo.

### Steps to reproduce

I saw this on the latest preview.

**Comment by flogross89** [comment]
We don't implement ordering of ECAM memos of the same color at the moment. The memos are sorted by color currently (red > purple > amber > green)
