### ISSUE TITLE
flyPad Payload page - ZFWCG/GWCG does not work

### ISSUE THREAD

**Issue by frankkopp** [flybywiresim/aircraft#9186]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-29T14:32:19+00:00",
    "ref": "HEAD",
    "sha": "1e433bf5a49ba39a13ff868ed117dd0e03bb14d2",
    "actor": "floridude <63071941+flogross89@users.noreply.github.com>",
    "event_name": "manual",
    "pretty_release_name": "v0.12:1e433bf5",
    "version": "a380x-v0.12.0-v0.12.1e433bf"
}
```

### Describe the bug

![image](https://github.com/user-attachments/assets/e560c0a7-88f2-4667-80d8-2e66bea40528)

Button not changing the display to GW CG

### Expected behavior

Change from ZFWCG to GW CG and vice versa

### Steps to reproduce

Start aircraft, load payload, test the button

**Comment by 2hwk** [comment]
This is strange as this is working on my build.

**Comment by vajonam** [comment]
I have the same issue, the button doesn't toggle between ZFWCG and GWCG

**Comment by el-lute2022** [comment]
I have a similar issue. I thought it might be related to the 4K version I use but same thing happens on the 8K version. It worked once and that was that. Never again, did it work (I wish I knew what I did the one time it worked!). In case it helps, I use an RTX 4070ti with DLSS and DirectX 11 with legacy controls. BTW, in the A20N, this feature works without issues.

**Comment by el-lute2022** [comment]
I have just made a finding. To look at the EFB, I was using the CTRL+8 keyboard shortcut, but it turns out that creating a new view to the EFB from the default cockpit view (or moving the view from the cockpit to look at the EFB), the ZFWCG/GWCG button works. Create a new view and that should be it. I hope this makes sense

**Comment by frankkopp** [comment]
@2hwk 

The cause seems to be that when using the flyPad view this button is exactly above the window handle clickspot and the click seems to go to the handle instead of the flyPad.

The handle has a condition to not open under certain view angles (earlier workaround) which is why the click doesn't do anything. 

Moving the view to the flyPad so that the handle is not behind the clickspot the CG button works as expected.

**Comment by vajonam** [comment]
Awesome catch! thanks adjust the view works as mentioned!
