### ISSUE TITLE
Logo light switch missing click spot and not functional.

### ISSUE THREAD

**Issue by 18simpsona** [flybywiresim/aircraft#9193]
### Aircraft Version

Development

### Build info

```json
0.12.0
```

### Describe the bug

Logo light switch missing click spot and not functional. Logo light is controlled by the nav light switch, should be the logo light switch.

### Expected behavior

Logo light switch should have a click spot and should be functional controlling the logo light, not the nav light switch.

### Steps to reproduce

click the nav light switch, look outside, see it controls the logo light, try to click the logo light switch, nothing happens.

**Comment by alepouna** [comment]
Duplicate of #8828
