### ISSUE TITLE
Wrong arrival information@

### ISSUE THREAD

**Issue by Goritoo11** [flybywiresim/aircraft#9196]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

On a flight from LROP to LRCL when prompted to select arrival info for LRCL, incorrect runway and approach configs show. You can't even select an approach to contrinue with the rest of the arrival info.
![Screenshot 2024-10-31 185342](https://github.com/user-attachments/assets/79aeee7b-ef2d-447a-a28d-4d65651f3507)
![Screenshot 2024-10-31 185354](https://github.com/user-attachments/assets/99ab946e-08d8-493b-b045-7a9a8822c315)

### Expected behavior

Runways in LRCL are 07 and 25 not 08 and 26. You should be able to select an approach and continue with the rest of the info which is clearly not available here.

### Steps to reproduce

1. Enter Flight number (FBW1)
2. Enter Departure and Arrival airports without uplink
3. Select Departure and enter departure information
4. Select Active and INIT 
5. Select LRCL
6. Select Arrival
7. Select either of the two runways 08 or 26 (incorrect config)
8. Not able to select approach and contrinue with the rest of the arrival instructions

### References (optional)

[https://streamable.com/0yw3em](url)

### Discord Username (optional)

adam.niu

**Comment by BlueberryKing** [comment]
Hi, this is a navdata issue. Are you using Navigraph navdata or any addon scenery for LRCL?

**Comment by Goritoo11** [comment]
> Hi, this is a navdata issue. Are you using Navigraph navdata or any addon scenery for LRCL?

I'm using latest airac, default scenery for LRCL

**Comment by tracernz** [comment]
The runways are defined by the base sim airport data. There's nothing we can do here. You may find a third party scenery that corrects the runways, and then it may work.
![image](https://github.com/user-attachments/assets/0a529182-7461-4dce-af7b-2505cf806938)
