### ISSUE TITLE
PERFORMANCE ISSUES

### ISSUE THREAD

**Issue by Siqueira-28** [flybywiresim/aircraft#9204]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T14:32:39+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "f26029363ad3edeeafbed20aa79c13b32c8090f8",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-HEAD.f260293"
}
```

### Describe the bug

The aircraft is very poorly optimized and heavier than ready-made aircraft such as the Fenix ​​A320, PMDG 737, 777...

### Expected behavior

Loss fps. (20FPS on cruise)

### Steps to reproduce

All time

### References (optional)

My setup:

Ryzen 5 3600
RTX 3060 TI 8GB
40gb RAM
SSD m2

### Discord Username (optional)

siqueira.jow

**Comment by AirPlaneBoy506** [comment]
I mean it is in Alpha so we cant be that mad about it

**Comment by e850205** [comment]
I'm sure your post contributed greatly to their understanding of the issue...

**Comment by karlito92d** [comment]
This post can't be legit LOL

**Comment by cptalpdeniz** [comment]
I hope this post gets closed immediately, this is not the correct way to use issues and also the aircraft is [ALPHA](https://en.wikipedia.org/wiki/Software_release_life_cycle#Alpha).
