### ISSUE TITLE
[A380X] GW, CG, FOB in Fuel/Load Page in the MFD Not updated from the EFB or aircraft loaded values

### ISSUE THREAD

**Issue by utkrishtm** [flybywiresim/aircraft#9207]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

I loaded the values into the EFB and click applied to load to aircraft. In the MFD after the I updated the values for ZFW, ZFQCG and Block fuel, the above green items did not get populated. `GW ---.-T,  CG --.-%, FOB ---.-T.`

![image](https://github.com/user-attachments/assets/24e755f5-c7bf-4abd-ae80-c0726e37adb3)

### Expected behavior

The figures should get loaded and look like this. 

`GW 438.4T,  CG 40.3%%, FOB 94.2T.`

### Steps to reproduce

1. Load the fuel and payload in EFB
2. Load them instantly
3. Go to the MFD and the fuel load page. Enter the ZFW, ZFWCG, FOB
4. see if the green values get populated.

### Discord Username (optional)

utkrishtm

**Comment by utkrishtm** [comment]
When I load into the plan ready directly at the runway, those values are populated and sensed by the plane. But if i start cold and dark at the gate, those values are empty.

**Comment by BravoMike99** [comment]
This is expected, the values are only populated after engine start. Real world example: 
![image](https://github.com/user-attachments/assets/40dbfc32-4bf7-48b3-bef3-78eaab790f00)
Before that you can check the values on the ECAM SD page

**Comment by utkrishtm** [comment]
@BravoMike99 
Hello, 

That makes sense, i tested again. The engines were running and I check the page. All the entries were filled in. However, there is still an issue. The FOB quantity is incorrect. I have 81100 KGS of fuel which is 81.1T. But the Page shows 0.1T. Please check the following image. 

![a380x test](https://github.com/user-attachments/assets/d323daad-f1d6-4842-bed8-3b91f2dfd1a7)

**Comment by BravoMike99** [comment]
> @BravoMike99 Hello,
> 
> That makes sense, I tested again. The engines were running and I checked the page. All the entries were filled in. However, there is still an issue. The FOB quantity is incorrect. I have 81100 KGS of fuel which is 81.1T. But the Page shows 0.1T. Please check the following image.
> 
> Do let me know if I need to open a new Issue.
> 
> ![a380x test](https://private-user-images.githubusercontent.com/69091189/386883761-d323daad-f1d6-4842-bed8-3b91f2dfd1a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MDAxNjIsIm5iZiI6MTczMTc5OTg2MiwicGF0aCI6Ii82OTA5MTE4OS8zODY4ODM3NjEtZDMyM2RhYWQtZjFkNi00ODQyLWJlZDgtM2I5MWYyZGZkMWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDIzMzEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiYjlmZDBjOTc2MDllZTYwNThkY2FkY2JiZTAyNGE5MTg1ZDkxNWQ1ZGZhMWM3ZmRmOGQ5MTJmNjA2MDI0MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.60Fk__Y7wZuP6kScWvQ5tjXm_CnFZenxbggIbGZLgi4)
 
 No need, #9540 has a fix for this

**Comment by utkrishtm** [comment]
Perfect! thanks a lot
