### ISSUE TITLE
Rudder Axis inversed below 80 knots on A380

### ISSUE THREAD

**Issue by ZEBRUHMAN** [flybywiresim/aircraft#9208]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T14:33:02+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "f26029363ad3edeeafbed20aa79c13b32c8090f8",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-HEAD.f260293"
}
```

### Describe the bug

Hello,

I've noticed that when I use the rudder below 80 knots, the rudder is inverted both on takeoff and landing. When I'm above this speed, the plane behaves correctly. (I specify the rudder and not the tiller).

I use the Thrustmaster T Flight Rudder and Logitech X56

### Expected behavior

Rudder not inversed

### Steps to reproduce

1) Start on a runway
2) accelerate 
3)constate below and above 80 knots

### References (optional)

https://www.swisstransfer.com/d/736f2e39-15c3-420b-9526-fdbd20a0f7e4

### Discord Username (optional)

BRUH_MAN

**Comment by tracernz** [comment]
Disable MSFS assistance settings if you're still struggling with that.
