### ISSUE TITLE
Doors Open and Airplane+System Freeze

### ISSUE THREAD

**Issue by TxmoTK** [flybywiresim/aircraft#9215]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T14:33:02+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "f26029363ad3edeeafbed20aa79c13b32c8090f8",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-HEAD.f260293"
}
```

### Describe the bug

Hey, I was flying to Dubai when suddenly, the doors opened mid-air over the Red Sea. I managed to close them by changing the page on the EFB. On Volanta, I saw that I was off course, even though I hadn’t changed anything. The PFD was frozen too. I couldn’t take over control by hand, and the plane didn’t respond to anything. My friend had exactly the same bug.

### Expected behavior

That the airplane continues to fly normally ;)

### Steps to reproduce

Video Link: https://youtu.be/DSDSrQeMCQ4

Video from my friend: https://youtu.be/X_B7gLpjw2c

### Discord Username (optional)

TxmoTK

**Comment by Toasty3920** [comment]
Plane froze for me aswell, but in my case it happened after inserting a Direct.

**Comment by TxmoTK** [comment]
You can also see how the PDF is frozen but on this small display you can see how the airplane loses height

**Comment by Waschmaschinenfreund** [comment]
Yes I had the same problem, though for me it happened after doing a direct. I had that door problem just before aswell...

**Comment by aubinschneider13** [comment]
Exactly same issue

**Comment by hendrikNX** [comment]
Same here, did a direct to and then everything got unresponsive. No controls, ND display did not update position etc

**Comment by Ollix79** [comment]
It could be that i had the same Issue, after a direct. But also my VRAM ussage was very high. And when i Look around in the Cockpit it will be stutter so flicker.

**Comment by eLeoneTV** [comment]
Same problem

[https://youtu.be/9EnoKvUnEWM](url)

**Comment by Neonbear464** [comment]
https://drive.google.com/file/d/1AiVgvCbTMlOVr-R3I-2KqRXx48D3X8u2/view?usp=sharing

**Comment by Sleinmaster** [comment]
Video above was shared on request after the report on GitHub.

![Screenshot_20241111-212428](https://github.com/user-attachments/assets/ce831c5c-4579-4e96-be7b-1ded0e20664a)
