### ISSUE TITLE
RUNWAY TOO SHORT, Airbone

### ISSUE THREAD

**Issue by Hoseboxxx** [flybywiresim/aircraft#9217]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

Runway too short after takeoff and retracing gear at 300 ft

### Expected behavior

Shouldnt say runway short and continue flying without warning

### Steps to reproduce

1. Pushback with engine 2 and 3 starting
2. Start engine 1 and 4 after 2&3 started
3. taxi as usual
4. Set flex temp 66+ temp
5. Takeoff at OUTPUTS:
   FLAPS         1     V1          132
   THRUST     FLEX     VR          138
   SEL TEMP     66     V2          147
Then rotate and gear up at 300Ft
then runway too short will sound shortly after retracting.

### Discord Username (optional)

fly.ho

**Comment by flogross89** [comment]
Fixed by #9355
