### ISSUE TITLE
Doors Opening inflight 

### ISSUE THREAD

**Issue by AirPlaneBoy506** [flybywiresim/aircraft#9218]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

it happens when you go to the doors page on the efb and they all open\.

### Expected behavior

I would think that they stay closed

### Steps to reproduce

1.Need to be inflight/ Cruising 
2. Open the doors page on the EFB all doors should open
3. if you close the doors page and reopen it then the doors should close

**Comment by Beedan1G** [comment]
Can confirm that it does the same for myself during my cruise inflight currently going from Dubai to Casablanca

**Comment by frankkopp** [comment]
Can't reproduce - please test without any other folders in Community / turn off thing like GSX etc.

**Comment by JasonO99** [comment]
Can somewhat reproduce this at least on my end with some erratic use of the EFB. The erratic behaviour perhaps increases the chance of it happening as there doesn't appear to be any consistency with it. I'm running a fairly good FPS (80+), so not sure if lower FPS systems are more prone to it occurring. 

I can make it happen by changing ground service pages sometimes. I can make it happen by clicking about the other page buttons sometimes, I can make it happen by holding my mouse down and shaking it on a blank page of the door page, sometimes. All very rare.

I can increase the rate of which I can reproduce it when simrate is higher - not sure if coincidence or not.

Video in QA channel - https://discord.com/channels/738864299392630914/1193615390861951086/1301678904213508196

**Comment by Ollix79** [comment]
No video but i can confirm it after a crash of the EFB in Flight the doors will be open. And the Cabin Altitude was 30000ft

**Comment by JasonO99** [comment]
Further notes;
- Yet to reproduce on the ground, despite best efforts. Seems the logic that's contributing to the issue only applies in the sky. 
- Seems to be that once you trigger it once, it seems possible to reproduce it even easier? Got to a point I could reproduce it by switching slowly between ground services and fuel page, ten times in a row. The very first time isn't so easy to initiate it.

**Comment by Generic-Jim** [comment]
Has happened on the ground, don’t know if it can be replicated because I was too busy rage quitting. I had toolbar pushback and GSX on. For me, just front two entry doors open, won’t stay closed when I click the button, also all cargo doors stuck open, I made sure I had everything disconnected through toolbar pushback.

**Comment by 2hwk** [comment]
Note that at this time this is a suspected to be a memory leak issue linked with the flyPad.

**Comment by Mike230296** [comment]
same here open when inflight  
![Microsoft Flight Simulator 01_11_2024 06_10_02](https://github.com/user-attachments/assets/b55b2734-1d5d-46e9-be7f-121141a37ba6)
![Microsoft Flight Simulator 01_11_2024 06_10_59](https://github.com/user-attachments/assets/a1bf323a-7a73-4ca8-8878-a9aaa6fb3372)

**Comment by 2hwk** [comment]
Note that the doors being left open eventually leads to a WASM crash due to a 2nd bug that is triggered in the cabin pressurization system.

**Comment by jernejrostan** [comment]
Now i know why I lost all controls today mid flight. could not even recover controls
