### ISSUE TITLE
A/THR does not respect commanded thrust output value

### ISSUE THREAD

**Issue by VATNZ-MR** [flybywiresim/aircraft#9224]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

when Autothrottle is set to LVR CLB the thrust output far exceeds the limits on the upper ECAM and climbs at a much higher rate than normal as a result.

### Expected behavior

Thrust output should not exceed the % amount on the ECAM and should respect the limits of the A/THR system

### Steps to reproduce

1. Load into the aircraft either on the runway or at the gate
2. Perform a normal takeoff with either FLEX or TOGA A/THR thrust settings
3. When commanded, move thrust levers to LVR CLB
4. Observe ECAM and observe thrust output value much higher than commanded
5. Continue to observe throughout CLB and CRUISE

### References (optional)

![image](https://github.com/user-attachments/assets/d911ba60-c82c-41aa-85bd-6db086ed846d)
![image](https://github.com/user-attachments/assets/36d2ec69-7bf8-4751-8ec0-4c5df405a30d)

**Comment by Maximilian-Reuter** [comment]
this is a bug, but not the one you mean. Currently we arent showing a THR Limit on the top of the EWD but a N1 Limit just like on the a32nx so it is working correctly just not how it really is in the real aircraft.
