### ISSUE TITLE
Airport map doesnt work on ND as shown in the trailer.

### ISSUE THREAD

**Issue by 18simpsona** [flybywiresim/aircraft#9228]
### Aircraft Version

Development

### Build info

```json
0.12.0
```

### Describe the bug

zooming in on the ND doesnt produce the map, it instead says not avail.

### Expected behavior

zooming in on the ND should show the airport map as shown in the trailer.

### Steps to reproduce

zoom in on the map. the ND will say not avail.

**Comment by eliasseverholt** [comment]
Have you connected your navigraph account in the EFB?

**Comment by Maximilian-Reuter** [comment]
This doesnt sound like a bug but rather that you are either not connected to your Navigraph account or you dont have an Ultimate subscription. If that is not the case then please reopen this issue.
