### ISSUE TITLE
GPU shows avail after disconnected

### ISSUE THREAD

**Issue by austinwilkins1** [flybywiresim/aircraft#9229]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T14:33:02+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "f26029363ad3edeeafbed20aa79c13b32c8090f8",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-HEAD.f260293"
}
```

### Describe the bug

GPU still shows available after being disconnected preparing for pushback

### Expected behavior

AVAIL lights should disappear

### Steps to reproduce

Connect GPU, program plane, start APU, disconnect GPU once APU power established

### Additional info (optional)

https://gyazo.com/c8822358185f64252b91833534a70199

https://gyazo.com/b13ab51a70856683136f61aee8103bc8

### Discord Username (optional)

adubsatc

**Comment by austinwilkins1** [comment]
Edit - went away after about 2 minutes in to the pushback cycle

**Comment by Maximilian-Reuter** [comment]
This is currently expected as we use the msfs definition of external power being available and MSFS defines that just as being in the parking spot which has power

**Comment by austinwilkins1** [comment]
Ok, thanks for the clarification.
