### ISSUE TITLE
[A380X] Graphicscard run out of Memory

### ISSUE THREAD

**Issue by Ollix79** [flybywiresim/aircraft#9234]
### Aircraft Version

Development

### Build info

```json
BUILD v.0.12.0 Stable 4K
Load 31.10.24
```

### Describe the bug

On first Flight my Grapiccard runs out of Memory after 1h+ Flying, i saw that anyting was wrong that when i look arroung in Cokpit it stutters an Fliker. The i look on memory Use of my RTX 3090 an saw that 23,4GB of 24 GB was in Use. The A380 also dont follow the Flightplan after i saw the max use om Memory and don't react off any Joystick input.

### Expected behavior

Could it be a problem with OANS that the GPU runs out of Memory ?

### Steps to reproduce

for the moment I have no idea how i can encountered this issue.

### Additional info (optional)

This problem i had with no other MSFS2020 Plane

### Discord Username (optional)

[MUC076]Olli

**Comment by Ollix79** [comment]
I had this Problem never before with any other Plane in MSFS 2020. I will do a Second test.

**Comment by jason5545** [comment]
Just make sure the texture settings, I got vram OOM with Ultra.

**Comment by Ani5z** [comment]
Yeah but that's bollocks anyways on 4k

**Comment by alepouna** [comment]
Please note of our [Minimum, Recommended and High Requirements Section](https://flybywiresim.com/notams/a380x-full-speed-ahead/#expectations-for-end-users) section on our release NOTAM. If you are running out of VRAM, you will need to reduce the texture settings and/or use the 4K texture pack. Closing this issue as this is expected. 

If you still have crashes or other issues, we recommend you try to reach out via our Discord Server first (https://discord.gg/flybywire) and reach out to our support channels! It will allow for easier communication and hopefully resolve the issue.
