### ISSUE TITLE
STD Baro knob

### ISSUE THREAD

**Issue by layth2310** [flybywiresim/aircraft#9239]
### Aircraft Version

Development

### Build info

```json
v0.12.0
```

### Describe the bug

When setting standard I have to pull the baro knob

### Expected behavior

On the 380/350 aircraft irl it is push for STD

### Steps to reproduce

try setting STD

### Discord Username (optional)

l23

**Comment by Steveveepee** [comment]
Confirmed as operation is incorrect

**Comment by danestfanous** [comment]
I'm working on this.
