### ISSUE TITLE
BTV not slowing down to 10kts

### ISSUE THREAD

**Issue by dennisko762** [flybywiresim/aircraft#9241]
### Aircraft Version

Development

### Build info

```json
"built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

Btv is selected and armed (BTV blue). After landing, FMA shows BTV. The btv does not slow down to arrive at the selected taxiway with 10kts but continues to overshoot the runway.

https://github.com/user-attachments/assets/f6f467c0-3aa7-4d76-86d0-53df3fdadfb9

### Expected behavior

After landing btv should activate and at a certain distance from the exit point, slow down to 10 kts as described per docs.

### Steps to reproduce

1. For your arrival airport, in the OANS select the runway and exit point
2. Put the autobrake to btv
3. verify btv blue in FMA
4. Land either manually or using autoland and monitor btv being active in the FMA with decel

### Additional info (optional)

I went on to debug the problem a little bit and discovered that the LVAR A32NX_OANS_BTV_REMAINING_DIST_TO_EXIT does not get updated.
For reference: At EDDP for RWY 26L with S4 selected as exit point, the value is always 14047249408.000 while the A32NX_OANS_BTV_REQ_STOPPING_DISTANCE is actually only 14043751424.000.

### Discord Username (optional)
dennis762

**Comment by dennisko762** [comment]
@flogross89 I found the problem:
`  if (this.props.side === 'L') {
      this.btvUtils.updateRemainingDistances(this.projectedPpos);
      this.btvUtils.updateRwyAheadAdvisory(
        this.ppos,
        this.arpCoordinates,
        this.planeTrueHeading.get(),
        this.layerFeatures[2]
      );
    }
`
Its the efis side that matters. All people are flying it from the left and Im the only guy that has always been flying from the right.
But the code says it only works from the LEFT, EFIS Side needs to be left.
So if i set up btv on the right, the updateRemainingDistanceToExit() is never called!!!!

**Comment by flogross89** [comment]
> @flogross89 I found the problem: ` if (this.props.side === 'L') { this.btvUtils.updateRemainingDistances(this.projectedPpos); this.btvUtils.updateRwyAheadAdvisory( this.ppos, this.arpCoordinates, this.planeTrueHeading.get(), this.layerFeatures[2] ); }` Its the efis side that matters. All people are flying it from the left and Im the only guy that has always been flying from the right. But the code says it only works from the LEFT, EFIS Side needs to be left. So if i set up btv on the right, the updateRemainingDistanceToExit() is never called!!!!

Good find, thank you for looking into it! Should be an easy fix

**Comment by dennisko762** [comment]
> > @flogross89 I found the problem: ` if (this.props.side === 'L') { this.btvUtils.updateRemainingDistances(this.projectedPpos); this.btvUtils.updateRwyAheadAdvisory( this.ppos, this.arpCoordinates, this.planeTrueHeading.get(), this.layerFeatures[2] ); }` Its the efis side that matters. All people are flying it from the left and Im the only guy that has always been flying from the right. But the code says it only works from the LEFT, EFIS Side needs to be left. So if i set up btv on the right, the updateRemainingDistanceToExit() is never called!!!!
> 
> Good find, thank you for looking into it! Should be an easy fix

Youre welcome. I was so eager to debug it that i spend 2 nights until 5am on this haha. But was fun. A bit like my first "contribution"

**Comment by dennisko762** [comment]
> > > > @flogross89 I found the problem: ` if (this.props.side === 'L') { this.btvUtils.updateRemainingDistances(this.projectedPpos); this.btvUtils.updateRwyAheadAdvisory( this.ppos, this.arpCoordinates, this.planeTrueHeading.get(), this.layerFeatures[2] ); }` Its the efis side that matters. All people are flying it from the left and Im the only guy that has always been flying from the right. But the code says it only works from the LEFT, EFIS Side needs to be left. So if i set up btv on the right, the updateRemainingDistanceToExit() is never called!!!!
> > > 
> > > 
> > > Good find, thank you for looking into it! Should be an easy fix
> > 
> > 
> > Youre welcome. I was so eager to debug it that i spend 2 nights until 5am on this haha. But was fun. A bit like my first "contribution"
> 
> Do you want to give the potential fix a try? You can download the package at https://github.com/flybywiresim/aircraft/actions/runs/11694412300 (PR --> Checks --> PR Tests& Build)

Yes, will do that today, thank you

**Comment by flogross89** [comment]
> > > > > @flogross89 I found the problem: ` if (this.props.side === 'L') { this.btvUtils.updateRemainingDistances(this.projectedPpos); this.btvUtils.updateRwyAheadAdvisory( this.ppos, this.arpCoordinates, this.planeTrueHeading.get(), this.layerFeatures[2] ); }` Its the efis side that matters. All people are flying it from the left and Im the only guy that has always been flying from the right. But the code says it only works from the LEFT, EFIS Side needs to be left. So if i set up btv on the right, the updateRemainingDistanceToExit() is never called!!!!
> > > > 
> > > > 
> > > > Good find, thank you for looking into it! Should be an easy fix
> > > 
> > > 
> > > Youre welcome. I was so eager to debug it that i spend 2 nights until 5am on this haha. But was fun. A bit like my first "contribution"
> > 
> > 
> > Do you want to give the potential fix a try? You can download the package at https://github.com/flybywiresim/aircraft/actions/runs/11694412300 (PR --> Checks --> PR Tests& Build)
> 
> Yes, will do that today, thank you

Thank you! See https://github.com/flybywiresim/aircraft/pull/9355#issuecomment-2463097033

**Comment by flogross89** [comment]
> @flogross89 So far so good. Thanks for taking care of it. Tested in LEPA rwy 24R with dry and wet conditions and in EHAM, works well.
> 
> One thing i noticed that I didnt have ever before, unrelated to this isseue, is flashing hdg/nav and VS in FMA and FCU when turning off AP while fd is still on. I cant get my video to be less than 10MB, maybe i can put it on discord or open a new issue.

Thanks! A video of that certainly sounds interesting, if you can reproduce it please open a separate issue for this
