### ISSUE TITLE
Help after takeoff, i pitch up regularly, and the plane stalls itself. Here's Swiss001 experiencing this https://www.youtube.com/watch?v=lHUuuHiEWxg (fast forward to 7:36)

### ISSUE THREAD

**Issue by xpomarker27** [flybywiresim/aircraft#9248]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:50:20+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

Plane pitches up uncontrollably, can't pitch down past-20%

### Expected behavior

The plane being controllable

### Steps to reproduce

Take off

### Discord Username (optional)

xpomarker27

**Comment by alepouna** [comment]
This is a known issue with the engine performance, it's been locked on. I will go ahead and close this issue as we are creating a meta issue for it
