### ISSUE TITLE
ND range change automactically when switching ND mode.

### ISSUE THREAD

**Issue by kowinleung** [flybywiresim/aircraft#9263]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

Switching ND mode from ARC to other ND mode (plan, nav, vor, ls) will increase range automactically. If the range is changed manually in other ND mode, switching to ARC mode will decrease the range.

### Expected behavior

Range should not be changed automactically when switching ND mode.

### Steps to reproduce

1. Set any range on the ND when on ARC mode
2. Switch ND display mode
3. The range will automactically increase by one selection
4. Switch to any ND mode other than ARC mode
5. Select a range manually
6. Change back to ARC mode
7. The range will decrease by one selection

### References (optional)

https://youtu.be/Ee7LTB9CFm4?si=b3LwaMXhHSmVZzU0

### Discord Username (optional)

super6u0

**Comment by BravoMike99** [comment]
That is a feature and not a bug 😛 . 
From the FCOM: "If the flight crew changes ND mode from ARC to one of the ROSE or PLAN modes, the ND range
automatically increases to the next value. Therefore, the distance in front of the aircraft mock-up
remains the same. If the flight crew changes ND mode to ARC mode, the ND range automatically
decreases to the previous range value."
