### ISSUE TITLE
Flypad is not responding the touch event

### ISSUE THREAD

**Issue by cqhhy2001** [flybywiresim/aircraft#9265]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

When entering the flight for the first time, the left navigation bar of Flypad does not respond to touch events

### Expected behavior

Switch pages according to the specific content of the navigation bar

### Steps to reproduce

Enter the game normally and start Flypad

### References (optional)

After restarting the MSFS everything is fine
In game restart can't solve this problem

### Additional info (optional)

After restarting the MSFS everything is fine
In game restart can't slove this problem

**Comment by kammy755** [comment]
I have the same issue, it seems that sometimes pressing CTRL helps to resolve the problem.
