### ISSUE TITLE
PERF Page some feature blank

### ISSUE THREAD

**Issue by GLF6** [flybywiresim/aircraft#9266]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

On MCDU performance page, select options such as Flaps, THS FOR, packs, etc. disappear and are not visible

In the beginning, FLAPS, THS FOR/PACS ANTI ICE etc. are displayed normally, but when the F-PLN selects the runway at the departure airport, the item disappears

### Expected behavior

As normal, these options should be enabled, not blank

### Steps to reproduce

1. Cold and Dark cockpit flow
2. Imported Simbrief information from EFB (I plan EGLL>EGLL test flight)
3. Importing Simbrief information from MCDU INIT
4. In F-PLN, select EGLL RWY 27L SID GOGS2G and insert
5. Enter values such as ZFW, block, etc. in Fuel & Load
6. Items in Flaps, THS FOR, PACKS, ANTI ICE are blank on the PERF page in question

### References (optional)

![dasda](https://github.com/user-attachments/assets/7436df3a-fce8-4489-957a-432358023c15)

### Discord Username (optional)

monflex

**Comment by ungenickt-de** [comment]
Can confirm this.

**Comment by stefanodat** [comment]
Can confirm - looked at both MCDU screens to see if it was replicated there.
![Perf Page](https://github.com/user-attachments/assets/66d3be49-50b3-4737-8360-e31bf3ddc70a)
