### ISSUE TITLE
Unrecoverable stall + flight controls frozen during takeoff 

### ISSUE THREAD

**Issue by aadee9940** [flybywiresim/aircraft#9269]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

Takeoff at any gross weight and if you pitch up to anything above 10-12 degrees, it will start to pitch up by itself. You cannot stop this behavior as it seems like the flight controls are frozen once you enter the amber speed protection range or sometimes it pops up if you exceed 17 degrees pitch up. 

Because the flight controls are frozen. you cannot use standard stall recovery to save yourself. The plane will not respond to nose down inputs nor roll inputs. 

The stall at low altitude just means you have no option but to crash. 

### Expected behavior

Expected behavior is before a stall, your flight controls should still respond to the inputs as there is enough airflow going past them  given your airspeed isn't terribly low. The plane should pitch down and start to gain airspeed but that does not happen. 

### Steps to reproduce

1. Takeoff at any gross weight 
2. Pitch up to 13-15 degrees and observe 
3. The plane will keep pitching up by itself and eventually put you in a stall. 

### References (optional)

![image](https://github.com/user-attachments/assets/5afc282d-159f-4a29-89c5-7ed5f1223bcb)

### Additional info (optional)

I have found a workaround for this, given you have enough altitude to recover from the insane nose up attitude. 
1. Full throttle
2. Turn off PRIM 1
3. Turn off SEC 1
4. Turn off PRIM 3
5. Turn off SEC 3
6. Pitch down

I am not a master at Airbus theory, but the turned off Flight control computers should drop you down to alternate law. This change to alternate law seems to reset the elevator, in the sense that it recovers from its jammed pitch state, and the aircraft will respond to any nose down inputs that you give it. After you have recovered and gained enough airspeed, you can turn all the flight computers back on. 

### Discord Username (optional)

banjigaming99

**Comment by Atonium83** [comment]
Same for me, right after each takeoff...

**Comment by IntegrierterKurde** [comment]
Also have the problem!

**Comment by jakestopher** [comment]
Same issue for me, also right after takeoff

**Comment by jakestopher** [comment]
https://www.swisstransfer.com/d/ad8add9b-f55d-4f28-abaf-882915c94da6

This is my FDR file from the flight where I experienced this issue

**Comment by pascalgrotzke** [comment]
Had the same issue. It was hard to recover.

**Comment by marbleflower** [comment]
Same issue here, I thought it was because I had FD off on takeoff and enabled autothrust after taking off that I kept crashing until the same thing happened to me with FD on, interesting to know it's because of the takeoff pitch angle.

**Comment by flogross89** [comment]
Reopen, needs rework

**Comment by JasonO99** [comment]
Using 0.12.3 I have found if you retract flaps/slats quickly after passing S speed, while in an open climb, the aircraft continues to climb and feels happy to hold the pitch it does, except will then drop speed down to alpha protection. 

Banking the aircraft under 200 knots generally causes the alpha protection to shoot up the speed tape if flaps retracted making the issue much worse. Alpha protection can be higher than green dot speed.

![18084af80df5f605f85fdc2391f5aa56](https://github.com/user-attachments/assets/78de737c-5650-490d-8689-8ef4c6a7eba7)

**Comment by Mart-320** [comment]
I confirm, this bug is still present in A380X v0.12.3
I hope this gets sorted soon.
