### ISSUE TITLE
Defueling from flypad when GSX Synced does the opposite in the aircraft (FOB goes up)

### ISSUE THREAD

**Issue by Guerckan** [flybywiresim/aircraft#9274]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

By default the aircraft loads up in the sim with 100+t of fuel.
On a short flight block fuel can be less than that and thus defueling is needed.

When GSX synced, after starting defueling from the flypad (when the gsx truck is in place) the FOB in the aircraft can be seen going up instead of down.

### Expected behavior

FOB in the aircraft should be going down when defueling.

### Steps to reproduce

1. Plan for a short flight (ie. LFPG-EGLL)
2. Load flight plan in flypad
3. Make sure flypad is GSX synced for fueling
4. Call refueling truck via GSX interface
5. When prompted by GSX start defueling from flypad
6. FOB goes up instead of down in the aircraft.

**Comment by fastsubalpha** [comment]
i dont use GSX but in cannot refuel and defuel from the EFB, whatever fuel value the sim loads by default remains.

**Comment by CvzImTom** [comment]
Can confirm this for me too. On a short flight (EDDM-EDDF for example), gsx loads fuel instead of dumping it. It seems like it loads the actual block fuel amount, disregarding the fact that it needs to dump fuel in order to achieve the block fuel.

**Comment by JasonO99** [comment]
There are some other issues around fuelling, but GSX does not support defueling, so you'll never see this working - it only ever checks for positive changes in the fuel level, so won't see the defueling through.

**Comment by Guerckan** [comment]
I will go ahead and close this issue since it does not seem to be particularly linked or limited to GSX usage as other issues opened seem to indicate.
Plus it seems that initial fuel levels are being addressed in a pre-existing PR ( https://github.com/flybywiresim/aircraft/pull/9397 ) anyway which should prevent this situation from happening in the first place.

Thanks to anybody involved for this amazing aircraft and all the work that went into it !
