### ISSUE TITLE
Cockpit window opens when clicking EFB

### ISSUE THREAD

**Issue by KejuBartin** [flybywiresim/aircraft#9279]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:50:20+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

When clicking the EFB in the position above the green part of the window handle, the cockpit window opens, even in flight.

### Expected behavior

The window should not open when operating the EFB. It should only open when specifically clicking the handle.

### Steps to reproduce

Click the EFB in an empty spot (so there shouldn't be any button) above the green part of the window handle and the window will open.

### References (optional)

https://github.com/user-attachments/assets/24e36854-1c8f-408e-a00a-e7509af156f4

### Additional info (optional)

Sometimes it is hard to find the exact spot where the window opens, but it happened to me a few times when I didn't try to reproduce the problem.

### Discord Username (optional)

mr_allyt

**Comment by Guerckan** [comment]
Happened to me as well, more specifically the clickspot was in the bottom left of the EFB around the cog wheel in my case.
