### ISSUE TITLE
Implement METOTS system for A380X

### ISSUE THREAD

**Issue by Tankman61** [flybywiresim/aircraft#9283]
### Aircraft Version

Stable

### Description

When taking off, the FADEC limits the maximum thrust of the engines to 78% N1 until speed is above 35 knots to prevent flutter on the engine's front fan blades.

### References (optional)

https://www.youtube.com/watch?v=8d5q-J6ZEwo

### Additional info (optional)

I would like to help work on and implement such a system into the aircraft. Please contact me on discord if you're working on the engine model, I'd love to collaborate.

### Discord Username (optional)

tankman69

**Comment by MicahBCode** [comment]
RR engines only

**Comment by Tankman61** [comment]
Yes, I thought the A380X uses the Trent 900 in game

**Comment by MicahBCode** [comment]
> Yes, I thought the A380X uses the Trent 900 in game

Yes, it does. Comment is just for documentary purposes. ;)

**Comment by cptnuss-ops** [comment]
I would add this feature to the EngineControl class of the A380? This seems to be the FADEC implementation. As I understand during T/O with TOGA or FLX and below 35 knots the FADEC would limit until the conditions are not met anymore. If that fits for you, I'd like to start with the very basic implementation and give it a try.

**Comment by Tankman61** [comment]
Yes. I'm going to try that over this weekend and make a PR

**Comment by cptnuss-ops** [comment]
Ah, okay.

**Comment by alepouna** [comment]
> Yes. I'm going to try that over this weekend and make a PR. Could someone assign me to the issue?

Done! Thank you 😃

**Comment by Manuel-Lahak** [comment]
any updates lads?

**Comment by cptnuss-ops** [comment]
I'll push my changes and you guys can have a look. I've the feeling, it's to simply...

**Comment by Manuel-Lahak** [comment]
> I'll push my changes and you guys can have a look. I've the feeling, it's too simple...

Apologies if this seems like a basic question, but how can I merge these lines into my aircraft's location inside MSFS? I tried searching for information but couldn't find anything.

**Comment by Tankman61** [comment]
https://www.youtube.com/watch?v=7pX9hxn-cmE - found a somewhat better video of METOTS in action with a cockpit view (though still incredibly blurry). Will also check out the new implementation
