### ISSUE TITLE
EFB touch events trigger on secondary monitor

### ISSUE THREAD

**Issue by ShiforGitHub222** [flybywiresim/aircraft#9289]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

When the EFB is positioned partially off-screen on the main monitor, clicking in the bottom right corner of a secondary monitor unintentionally triggers the EFB’s functions. This occurs even though the EFB is only partially visible on the main monitor and not visible at all on the secondary monitor.

### Expected behavior

The EFB should only respond to clicks that occur within its visible area on the main monitor, ignoring clicks from other monitors.

### Steps to reproduce

1. Have two or more monitors
2. Go to default cockpit view and zoom out enough to have the EFB partially visible
3. Power off EFB 
4. Click in the bottom right corner of the secondary monitor, aligned with where the EFB would appear if extended across multiple screens.
5. Observe the EFB turning on

https://github.com/user-attachments/assets/13b3186a-c7bb-4372-b445-a0c4b6e50ce4

### References (optional)

https://github.com/user-attachments/assets/13b3186a-c7bb-4372-b445-a0c4b6e50ce4

### Discord Username (optional)

Shifor

**Comment by tracernz** [comment]
This is not something we have any control over. Please raise with Microsoft.
