### ISSUE TITLE
EFB - Can't switch back to Main Deck view after switching from Main to Upper Deck display in Ground Payload menu 

### ISSUE THREAD

**Issue by ShiforGitHub222** [flybywiresim/aircraft#9290]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

In the EFB Ground Payload menu, if you switch from the Main deck view to the Upper deck view, clicking the Main button does nothing. 

To view the Main deck again, an EFB restart is required.

### Expected behavior

When clicking Upper, I should be able to click Main and view the Main deck again.

### Steps to reproduce

1. Turn on EFB
2. Go to Ground > Payload
3. Click Upper
4. Click Main
5. Observe Main deck view does not show

### References (optional)

https://github.com/user-attachments/assets/aa75b0bb-09e3-4623-876a-9af4fcdefa22

### Discord Username (optional)

Shifor

**Comment by git-user16** [comment]
The issue appears to be with the click-spot of the window handle. For now, try moving your camera a bit and then clicking it.

Similar to #9279

**Comment by Benjozork** [comment]
Closing in favor of #9279
