### ISSUE TITLE
A380X - Sim Rate Selector in EFB

### ISSUE THREAD

**Issue by OscarP-380X** [flybywiresim/aircraft#9293]
### Aircraft Version

Stable

### Description

If we could have a tab in the EFB for a sim rate selector for the A380X (I couldn't find the feature request for the A380.)

### References (optional)

Like the PMDG 777
![Uploading anyone-tried-out-the-time-compression-yet-its-such-a-cool-v0-6qs8xwjlts8d1.png…]()

### Discord Username (optional)

oscar.pearson

**Comment by ungenickt-de** [comment]
Hi, its already in!

![image](https://github.com/user-attachments/assets/d37cb21d-0c74-4554-8a62-f803da30d43d)
![image](https://github.com/user-attachments/assets/73739e30-189f-4d87-85b8-326be46a8cc1)

**Comment by git-user16** [comment]
There is one implemented already! On the EFB, click on the gear icon (at the top right) and you should see it there.

![image](https://github.com/user-attachments/assets/a30e879c-4cac-4fd0-adbd-34de1da7c190)

**Comment by OscarP-380X** [comment]
Haha thank you I obviously didn't look hard enough, Thanks :)
