### ISSUE TITLE
Default Cockpit camera not in correct position

### ISSUE THREAD

**Issue by CvzImTom** [flybywiresim/aircraft#9294]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

When starting the flight, the default cockpit view is not correctly placed (too far down and too far left), and when pressing the "Reset Cockpit View" keybind, it goes to the same position.

### Expected behavior

It should be placed according to the Captains seat position and to the red/white dots. (See attached image for correct position)

### Steps to reproduce

1. Enter cockpit camera
2. Press "Reset Cockpit View" Keybind

### References (optional)

Two pictures, one the default position and the other the correct one.

**Correct**
![20241101225512_1](https://github.com/user-attachments/assets/f70d8b0a-fa7b-43a9-b732-e805dd96206d)

**Incorrect (Default cockpit view)**
![20241101225443_1](https://github.com/user-attachments/assets/c5db01de-d8c5-4bf1-a38e-5eb75a259d38)

### Additional info (optional)

I know that you are able to save a new custom camera position, but it's more practical to have it set correctly by default.

### Discord Username (optional)

cvzimtom

**Comment by ungenickt-de** [comment]
Can't reproduce this. The default view is like the one on your first picture. This is an issue on your site, maybe you have set a new view by accident with a hotkey?

**Comment by CvzImTom** [comment]
> Can't reproduce this. The default view is like the one on your first picture. This is an issue on your site, maybe you have set a new view by accident with a hotkey?

It can't be a custom view for me, I already tried resetting every view possible with the keybinds. It's really what the default views are for me, don't know why. This problem is not present in any other aircraft.

**Comment by CvzImTom** [comment]
Fixed the issue. It was not the aircraft's fault, but some messed up values in the Camera settings that I have never seen before.
