### ISSUE TITLE
Unable to edit or add Altitude Constraints to waypoints

### ISSUE THREAD

**Issue by Brad1511** [flybywiresim/aircraft#9297]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

Unable to edit constraints that are added automatically on STAR's. In a lot of cases you might be told to decent to a flight level above what is published on the charts because of Transition Layers etc. For example FL80 instead of FL70.
It allows you to type them in but no way of confirming and inserting it. 
![Screenshot_1](https://github.com/user-attachments/assets/510fdc0b-1775-4fd0-acca-43465e399e1b)
![Screenshot_2](https://github.com/user-attachments/assets/07d5a432-3b28-4d70-87b9-b7d6ab3c2aab)
![Screenshot_3](https://github.com/user-attachments/assets/27b98e93-0d30-4563-bd15-9d870b90badd)

### Expected behavior

You should be able to edit any constraint as ATC can give you instructions that differ from the published charts.

### Steps to reproduce

1. Insert any STAR that has Altitude Constraints
2. Attempt to edit an Altitude Constraint
3. Unable to progress any further with the edit

### Additional info (optional)

Sorry if it's already been flagged up, couldn't see it on the issues

### Discord Username (optional)

#15.11

**Comment by Goritoo11** [comment]
Sorry for the last line meant 1024p not 1080p and 2k is 2048 and so on

**Comment by Maximilian-Reuter** [comment]
I have seen reports that ALT contraints on ANY waypoint are inop

**Comment by rajagopalvenkat** [comment]
ALT constraints being INOP seems to be the case, when trying to add a constraint to a waypoint not on a SID/STAR, I get a message saying "ALT CSTR NOT ALLOWED AT _____".
