### ISSUE TITLE
Flaps 1+F instead of Flaps 1 on approach

### ISSUE THREAD

**Issue by TheFl4me** [flybywiresim/aircraft#9315]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

When extending the flaps inflight by selecting Flaps 1 from Flaps zero, the Flaps extend to Flaps 1+F.

### Expected behavior

When extending the flaps inflight by selecting Flaps 1 from Flaps zero, only the leading edge flaps should deploy to position Flaps 1, not Flaps 1+F.

### Steps to reproduce

Select Flaps 1 from Flaps 0 while inflight.

**Comment by geninguillaume** [comment]
according to A380 FCOM:

1. slats/flaps configurations:
- flap 1 conf = 1 (slats only) on holding or speed <263 kt
- 3. flap 1 = 1+F on takeoff/landing phases, if speed <222 kt

2. slats/flaps extension/retraction:
AES (automatic extension system) will go from flap 1 to flaps 1+F when speed <205 kt and flaps 1 already selected.

**Comment by chinjh93** [comment]
A380 and A350 flaps will come down on 1+f unlike the A320/A330/A340 where only the slats are extended unless it is extended to config 2 during approach.

**Comment by r-ctr** [comment]
![Capture d’écran 2024-11-04 à 15 17 33](https://github.com/user-attachments/assets/a8142ae1-93b0-4457-b800-4b73678c6864)

:)

**Comment by TheFl4me** [comment]
It would seem like I was mistaken
