### ISSUE TITLE
A380X report

### ISSUE THREAD

**Issue by ImNotSergej** [flybywiresim/aircraft#9316]
### Aircraft Version

Stable

### Description

Hi. I would like if you can add sim rate because when i change it doesn't go above 2x and it will eventually go back to 1x automatically. I know it's been inhibited for autopilot stability but in a 12 hour long-haul flight it would be very useful not to wait 12 hour real time to arrive to destination.
I also want to report some issues:
- A380X doesn't go above Mach 0.85 when the max speed is M 0.89
- Performance on takeoff seems a bit unrealistic, the aircraft appears overpowered
Thanks

### Discord Username (optional)

ImNotSergej

**Comment by CaptCrystal** [comment]
The developers are aware that the aircraft is overpowered. It is still in an alpha state, and the unique engine model has not been fully implemented yet. The engine model is actively being worked on.

**Comment by alepouna** [comment]
> Performance on takeoff seems a bit unrealistic, the aircraft appears overpowered

Known issue, #9254

**Comment by callie0923** [comment]
#9350 I have corrected the issue regarding cruise speed its due to the Drag Coefficient being to high at mach 0.853 or 0.854 the Change has been Pushed to into a Pull request we are just awaiting a response. Regarding the rest of the model overpowered the engines are clearly still very into development and will be corrected as time goes on to accurately reflect the Real life counterpart.

**Comment by ImNotSergej** [comment]
Thanks for sending the feedback to the developers. Just to clarify - the
cruise at M 0.85 is normal for an A380 but I was surprised that the
aircraft won't go any faster even at TOGA.
I would also be very glad if can you correct the locked sim rate because
since it's a long haul flight waiting 12+ hours it's a bit weird.
Thanks for everything
Sergio

Il Dom 3 Nov 2024, 05:10 MCampbell ***@***.***> ha scritto:

**Comment by Benjozork** [comment]
Thanks for your feedback - we only accept individual issue tickets for individual bugs on github. Please open tickets for individual issues if they don't already exist.
