### ISSUE TITLE
A380X/ND: OANS available without IRS position

### ISSUE THREAD

**Issue by BravoMike99** [flybywiresim/aircraft#9317]
### Aircraft Version

Development

### Build info

```json
master
```

### Describe the bug

OANS is available without IRS position:
![image](https://github.com/user-attachments/assets/9dde4f48-ab76-4ee1-af16-74a665577b8f)

### Expected behavior

OANS position should not be available if the on side ADIRS does not have a valid position. In this situation, the "ARPT NAV POS LOST" amber message should appear.
Captain side uses ADIRS1 while FO ADIRS2, however, it is possible to change the position data source to ADIRS3 to either side with the ATT HDG selector.

### Steps to reproduce

1) Spawn in with the IRS off and set the ND range to "ZOOM"

### Discord Username (optional)

bruno_pt99

**Comment by Nufflee** [comment]
Would like to take a look at this.
