### ISSUE TITLE
Baro Ref Presel Unit Bug

### ISSUE THREAD

**Issue by NickFarin** [flybywiresim/aircraft#9319]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

When preselecting the baro ref, the selector is in the hpa position, but the preselected unit is shown in inHg as it was the unit used before setting standard. The same vice-versa.

### Expected behavior

The preselected baro ref should match the unit selected.

### Steps to reproduce

1. Set standard after using hPa or inHg.
2. Change the selected unit to the opposite of what you just used.
3. Preselect a baro ref and find that a different unit than the selected is shown.

### References (optional)

![Screenshot (271)](https://github.com/user-attachments/assets/c8460c3f-8418-4477-a4b1-e7d57597dade)

**Comment by git-user16** [comment]
Similar to #9161 which is fixed and will be available in the next update

**Comment by tracernz** [comment]
Duplicate and already fixed as above.
