### ISSUE TITLE
Cabint Alt Alert

### ISSUE THREAD

**Issue by NekoliveGaming** [flybywiresim/aircraft#9326]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

I had a mishap happen where the 1L door got left open during departure, and it wassent before i was in criuse and had to deal with an ENG 1 Gearbox disconnect for the Hydralics that i realized my cabin altitude was 37 000 feet. I did not get any cabin alt alert what so ever and I'm pretty sure there's supposed to be one

### Expected behavior

Cabin Alt alert at around 9000-10000 feet cabin altitude

### Steps to reproduce

Just leave the front door open, take off and get up to ur crz alt. I did not see any cabin alt alert

### References (optional)

![image](https://github.com/user-attachments/assets/69cb790e-8935-4fd0-bd81-1aa999e4a2ad)

![image](https://github.com/user-attachments/assets/5b0f7385-c743-4fe4-9ef1-35c1f1fcf56c)

me trying to get the cabin alt back down again after manually closing the door with high pack flow and cross bleed on with not cabin altitude warning

### Discord Username (optional)

neko_4789

**Comment by BravoMike99** [comment]
This should be fixed in #9112

**Comment by NekoliveGaming** [comment]
Ah ok. I see it hassent been built and put on the installer or atleast the checks says so, i did have an update thou so im gonna check, if not ill download the updated file and test it manualy, and then ill come back and close if its fixed

**Comment by BravoMike99** [comment]
Yes, its not on the stable version yet. You can keep the issue open as it is and after the PR is merged it can be closed.
