### ISSUE TITLE
When moving ND mode changer the zoom sometimes moves

### ISSUE THREAD

**Issue by VeIocityy** [flybywiresim/aircraft#9331]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

When I move the ND mode changer it moves the range between 320nm-640nm.

### Expected behavior

For them to work independently and not affect each other.
https://gyazo.com/f32c34ee35215d4231366ad814bf4879

### Steps to reproduce

1. Start at 640nm
2. Move from ARC to PLAN mode.
3. Observe the zoom knob move to 340nm

### Discord Username (optional)

velocity.

**Comment by Pruznak** [comment]
I think this is expected - see #9263

**Comment by VeIocityy** [comment]
Sounds about right. Thanks!
