### ISSUE TITLE
Pause at Top of Descent does not work.

### ISSUE THREAD

**Issue by NitroByte** [flybywiresim/aircraft#9338]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

T/D Pause does not work.

### Expected behavior

The Flight should be paused when the T/D Pause switch in the EFB is activated.

### Steps to reproduce

Activate the T/D switch under Settings - Realism and fly past the Top of Descent.

**Comment by dsolesvik** [comment]
Getting this issue too. An MSFS window shows up saying it has been paused, but in reality the flight continues unpaused.

**Comment by 2hwk** [comment]
Not able to reproduce but #9517 might help
