### ISSUE TITLE
The communication radio with the airport ATC does not work

### ISSUE THREAD

**Issue by sergiolm85** [flybywiresim/aircraft#9339]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

With the plane at the airport, after starting the systems and entering the flight plan, when trying to request clearance from ATC through the radio menu, no communication option appears. Only the options for tune to ground, clearance, etc. appear, but clicking on the option does nothing.

On the other hand, indicating actions such as "Request taxi - departh whatever" does nothing.

![image](https://github.com/user-attachments/assets/cea83e95-2b87-4b2e-8c7b-3d288c6d7348)

### Expected behavior

It should be able to talk to ATC, and the actions listed in the menu should be executed.

### Steps to reproduce

1. Start a new flight at an airport (in my example LEBL)
2. Start the A380x aircraft systems and enter the flight plan by importing it from Simbrief.
3. Tune to Airport Clearance to request permission.
4. The action in point 3 does nothing, you cannot continue

**Comment by tracernz** [comment]
Do you have the the radio in rx and tx modes?

**Comment by jason5545** [comment]
Turn on VHF 1

**Comment by sergiolm85** [comment]
> Turn on VHF 1

I have VHF 1 turned on

**Comment by sergiolm85** [comment]
> Do you have the the radio in rx and tx modes?

how can I switch the radio mode to rx and tx? I'm looking for it in the RMP but I can't find it, thank you very much!!

**Comment by tracernz** [comment]
> > Do you have the the radio in rx and tx modes?
> 
> how can I switch the radio mode to rx and tx? I'm looking for it in the RMP but I can't find it, thank you very much!!

See VHF transmission and reception in https://docs.flybywiresim.com/pilots-corner/a380x/a380x-briefing/flight-deck/pedestal/rmp/

**Comment by sergiolm85** [comment]
I fixed it pressing this button, thank you very much for your help!!

![image](https://github.com/user-attachments/assets/349b2787-dd1e-481b-8231-4e7549f2a85e)
