### ISSUE TITLE
Aircraft begins to fly uncontrolable circles midflight

### ISSUE THREAD

**Issue by Viktor548** [flybywiresim/aircraft#9340]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

I was flying from Frankfurt to Abu Dhabi and everything went well until the A380 started to fly big circles in the rumanian airspace. All the displays showed that I was following the planned route and that I am flying the correct heading. Also the horizon was leveled. Only in the outside view you can see, that your flying a bit angled.
I was able to put a new direct into the flight computer but that did`t change the aircraft`s state in the air. Disconnecting the autopilot and flying manually didn`t help either. You can see how the sidestick is moving but the aircraft is not reacting to the inputs. The circles are not controlable and I had to abort the flight.

### Expected behavior

Because everything else of the flight went perfectly fine, I expected the aircraft to follow the route. There was absolutely no reason for this behavior of the aircraft.

### Steps to reproduce

1. Departing in EDDF
2. Using the autopilot
3. Following the planned route without any extras (e.g.: no direct by ATC)
4. Cruising at FL390
5. The bug came out of nowhere

**Comment by jakub738** [comment]
same issue

**Comment by PilotMathews** [comment]
I believe this issue is the same/related-to #9215 and #9341

What you describe is exactly what happened to me on my first flight...

**Comment by Maximilian-Reuter** [comment]
yes this sounds like a systems crash as such it is a duplicate
