### ISSUE TITLE
[A380] Add keybinds for ECAM C/L and Check buttons

### ISSUE THREAD

**Issue by julianpoma** [flybywiresim/aircraft#9344]
### Aircraft Version

Development

### Description

Add MSFS keybinds for the ECAM C/L and Check buttons. It would make it easier to perform the checklists on heavy workload environments.

**Comment by macieksoft** [comment]
Also adding keybing to ECAM clear button would be a nice thing.

**Comment by TazerXI** [comment]
Having click spots on the ECAM, similar to what the ATR has for checklists, would also be nice

**Comment by flogross89** [comment]
Can't add custom keybinds, but we are considering adding virtual soft keys, which can be enabled via the EFB

**Comment by julianpoma** [comment]
Thank you @flogross89, your implementation is a great solution!
