### ISSUE TITLE
Questions about A380X products

### ISSUE THREAD

**Issue by resfdjf** [flybywiresim/aircraft#9360]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-11-02T19:03:34+00:00",
    "ref": "refs/tags/v0.12.1",
    "sha": "2776100c286d3723826c62df36dc48207657d937",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.1",
    "version": "a380x-v0.12.1-rel.2776100"
}
```

### Describe the bug

Hello Flybywiresim developers. Here I will leave you with five questions about the Airbus A380:
1. When the aircraft just reaches the cruising altitude, the game crashes.
2. I cannot use the "double speed" function in EFB.
3. Hope the in-game frame rate issue can be improved.
4. The "LOGO Light" on the upper top panel cannot be used, and the "TCAS" system below cannot be opened and used.
5. Many buttons and texts in EFB have not been translated, and I hope they can be improved. Thanks! Wish the team good luck with the development!

### Expected behavior

1.When the aircraft just reaches the cruising altitude, the game crashes.
2. I cannot use the "double speed" function in EFB.

### Steps to reproduce

1. When the aircraft just reaches the cruising altitude, the game crashes.
2. I cannot use the "double speed" function in EFB.
3. Hope the in-game frame rate issue can be improved.
4. The "LOGO Light" on the upper top panel cannot be used, and the "TCAS" system below cannot be opened and used.
5. Many buttons and texts in EFB have not been translated, and I hope they can be improved. Thanks! Wish the team good luck with the development!

### References (optional)

[FBW_A380X_Checklist.pdf](https://github.com/user-attachments/files/17609845/FBW_A380X_Checklist.pdf)

**Comment by Benjozork** [comment]
Thanks for your feedback. Github issues must only be regarding a single issue. Please open tickets for the individual items (make sure tickets don't already exist).
