### ISSUE TITLE
OANS to work without Navigraph sub

### ISSUE THREAD

**Issue by Aryeh123is** [flybywiresim/aircraft#9361]
### Aircraft Version

Stable

### Description

To make OANS work for anyone who doesn't have a Navigrpah sub.

To make things easier, don't do every airport in the world as it would take too long but at least do some of the main A380 hubs (e.g. LHR, JFK, AUH, DXB etc).

NOTE: As of now, 140 airports are capable of the A380 in the world.

Thank you

**Comment by TazerXI** [comment]
I'd be very happy for this. At least maybe something like the 787 where you can get a zoomed in picture of the airport, and the ATR has a map that can show stand numbers. I imagine it is possible, or to at least get a trimmed down version of it, but I am not sure on how to do it/how much effort it would take.

**Comment by Aryeh123is** [comment]
Literally anything.

Also as you are landing, its quite hard to see which exit is which and if you get the wrong one, of which you put in the manual BTV and is suitable for an A380, without OANS, most times its not a suitable exit. So anything would be greatly appreciated

**Comment by flogross89** [comment]
Duplicate to #9133
