### ISSUE TITLE
Missing STARs in arrival planning

### ISSUE THREAD

**Issue by mattgogerly** [flybywiresim/aircraft#9363]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-11-02T19:03:13+00:00",
    "ref": "refs/tags/v0.12.1",
    "sha": "2776100c286d3723826c62df36dc48207657d937",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.1",
    "version": "a380x-v0.12.1-rel.2776100"
}
```

### Describe the bug

Flying in to WSSS (Singapore), selected runway and approach, STAR dropdown is greyed out. Choosing a via does not enable the dropdown.

### Expected behavior

Able to choose a STAR for the arrival.

### Steps to reproduce

1. Create SimBrief flight to WSSS
2. Load into sim and setup flight plan
3. Click WSSS in F-PLN
4. Click Arrival
5. Choose runway and approach
6. STAR is greyed out

### References (optional)

![image](https://github.com/user-attachments/assets/5773b433-c71d-4e40-bff7-a66bc9ee7e58)

### Discord Username (optional)

nothematic

**Comment by tracernz** [comment]
Which runways and procedures do you have available at the MSFS world map? If your desired procedures are not there it isn’t a bug with the plane, just likely outdated runway numbers in MSFS itself which we have no control over. In that case you may be able to improve the situation with a 3rd party scenery either from flightsim.to or a commercial vendor.

**Comment by Torellmania** [comment]
I did experience the same with the SID in aerosoft EDDB. There was a runway numbers change some weeks ago so there could be a correlation to the outdated runway numbers, which tracernz said.

**Comment by mattgogerly** [comment]
> Which runways and procedures do you have available at the MSFS world map? If your desired procedures are not there it isn’t a bug with the plane, just likely outdated runway numbers in MSFS itself which we have no control over. In that case you may be able to improve the situation with a 3rd party scenery either from flightsim.to or a commercial vendor.

Does the aircraft load from Navigraph, or MSFS? I checked in the MSFS DB and you're correct, the issue is the STARs are not there.

**Comment by mattgogerly** [comment]
So it appears the issue is as @tracernz said - MSFS has outdated runways, and for some unknown reason that means it then supresses *all* SIDs/STARs for that airport.
