### ISSUE TITLE
Move jetway positioning when docked to include opened aircraft door

### ISSUE THREAD

**Issue by CvzImTom** [flybywiresim/aircraft#9366]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-11-02T19:03:34+00:00",
    "ref": "refs/tags/v0.12.1",
    "sha": "2776100c286d3723826c62df36dc48207657d937",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.1",
    "version": "a380x-v0.12.1-rel.2776100"
}
```

### Describe the bug

Connecting the jetway is working perfectly fine, but the aircraft door is always outside of the connected jetway (I guess because it is very wide), and to the right of the door, there is so much empty space included in the jetway that makes me wonder if the jetway connection point can be moved further left. See reference pictures for visuals.

### Expected behavior

As said, everything works as expected, but moving it further left would look better and from the outside. Clearly this problem can't be solved for every jetway existing because they come in different forms and sizes, but the doors lurking out would be less frequent.

Maybe this also a sim limitation and can't be changed and only scenery devs can change the jetway connection, but I have no knowledge about that.

### Steps to reproduce

1. Connect the jetway and look how the door clips out of the jetway.

### References (optional)

**for example iniBuilds OMDB**
![20241102222713_1](https://github.com/user-attachments/assets/e7710806-94e1-4247-b89b-c50e0c4e105f)

**Comment by C-Schaffhausen** [comment]
I'd try to work on this tonight 🙋🏻‍♂️

**Comment by MjrIncident** [comment]
I used the deafault baggage and catering at heathrow - couldnt get a clean T.O readout but took off anyway.
5 mins into the flight I looked externally and saw the doors were still open.
Do I have to do the C/L to search for this and how do I close the doors?
