### ISSUE TITLE
The dashboard does not start

### ISSUE THREAD

**Issue by sergey2000122** [flybywiresim/aircraft#9367]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2024-11-03T12:50:11+00:00",
    "ref": "refs/heads/master",
    "sha": "9e9022a718255512a89e6f753ff9475be49cbf0d",
    "actor": "svengcz",
    "event_name": "manual",
    "pretty_release_name": "master:9e9022a7",
    "version": "a32nx-v0.13.0-dev.9e9022a"
}
```

### Describe the bug

The dashboard does not start, writes the problem: if you re seeing this,instrument didnt load

### Expected behavior

I was waiting for the electrical system and dashboard to start operating the aircraft, and when I pressed the power button on the overhead, I did not notice a reaction, the tablet did not work either
### Steps to reproduce

1-I loaded the plane at the airport
2-I went into the cockpit of the plane
3rd moved to the overhead 
4-I pressed exl pwr and pressed bat1 and bat2 to turn on the power supply to the aircraft
5-I noticed that the plane did not respond to these commands, that is, the buttons were not lit and the dashboard also did not turn on

### References (optional)

![2024-11-03_17-55-17](https://github.com/user-attachments/assets/fcdd1382-a2e8-41ca-8e3a-a1804d8fff53)
![2024-11-03_17-54-24](https://github.com/user-attachments/assets/fb8da432-36cc-42ee-92a1-35d65e226433)

### Additional info (optional)

After installing the aircraft through the installer, the problem immediately appeared, I tried all versions and the result is the same

### Discord Username (optional)

Sergey_Mackarov

**Comment by MicahBCode** [comment]
English please

**Comment by sergey2000122** [comment]
The test was edited in English

**Comment by sergey2000122** [comment]
> Пожалуйста, на английском

The test was edited in English

**Comment by frankkopp** [comment]
That is not a bug - please ask on the Discord for support.

**Comment by niuxiaoyang-a** [comment]
Hi, I also met this problem after updated A32NX and A380X. They suggested me change region utf-8, reinstall, but didnt work. Waiting for help...
