### ISSUE TITLE
Reflection of PFD / ND instrumentation on front windshield incorrect.

### ISSUE THREAD

**Issue by infinisigma** [flybywiresim/aircraft#9380]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-11-02T19:03:34+00:00",
    "ref": "refs/tags/v0.12.1",
    "sha": "2776100c286d3723826c62df36dc48207657d937",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.1",
    "version": "a380x-v0.12.1-rel.2776100"
}
```

### Describe the bug

In dark environments, the reflections of main instrumentation should not be visible on the front windshield as they are tucked below a glare shield.

<img width="776" alt="image" src="https://github.com/user-attachments/assets/3c1de6ac-d21b-41a0-9d59-63d99310ae2f">

### Expected behavior

No reflection of these instruments.

### Steps to reproduce

1. Load aircraft at night.

**Comment by Benjozork** [comment]
This is how screen space reflections work and not in the scope of what we can control about MSFS rendering. It would need ray traced reflections to fix this.
