### ISSUE TITLE
[A380X] 5° spoiler raise when on ground in clean or moving

### ISSUE THREAD

**Issue by henrybungee** [flybywiresim/aircraft#9426]
### Aircraft Version

Stable

### Description

Add special ground spoiler logic. The A380 spoilers do a 5° raise when on the ground with at least 1 engine started, in clean configuration, or flaps are in the process of extending or retracting from CONF 1 to CONF 2. 

### References (optional)

(Timestamps included where necessary)

https://youtu.be/wBCU2aEjYno?si=070L_75C6N0AT1TI&t=158
https://youtu.be/PrNz5-2Q72c?si=giLkjLDtM92liZ1_ (in this video, the middle 3 spoilers can be seen lowering back before the inner and outer spoilers as flaps transition to CONF 2)
https://youtu.be/yB2ES1jWlow?si=NTNGdT_-i5u66sCA&t=1057
https://www.pprune.org/tech-log/519217-a380-spoilers-movement.html

### Additional info (optional)

I don't have access to the FCOM but it could possibly say something about this spoiler logic in there somewhere, if anyone who does have access wants to check.

### Discord Username (optional)

hidinginabush

**Comment by flogross89** [comment]
Have you checked in the sim, whether this is currently behaving differently? We explicitly implemented this part of the spoiler logic
