### ISSUE TITLE
Airspeed fluctuating during cruise flight

### ISSUE THREAD

**Issue by BlueFalcon069** [flybywiresim/aircraft#9430]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2024-11-02T19:03:34+00:00",
    "ref": "refs/tags/v0.12.1",
    "sha": "2776100c286d3723826c62df36dc48207657d937",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.1",
    "version": "a380x-v0.12.1-rel.2776100"
}
```

### Describe the bug

The aircraft's airspeed seems to be rapidly fluctuating in cruise phase, as seen on the PFD, despite autothrottle and managed airspeed active

### Expected behavior

Aircraft airspeed should've remained constant and stable, especially since the plane is in cruise flight

### Steps to reproduce

1. Draw up a flight plan on simbrief (VTBS to RJAA used here)
2. Takeoff and reach cruising altitude using SOPs
3. Put heading, airspeed, and altitude into managed mode, set throttle to CLB
4. Wait for around 2 hours and 15 minutes post-takeoff for issue to appear
5. Observe airspeed on PFD

### References (optional)

https://github.com/user-attachments/assets/0f89ee11-eb9e-4495-b990-e035e70a1e32

### Additional info (optional)

All piloting assists are off

### Discord Username (optional)

comrade_cat69

**Comment by Waveif** [comment]
Look at your wind indicator. You've entered an area with turbulence. That's why its fluctuating
