### ISSUE TITLE
Clearing ECAM Warnings

### ISSUE THREAD

**Issue by CaptCrystal** [flybywiresim/aircraft#9433]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2024-11-02T19:03:34+00:00",
    "ref": "refs/tags/v0.12.1",
    "sha": "2776100c286d3723826c62df36dc48207657d937",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.1",
    "version": "a380x-v0.12.1-rel.2776100"
}
```

### Describe the bug

The button to clear ECAM warnings doesn't complete it's function.

### Expected behavior

The function to clear these issues (or whatever is more realistic)

### Steps to reproduce

1. Begin a flight
2. Conduct an error that would pop up an error on the ECAM (A way to do this is taking off with the XPDR on STBY)

### References (optional)

![image](https://github.com/user-attachments/assets/f7e48f7f-98dc-4561-a05a-e255ab8f228e)

### Additional info (optional)

This may be a feature request. However, to my knowledge, this function has been implemented.

### Discord Username (optional)

captcrystal

**Comment by CaptCrystal** [comment]
This might just be user error, please let me know if it is.

**Comment by flogross89** [comment]
Have you tried clicking the CLEAR button on the ECAM CP? 
https://docs.flybywiresim.com/pilots-corner/a380x/a380x-briefing/flight-deck/pedestal/ecam-cp/
In theory, it's implemented. Alternatively, pressing one of the check mark buttons should also work. 

If pressing CLEAR doesn't work, does this bug occur for specific messages only?

**Comment by CaptCrystal** [comment]
> Have you tried clicking the CLEAR button on the ECAM CP? https://docs.flybywiresim.com/pilots-corner/a380x/a380x-briefing/flight-deck/pedestal/ecam-cp/ In theory, it's implemented. Alternatively, pressing one of the check mark buttons should also work.
> 
> If pressing CLEAR doesn't work, does this bug occur for specific messages only?

Not sure if this is specific to certain messages. However, this issue does appear to be user error 😳. Anyway, making the clear button on the ECAM page functional might be a nice feature to add.

**Comment by flogross89** [comment]
The abnormal ECL is still WIP (as mentioned in the INOP list), but the things you describe are working. Closing this issue, if there is a real bug (please verify on Discord support first) feel free to open another issue, with a more detailed description.
