### ISSUE TITLE
A380: Taxi thrust and deceleration in turns

### ISSUE THREAD

**Issue by C-Schaffhausen** [flybywiresim/aircraft#9437]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2024-11-02T19:03:34+00:00",
    "ref": "refs/tags/v0.12.1",
    "sha": "2776100c286d3723826c62df36dc48207657d937",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.1",
    "version": "a380x-v0.12.1-rel.2776100"
}
```

### Describe the bug

The aircraft took close to 20% THR to start rolling, it also slows down significantly in turns.

### Expected behavior

- Less THR required for the aircraft to start rolling.
- Aircraft should not decelerate as much in turns

### Steps to reproduce

Taxi the aircraft

### Discord Username (optional)

C.Schaffhausen

**Comment by danbw9** [comment]
Hi. Thanks for your issue. Currently there is a fix being tested which will require less breakaway thrust. It should solve the problems you mentioned.
