### ISSUE TITLE
A380: Simbrief profile and fuel burn accuracy

### ISSUE THREAD

**Issue by C-Schaffhausen** [flybywiresim/aircraft#9439]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2024-11-02T19:03:34+00:00",
    "ref": "refs/tags/v0.12.1",
    "sha": "2776100c286d3723826c62df36dc48207657d937",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.1",
    "version": "a380x-v0.12.1-rel.2776100"
}
```

### Describe the bug

I planned for the long-haul flight flown by Emirates from NZAA to OMDB using simbrief, but the fuel burn was so great that no payload could be loaded onto the aircraft.

![image](https://github.com/user-attachments/assets/cf85aa76-686c-40e9-845a-d6d85f653c1e)

This is my FPL
(FPL-UAE1QH-IS
-A388/J-SADE3GHIJ2J3J4J5M1P2RWXYZ/LB1D1
-NZAA1530
-N0494F320 OSRAP1P UPLAR A464 RIGMI/N0499F340 A464 SCOTT J208 BN
 G326 LIKTO/N0499F360 G326 ROM T11 CESCI/N0495F380 T11 BRM G222 SAPDA
 L896 OBMAT/N0488F400 M766 KAT P570 MIXAM/N0373F200 P574 IMPED
 IMPED3C
-OMDB1625 OMAL
-PBN/A1B1C1D1L1O1S2 NAV/RNP2 DAT/CPDLCX 1FANSE2PDC SUR/RSP180 260B
 CANMANDATE DOF/241107 REG/A6EOG EET/NZZO0031 YBBB0123 YMMM0433
 YBBB0530 YMMM0734 WIIF0805 VCCF1054 VOMF1239 VABF1337 OOMM1521
 OMAE1611 SEL/AMHR CODE/8963E4 OPR/UAE PER/C RALT/YPAD WIPP VABO
 IFP/MODESASP RMK/NRP HAR TCAS ADSB)

Could Emirates be using a special variant for the flight, or is the fuel burn of the FBW A380 a bit off?

### Expected behavior

It should be able to fly NZAA to OMDB with payload capacity

### Steps to reproduce

Plan a flight from NZAA to OMDB on simbrief

### Discord Username (optional)

C.Schaffhausen

**Comment by chinjh93** [comment]
It's the issue with FBW's MTOW. They're using the WV003 payload variant which is restricted to Max Take Off Weight of 510000kg. 

Most airlines i recall have their MTOW at 550000 to 575000kg. 

So its a potential loss of either 40000kg worth of fuel/payload that can be loaded.

For now you can amend the default simbrief profile with greater maximum take off weights.

**Comment by C-Schaffhausen** [comment]
I'm trying to increase the MTOW of the simbrief profile and fly in this config. Let's see if this gets off the ground.

![image](https://github.com/user-attachments/assets/949e11f6-eef2-4780-86ae-3afe060f39b4)

**Comment by denmax18** [comment]
> I'm trying to increase the MTOW of the simbrief profile and fly in this config. Let's see if this gets off the ground.
> 
> ![image](https://private-user-images.githubusercontent.com/93766735/384044978-949e11f6-eef2-4780-86ae-3afe060f39b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MzI4MzEsIm5iZiI6MTczMTQzMjUzMSwicGF0aCI6Ii85Mzc2NjczNS8zODQwNDQ5NzgtOTQ5ZTExZjYtZWVmMi00NzgwLTg2YWUtM2FmZTA2MGYzOWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE3Mjg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYjAzMzhmZDdlNzcxNTM3ZmQyOWNhNDYzZTQ2ZDNlZGVmZjkwNjUyNTZkNjYxZDA2MWIxMDZmM2RiODZjMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.X0riSPTX1nblnm8UgPtvWUmZKk2DY5MxeFKi0ig6tZU)
Weight Units

Kilograms
Max Passengers 
484
Passenger Weight KG ? 
84
Baggage Weight KG ? 
20
Empty Weight KG 
285000
Max Zero Fuel Weight KG 
373000
Max Takeoff Weight KG 
510000
Max Landing Weight KG 
395000
Max Fuel Capacity KG 
209993
Max Cargo Weight KG 
51400
Default Freight Mode ?

Auto

**Comment by denmax18** [comment]
> I took off from NZAA with 575 tons, seems to work fine, the flaps retraction speed doesn't seem to match the green dot as it is much higher, but no big issues other than that. I'll bump my simbrief profile of my A380 to 575,000kg MTOW.
https://dispatch.simbrief.com/airframes/saved/1730666438156

**Comment by denmax18** [comment]
> I took off from NZAA with 575 tons, seems to work fine, the flaps retraction speed doesn't seem to match the green dot as it is much higher, but no big issues other than that. I'll bump my simbrief profile of my A380 to 575,000kg MTOW.

trayyy       it A380: Simbrief profile

https://dispatch.simbrief.com/airframes/saved/1730666438156

**Comment by woutsp** [comment]
hello this airframe doens't exist anymore says simbrief
