### ISSUE TITLE
[A380X] Link AUTO BRK BTV position and AUTO BRK RTO button to any useless command for in sim configuration

### ISSUE THREAD

**Issue by Amorisia** [flybywiresim/aircraft#9506]
### Aircraft Version

Stable

### Description

Link AUTO BRK rotative knob BTV position and AUTO BRK TO (RTO) push button to any useless in sim assignation in order to be able to link it with any peripheral as you did for the separate tiller axis.

See below TCA description as an example. As both are close as in the real aircraft, it could be a very nice option for many simmers.

### References (optional)

![image](https://github.com/user-attachments/assets/2ecb4ca0-8c70-4dd9-8630-4c050da2dbf0)

### Discord Username (optional)

amorisia

**Comment by frankkopp** [comment]
Both is possible if you use the API and not the default drivers. 
Use a tool like Mobiflight, AaO, SPAD.neXt, or similar to use the API.
This is recommendable for any complex aircraft anyway as the sim's default events are not sufficient. 

![image](https://github.com/user-attachments/assets/54afd011-68bd-447e-8b3a-72d0e5759547)
![image](https://github.com/user-attachments/assets/06330e16-bc86-4112-a12f-b5c666a02246)

**Comment by Amorisia** [comment]
> Both is possible if you use the API and not the default drivers. Use a tool like Mobiflight, AaO, SPAD.neXt, or similar to use the API. This is recommendable for any complex aircraft anyway as the sim's default events are not sufficient.
> 

Thanks for your answer. With this method is it possible to link only those actions using Mobiflight then all other inputs are still controlled by MSFS settings ? I was thinking I had to configure everything if going through this method.

**Comment by frankkopp** [comment]
> > Both is possible if you use the API and not the default drivers. Use a tool like Mobiflight, AaO, SPAD.neXt, or similar to use the API. This is recommendable for any complex aircraft anyway as the sim's default events are not sufficient.
> 
> Thanks for your answer. With this method is it possible to link only those actions using Mobiflight then all other inputs are still controlled by MSFS settings ? I was thinking I had to configure everything if going through this method.

Yes you can mix this - I use SPAD (see screenshots) - but still have a lot mapped in the MSFS Controller Options. No need to redo everything.

**Comment by Amorisia** [comment]
> > > Both is possible if you use the API and not the default drivers. Use a tool like Mobiflight, AaO, SPAD.neXt, or similar to use the API. This is recommendable for any complex aircraft anyway as the sim's default events are not sufficient.
> > 
> > 
> > Thanks for your answer. With this method is it possible to link only those actions using Mobiflight then all other inputs are still controlled by MSFS settings ? I was thinking I had to configure everything if going through this method.
> 
> Yes you can mix this - I use SPAD (see screenshots) - but still have a lot mapped in the MSFS Controller Options. No need to redo everything.

Thank you, I managed to do it with Mobiflight. It works well. By the way, I am unable to find vars for FCU switches like Meter and TRUE/MAG ref switch. Any clue if they are available through API ?
