### ISSUE TITLE
FMC Error 

### ISSUE THREAD

**Issue by smartironman3** [flybywiresim/aircraft#9508]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2024-11-09T16:33:35+00:00",
    "ref": "refs/tags/v0.12.3",
    "sha": "7c0bb7fee6051b07edd3435d923b7acf1cec2945",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.3",
    "version": "a380x-v0.12.3-rel.7c0bb7f"
}
```

### Describe the bug

Being unable to enter the flight plan manually or receiving CPNY flight plan from simbrief

### Expected behavior

Working normally?

### Steps to reproduce

I don't know :)

### References (optional)

https://github.com/user-attachments/assets/6acbf320-a07f-447a-9dfa-30f39799c9b1

### Discord Username (optional)

toto_leung

**Comment by CaptCrystal** [comment]
I haven't been able to reproduce this issue

**Comment by Benjozork** [comment]
Does it only happen for this airport? Have you tried with others? Do you have scenery for it?

Also, please don't leave sections of the bug report blank. Without steps to reproduce an issue we cannot possibly fix it.
