### ISSUE TITLE
OANS / BTV + Runway Selection Mismatch to Navdata at BKK resulting in unavailable SID/STARs/Approaches and BTV Mismatch 

### ISSUE THREAD

**Issue by vossiniko** [flybywiresim/aircraft#9516]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2024-11-09T16:33:35+00:00",
    "ref": "refs/tags/v0.12.3",
    "sha": "7c0bb7fee6051b07edd3435d923b7acf1cec2945",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.3",
    "version": "a380x-v0.12.3-rel.7c0bb7f"
}
```

### Describe the bug

Bangkok / Suvarnabhumi Intl (VTBS/BKK) has a new western Runway, which has changed the Runway Lettering. 
The OANS does not reflect this, thus making the Runways unusable for selecting a SID/STAR and shows BTV Mismatch.

Error Presists after Navdata Update / Reinstallation
![RWY Selection](https://github.com/user-attachments/assets/6837975f-79f9-4940-8f6f-5a57ded85d65)
![RWY Mismatch Database](https://github.com/user-attachments/assets/9699ff95-24bd-40df-b626-e9738e75cbd1)

### Expected behavior

RWYs in BTW/OANS and Navdatabase should match. SID/STAR Selection should be possible with the correct runways available

### Steps to reproduce

1. Restarted SIM
2. Placed Aircraft in Bangkok / Suvarnabhumi Intl (VTBS/BKK)
3. Tried to enter SID
4. Restarted PC
5. Uninstalled NAVDATA and Reinstalled with Navigraph Updater
6. Started SIM
2. Placed Aircraft in Bangkok / Suvarnabhumi Intl (VTBS/BKK)
3. Tried to enter SID
4. Restarted SIM
5. Took Off from Chiang Mai (VTCC/CNX) and flew towards BKK
6. Tried BTV Selection

### Additional info (optional)

Not a copy of https://github.com/flybywiresim/aircraft/issues/9411 since this is not an issue with a leading 0, but rather due to renaming of the runway system.

Not a duplicate of https://github.com/flybywiresim/aircraft/issues/9285 since there the Runway Number is current.

### Discord Username (optional)

vossiniko

**Comment by vossiniko** [comment]
Further Pictures
![2024-11-15 06_57_38-Microsoft Flight Simulator - 1 38 2 0](https://github.com/user-attachments/assets/0b99812d-b514-472b-b2d1-796e25538b48)
![2024-11-15 06_57_54-WASMINSTRUMENT](https://github.com/user-attachments/assets/d036f99d-38fb-4711-aaee-fe46c6e9de38)
![2024-11-15 07_00_36-A380X_MFD](https://github.com/user-attachments/assets/b20f6168-64f8-4509-86e7-800330be173f)
![2024-11-15 07_00_59-A380X_MFD](https://github.com/user-attachments/assets/a3a8482d-571e-4ed1-9048-eeddd4f0e7d1)

**Comment by tracernz** [comment]
Neither than the runways in the sim/nav database, nor the Navigraph airport map database are controlled by FlyByWire, so there’s nothing we can do here unfortunately. I suggest reporting to Navigraph and Microsoft.

**Comment by vossiniko** [comment]
Hi Michael

Thanks for the quick reply! 

Can you enlighten me then as to where you pull the Runways information from?

Since the Navdata are being pulled from the Flightsim, and those data are up to date from navigraph, the Runways Data seem to be from a doubious source?

**Comment by tracernz** [comment]
The runways for the Nav DB come from the sim airports/scenery, so it depends what you have installed, and the airport nav database for OANS/ANF comes from Navigraph.

**Comment by vossiniko** [comment]
Just for reference, Problem was solved with the Fix [A380X/OANS] Fix "BTV/FMS RWY DISAGREE" message for single-digit runway identifiers - @flogross89 (floridude), so it was a A380X Issue all along.

**Comment by flogross89** [comment]
@vossiniko Perfect, thank you!
