### ISSUE TITLE
No sound of the plane.

### ISSUE THREAD

**Issue by DieBanane2200** [flybywiresim/aircraft#9526]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2024-11-09T16:34:34+00:00",
    "ref": "refs/tags/v0.12.3",
    "sha": "7c0bb7fee6051b07edd3435d923b7acf1cec2945",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.3",
    "version": "a380x-v0.12.3-rel.7c0bb7f"
}
```

### Describe the bug

Ok so when I start the flight everything works perfectly fine, I can hear everything and there are no issues. But when I use the skipping tool from the toolbar, and skip to approach, I just hear no sounds of the aircraft when in external or drone view. I can hear other planes sounds but just not the A380 ones, when in external view. In the cockpit view I can hear everything fine. This only encounters on the A380. I also removed every livery/mod as recommend, but it wouldnt work.

### Expected behavior

I expected that if I used the skipping tool, and skip to the final approach that I could hear my Aircraft when in external view.

### Steps to reproduce

1. I load into the game at a gate.
2. I start the plane as normal
3. I taxi to the Runway
4. I take off
5. I reach my crusing alt
6. I skip to final approach
7. I switch to external view and can not hear any sounds from the A380

### References (optional)

No sorry, I dont have one.

### Additional info (optional)

Only happens on the A380. All other planes including the A320 work fine.

### Discord Username (optional)

diebanane2200_46798

**Comment by DieBanane2200** [comment]
I would be happy if you could fix this. Thank you!

**Comment by Maximilian-Reuter** [comment]
Are you sure that is a sim function ? I dont remember such a function.

**Comment by DieBanane2200** [comment]
> Are you sure that is a sim function ? I dont remember such a function.

Yes it is.

**Comment by tracernz** [comment]
This feature is not something we test or support. It generally doesn't go too well with complex aircraft.
