### ISSUE TITLE
Ambient light does not light up overhead panel when cabin is disabled 

### ISSUE THREAD

**Issue by Mocha27** [flybywiresim/aircraft#9542]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2024-11-09T16:34:34+00:00",
    "ref": "refs/tags/v0.12.3",
    "sha": "7c0bb7fee6051b07edd3435d923b7acf1cec2945",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.3",
    "version": "a380x-v0.12.3-rel.7c0bb7f"
}
```

### Describe the bug

the ambient light knob that is supposed to light up the overhead panel and surrounding walls/ceilings only does so when the cabin is enabled. if cabin is disabled, it only lights up the bottom pedestal 

### Expected behavior

the cockpit ambient light shouldn't be connected to the cabin. it should light up the flight deck regardless whether cabin is enabled or not

### Steps to reproduce

1. Crank the ambient light all the way up
2. Disable Cabin
3. Enable Cabin
4. Observe the difference

### References (optional)

![image](https://github.com/user-attachments/assets/b8042e6e-b81f-4724-9c65-66f6ede041e1) cabin disabled
![image](https://github.com/user-attachments/assets/66834a12-d7d0-4773-98e9-17b73c69a6df) cabin enabled

### Discord Username (optional)

rkk27

**Comment by 2hwk** [comment]
Fixed in development version
