### ISSUE TITLE
у меня не отоброжается самолёт он невидимый

### ISSUE THREAD

**Issue by nezer212** [flybywiresim/aircraft#9551]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-11-17T07:11:20+00:00",
    "ref": "refs/heads/master",
    "sha": "2f774e9202935c8b4616b9fe66166a36889d7d13",
    "actor": "2hwk",
    "event_name": "manual",
    "pretty_release_name": "master:2f774e92",
    "version": "a32nx-v0.13.0-dev.2f774e9"
}
```

### Describe the bug

помогите пожалуйста мой самолёт A32NX невидимый когда я захожу в полёт он совершенно не видимый не кабина не сам самолёт снаружи прозрачен пробовал переустановить не помогло 

### Expected behavior

хочу чтоб самолёт было видно

### Steps to reproduce

установил установщик
загрузил самолёт
выбрал его
зашол в полёт самолёт не видно

**Comment by nezer212** [comment]
![Снимок экрана (99)](https://github.com/user-attachments/assets/ee63681d-dd2a-4cc7-9775-73128ddf3c0b)

**Comment by IntegrierterKurde** [comment]
English Please

**Comment by nezer212** [comment]
ok

**Comment by beheh** [comment]
Duplicate of #9552
