### ISSUE TITLE
 step alts page in vert rev says not implemented

### ISSUE THREAD

**Issue by relt1hfl0dagaming** [flybywiresim/aircraft#9556]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2024-11-17T07:11:17+00:00",
    "ref": "refs/heads/master",
    "sha": "2f774e9202935c8b4616b9fe66166a36889d7d13",
    "actor": "2hwk",
    "event_name": "manual",
    "pretty_release_name": "master:2f774e92",
    "version": "a380x-v0.13.0-dev.2f774e9"
}
```

### Describe the bug

can you devs implement theses features and as if it were implement i would be happy with it shown in the image
![Screenshot 2024-11-19 170248](https://github.com/user-attachments/assets/22e79c1e-68cc-4bd0-893d-384d5114bfee)

### Expected behavior

it should be implemented

### Steps to reproduce

1. pls add these tabs on vert rev page shown on the image
2. do find some references for these features
3. implement them for a380x 

### References (optional)

![image](https://github.com/user-attachments/assets/df212556-493a-417f-b5e3-7cfb20eb638b)

### Discord Username (optional)

xrobloxianhaulerz

**Comment by BravoMike99** [comment]
Duplicate #9486
