### ISSUE TITLE
[A32NX] FS2024: Importing Simbrief Data to MCDU Initialization Causes CTD

### ISSUE THREAD

**Issue by MJ-AmJay** [flybywiresim/aircraft#9574]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-11-21T09:20:01+00:00",
    "ref": "refs/heads/master",
    "sha": "1d42acddaf69e496f74e1ca1d6967183eaecf65c",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "master:1d42acdd",
    "version": "a32nx-v0.13.0-dev.1d42acd"
}
```

### Describe the bug

Flight Simulator 2024 (FS24) crashes to desktop (CTD) when importing an extensive/large simbrief flight plan from Electronic Flight Bag (EFB) into the MCDU Init page.

### Expected behavior

The EFB's flight plan should be successfully imported into the MCDU without causing the simulator to crash.

### Steps to reproduce

1. Import a flight plan with from Simbrief with at least 15-20 waypoints to the EFB.
2. Navigate to the MCDU and access the Init page.
3. Attempt to initialize the Simbrief plan.
4. Observe the CTD & Memory leak during or immediately after initialization.

### Additional info (optional)

Memory Leak observed during CTD.

It’s hypothesized that there is a certain threshold to how large the simbrief data imported into the MCDU before CTD happens  followed by a memory leak that freezes the simulator.

Do note that this bug is only found in FS2024.

_No response_

### Discord Username (optional)

MJ

**Comment by MJ-AmJay** [comment]
Unable to Reproduce

**Comment by wined2310** [comment]
This also applies to the A380
