### ISSUE TITLE
[A380X] FCU Toggle Between Increments of 100 and 1000 INOP

### ISSUE THREAD

**Issue by JohnnyBoii189** [flybywiresim/aircraft#9577]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2024-11-21T09:21:42+00:00",
    "ref": "refs/heads/master",
    "sha": "1d42acddaf69e496f74e1ca1d6967183eaecf65c",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "master:1d42acdd",
    "version": "a380x-v0.13.0-dev.1d42acd"
}
```

### Describe the bug

The Airbus A380 has a selector ring that allows the PM to change the altitude between increments of 100 and 1000, as with the full Airbus family. Looking for implementation of this feature. 

### Expected behavior

Ring/knob should function the same as the existing A32NX project

### Steps to reproduce

Load into A380X, click spot does not exist for toggle.

### References (optional)

See link for an Etihad A380 FCU: https://lh3.googleusercontent.com/proxy/grhO0aLTB5IMFwwgms88dCrJdmG_MCmsKkXy6JUJCUqyTYdK2U9UzX_jH0WkgEAosS0I-rGNIv7fOp8DOZkVWZ0

### Discord Username (optional)

johnnyboii

**Comment by flogross89** [comment]
This is implemented, please check again.
