### ISSUE TITLE
INI FLT not working

### ISSUE THREAD

**Issue by wined2310** [flybywiresim/aircraft#9593]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2024-11-26T11:54:27+00:00",
    "ref": "refs/heads/master",
    "sha": "461887261aec24df9119b257aada123f7ab98f02",
    "actor": "Maximilian-Reuter",
    "event_name": "manual",
    "pretty_release_name": "master:46188726",
    "version": "a380x-v0.13.0-dev.4618872"
}
```

### Describe the bug

Issue #9574 was marked solved by #9587

Indeed MSFS2024 no longer CTD when requesting Company Flight.
But the import of the Simbrief flight is still not working.

### Expected behavior

Simbrief Flightplan should be imported to the MCDU

### Steps to reproduce

1. create a simbrief flight ( in my case LOWW to VTBS)
2. open the INIT Page and Request CPY FLT
3. Check if FLightplan was imported

**Comment by tracernz** [comment]
This is a sim bug, so not something we can address (we could only stop it making us CTD). Hopefully will be addressed in a future update.
