### ISSUE TITLE
A32NX: Leading 0 missing on barometric display for altimeter values below 1000hPa

### ISSUE THREAD

**Issue by BravoMike99** [flybywiresim/aircraft#9595]
### Aircraft Version

Development

### Build info

```json
master
```

### Describe the bug

Leading 0 is missing on the barometric reference display for values below 1000hPa if hPa is selected
![FCU](https://github.com/user-attachments/assets/8dc2a95b-3e42-4af7-900a-ef8b3680b33c)

### Expected behavior

See ref

### Steps to reproduce

Set the barometric reference to QNH on the efis control panel.
Select a QNH value below 1000hPa.

### References (optional)

![image](https://github.com/user-attachments/assets/e0aafaf2-f93c-4715-a4c1-547336065bfe)

### Discord Username (optional)

bruno_pt99

**Comment by lukecologne** [comment]
Oops, probably a regression from #7587, will fix
