### ISSUE TITLE
A380 NAV frozen flying out of VHHH

### ISSUE THREAD

**Issue by C-Schaffhausen** [flybywiresim/aircraft#9609]
### Aircraft Version

Development 

### Build info

```json
    "built": "2024-11-29T00:27:13+00:00",
    "ref": "refs/heads/master",
    "sha": "0543c5cb54fdc05a6e80f80d8c3119bd5fc2841d",
    "actor": "flogross89",
    "event_name": "manual",
    "pretty_release_name": "master:0543c5cb",
    "version": "a380x-v0.13.0-dev.0543c5c"
```

### Describe the bug

FS2020

I flew the A380 in FS2020 on the BEKOL1X departure out of VHHH which contain an RF segment after PORPA, the ND keep indicating the next waypoint is PORPA at 0.8NM even though the aircraft was over PORPA, and it also lost its LNAV capability, HDG mode works. I tried turning FD off and ON again and directing to other waypoints, but none worked.

### Expected behavior

I expect the aircraft to follow the RF leg and the LNAV capability should not be affected. Next waypoint indication should jump to the next logical waypoint/next DIR waypoint when commanded

### Steps to reproduce

1. Setup the aircraft on RWY07R of VHHH for BEKOL1X departure
2. Takeoff as normal, stay on manual flight
3. As the aircraft passes HH301 and approaches PORPA, ND indicates PORPA at 0.8NM then stop refreshing. LNAV capability lost.

### Discord Username (optional)

C.Schaffhausen

**Comment by C-Schaffhausen** [comment]
Also tried non RF SID BEKOL5A, which also failed in a similar way

**Comment by C-Schaffhausen** [comment]
I discovered that the issue only happens if you import a Simbrief flightplan which contains an old SID, as VHHH recently updated their SID the FBW aircraft might have encountered a bug when importing the flight plan with an old SID, which caused the LNAV to stop working. The solution is to remove the SID from the simbrief fpl and you should be good to go.

**Comment by C-Schaffhausen** [comment]
Video support
https://youtu.be/LwfETs9C2p8

**Comment by C-Schaffhausen** [comment]
Disabled VHHH scenery but kept the latest navdata, same bug
https://youtu.be/Zz9GMp4zqFQ

**Comment by tracernz** [comment]
Thanks for the detailed reports! Will check this out and see what’s happening.

**Comment by C-Schaffhausen** [comment]
Another test flight with nothing in the Community folder, except FBW A380 and A380 texture. Same issue.
https://youtu.be/Y9ytO6h03oY

**Comment by tracernz** [comment]
Interestingly it flies absolutely fine in the A32NX (BEKO1X).

**Comment by C-Schaffhausen** [comment]
> Interestingly it flies absolutely fine in the A32NX (BEKO1X).
 
Interesting, did your A380 have the same issue though?

**Comment by denmax18** [comment]
> Interestingly it flies absolutely fine in the A32NX (BEKO1X).

https://github.com/Maximilian-Reuter/a32nx/tree/fixWarningSounds

**Comment by tracernz** [comment]
> [#9615 (comment)](https://github.com/flybywiresim/aircraft/pull/9615#issue-2709218245)

I'm not sure how this is relevant? Can you explain?

**Comment by denmax18** [comment]
> > [#9615 (comment)](https://github.com/flybywiresim/aircraft/pull/9615#issue-2709218245)
> 
> I'm not sure how this is relevant? Can you explain?
fix(fcu-api): fix KOHLSMANN_SET and custom baro set events #9617

**Comment by C-Schaffhausen** [comment]
How are the above relevant posts relevant?

**Comment by C-Schaffhausen** [comment]
I just flew the the SID with the FBW A320 and the A320 flew without problems, so it's not something navdata related, instead it's something with the A380's LNAV

**Comment by denmax18** [comment]
> I just flew the the SID with the FBW A320 and the A320 flew without problems, so it's not something navdata related, instead it's something with the A380's LNAV

#9622

**Comment by Pruznak** [comment]
Is that account just trolling ?

**Comment by Amorisia** [comment]
Hello, I got the same on a flight inbound VHHH 25R today. STAR CANT3B. Came back after 2 or 3 minutes and performed a DIR TO to continue approach.

**Comment by C-Schaffhausen** [comment]
> Hello, I got the same on a flight inbound VHHH 25R today. STAR CANT3B. Came back after 2 or 3 minutes and performed a DIR TO to continue approach.

I haven't tried arriving, but departing has issues. Try if you have time.

**Comment by C-Schaffhausen** [comment]
I've flown the VHHH SID with the stable version of A380 without any issues. It must be something that was introduced between 0.12.3 and the current dev build which resulted in the issue. I don't have the expertise of these codes, may I ask @2hwk take a look please?

**Comment by tracernz** [comment]
Here's the bug.
![image](https://github.com/user-attachments/assets/60aad31f-e92e-442f-adbd-22228ef8722b)
