### ISSUE TITLE
T/O CONFIG button not working

### ISSUE THREAD

**Issue by C-Schaffhausen** [flybywiresim/aircraft#9610]
### Aircraft Version

Development 

### Build info

```json
    "built": "2024-11-29T00:27:13+00:00",
    "ref": "refs/heads/master",
    "sha": "0543c5cb54fdc05a6e80f80d8c3119bd5fc2841d",
    "actor": "flogross89",
    "event_name": "manual",
    "pretty_release_name": "master:0543c5cb",
    "version": "a380x-v0.13.0-dev.0543c5c"
```

### Describe the bug

FS2020

Pressing the T/O CONFIG button did not work even when the aircraft is fully configured. The Takeoff config line on EWD remains blue.

### Expected behavior

The Takeoff config line changes to green when the button is pressed if the aircraft is correctly configured.

### Steps to reproduce

1. Setup the aircraft for departure from the gate, importing your simbrief fpl etc.
2. Startup and taxi as usual
3. Press the T/O CONFIG Button

**Comment by C-Schaffhausen** [comment]
Video support
https://youtu.be/omxeNSdp5wo

**Comment by heclak** [comment]
Is this in 2020 or 2024?

**Comment by C-Schaffhausen** [comment]
> Is this in 2020 or 2024?

2020

**Comment by Jaronics** [comment]
Had the same problem yesterday

**Comment by Fowl38** [comment]
I also had this problem. I tapped many times on the button and it finished to be green. Since, it works directly after the first tap on the button

**Comment by BravoMike99** [comment]
Did any of you get the TO SPEEDS TOO LOW scratchpad message on the MFD after inserting the V speeds in the flights that this occurred (related to #9620 )? If so that's most likely the cause as the takeoff config will never succeed if that's the case .

**Comment by frankkopp** [comment]
> Did any of you get the TO SPEEDS TOO LOW scratchpad message on the MFD after inserting the V speeds in the flights that this occurred (related to #9620 )? If so that's most likely the cause as the takeoff config will never succeed if that's the case .

Yes - has been discussed in within the team now. It is likely caused by #9620 .
But there surely should be an ECAM warning or something. Just not accepting the T.O CONFIG button can't be correct.
