### ISSUE TITLE
Unable to input any number in INIT page on FROM/TO fields

### ISSUE THREAD

**Issue by baskoropn** [flybywiresim/aircraft#9613]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2024-11-09T16:32:29+00:00",
    "ref": "refs/tags/v0.12.3",
    "sha": "7c0bb7fee6051b07edd3435d923b7acf1cec2945",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.3",
    "version": "a32nx-v0.12.3-rel.7c0bb7f"
}
```

### Describe the bug

As a user, I am unable to input any number in INIT page on FROM/TO section. Example input `WA1A/WIII` .

Currently, the MCDU will always show error FORMAT ERROR 

### Expected behavior

expected results: able to input number in INIT page on FROM/TO section.

### Steps to reproduce

1. load simulator
2. try to type WA1A/WIII
3. click FROM/TO section
4. it will gives FORMAT ERROR

video reference
https://www.youtube.com/watch?v=EKIjN0DfdVw

### References (optional)
![20241201162425_1](https://github.com/user-attachments/assets/da9484ac-13da-4ca1-859d-367c1ccd8c8c)
![20241201162622_1](https://github.com/user-attachments/assets/6731bb5e-753d-4ad7-8822-f94bc0476757)

### Additional info (optional)

-

### Discord Username (optional)

-

**Comment by tshomas** [comment]
Hi, is WA1A the right ICAO code? I see that WASS might be the more modern and correct code, which navigraph might be using?

**Comment by baskoropn** [comment]
hi @Maximilian-Reuter @tshomas , I use AIRAC CYCLE 2412 REV.1

**Comment by tracernz** [comment]
The A320 family FMS only accepts 4 letters for the airport code, numbers are not possible.
