### ISSUE TITLE
Difference between DEV and STABLE causing problems with Winwing FCU on DEV-Version

### ISSUE THREAD

**Issue by GAF5006** [flybywiresim/aircraft#9618]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-11-29T00:26:46+00:00",
    "ref": "refs/heads/master",
    "sha": "0543c5cb54fdc05a6e80f80d8c3119bd5fc2841d",
    "actor": "flogross89",
    "event_name": "manual",
    "pretty_release_name": "master:0543c5cb",
    "version": "a32nx-v0.13.0-dev.0543c5c"
}
```

### Describe the bug

I own the Hardware FCU of WinWing and used ist with the Development Version of the A320. Some days ago I noticed 3 failures:

1. Pressing the LOC-key I get is's green light in the virtual cockpit as response, but not in the key of the Winwing FCU
2. Same effect with the APP-key. If I press APP, the green light shows up on FCU virtual cockpit, but not on Winwing FCU
3. The Switch 100/1000 ft on Winwing FCU doesn't work in FBW-Cockpit. 

**No problems with the Stable-Version of FBW A320. All switches and lights work correctly**
But there must something have been changed in the DEV-Version

### Expected behavior

I would like to use the DEV in future, but therefore it is important, that my Winwing FCU works on all version

### Steps to reproduce

1. Noticed problem while flying with the DEV
2. Changed so STABLE > no problem
3. uninstalled/installed both versions several times - no change of the behaviour
4. Checked ist in the MSFS of a friend - same problem

**Comment by lukecologne** [comment]
It is not our responsibility to update the hardware profiles, our docs have been updated accordingly so the manufacturerers or developers of the software for the hardware. Having said that, the LVars previously used to indicate these should still work. Please go over to our discord to talk about this further, github is not the place for this.

**Comment by lukecologne** [comment]
For example, provide two profiles for both current stable and development, or alternatively only provide a profile for stable and have their users only install stable. It is unreasonable to assume the API will never change, that would stall our development. For stability in API, only the stable version should be used. Now, as I said, GitHub issues are for actual bugs in our aircraft, not for discussion on API stability.

**Comment by tracernz** [comment]
Just use Mobiflight instead.
