### ISSUE TITLE
Many new EFIS LVars are not writable

### ISSUE THREAD

**Issue by YLevesque34** [flybywiresim/aircraft#9671]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-12-10T01:40:59+00:00",
    "ref": "refs/heads/master",
    "sha": "33c4a62f9e8074ad140848c399072f46dd880c69",
    "actor": "flogross89",
    "event_name": "manual",
    "pretty_release_name": "master:33c4a62f",
    "version": "a32nx-v0.13.0-dev.33c4a62"
}
```

### Describe the bug

Many new EFIS LVars are not writable:
A32NX_FCU_EFIS_L_CSTR_LIGHT_ON
A32NX_FCU_EFIS_L_VORD_LIGHT_ON
A32NX_FCU_EFIS_L_WPT_LIGHT_ON
A32NX_FCU_EFIS_L_NDB_LIGHT_ON
A32NX_FCU_EFIS_L_ARPT_LIGHT_ON
A32NX_FCU_EFIS_R_LS_LIGHT_ON

### Expected behavior

These variables can be changed with an external program as it is the case with other variables(ex. A32NX_FCU_EFIS_R_EFIS_MODE)

### Steps to reproduce

Open the Behavior tool in  the DevMode window (MS2024)
Locate the variable in the variables tab.
Enter a new value.
The variable value is not updated 

### Additional info (optional)

Now it is impossible to changes these variables with an external program.
Previously, these button lights were controlled by A32NX_EFIS_L_OPTION and it was possible to change the value.

### Discord Username (optional)

ylevesque

**Comment by tracernz** [comment]
Use the key events for button pushes. These local vars are outputs only. https://github.com/flybywiresim/aircraft/blob/master/fbw-a32nx/docs/a320-events.md#efis-cp

**Comment by YLevesque34** [comment]
Thanks Michael

Events work perfectly.

Yves



Le jeu. 19 déc. 2024 à 19:59, Michael Corcoran ***@***.***> a
écrit :
